// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { Consonant } from '../types';

/** Ordre d'introduction des consonnes dans le parcours (fréquence et utilité). */
export const CONSONANT_ORDER = "กดตบปอจนมรลงยวสหขคทพชถผฝฉซฟฮญณธภศษฐฆฌฎฏฑฒฬฃฅ";

export const CONSONANTS: Consonant[] = [
  { id: "c:ก", char: "ก", nameWord: "ไก่", nameRom: "kɔɔ kài", nameMeaning: { fr: "poulet" }, cls: "M", initial: "k", initialIPA: "k", final: "k", audioBase: "ก" },
  { id: "c:ข", char: "ข", nameWord: "ไข่", nameRom: "khɔ̌ɔ khài", nameMeaning: { fr: "œuf" }, cls: "H", initial: "kh", initialIPA: "kʰ", final: "k", audioBase: "ข" },
  { id: "c:ฃ", char: "ฃ", nameWord: "ขวด", nameRom: "khɔ̌ɔ khùat", nameMeaning: { fr: "bouteille" }, cls: "H", initial: "kh", initialIPA: "kʰ", final: "k", audioBase: "ข", note: { fr: "Lettre obsolète : remplacée par ข dans l'usage actuel." }, obsolete: true },
  { id: "c:ค", char: "ค", nameWord: "ควาย", nameRom: "khɔɔ khwaai", nameMeaning: { fr: "buffle" }, cls: "L", initial: "kh", initialIPA: "kʰ", final: "k", audioBase: "ค" },
  { id: "c:ฅ", char: "ฅ", nameWord: "คน", nameRom: "khɔɔ khon", nameMeaning: { fr: "personne" }, cls: "L", initial: "kh", initialIPA: "kʰ", final: "k", audioBase: "ค", note: { fr: "Lettre obsolète : remplacée par ค dans l'usage actuel." }, obsolete: true },
  { id: "c:ฆ", char: "ฆ", nameWord: "ระฆัง", nameRom: "khɔɔ rá-khang", nameMeaning: { fr: "cloche" }, cls: "L", initial: "kh", initialIPA: "kʰ", final: "k", audioBase: "ค", note: { fr: "Rare." }, rare: true },
  { id: "c:ง", char: "ง", nameWord: "งู", nameRom: "ngɔɔ nguu", nameMeaning: { fr: "serpent" }, cls: "L", initial: "ng", initialIPA: "ŋ", final: "ng", audioBase: "ง" },
  { id: "c:จ", char: "จ", nameWord: "จาน", nameRom: "jɔɔ jaan", nameMeaning: { fr: "assiette" }, cls: "M", initial: "j", initialIPA: "tɕ", final: "t", audioBase: "จ" },
  { id: "c:ฉ", char: "ฉ", nameWord: "ฉิ่ง", nameRom: "chɔ̌ɔ chìng", nameMeaning: { fr: "petites cymbales" }, cls: "H", initial: "ch", initialIPA: "tɕʰ", final: "", audioBase: "ฉ" },
  { id: "c:ช", char: "ช", nameWord: "ช้าง", nameRom: "chɔɔ cháang", nameMeaning: { fr: "éléphant" }, cls: "L", initial: "ch", initialIPA: "tɕʰ", final: "t", audioBase: "ช" },
  { id: "c:ซ", char: "ซ", nameWord: "โซ่", nameRom: "sɔɔ sôo", nameMeaning: { fr: "chaîne" }, cls: "L", initial: "s", initialIPA: "s", final: "t", audioBase: "ซ" },
  { id: "c:ฌ", char: "ฌ", nameWord: "เฌอ", nameRom: "chɔɔ chəə", nameMeaning: { fr: "arbre" }, cls: "L", initial: "ch", initialIPA: "tɕʰ", final: "", audioBase: "ช", note: { fr: "Très rare." }, rare: true },
  { id: "c:ญ", char: "ญ", nameWord: "หญิง", nameRom: "yɔɔ yǐng", nameMeaning: { fr: "femme" }, cls: "L", initial: "y", initialIPA: "j", final: "n", audioBase: "ย" },
  { id: "c:ฎ", char: "ฎ", nameWord: "ชฎา", nameRom: "dɔɔ chá-daa", nameMeaning: { fr: "coiffe de danse" }, cls: "M", initial: "d", initialIPA: "d", final: "t", audioBase: "ด", note: { fr: "Rare." }, rare: true },
  { id: "c:ฏ", char: "ฏ", nameWord: "ปฏัก", nameRom: "tɔɔ pà-tàk", nameMeaning: { fr: "aiguillon" }, cls: "M", initial: "t", initialIPA: "t", final: "t", audioBase: "ต", note: { fr: "Rare." }, rare: true },
  { id: "c:ฐ", char: "ฐ", nameWord: "ฐาน", nameRom: "thɔ̌ɔ thǎan", nameMeaning: { fr: "socle, base" }, cls: "H", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ถ" },
  { id: "c:ฑ", char: "ฑ", nameWord: "มณโฑ", nameRom: "thɔɔ mon-thoo", nameMeaning: { fr: "Montho (personnage du Ramakien)" }, cls: "L", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ท", note: { fr: "Rare. Se lit d dans quelques mots." }, rare: true },
  { id: "c:ฒ", char: "ฒ", nameWord: "ผู้เฒ่า", nameRom: "thɔɔ phûu-thâo", nameMeaning: { fr: "vieillard" }, cls: "L", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ท", note: { fr: "Rare." }, rare: true },
  { id: "c:ณ", char: "ณ", nameWord: "เณร", nameRom: "nɔɔ neen", nameMeaning: { fr: "novice (jeune moine)" }, cls: "L", initial: "n", initialIPA: "n", final: "n", audioBase: "น" },
  { id: "c:ด", char: "ด", nameWord: "เด็ก", nameRom: "dɔɔ dèk", nameMeaning: { fr: "enfant" }, cls: "M", initial: "d", initialIPA: "d", final: "t", audioBase: "ด" },
  { id: "c:ต", char: "ต", nameWord: "เต่า", nameRom: "tɔɔ tào", nameMeaning: { fr: "tortue" }, cls: "M", initial: "t", initialIPA: "t", final: "t", audioBase: "ต" },
  { id: "c:ถ", char: "ถ", nameWord: "ถุง", nameRom: "thɔ̌ɔ thǔng", nameMeaning: { fr: "sac" }, cls: "H", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ถ" },
  { id: "c:ท", char: "ท", nameWord: "ทหาร", nameRom: "thɔɔ thá-hǎan", nameMeaning: { fr: "soldat" }, cls: "L", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ท" },
  { id: "c:ธ", char: "ธ", nameWord: "ธง", nameRom: "thɔɔ thong", nameMeaning: { fr: "drapeau" }, cls: "L", initial: "th", initialIPA: "tʰ", final: "t", audioBase: "ท" },
  { id: "c:น", char: "น", nameWord: "หนู", nameRom: "nɔɔ nǔu", nameMeaning: { fr: "souris" }, cls: "L", initial: "n", initialIPA: "n", final: "n", audioBase: "น" },
  { id: "c:บ", char: "บ", nameWord: "ใบไม้", nameRom: "bɔɔ bai-máai", nameMeaning: { fr: "feuille d'arbre" }, cls: "M", initial: "b", initialIPA: "b", final: "p", audioBase: "บ" },
  { id: "c:ป", char: "ป", nameWord: "ปลา", nameRom: "pɔɔ plaa", nameMeaning: { fr: "poisson" }, cls: "M", initial: "p", initialIPA: "p", final: "p", audioBase: "ป" },
  { id: "c:ผ", char: "ผ", nameWord: "ผึ้ง", nameRom: "phɔ̌ɔ phʉ̂ng", nameMeaning: { fr: "abeille" }, cls: "H", initial: "ph", initialIPA: "pʰ", final: "", audioBase: "ผ" },
  { id: "c:ฝ", char: "ฝ", nameWord: "ฝา", nameRom: "fɔ̌ɔ fǎa", nameMeaning: { fr: "couvercle" }, cls: "H", initial: "f", initialIPA: "f", final: "", audioBase: "ฝ" },
  { id: "c:พ", char: "พ", nameWord: "พาน", nameRom: "phɔɔ phaan", nameMeaning: { fr: "plateau à pied" }, cls: "L", initial: "ph", initialIPA: "pʰ", final: "p", audioBase: "พ" },
  { id: "c:ฟ", char: "ฟ", nameWord: "ฟัน", nameRom: "fɔɔ fan", nameMeaning: { fr: "dent" }, cls: "L", initial: "f", initialIPA: "f", final: "p", audioBase: "ฟ" },
  { id: "c:ภ", char: "ภ", nameWord: "สำเภา", nameRom: "phɔɔ sǎm-phao", nameMeaning: { fr: "jonque" }, cls: "L", initial: "ph", initialIPA: "pʰ", final: "p", audioBase: "พ" },
  { id: "c:ม", char: "ม", nameWord: "ม้า", nameRom: "mɔɔ máa", nameMeaning: { fr: "cheval" }, cls: "L", initial: "m", initialIPA: "m", final: "m", audioBase: "ม" },
  { id: "c:ย", char: "ย", nameWord: "ยักษ์", nameRom: "yɔɔ yák", nameMeaning: { fr: "géant, ogre" }, cls: "L", initial: "y", initialIPA: "j", final: "y", audioBase: "ย" },
  { id: "c:ร", char: "ร", nameWord: "เรือ", nameRom: "rɔɔ rʉa", nameMeaning: { fr: "bateau" }, cls: "L", initial: "r", initialIPA: "r", final: "n", audioBase: "ร" },
  { id: "c:ล", char: "ล", nameWord: "ลิง", nameRom: "lɔɔ ling", nameMeaning: { fr: "singe" }, cls: "L", initial: "l", initialIPA: "l", final: "n", audioBase: "ล" },
  { id: "c:ว", char: "ว", nameWord: "แหวน", nameRom: "wɔɔ wɛ̌ɛn", nameMeaning: { fr: "bague" }, cls: "L", initial: "w", initialIPA: "w", final: "w", audioBase: "ว" },
  { id: "c:ศ", char: "ศ", nameWord: "ศาลา", nameRom: "sɔ̌ɔ sǎa-laa", nameMeaning: { fr: "pavillon" }, cls: "H", initial: "s", initialIPA: "s", final: "t", audioBase: "ส" },
  { id: "c:ษ", char: "ษ", nameWord: "ฤๅษี", nameRom: "sɔ̌ɔ rʉʉ-sǐi", nameMeaning: { fr: "ermite" }, cls: "H", initial: "s", initialIPA: "s", final: "t", audioBase: "ส" },
  { id: "c:ส", char: "ส", nameWord: "เสือ", nameRom: "sɔ̌ɔ sʉ̌a", nameMeaning: { fr: "tigre" }, cls: "H", initial: "s", initialIPA: "s", final: "t", audioBase: "ส" },
  { id: "c:ห", char: "ห", nameWord: "หีบ", nameRom: "hɔ̌ɔ hìip", nameMeaning: { fr: "coffre" }, cls: "H", initial: "h", initialIPA: "h", final: "", audioBase: "ห", note: { fr: "Sert aussi de lettre muette pour faire passer une consonne basse en classe haute (ห นำ)." } },
  { id: "c:ฬ", char: "ฬ", nameWord: "จุฬา", nameRom: "lɔɔ jù-laa", nameMeaning: { fr: "cerf-volant" }, cls: "L", initial: "l", initialIPA: "l", final: "n", audioBase: "ล", note: { fr: "Rare." }, rare: true },
  { id: "c:อ", char: "อ", nameWord: "อ่าง", nameRom: "ɔɔ àang", nameMeaning: { fr: "bassine" }, cls: "M", initial: "(muet)", initialIPA: "ʔ", final: "", audioBase: "อ", note: { fr: "Support de voyelle : pas de son propre. Sert aussi à écrire la voyelle ɔɔ." } },
  { id: "c:ฮ", char: "ฮ", nameWord: "นกฮูก", nameRom: "hɔɔ nók-hûuk", nameMeaning: { fr: "hibou" }, cls: "L", initial: "h", initialIPA: "h", final: "", audioBase: "ฮ" },
];
