// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { Dialog } from '../types';
import { EXTRA_DIALOGS, EXTRA_DIALOG_FOR_THEME } from './dialogsExtra';
import { DIALOG_QUESTIONS } from './dialogQuestions';

/** Dialogue rattaché à un thème de vocabulaire dans le parcours. */
export const DIALOG_FOR_THEME: Record<string, string> = {"pres":"d:intro","eng":"d:site","work":"d:meeting","dir":"d:way","health":"d:pharm","drink":"d:cafe","hosp":"d:hosp","trans":"d:train","travel":"d:exchange","food":"d:lunch","out":"d:chat"};

export const DIALOGS: Dialog[] = [
  {
    id: "d:market", title: { fr: "Acheter au marché" }, icon: "🧺", other: { fr: "Vendeuse" },
    lines: [
      { who: "me", thai: "อันนี้เท่าไหร่{Q}", rom: "an-níi thâo-rài {q}", tr: { fr: "Combien coûte ceci ?" } },
      { who: "other", thai: "สองร้อยห้าสิบบาทค่ะ", rom: "sɔ̌ɔng-rɔ́ɔi hâa-sìp bàat khâ", tr: { fr: "Deux cent cinquante bahts." } },
      { who: "me", thai: "แพงไปหน่อย ลดได้ไหม{Q}", rom: "phɛɛng pai nɔ̀i lót dâai mái {q}", tr: { fr: "C'est un peu cher. Vous pouvez baisser ?" } },
      { who: "other", thai: "ลดให้ยี่สิบบาทค่ะ", rom: "lót hâi yîi-sìp bàat khâ", tr: { fr: "Je vous enlève vingt bahts." } },
      { who: "me", thai: "สองร้อยได้ไหม{Q}", rom: "sɔ̌ɔng-rɔ́ɔi dâai mái {q}", tr: { fr: "Deux cents, c'est possible ?" } },
      { who: "other", thai: "ได้ค่ะ เอากี่ตัวคะ", rom: "dâai khâ ao kìi tua khá", tr: { fr: "D'accord. Vous en prenez combien ?" } },
      { who: "me", thai: "เอาสองตัว{P}", rom: "ao sɔ̌ɔng tua {p}", tr: { fr: "J'en prends deux." } },
      { who: "other", thai: "ทั้งหมดสี่ร้อยบาทค่ะ ขอบคุณค่ะ", rom: "tháng-mòt sìi-rɔ́ɔi bàat khâ khɔ̀ɔp-khun khâ", tr: { fr: "Ça fait quatre cents bahts en tout. Merci." } },
    ],
  },
  {
    id: "d:resto", title: { fr: "Commander au restaurant" }, icon: "🍽️", other: { fr: "Serveur" },
    lines: [
      { who: "other", thai: "สวัสดีครับ กี่ท่านครับ", rom: "sà-wàt-dii khráp kìi thân khráp", tr: { fr: "Bonjour, combien de personnes ?" } },
      { who: "me", thai: "สองคน{P}", rom: "sɔ̌ɔng khon {p}", tr: { fr: "Deux personnes." } },
      { who: "other", thai: "รับอะไรดีครับ", rom: "ráp à-rai dii khráp", tr: { fr: "Que désirez-vous ?" } },
      { who: "me", thai: "ขอผัดไทยกุ้งหนึ่งจาน กับข้าวผัดไก่หนึ่งจาน{P}", rom: "khɔ̌ɔ phàt-thai kûng nʉ̀ng jaan kàp khâao-phàt kài nʉ̀ng jaan {p}", tr: { fr: "Un pad thaï aux crevettes et un riz sauté au poulet." } },
      { who: "other", thai: "เผ็ดไหมครับ", rom: "phèt mái khráp", tr: { fr: "Épicé ?" } },
      { who: "me", thai: "ไม่เผ็ด{P} แล้วก็ขอน้ำเปล่าสองขวด", rom: "mâi phèt {p} lɛ́ɛo-kɔ̂ɔ khɔ̌ɔ náam-plàao sɔ̌ɔng khùat", tr: { fr: "Pas épicé. Et aussi deux bouteilles d'eau." } },
      { who: "other", thai: "ได้ครับ รอสักครู่นะครับ", rom: "dâai khráp rɔɔ sàk-khrûu ná khráp", tr: { fr: "Très bien, un instant." } },
      { who: "me", thai: "เช็กบิลด้วย{P}", rom: "chék-bin dûai {p}", tr: { fr: "L'addition, s'il vous plaît." } },
    ],
  },
  {
    id: "d:taxi", title: { fr: "Taxi vers l'aéroport" }, icon: "🚕", other: { fr: "Chauffeur" },
    lines: [
      { who: "me", thai: "ไปสนามบินสุวรรณภูมิ{P}", rom: "pai sà-nǎam-bin sù-wan-ná-phuum {p}", tr: { fr: "À l'aéroport Suvarnabhumi, s'il vous plaît." } },
      { who: "other", thai: "ขึ้นทางด่วนไหมครับ", rom: "khʉ̂n thaang-dùan mái khráp", tr: { fr: "On prend la voie express ?" } },
      { who: "me", thai: "ขึ้น{P} ใช้เวลานานเท่าไหร่{Q}", rom: "khʉ̂n {p} chái wee-laa naan thâo-rài {q}", tr: { fr: "Oui. Ça prend combien de temps ?" } },
      { who: "other", thai: "ประมาณสี่สิบนาทีครับ รถติดนิดหน่อย", rom: "prà-maan sìi-sìp naa-thii khráp rót tìt nít-nɔ̀i", tr: { fr: "Environ quarante minutes. Il y a un peu d'embouteillage." } },
      { who: "me", thai: "เปิดมิเตอร์ด้วยนะ{Q}", rom: "pə̀ət mí-təə dûai ná {q}", tr: { fr: "Mettez le compteur, d'accord ?" } },
      { who: "other", thai: "ได้ครับ", rom: "dâai khráp", tr: { fr: "Bien sûr." } },
      { who: "me", thai: "จอดตรงนี้{P} เท่าไหร่{Q}", rom: "jɔ̀ɔt trong-níi {p} thâo-rài {q}", tr: { fr: "Arrêtez-vous ici. C'est combien ?" } },
      { who: "other", thai: "สามร้อยยี่สิบบาทครับ", rom: "sǎam-rɔ́ɔi yîi-sìp bàat khráp", tr: { fr: "Trois cent vingt bahts." } },
      { who: "me", thai: "ไม่ต้องทอน{P} ขอบคุณ{P}", rom: "mâi tɔ̂ng thɔɔn {p} khɔ̀ɔp-khun {p}", tr: { fr: "Gardez la monnaie. Merci." } },
    ],
  },
  {
    id: "d:hosp", title: { fr: "Rendre visite à l'hôpital" }, icon: "🏥", other: { fr: "Accueil" },
    lines: [
      { who: "me", thai: "ขอโทษ{P} {I}มาเยี่ยมคนไข้{P}", rom: "khɔ̌ɔ-thôot {p} {i} maa yîam khon-khâi {p}", tr: { fr: "Excusez-moi, je viens rendre visite à un patient." } },
      { who: "other", thai: "คนไข้ชื่ออะไรคะ", rom: "khon-khâi chʉ̂ʉ à-rai khá", tr: { fr: "Comment s'appelle le patient ?" } },
      { who: "me", thai: "ชื่อนี้{P}", rom: "chʉ̂ʉ níi {p}", tr: { fr: "Voici son nom. (en montrant le nom écrit)" } },
      { who: "other", thai: "อยู่ห้องห้าศูนย์สอง ชั้นห้าค่ะ", rom: "yùu hɔ̂ng hâa-sǔun-sɔ̌ɔng chán hâa khâ", tr: { fr: "Chambre 502, au cinquième niveau." } },
      { who: "me", thai: "ลิฟต์อยู่ที่ไหน{Q}", rom: "líp yùu thîi-nǎi {q}", tr: { fr: "Où est l'ascenseur ?" } },
      { who: "other", thai: "ตรงไปแล้วเลี้ยวซ้ายค่ะ", rom: "trong pai lɛ́ɛo líao sáai khâ", tr: { fr: "Tout droit, puis à gauche." } },
      { who: "me", thai: "เยี่ยมได้ถึงกี่โมง{Q}", rom: "yîam dâai thʉ̌ng kìi moong {q}", tr: { fr: "Jusqu'à quelle heure peut-on rendre visite ?" } },
      { who: "other", thai: "ถึงสองทุ่มค่ะ", rom: "thʉ̌ng sɔ̌ɔng thûm khâ", tr: { fr: "Jusqu'à vingt heures." } },
      { who: "me", thai: "ขอบคุณมาก{P}", rom: "khɔ̀ɔp-khun mâak {p}", tr: { fr: "Merci beaucoup." } },
    ],
  },
  {
    id: "d:intro", title: { fr: "Faire connaissance" }, icon: "👋", other: { fr: "Nouvelle connaissance" },
    lines: [
      { who: "other", thai: "สวัสดีค่ะ คุณชื่ออะไรคะ", rom: "sà-wàt-dii khâ khun chʉ̂ʉ à-rai khá", tr: { fr: "Bonjour. Comment vous appelez-vous ?" } },
      { who: "me", thai: "สวัสดี{P} {I}ชื่อ {N} {P}", rom: "sà-wàt-dii {p} {i} chʉ̂ʉ {n} {p}", tr: { fr: "Bonjour. Je m'appelle {n}." } },
      { who: "other", thai: "คุณมาจากประเทศอะไรคะ", rom: "khun maa jàak prà-thêet à-rai khá", tr: { fr: "De quel pays venez-vous ?" } },
      { who: "me", thai: "{I}มาจากประเทศเบลเยียม{P}", rom: "{i} maa jàak prà-thêet ben-yîam {p}", tr: { fr: "Je viens de Belgique." } },
      { who: "other", thai: "คุณทำงานอะไรคะ", rom: "khun tham-ngaan à-rai khá", tr: { fr: "Que faites-vous dans la vie ?" } },
      { who: "me", thai: "{I}เป็นวิศวกรโครงสร้าง{P}", rom: "{i} pen wít-sà-wá-kɔɔn khroong-sâang {p}", tr: { fr: "Je suis ingénieur en structure." } },
      { who: "other", thai: "พูดไทยเก่งมากค่ะ", rom: "phûut thai kèng mâak khâ", tr: { fr: "Vous parlez très bien thaï." } },
      { who: "me", thai: "ขอบคุณ{P} {I}พูดได้นิดหน่อย{P}", rom: "khɔ̀ɔp-khun {p} {i} phûut dâai nít-nɔ̀i {p}", tr: { fr: "Merci. Je parle juste un peu." } },
    ],
  },
  {
    id: "d:hotel", title: { fr: "Arriver à l'hôtel" }, icon: "🏨", other: { fr: "Réception" },
    lines: [
      { who: "me", thai: "สวัสดี{P} {I}จองห้องไว้แล้ว{P}", rom: "sà-wàt-dii {p} {i} jɔɔng hɔ̂ng wái lɛ́ɛo {p}", tr: { fr: "Bonjour, j'ai une réservation." } },
      { who: "other", thai: "ขอดูหนังสือเดินทางหน่อยค่ะ", rom: "khɔ̌ɔ duu nǎng-sʉ̌ʉ dəən-thaang nɔ̀i khâ", tr: { fr: "Puis-je voir votre passeport ?" } },
      { who: "me", thai: "นี่{P}", rom: "nîi {p}", tr: { fr: "Voici." } },
      { who: "other", thai: "พักสามคืนใช่ไหมคะ", rom: "phák sǎam khʉʉn châi mái khá", tr: { fr: "Vous restez trois nuits, c'est bien ça ?" } },
      { who: "me", thai: "ใช่{P} มีอาหารเช้าไหม{Q}", rom: "châi {p} mii aa-hǎan cháao mái {q}", tr: { fr: "Oui. Y a-t-il un petit déjeuner ?" } },
      { who: "other", thai: "มีค่ะ หกโมงเช้าถึงสิบโมงค่ะ", rom: "mii khâ hòk moong cháao thʉ̌ng sìp moong khâ", tr: { fr: "Oui, de six heures à dix heures." } },
      { who: "other", thai: "ห้องอยู่ชั้นสี่ นี่กุญแจค่ะ", rom: "hɔ̂ng yùu chán sìi nîi kun-jɛɛ khâ", tr: { fr: "La chambre est au quatrième niveau. Voici la clé." } },
      { who: "me", thai: "รหัสไวไฟอะไร{Q}", rom: "rá-hàt waai-faai à-rai {q}", tr: { fr: "Quel est le mot de passe du wifi ?" } },
    ],
  },
  {
    id: "d:site", title: { fr: "Inspection sur chantier" }, icon: "🏗️", other: { fr: "Chef de chantier" },
    lines: [
      { who: "me", thai: "สวัสดี{P} วันนี้{I}มาตรวจสอบโครงสร้าง{P}", rom: "sà-wàt-dii {p} wan-níi {i} maa trùat-sɔ̀ɔp khroong-sâang {p}", tr: { fr: "Bonjour. Aujourd'hui je viens inspecter la structure." } },
      { who: "other", thai: "ได้ครับ เชิญทางนี้ครับ", rom: "dâai khráp chəən thaang níi khráp", tr: { fr: "Très bien, par ici je vous prie." } },
      { who: "me", thai: "คานนี้มีรอยร้าว เห็นไหม{Q}", rom: "khaan níi mii rɔɔi-ráao hěn mái {q}", tr: { fr: "Cette poutre a une fissure, vous voyez ?" } },
      { who: "other", thai: "เห็นครับ มีปัญหาไหมครับ", rom: "hěn khráp mii pan-hǎa mái khráp", tr: { fr: "Je vois. C'est un problème ?" } },
      { who: "me", thai: "ต้องคำนวณใหม่ก่อน{P} ขอดูแบบหน่อย{P}", rom: "tɔ̂ng kham-nuan mài kɔ̀ɔn {p} khɔ̌ɔ duu bɛ̀ɛp nɔ̀i {p}", tr: { fr: "Il faut d'abord recalculer. Puis-je voir les plans ?" } },
      { who: "other", thai: "นี่ครับ แบบโครงสร้างชั้นสอง", rom: "nîi khráp bɛ̀ɛp khroong-sâang chán sɔ̌ɔng", tr: { fr: "Voici, les plans de structure du deuxième niveau." } },
      { who: "me", thai: "เหล็กเสริมขนาดเท่าไหร่{Q}", rom: "lèk-sə̌əm khà-nàat thâo-rài {q}", tr: { fr: "Quel est le diamètre des armatures ?" } },
      { who: "other", thai: "ยี่สิบมิลครับ", rom: "yîi-sìp min khráp", tr: { fr: "Vingt millimètres." } },
      { who: "me", thai: "อย่าเพิ่งเทคอนกรีตนะ{Q} รอผลตรวจก่อน", rom: "yàa phə̂ng thee khɔɔn-krìit ná {q} rɔɔ phǒn trùat kɔ̀ɔn", tr: { fr: "Ne coulez pas encore le béton. Attendez le résultat du contrôle." } },
    ],
  },
  {
    id: "d:meeting", title: { fr: "Réunion de chantier" }, icon: "📐", other: { fr: "Architecte" },
    lines: [
      { who: "other", thai: "ประชุมเริ่มกี่โมงคะ", rom: "prà-chum rə̂əm kìi moong khá", tr: { fr: "À quelle heure commence la réunion ?" } },
      { who: "me", thai: "เริ่มสิบโมง{P} ผู้รับเหมามาแล้วหรือยัง{Q}", rom: "rə̂əm sìp moong {p} phûu-ráp-mǎo maa lɛ́ɛo rʉ̌ʉ yang {q}", tr: { fr: "À dix heures. L'entrepreneur est-il déjà arrivé ?" } },
      { who: "other", thai: "มาแล้วค่ะ", rom: "maa lɛ́ɛo khâ", tr: { fr: "Oui, il est arrivé." } },
      { who: "me", thai: "วันนี้เราจะคุยเรื่องฐานรากกับเสาเข็ม{P}", rom: "wan-níi rao jà khui rʉ̂ang thǎan-râak kàp sǎo-khěm {p}", tr: { fr: "Aujourd'hui nous parlerons des fondations et des pieux." } },
      { who: "other", thai: "น้ำหนักบรรทุกเปลี่ยนไหมคะ", rom: "náam-nàk ban-thúk plìan mái khá", tr: { fr: "Les charges ont-elles changé ?" } },
      { who: "me", thai: "เปลี่ยน{P} ต้องเพิ่มเสาอีกสองต้น", rom: "plìan {p} tɔ̂ng phə̂əm sǎo ìik sɔ̌ɔng tôn", tr: { fr: "Oui. Il faut ajouter deux poteaux." } },
      { who: "other", thai: "ส่งรายการคำนวณให้ได้เมื่อไหร่คะ", rom: "sòng raai-kaan kham-nuan hâi dâai mʉ̂a-rài khá", tr: { fr: "Quand pouvez-vous envoyer la note de calcul ?" } },
      { who: "me", thai: "พรุ่งนี้{P}", rom: "phrûng-níi {p}", tr: { fr: "Demain." } },
    ],
  },
  {
    id: "d:way", title: { fr: "Demander son chemin" }, icon: "🧭", other: { fr: "Passant" },
    lines: [
      { who: "me", thai: "ขอโทษ{P} สถานีรถไฟฟ้าอยู่ที่ไหน{Q}", rom: "khɔ̌ɔ-thôot {p} sà-thǎa-nii rót-fai-fáa yùu thîi-nǎi {q}", tr: { fr: "Excusez-moi, où est la station de métro aérien ?" } },
      { who: "other", thai: "เดินตรงไป แล้วเลี้ยวขวาที่สี่แยกครับ", rom: "dəən trong pai lɛ́ɛo líao khwǎa thîi sìi-yɛ̂ɛk khráp", tr: { fr: "Marchez tout droit, puis tournez à droite au carrefour." } },
      { who: "me", thai: "ไกลไหม{Q}", rom: "klai mái {q}", tr: { fr: "C'est loin ?" } },
      { who: "other", thai: "ไม่ไกลครับ เดินประมาณห้านาที", rom: "mâi klai khráp dəən prà-maan hâa naa-thii", tr: { fr: "Non, environ cinq minutes à pied." } },
      { who: "me", thai: "ขอบคุณมาก{P}", rom: "khɔ̀ɔp-khun mâak {p}", tr: { fr: "Merci beaucoup." } },
      { who: "other", thai: "ไม่เป็นไรครับ", rom: "mâi-pen-rai khráp", tr: { fr: "De rien." } },
    ],
  },
  {
    id: "d:grab", title: { fr: "Le chauffeur Grab appelle" }, icon: "📱", other: { fr: "Chauffeur" },
    lines: [
      { who: "other", thai: "สวัสดีครับ คุณอยู่ตรงไหนครับ", rom: "sà-wàt-dii khráp khun yùu trong-nǎi khráp", tr: { fr: "Bonjour, vous êtes où exactement ?" } },
      { who: "me", thai: "{I}อยู่หน้าโรงแรม{P} ใส่เสื้อสีขาว", rom: "{i} yùu nâa roong-rɛɛm {p} sài sʉ̂a sǐi-khǎao", tr: { fr: "Je suis devant l'hôtel. Je porte un haut blanc." } },
      { who: "other", thai: "ครับ อีกสามนาทีถึงครับ", rom: "khráp ìik sǎam naa-thii thʉ̌ng khráp", tr: { fr: "D'accord, j'arrive dans trois minutes." } },
      { who: "me", thai: "รถสีอะไร{Q}", rom: "rót sǐi à-rai {q}", tr: { fr: "De quelle couleur est la voiture ?" } },
      { who: "other", thai: "สีดำครับ ทะเบียนหนึ่งสองสามสี่", rom: "sǐi-dam khráp thá-bian nʉ̀ng sɔ̌ɔng sǎam sìi", tr: { fr: "Noire. Plaque un-deux-trois-quatre." } },
      { who: "me", thai: "{I}รออยู่{P}", rom: "{i} rɔɔ yùu {p}", tr: { fr: "Je vous attends." } },
    ],
  },
  {
    id: "d:friends", title: { fr: "Sortir avec une amie" }, icon: "🎶", other: { fr: "Amie" },
    lines: [
      { who: "other", thai: "เย็นนี้ว่างไหม", rom: "yen-níi wâang mái", tr: { fr: "Tu es libre ce soir ?" } },
      { who: "me", thai: "ว่าง ทำไมเหรอ", rom: "wâang tham-mai rə̌ə", tr: { fr: "Oui, pourquoi ?" } },
      { who: "other", thai: "ไปกินข้าวกันไหม", rom: "pai kin khâao kan mái", tr: { fr: "On va manger ensemble ?" } },
      { who: "me", thai: "ไปสิ กินอะไรดี", rom: "pai sì kin à-rai dii", tr: { fr: "Allons-y ! On mange quoi ?" } },
      { who: "other", thai: "อาหารอีสานดีไหม", rom: "aa-hǎan ii-sǎan dii mái", tr: { fr: "De la cuisine de l'Isan, ça te dit ?" } },
      { who: "me", thai: "ดี {I}ชอบส้มตำ", rom: "dii {i} chɔ̂ɔp sôm-tam", tr: { fr: "Parfait, j'aime la salade de papaye." } },
      { who: "other", thai: "เจอกันหกโมงเย็นนะ", rom: "jəə kan hòk moong yen ná", tr: { fr: "On se retrouve à dix-huit heures." } },
      { who: "me", thai: "เจอกัน", rom: "jəə kan", tr: { fr: "À tout à l'heure." } },
    ],
  },
  {
    id: "d:pharm", title: { fr: "À la pharmacie" }, icon: "💊", other: { fr: "Pharmacienne" },
    lines: [
      { who: "me", thai: "สวัสดี{P} มียาแก้ปวดหัวไหม{Q}", rom: "sà-wàt-dii {p} mii yaa kɛ̂ɛ pùat-hǔa mái {q}", tr: { fr: "Bonjour, avez-vous un médicament contre le mal de tête ?" } },
      { who: "other", thai: "มีค่ะ เป็นมานานแค่ไหนแล้วคะ", rom: "mii khâ pen maa naan khɛ̂ɛ-nǎi lɛ́ɛo khá", tr: { fr: "Oui. Depuis combien de temps avez-vous mal ?" } },
      { who: "me", thai: "ตั้งแต่เมื่อวาน{P}", rom: "tâng-tɛ̀ɛ mʉ̂a-waan {p}", tr: { fr: "Depuis hier." } },
      { who: "other", thai: "มีไข้ไหมคะ", rom: "mii khâi mái khá", tr: { fr: "Avez-vous de la fièvre ?" } },
      { who: "me", thai: "ไม่มี{P} แต่ไอนิดหน่อย", rom: "mâi mii {p} tɛ̀ɛ ai nít-nɔ̀i", tr: { fr: "Non, mais je tousse un peu." } },
      { who: "other", thai: "แพ้ยาอะไรไหมคะ", rom: "phɛ́ɛ yaa à-rai mái khá", tr: { fr: "Êtes-vous allergique à un médicament ?" } },
      { who: "me", thai: "ไม่แพ้{P}", rom: "mâi phɛ́ɛ {p}", tr: { fr: "Non, à aucun." } },
      { who: "other", thai: "กินครั้งละหนึ่งเม็ด หลังอาหารนะคะ", rom: "kin khráng lá nʉ̀ng mét lǎng aa-hǎan ná khá", tr: { fr: "Un comprimé à la fois, après le repas." } },
      { who: "me", thai: "เท่าไหร่{Q}", rom: "thâo-rài {q}", tr: { fr: "C'est combien ?" } },
      { who: "other", thai: "หกสิบบาทค่ะ", rom: "hòk-sìp bàat khâ", tr: { fr: "Soixante bahts." } },
    ],
  },
  {
    id: "d:cafe", title: { fr: "Commander un café" }, icon: "☕", other: { fr: "Serveuse" },
    lines: [
      { who: "other", thai: "รับอะไรดีคะ", rom: "ráp à-rai dii khá", tr: { fr: "Que désirez-vous ?" } },
      { who: "me", thai: "เอากาแฟเย็นหนึ่งแก้ว{P}", rom: "ao kaa-fɛɛ yen nʉ̀ng kɛ̂ɛo {p}", tr: { fr: "Un café glacé, s'il vous plaît." } },
      { who: "other", thai: "หวานปกติไหมคะ", rom: "wǎan pòk-kà-tì mái khá", tr: { fr: "Sucré normalement ?" } },
      { who: "me", thai: "หวานน้อย{P}", rom: "wǎan nɔ́ɔi {p}", tr: { fr: "Peu sucré." } },
      { who: "other", thai: "ทานที่นี่หรือกลับบ้านคะ", rom: "thaan thîi-nîi rʉ̌ʉ klàp bâan khá", tr: { fr: "Sur place ou à emporter ?" } },
      { who: "me", thai: "กลับบ้าน{P}", rom: "klàp bâan {p}", tr: { fr: "À emporter." } },
      { who: "other", thai: "ห้าสิบห้าบาทค่ะ", rom: "hâa-sìp-hâa bàat khâ", tr: { fr: "Cinquante-cinq bahts." } },
      { who: "me", thai: "สแกนจ่ายได้ไหม{Q}", rom: "sà-kɛɛn jàai dâai mái {q}", tr: { fr: "Puis-je payer en scannant le QR code ?" } },
      { who: "other", thai: "ได้ค่ะ รอสักครู่นะคะ", rom: "dâai khâ rɔɔ sàk-khrûu ná khá", tr: { fr: "Oui. Un instant, s'il vous plaît." } },
    ],
  },
  {
    id: "d:visit", title: { fr: "Dans la chambre du patient" }, icon: "🛏️", other: { fr: "Ami" },
    lines: [
      { who: "me", thai: "เป็นยังไงบ้าง ดีขึ้นไหม", rom: "pen yang-ngai bâang dii-khʉ̂n mái", tr: { fr: "Comment ça va ? Tu vas mieux ?" } },
      { who: "other", thai: "ดีขึ้นแล้ว ขอบใจที่มาเยี่ยมนะ", rom: "dii-khʉ̂n lɛ́ɛo khɔ̀ɔp-jai thîi maa yîam ná", tr: { fr: "Ça va mieux. Merci de ta visite." } },
      { who: "me", thai: "ยังเจ็บอยู่ไหม", rom: "yang jèp yùu mái", tr: { fr: "Tu as encore mal ?" } },
      { who: "other", thai: "เจ็บนิดหน่อย แต่หมอบอกว่าไม่เป็นไร", rom: "jèp nít-nɔ̀i tɛ̀ɛ mɔ̌ɔ bɔ̀ɔk wâa mâi-pen-rai", tr: { fr: "Un peu, mais le médecin dit que ce n'est rien." } },
      { who: "me", thai: "กินข้าวได้ไหม", rom: "kin khâao dâai mái", tr: { fr: "Tu arrives à manger ?" } },
      { who: "other", thai: "ได้ แต่อาหารที่นี่ไม่อร่อยเลย", rom: "dâai tɛ̀ɛ aa-hǎan thîi-nîi mâi à-rɔ̀i ləəi", tr: { fr: "Oui, mais la nourriture d'ici n'est pas bonne du tout." } },
      { who: "me", thai: "{I}เอาผลไม้มาฝาก", rom: "{i} ao phǒn-lá-máai maa fàak", tr: { fr: "Je t'ai apporté des fruits." } },
      { who: "other", thai: "ขอบใจมาก", rom: "khɔ̀ɔp-jai mâak", tr: { fr: "Merci beaucoup." } },
      { who: "me", thai: "จะได้กลับบ้านเมื่อไหร่", rom: "jà dâai klàp bâan mʉ̂a-rài", tr: { fr: "Quand pourras-tu rentrer chez toi ?" } },
      { who: "other", thai: "หมอบอกว่าอีกสองสามวัน", rom: "mɔ̌ɔ bɔ̀ɔk wâa ìik sɔ̌ɔng sǎam wan", tr: { fr: "Le médecin dit : encore deux ou trois jours." } },
      { who: "me", thai: "พักผ่อนเยอะๆนะ หายเร็วๆ", rom: "phák-phɔ̀n yə́-yə́ ná hǎai reo-reo", tr: { fr: "Repose-toi bien. Guéris vite." } },
    ],
  },
  {
    id: "d:office", title: { fr: "Au bureau d'études" }, icon: "🗂️", other: { fr: "Collègue" },
    lines: [
      { who: "me", thai: "ขอโทษ{P} คุณมีแบบโครงสร้างล่าสุดไหม{Q}", rom: "khɔ̌ɔ-thôot {p} khun mii bɛ̀ɛp khroong-sâang lâa-sùt mái {q}", tr: { fr: "Excusez-moi, avez-vous les derniers plans de structure ?" } },
      { who: "other", thai: "มีค่ะ จะส่งให้วันนี้นะคะ", rom: "mii khâ jà sòng hâi wan-níi ná khá", tr: { fr: "Oui. Je vous les envoie aujourd'hui." } },
      { who: "me", thai: "ขอบคุณ{P} แล้วรายการคำนวณล่ะ{Q}", rom: "khɔ̀ɔp-khun {p} lɛ́ɛo raai-kaan kham-nuan lâ {q}", tr: { fr: "Merci. Et la note de calcul ?" } },
      { who: "other", thai: "ยังไม่เสร็จค่ะ พรุ่งนี้เช้าได้ไหมคะ", rom: "yang mâi sèt khâ phrûng-níi cháao dâai mái khá", tr: { fr: "Elle n'est pas encore terminée. Demain matin, ça irait ?" } },
      { who: "me", thai: "ได้{P} ไม่รีบ", rom: "dâai {p} mâi rîip", tr: { fr: "Oui, ce n'est pas pressé." } },
      { who: "other", thai: "มีอะไรให้ช่วยอีกไหมคะ", rom: "mii à-rai hâi chûai ìik mái khá", tr: { fr: "Puis-je vous aider pour autre chose ?" } },
      { who: "me", thai: "ช่วยนัดประชุมกับผู้รับเหมาให้หน่อย{P}", rom: "chûai nát prà-chum kàp phûu-ráp-mǎo hâi nɔ̀i {p}", tr: { fr: "Pourriez-vous fixer une réunion avec l'entrepreneur ?" } },
      { who: "other", thai: "วันศุกร์บ่ายสองโมงดีไหมคะ", rom: "wan-sùk bàai sɔ̌ɔng moong dii mái khá", tr: { fr: "Vendredi à quatorze heures, ça convient ?" } },
      { who: "me", thai: "ดีมาก{P} ขอบคุณ{P}", rom: "dii mâak {p} khɔ̀ɔp-khun {p}", tr: { fr: "Très bien, merci." } },
    ],
  },
  {
    id: "d:sim", title: { fr: "Acheter une carte SIM" }, icon: "📶", other: { fr: "Vendeuse" },
    lines: [
      { who: "me", thai: "สวัสดี{P} {I}อยากซื้อซิม{P}", rom: "sà-wàt-dii {p} {i} yàak sʉ́ʉ sim {p}", tr: { fr: "Bonjour, je voudrais acheter une carte SIM." } },
      { who: "other", thai: "ใช้กี่วันคะ", rom: "chái kìi wan khá", tr: { fr: "Pour combien de jours ?" } },
      { who: "me", thai: "สองอาทิตย์{P} มีเน็ตไม่อั้นไหม{Q}", rom: "sɔ̌ɔng aa-thít {p} mii nét mâi-ân mái {q}", tr: { fr: "Deux semaines. Avez-vous de l'Internet illimité ?" } },
      { who: "other", thai: "มีค่ะ สามสิบวัน สามร้อยบาทค่ะ", rom: "mii khâ sǎam-sìp wan sǎam-rɔ́ɔi bàat khâ", tr: { fr: "Oui. Trente jours, trois cents bahts." } },
      { who: "me", thai: "เอาอันนี้{P} ช่วยใส่ซิมให้ด้วยได้ไหม{Q}", rom: "ao an-níi {p} chûai sài sim hâi dûai dâai mái {q}", tr: { fr: "Je prends celle-ci. Pouvez-vous me l'installer ?" } },
      { who: "other", thai: "ได้ค่ะ ขอดูหนังสือเดินทางหน่อยค่ะ", rom: "dâai khâ khɔ̌ɔ duu nǎng-sʉ̌ʉ dəən-thaang nɔ̀i khâ", tr: { fr: "Bien sûr. Puis-je voir votre passeport ?" } },
      { who: "me", thai: "นี่{P} เบอร์โทรอะไร{Q}", rom: "nîi {p} bəə-thoo à-rai {q}", tr: { fr: "Voici. Quel est le numéro ?" } },
      { who: "other", thai: "เบอร์อยู่ที่ซองค่ะ ใช้ได้แล้วค่ะ", rom: "bəə yùu thîi sɔɔng khâ chái dâai lɛ́ɛo khâ", tr: { fr: "Le numéro est sur la pochette. C'est prêt." } },
    ],
  },
  {
    id: "d:seven", title: { fr: "À la supérette" }, icon: "🏪", other: { fr: "Caissière" },
    lines: [
      { who: "other", thai: "มีบัตรสมาชิกไหมคะ", rom: "mii bàt sà-maa-chík mái khá", tr: { fr: "Avez-vous la carte de membre ?" } },
      { who: "me", thai: "ไม่มี{P}", rom: "mâi mii {p}", tr: { fr: "Non." } },
      { who: "other", thai: "อุ่นไหมคะ", rom: "ùn mái khá", tr: { fr: "Je vous le réchauffe ?" } },
      { who: "me", thai: "อุ่นด้วย{P}", rom: "ùn dûai {p}", tr: { fr: "Oui, s'il vous plaît." } },
      { who: "other", thai: "รับถุงไหมคะ", rom: "ráp thǔng mái khá", tr: { fr: "Voulez-vous un sac ?" } },
      { who: "me", thai: "ไม่รับ{P}", rom: "mâi ráp {p}", tr: { fr: "Non merci." } },
      { who: "other", thai: "ทั้งหมดแปดสิบห้าบาทค่ะ", rom: "tháng-mòt pɛ̀ɛt-sìp-hâa bàat khâ", tr: { fr: "Quatre-vingt-cinq bahts en tout." } },
      { who: "me", thai: "สแกนจ่ายได้ไหม{Q}", rom: "sà-kɛɛn jàai dâai mái {q}", tr: { fr: "Puis-je payer en scannant ?" } },
      { who: "other", thai: "ได้ค่ะ ขอบคุณค่ะ", rom: "dâai khâ khɔ̀ɔp-khun khâ", tr: { fr: "Oui. Merci." } },
    ],
  },
  {
    id: "d:train", title: { fr: "Acheter un billet de train" }, icon: "🚆", other: { fr: "Guichet" },
    lines: [
      { who: "me", thai: "ขอตั๋วไปเชียงใหม่หนึ่งใบ{P}", rom: "khɔ̌ɔ tǔa pai chiang-mài nʉ̀ng bai {p}", tr: { fr: "Un billet pour Chiang Mai, s'il vous plaît." } },
      { who: "other", thai: "ไปวันไหนครับ", rom: "pai wan nǎi khráp", tr: { fr: "Pour quel jour ?" } },
      { who: "me", thai: "พรุ่งนี้{P} รถออกกี่โมง{Q}", rom: "phrûng-níi {p} rót ɔ̀ɔk kìi moong {q}", tr: { fr: "Demain. À quelle heure part le train ?" } },
      { who: "other", thai: "หกโมงเย็นครับ ถึงเจ็ดโมงเช้า", rom: "hòk moong yen khráp thʉ̌ng jèt moong cháao", tr: { fr: "À dix-huit heures. Arrivée à sept heures du matin." } },
      { who: "me", thai: "มีตู้นอนไหม{Q}", rom: "mii tûu-nɔɔn mái {q}", tr: { fr: "Y a-t-il un wagon-lit ?" } },
      { who: "other", thai: "มีครับ เที่ยวเดียวหรือไปกลับครับ", rom: "mii khráp thîao diao rʉ̌ʉ pai-klàp khráp", tr: { fr: "Oui. Aller simple ou aller-retour ?" } },
      { who: "me", thai: "เที่ยวเดียว{P} ขอที่นั่งริมหน้าต่าง", rom: "thîao diao {p} khɔ̌ɔ thîi-nâng rim nâa-tàang", tr: { fr: "Aller simple. Une place côté fenêtre." } },
      { who: "other", thai: "ชานชาลาห้าครับ", rom: "chaan-chaa-laa hâa khráp", tr: { fr: "Quai numéro cinq." } },
    ],
  },
  {
    id: "d:massage", title: { fr: "Au salon de massage" }, icon: "💆", other: { fr: "Masseuse" },
    lines: [
      { who: "me", thai: "นวดไทยหนึ่งชั่วโมงเท่าไหร่{Q}", rom: "nûat thai nʉ̀ng chûa-moong thâo-rài {q}", tr: { fr: "Combien coûte une heure de massage thaï ?" } },
      { who: "other", thai: "สามร้อยบาทค่ะ", rom: "sǎam-rɔ́ɔi bàat khâ", tr: { fr: "Trois cents bahts." } },
      { who: "me", thai: "{I}ปวดหลังกับปวดไหล่{P}", rom: "{i} pùat lǎng kàp pùat lài {p}", tr: { fr: "J'ai mal au dos et aux épaules." } },
      { who: "other", thai: "ได้ค่ะ เจ็บไหมคะ", rom: "dâai khâ jèp mái khá", tr: { fr: "D'accord. Ça fait mal ?" } },
      { who: "me", thai: "เจ็บนิดหน่อย เบาๆ หน่อย{P}", rom: "jèp nít-nɔ̀i bao-bao nɔ̀i {p}", tr: { fr: "Un peu. Plus doucement, s'il vous plaît." } },
      { who: "other", thai: "แบบนี้ดีไหมคะ", rom: "bɛ̀ɛp níi dii mái khá", tr: { fr: "Comme ça, c'est bien ?" } },
      { who: "me", thai: "ดี{P} สบายมาก", rom: "dii {p} sà-baai mâak", tr: { fr: "Oui, c'est très agréable." } },
    ],
  },
  {
    id: "d:scooter", title: { fr: "Louer un scooter" }, icon: "🛵", other: { fr: "Loueur" },
    lines: [
      { who: "me", thai: "{I}อยากเช่ามอเตอร์ไซค์{P} วันละเท่าไหร่{Q}", rom: "{i} yàak châo mɔɔ-təə-sai {p} wan lá thâo-rài {q}", tr: { fr: "Je voudrais louer un scooter. C'est combien par jour ?" } },
      { who: "other", thai: "วันละสองร้อยห้าสิบบาทครับ", rom: "wan lá sɔ̌ɔng-rɔ́ɔi hâa-sìp bàat khráp", tr: { fr: "Deux cent cinquante bahts par jour." } },
      { who: "me", thai: "เช่าสามวัน{P} มีหมวกกันน็อกไหม{Q}", rom: "châo sǎam wan {p} mii mùak kan-nɔ́k mái {q}", tr: { fr: "Trois jours. Avez-vous un casque ?" } },
      { who: "other", thai: "มีครับ ขอดูใบขับขี่หน่อยครับ", rom: "mii khráp khɔ̌ɔ duu bai-khàp-khìi nɔ̀i khráp", tr: { fr: "Oui. Puis-je voir votre permis ?" } },
      { who: "me", thai: "นี่{P} ต้องมัดจำไหม{Q}", rom: "nîi {p} tɔ̂ng mát-jam mái {q}", tr: { fr: "Voici. Faut-il une caution ?" } },
      { who: "other", thai: "มัดจำสองพันบาทครับ", rom: "mát-jam sɔ̌ɔng-phan bàat khráp", tr: { fr: "Deux mille bahts de caution." } },
      { who: "me", thai: "ต้องคืนรถกี่โมง{Q}", rom: "tɔ̂ng khʉʉn rót kìi moong {q}", tr: { fr: "À quelle heure faut-il le rendre ?" } },
      { who: "other", thai: "ก่อนหกโมงเย็นครับ เติมน้ำมันเต็มถังด้วยนะครับ", rom: "kɔ̀ɔn hòk moong yen khráp təəm náam-man tem thǎng dûai ná khráp", tr: { fr: "Avant dix-huit heures. Et avec le plein, s'il vous plaît." } },
    ],
  },
  {
    id: "d:doctor", title: { fr: "Chez le médecin" }, icon: "🩺", other: { fr: "Médecin" },
    lines: [
      { who: "other", thai: "เป็นอะไรมาครับ", rom: "pen à-rai maa khráp", tr: { fr: "Qu'est-ce qui vous amène ?" } },
      { who: "me", thai: "{I}ปวดท้องกับท้องเสีย{P}", rom: "{i} pùat-thɔ́ɔng kàp thɔ́ɔng-sǐa {p}", tr: { fr: "J'ai mal au ventre et la diarrhée." } },
      { who: "other", thai: "เป็นตั้งแต่เมื่อไหร่ครับ", rom: "pen tâng-tɛ̀ɛ mʉ̂a-rài khráp", tr: { fr: "Depuis quand ?" } },
      { who: "me", thai: "ตั้งแต่เมื่อคืน{P}", rom: "tâng-tɛ̀ɛ mʉ̂a-khʉʉn {p}", tr: { fr: "Depuis hier soir." } },
      { who: "other", thai: "แพ้ยาอะไรไหมครับ", rom: "phɛ́ɛ yaa à-rai mái khráp", tr: { fr: "Êtes-vous allergique à un médicament ?" } },
      { who: "me", thai: "ไม่แพ้{P}", rom: "mâi phɛ́ɛ {p}", tr: { fr: "Non." } },
      { who: "other", thai: "กินยานี้หลังอาหาร วันละสามครั้งครับ", rom: "kin yaa níi lǎng aa-hǎan wan lá sǎam khráng khráp", tr: { fr: "Prenez ce médicament après les repas, trois fois par jour." } },
      { who: "other", thai: "ดื่มน้ำเยอะๆ ถ้าไม่ดีขึ้น กลับมาใหม่นะครับ", rom: "dʉ̀ʉm náam yə́-yə́ thâa mâi dii-khʉ̂n klàp maa mài ná khráp", tr: { fr: "Buvez beaucoup d'eau. Si ça ne va pas mieux, revenez." } },
      { who: "me", thai: "ขอบคุณ{P}คุณหมอ", rom: "khɔ̀ɔp-khun {p} khun mɔ̌ɔ", tr: { fr: "Merci, docteur." } },
    ],
  },
  {
    id: "d:exchange", title: { fr: "Changer de l'argent" }, icon: "💶", other: { fr: "Guichetière" },
    lines: [
      { who: "me", thai: "{I}อยากแลกเงิน{P} วันนี้ยูโรละเท่าไหร่{Q}", rom: "{i} yàak lɛ̂ɛk ngən {p} wan-níi yuu-roo lá thâo-rài {q}", tr: { fr: "Je voudrais changer de l'argent. À combien est l'euro aujourd'hui ?" } },
      { who: "other", thai: "สามสิบแปดบาทค่ะ", rom: "sǎam-sìp-pɛ̀ɛt bàat khâ", tr: { fr: "Trente-huit bahts." } },
      { who: "me", thai: "แลกสองร้อยยูโร{P}", rom: "lɛ̂ɛk sɔ̌ɔng-rɔ́ɔi yuu-roo {p}", tr: { fr: "Je change deux cents euros." } },
      { who: "other", thai: "ขอดูหนังสือเดินทางหน่อยค่ะ", rom: "khɔ̌ɔ duu nǎng-sʉ̌ʉ dəən-thaang nɔ̀i khâ", tr: { fr: "Puis-je voir votre passeport ?" } },
      { who: "me", thai: "นี่{P} ขอแบงก์ย่อยด้วยได้ไหม{Q}", rom: "nîi {p} khɔ̌ɔ bɛ́ng yɔ̂i dûai dâai mái {q}", tr: { fr: "Voici. Puis-je avoir aussi des petites coupures ?" } },
      { who: "other", thai: "ได้ค่ะ นับดูก่อนนะคะ", rom: "dâai khâ náp duu kɔ̀ɔn ná khá", tr: { fr: "Bien sûr. Recomptez avant de partir." } },
      { who: "me", thai: "ครบ{P} ขอบคุณ{P}", rom: "khróp {p} khɔ̀ɔp-khun {p}", tr: { fr: "Le compte y est. Merci." } },
    ],
  },
  {
    id: "d:lunch", title: { fr: "Déjeuner avec un collègue" }, icon: "🍱", other: { fr: "Collègue" },
    lines: [
      { who: "other", thai: "ไปกินข้าวเที่ยงกันไหม", rom: "pai kin khâao-thîang kan mái", tr: { fr: "On va déjeuner ensemble ?" } },
      { who: "me", thai: "ไปสิ รอแป๊บนึงนะ งานยังไม่เสร็จ", rom: "pai sì rɔɔ pɛ́p nʉng ná ngaan yang mâi sèt", tr: { fr: "Oui ! Attends une minute, je n'ai pas fini." } },
      { who: "other", thai: "กินอะไรดี", rom: "kin à-rai dii", tr: { fr: "On mange quoi ?" } },
      { who: "me", thai: "ร้านข้าวมันไก่ดีไหม ใกล้ๆ นี่เอง", rom: "ráan khâao-man-kài dii mái klâi-klâi nîi eeng", tr: { fr: "Le resto de riz au poulet, ça te va ? C'est tout près." } },
      { who: "other", thai: "ดี วันนี้ร้อนมาก ไม่อยากเดินไกล", rom: "dii wan-níi rɔ́ɔn mâak mâi yàak dəən klai", tr: { fr: "Parfait. Il fait très chaud, je n'ai pas envie de marcher loin." } },
      { who: "me", thai: "วันนี้{I}เลี้ยงเอง", rom: "wan-níi {i} líang eeng", tr: { fr: "Aujourd'hui, c'est moi qui invite." } },
      { who: "other", thai: "ขอบคุณมาก คราวหน้าเราเลี้ยงนะ", rom: "khɔ̀ɔp-khun mâak khraao nâa rao líang ná", tr: { fr: "Merci beaucoup. La prochaine fois, c'est pour moi." } },
    ],
  },
  {
    id: "d:pour", title: { fr: "Coulage du béton" }, icon: "🚧", other: { fr: "Chef de chantier" },
    lines: [
      { who: "me", thai: "วันนี้เทคอนกรีตกี่โมง{Q}", rom: "wan-níi thee khɔɔn-krìit kìi moong {q}", tr: { fr: "À quelle heure coule-t-on le béton aujourd'hui ?" } },
      { who: "other", thai: "เก้าโมงครับ รถปูนมาถึงแล้ว", rom: "kâao moong khráp rót puun maa thʉ̌ng lɛ́ɛo", tr: { fr: "À neuf heures. Le camion-toupie est déjà arrivé." } },
      { who: "me", thai: "ตรวจเหล็กเสริมแล้วหรือยัง{Q}", rom: "trùat lèk-sə̌əm lɛ́ɛo rʉ̌ʉ yang {q}", tr: { fr: "Les armatures ont-elles déjà été contrôlées ?" } },
      { who: "other", thai: "ตรวจแล้วครับ เรียบร้อยดี", rom: "trùat lɛ́ɛo khráp rîap-rɔ́ɔi dii", tr: { fr: "Oui, tout est en ordre." } },
      { who: "me", thai: "อย่าลืมเก็บตัวอย่างคอนกรีตนะ{Q}", rom: "yàa lʉʉm kèp tua-yàang khɔɔn-krìit ná {q}", tr: { fr: "N'oubliez pas de prélever des échantillons de béton." } },
      { who: "other", thai: "ครับ ทดสอบกำลังอัดที่เจ็ดวันกับยี่สิบแปดวัน", rom: "khráp thót-sɔ̀ɔp kam-lang àt thîi jèt wan kàp yîi-sìp-pɛ̀ɛt wan", tr: { fr: "Oui. Essais de compression à sept et à vingt-huit jours." } },
      { who: "me", thai: "ดี{P} แล้วต้องบ่มคอนกรีตเจ็ดวันด้วย", rom: "dii {p} lɛ́ɛo tɔ̂ng bòm khɔɔn-krìit jèt wan dûai", tr: { fr: "Bien. Et il faut aussi une cure du béton de sept jours." } },
      { who: "other", thai: "ได้ครับ ทุกคนใส่หมวกนิรภัยแล้วครับ", rom: "dâai khráp thúk khon sài mùak ní-rá-phai lɛ́ɛo khráp", tr: { fr: "Entendu. Tout le monde porte son casque." } },
    ],
  },
  {
    id: "d:phone", title: { fr: "Au téléphone" }, icon: "☎️", other: { fr: "Standardiste" },
    lines: [
      { who: "other", thai: "ฮัลโหล สวัสดีค่ะ", rom: "han-lǒo sà-wàt-dii khâ", tr: { fr: "Allô, bonjour." } },
      { who: "me", thai: "สวัสดี{P} ขอสายคุณสมชายหน่อย{P}", rom: "sà-wàt-dii {p} khɔ̌ɔ sǎai khun sǒm-chaai nɔ̀i {p}", tr: { fr: "Bonjour. Pourrais-je parler à Khun Somchai ?" } },
      { who: "other", thai: "ใครพูดคะ", rom: "khrai phûut khá", tr: { fr: "C'est de la part de qui ?" } },
      { who: "me", thai: "{I}ชื่อ {N} {P}", rom: "{i} chʉ̂ʉ {n} {p}", tr: { fr: "Je m'appelle {n}." } },
      { who: "other", thai: "สักครู่นะคะ ตอนนี้คุณสมชายไม่อยู่ค่ะ", rom: "sàk-khrûu ná khá tɔɔn-níi khun sǒm-chaai mâi yùu khâ", tr: { fr: "Un instant… Khun Somchai n'est pas là pour le moment." } },
      { who: "me", thai: "ฝากข้อความได้ไหม{Q}", rom: "fàak khɔ̂ɔ-khwaam dâai mái {q}", tr: { fr: "Puis-je laisser un message ?" } },
      { who: "other", thai: "ได้ค่ะ", rom: "dâai khâ", tr: { fr: "Bien sûr." } },
      { who: "me", thai: "ช่วยบอกให้โทรกลับด้วย{P} ขอบคุณ{P}", rom: "chûai bɔ̀ɔk hâi thoo klàp dûai {p} khɔ̀ɔp-khun {p}", tr: { fr: "Dites-lui de me rappeler, s'il vous plaît. Merci." } },
    ],
  },
  {
    id: "d:chat", title: { fr: "Bavarder avec le chauffeur" }, icon: "🗨️", other: { fr: "Chauffeur" },
    lines: [
      { who: "other", thai: "มาเที่ยวหรือมาทำงานครับ", rom: "maa thîao rʉ̌ʉ maa tham-ngaan khráp", tr: { fr: "Vous êtes ici en vacances ou pour le travail ?" } },
      { who: "me", thai: "มาทำงาน{P} แล้วก็มาเยี่ยมเพื่อนด้วย", rom: "maa tham-ngaan {p} lɛ́ɛo-kɔ̂ɔ maa yîam phʉ̂an dûai", tr: { fr: "Pour le travail, et aussi pour rendre visite à un ami." } },
      { who: "other", thai: "อยู่เมืองไทยนานไหมครับ", rom: "yùu mʉang-thai naan mái khráp", tr: { fr: "Vous restez longtemps en Thaïlande ?" } },
      { who: "me", thai: "สองอาทิตย์{P}", rom: "sɔ̌ɔng aa-thít {p}", tr: { fr: "Deux semaines." } },
      { who: "other", thai: "พูดไทยได้ด้วย เก่งมากครับ", rom: "phûut thai dâai dûai kèng mâak khráp", tr: { fr: "Et vous parlez thaï, bravo !" } },
      { who: "me", thai: "ขอบคุณ{P} {I}กำลังเรียนอยู่{P}", rom: "khɔ̀ɔp-khun {p} {i} kam-lang rian yùu {p}", tr: { fr: "Merci. Je suis en train d'apprendre." } },
      { who: "other", thai: "ชอบอาหารไทยไหมครับ", rom: "chɔ̂ɔp aa-hǎan thai mái khráp", tr: { fr: "Vous aimez la cuisine thaïe ?" } },
      { who: "me", thai: "ชอบมาก{P} แต่กินเผ็ดไม่ค่อยได้", rom: "chɔ̂ɔp mâak {p} tɛ̀ɛ kin phèt mâi khɔ̂i dâai", tr: { fr: "Beaucoup. Mais je supporte mal le piment." } },
    ],
  },
];

DIALOGS.push(...EXTRA_DIALOGS);
Object.assign(DIALOG_FOR_THEME, EXTRA_DIALOG_FOR_THEME);
// Questions de compréhension orale rédigées, rattachées à chaque dialogue
for (const d of DIALOGS) if (DIALOG_QUESTIONS[d.id]) d.questions = DIALOG_QUESTIONS[d.id];
