// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { GlossEntry } from '../types';

/** Mots-outils et mots très fréquents : sert au découpage « mot à mot » des phrases. */
export const GLOSS: GlossEntry[] = [
  { thai: "ครับ", rom: "khráp", meaning: { fr: "(politesse, homme)" } },
  { thai: "ค่ะ", rom: "khâ", meaning: { fr: "(politesse, femme)" } },
  { thai: "คะ", rom: "khá", meaning: { fr: "(politesse, question)" } },
  { thai: "ผม", rom: "phǒm", meaning: { fr: "je (homme)" } },
  { thai: "ฉัน", rom: "chǎn", meaning: { fr: "je (femme)" } },
  { thai: "นะ", rom: "ná", meaning: { fr: "(adoucit)" } },
  { thai: "ไหม", rom: "mái", meaning: { fr: "(question)" } },
  { thai: "หน่อย", rom: "nɔ̀i", meaning: { fr: "un peu, s'il vous plaît" } },
  { thai: "ด้วย", rom: "dûai", meaning: { fr: "aussi ; s'il vous plaît" } },
  { thai: "ได้", rom: "dâai", meaning: { fr: "pouvoir" } },
  { thai: "ขอ", rom: "khɔ̌ɔ", meaning: { fr: "je voudrais" } },
  { thai: "ช่วย", rom: "chûai", meaning: { fr: "aider ; pourriez-vous" } },
  { thai: "ให้", rom: "hâi", meaning: { fr: "donner ; pour" } },
  { thai: "จะ", rom: "jà", meaning: { fr: "(futur)" } },
  { thai: "แล้ว", rom: "lɛ́ɛo", meaning: { fr: "déjà ; puis" } },
  { thai: "ก็", rom: "kɔ̂ɔ", meaning: { fr: "aussi, alors" } },
  { thai: "ที่", rom: "thîi", meaning: { fr: "à ; qui, que" } },
  { thai: "นี้", rom: "níi", meaning: { fr: "ce…-ci" } },
  { thai: "นั้น", rom: "nán", meaning: { fr: "ce…-là" } },
  { thai: "นี่", rom: "nîi", meaning: { fr: "ceci, voici" } },
  { thai: "อยู่", rom: "yùu", meaning: { fr: "se trouver" } },
  { thai: "ไหน", rom: "nǎi", meaning: { fr: "quel ; où" } },
  { thai: "ที่ไหน", rom: "thîi-nǎi", meaning: { fr: "où" } },
  { thai: "กี่", rom: "kìi", meaning: { fr: "combien de" } },
  { thai: "อีก", rom: "ìik", meaning: { fr: "encore" } },
  { thai: "ละ", rom: "lá", meaning: { fr: "par, chaque" } },
  { thai: "เท่าไหร่", rom: "thâo-rài", meaning: { fr: "combien" } },
  { thai: "อะไร", rom: "à-rai", meaning: { fr: "quoi" } },
  { thai: "ยังไง", rom: "yang-ngai", meaning: { fr: "comment" } },
  { thai: "เมื่อไหร่", rom: "mʉ̂a-rài", meaning: { fr: "quand" } },
  { thai: "ใคร", rom: "khrai", meaning: { fr: "qui" } },
  { thai: "ทำไม", rom: "tham-mai", meaning: { fr: "pourquoi" } },
  { thai: "ไม่", rom: "mâi", meaning: { fr: "ne… pas" } },
  { thai: "ใช่", rom: "châi", meaning: { fr: "oui, c'est ça" } },
  { thai: "หรือ", rom: "rʉ̌ʉ", meaning: { fr: "ou" } },
  { thai: "ยัง", rom: "yang", meaning: { fr: "encore ; pas encore" } },
  { thai: "กับ", rom: "kàp", meaning: { fr: "avec, et" } },
  { thai: "และ", rom: "lɛ́", meaning: { fr: "et" } },
  { thai: "แต่", rom: "tɛ̀ɛ", meaning: { fr: "mais" } },
  { thai: "ของ", rom: "khɔ̌ɔng", meaning: { fr: "de (possession) ; chose" } },
  { thai: "ใน", rom: "nai", meaning: { fr: "dans" } },
  { thai: "จาก", rom: "jàak", meaning: { fr: "de, depuis" } },
  { thai: "ถึง", rom: "thʉ̌ng", meaning: { fr: "jusqu'à ; arriver" } },
  { thai: "ไป", rom: "pai", meaning: { fr: "aller" } },
  { thai: "มา", rom: "maa", meaning: { fr: "venir" } },
  { thai: "มี", rom: "mii", meaning: { fr: "avoir, il y a" } },
  { thai: "เป็น", rom: "pen", meaning: { fr: "être" } },
  { thai: "คือ", rom: "khʉʉ", meaning: { fr: "c'est" } },
  { thai: "เอา", rom: "ao", meaning: { fr: "prendre, vouloir" } },
  { thai: "อยาก", rom: "yàak", meaning: { fr: "avoir envie de" } },
  { thai: "ต้อง", rom: "tɔ̂ng", meaning: { fr: "devoir" } },
  { thai: "กำลัง", rom: "kam-lang", meaning: { fr: "en train de" } },
  { thai: "เคย", rom: "khəəi", meaning: { fr: "avoir déjà…" } },
  { thai: "มาก", rom: "mâak", meaning: { fr: "très, beaucoup" } },
  { thai: "นิดหน่อย", rom: "nít-nɔ̀i", meaning: { fr: "un peu" } },
  { thai: "เกินไป", rom: "kəən pai", meaning: { fr: "trop" } },
  { thai: "กว่า", rom: "kwàa", meaning: { fr: "plus… que" } },
  { thai: "ที่สุด", rom: "thîi-sùt", meaning: { fr: "le plus" } },
  { thai: "ตรงนี้", rom: "trong-níi", meaning: { fr: "ici même" } },
  { thai: "ตรงไหน", rom: "trong-nǎi", meaning: { fr: "où exactement" } },
  { thai: "ที่นี่", rom: "thîi-nîi", meaning: { fr: "ici" } },
  { thai: "ที่นั่น", rom: "thîi-nân", meaning: { fr: "là-bas" } },
  { thai: "วันนี้", rom: "wan-níi", meaning: { fr: "aujourd'hui" } },
  { thai: "พรุ่งนี้", rom: "phrûng-níi", meaning: { fr: "demain" } },
  { thai: "ตอนนี้", rom: "tɔɔn-níi", meaning: { fr: "maintenant" } },
  { thai: "คุณ", rom: "khun", meaning: { fr: "vous" } },
  { thai: "เขา", rom: "khǎo", meaning: { fr: "il, elle" } },
  { thai: "เรา", rom: "rao", meaning: { fr: "nous" } },
  { thai: "อัน", rom: "an", meaning: { fr: "(classif. objet)" } },
  { thai: "อันนี้", rom: "an-níi", meaning: { fr: "celui-ci" } },
  { thai: "อันนั้น", rom: "an-nán", meaning: { fr: "celui-là" } },
  { thai: "อันไหน", rom: "an-nǎi", meaning: { fr: "lequel" } },
  { thai: "คน", rom: "khon", meaning: { fr: "personne" } },
  { thai: "บาท", rom: "bàat", meaning: { fr: "baht" } },
  { thai: "โมง", rom: "moong", meaning: { fr: "heure" } },
  { thai: "นาที", rom: "naa-thii", meaning: { fr: "minute" } },
  { thai: "ชั่วโมง", rom: "chûa-moong", meaning: { fr: "heure (durée)" } },
  { thai: "วัน", rom: "wan", meaning: { fr: "jour" } },
  { thai: "คืน", rom: "khʉʉn", meaning: { fr: "nuit ; rendre" } },
  { thai: "สิบ", rom: "sìp", meaning: { fr: "dix" } },
  { thai: "ร้อย", rom: "rɔ́ɔi", meaning: { fr: "cent" } },
  { thai: "พัน", rom: "phan", meaning: { fr: "mille" } },
  { thai: "หมื่น", rom: "mʉ̀ʉn", meaning: { fr: "dix mille" } },
  { thai: "แสน", rom: "sɛ̌ɛn", meaning: { fr: "cent mille" } },
  { thai: "ล้าน", rom: "láan", meaning: { fr: "million" } },
  { thai: "ยี่", rom: "yîi", meaning: { fr: "vingt- (dans 20)" } },
  { thai: "เอ็ด", rom: "èt", meaning: { fr: "-et-un" } },
  { thai: "ขอบคุณ", rom: "khɔ̀ɔp-khun", meaning: { fr: "merci" } },
  { thai: "ขอโทษ", rom: "khɔ̌ɔ-thôot", meaning: { fr: "pardon" } },
  { thai: "สวัสดี", rom: "sà-wàt-dii", meaning: { fr: "bonjour" } },
  { thai: "ไม่เป็นไร", rom: "mâi-pen-rai", meaning: { fr: "ce n'est rien" } },
  { thai: "เชิญ", rom: "chəən", meaning: { fr: "je vous en prie" } },
  { thai: "รอ", rom: "rɔɔ", meaning: { fr: "attendre" } },
  { thai: "สักครู่", rom: "sàk-khrûu", meaning: { fr: "un instant" } },
  { thai: "ก่อน", rom: "kɔ̀ɔn", meaning: { fr: "d'abord, avant" } },
  { thai: "หลัง", rom: "lǎng", meaning: { fr: "après, derrière" } },
  { thai: "เลย", rom: "ləəi", meaning: { fr: "vraiment ; du tout" } },
  { thai: "จัง", rom: "jang", meaning: { fr: "tellement" } },
  { thai: "บ้าง", rom: "bâang", meaning: { fr: "un peu, quelques" } },
  { thai: "เอง", rom: "eeng", meaning: { fr: "soi-même" } },
  { thai: "ด้วยกัน", rom: "dûai-kan", meaning: { fr: "ensemble" } },
  { thai: "กัน", rom: "kan", meaning: { fr: "ensemble" } },
  { thai: "ว่า", rom: "wâa", meaning: { fr: "que ; dire" } },
  { thai: "ถ้า", rom: "thâa", meaning: { fr: "si" } },
  { thai: "เพราะ", rom: "phrɔ́", meaning: { fr: "parce que" } },
  { thai: "โทร", rom: "thoo", meaning: { fr: "téléphoner" } },
  { thai: "ดู", rom: "duu", meaning: { fr: "regarder" } },
  { thai: "บอก", rom: "bɔ̀ɔk", meaning: { fr: "dire" } },
  { thai: "พูด", rom: "phûut", meaning: { fr: "parler" } },
  { thai: "เข้า", rom: "khâo", meaning: { fr: "entrer" } },
  { thai: "ออก", rom: "ɔ̀ɔk", meaning: { fr: "sortir" } },
  { thai: "ใส่", rom: "sài", meaning: { fr: "mettre" } },
  { thai: "ใช้", rom: "chái", meaning: { fr: "utiliser" } },
  { thai: "ทำ", rom: "tham", meaning: { fr: "faire" } },
  { thai: "รับ", rom: "ráp", meaning: { fr: "recevoir, prendre" } },
  { thai: "จ่าย", rom: "jàai", meaning: { fr: "payer" } },
  { thai: "ซื้อ", rom: "sʉ́ʉ", meaning: { fr: "acheter" } },
  { thai: "ขาย", rom: "khǎai", meaning: { fr: "vendre" } },
  { thai: "ลด", rom: "lót", meaning: { fr: "baisser" } },
  { thai: "เปิด", rom: "pə̀ət", meaning: { fr: "ouvrir, allumer" } },
  { thai: "ปิด", rom: "pìt", meaning: { fr: "fermer, éteindre" } },
  { thai: "จอด", rom: "jɔ̀ɔt", meaning: { fr: "s'arrêter, se garer" } },
  { thai: "เลี้ยว", rom: "líao", meaning: { fr: "tourner" } },
  { thai: "ตรง", rom: "trong", meaning: { fr: "droit" } },
  { thai: "ซ้าย", rom: "sáai", meaning: { fr: "gauche" } },
  { thai: "ขวา", rom: "khwǎa", meaning: { fr: "droite" } },
  { thai: "หน้า", rom: "nâa", meaning: { fr: "devant ; visage" } },
  { thai: "ข้างหน้า", rom: "khâang-nâa", meaning: { fr: "devant" } },
  { thai: "เวลา", rom: "wee-laa", meaning: { fr: "temps" } },
  { thai: "ห้อง", rom: "hɔ̂ng", meaning: { fr: "pièce, chambre" } },
  { thai: "ชั้น", rom: "chán", meaning: { fr: "étage, niveau" } },
  { thai: "เยี่ยม", rom: "yîam", meaning: { fr: "rendre visite" } },
  { thai: "คนไข้", rom: "khon-khâi", meaning: { fr: "patient" } },
  { thai: "หมอ", rom: "mɔ̌ɔ", meaning: { fr: "médecin" } },
  { thai: "อาการ", rom: "aa-kaan", meaning: { fr: "état, symptômes" } },
  { thai: "ดีขึ้น", rom: "dii-khʉ̂n", meaning: { fr: "s'améliorer" } },
  { thai: "เหล็ก", rom: "lèk", meaning: { fr: "acier" } },
  { thai: "เสริม", rom: "sə̌əm", meaning: { fr: "renforcer" } },
  { thai: "เพิ่ม", rom: "phə̂əm", meaning: { fr: "ajouter" } },
  { thai: "ตรวจ", rom: "trùat", meaning: { fr: "contrôler" } },
  { thai: "แบบ", rom: "bɛ̀ɛp", meaning: { fr: "plan ; modèle" } },
  { thai: "งาน", rom: "ngaan", meaning: { fr: "travail" } },
  { thai: "เสร็จ", rom: "sèt", meaning: { fr: "fini" } },
  { thai: "หยุด", rom: "yùt", meaning: { fr: "arrêter" } },
  { thai: "สบาย", rom: "sà-baai", meaning: { fr: "à l'aise, bien" } },
  { thai: "ประเทศ", rom: "prà-thêet", meaning: { fr: "pays" } },
  { thai: "นาน", rom: "naan", meaning: { fr: "longtemps" } },
  { thai: "เยอะ", rom: "yə́", meaning: { fr: "beaucoup" } },
  { thai: "เลี้ยง", rom: "líang", meaning: { fr: "inviter, offrir" } },
  { thai: "ตั้งแต่", rom: "tâng-tɛ̀ɛ", meaning: { fr: "depuis" } },
  { thai: "เข้าใจ", rom: "khâo-jai", meaning: { fr: "comprendre" } },
  { thai: "ยินดี", rom: "yin-dii", meaning: { fr: "ravi" } },
  { thai: "รู้จัก", rom: "rúu-jàk", meaning: { fr: "connaître" } },
  { thai: "อายุ", rom: "aa-yú", meaning: { fr: "âge" } },
  { thai: "ประมาณ", rom: "prà-maan", meaning: { fr: "environ" } },
  { thai: "ประชุม", rom: "prà-chum", meaning: { fr: "réunion" } },
  { thai: "โทรศัพท์", rom: "thoo-rá-sàp", meaning: { fr: "téléphone" } },
  { thai: "กระเป๋าสตางค์", rom: "krà-pǎo-sà-taang", meaning: { fr: "portefeuille" } },
  { thai: "ทางด่วน", rom: "thaang-dùan", meaning: { fr: "voie express" } },
  { thai: "ขึ้น", rom: "khʉ̂n", meaning: { fr: "monter" } },
  { thai: "ทาง", rom: "thaang", meaning: { fr: "chemin, voie" } },
  { thai: "เช็กบิล", rom: "chék-bin", meaning: { fr: "l'addition" } },
  { thai: "อื่น", rom: "ʉ̀ʉn", meaning: { fr: "autre" } },
  { thai: "มิเตอร์", rom: "mí-təə", meaning: { fr: "compteur" } },
  { thai: "ทอน", rom: "thɔɔn", meaning: { fr: "rendre la monnaie" } },
  { thai: "รีบ", rom: "rîip", meaning: { fr: "se dépêcher" } },
  { thai: "ไว้", rom: "wái", meaning: { fr: "(garder, laisser)" } },
  { thai: "รหัส", rom: "rá-hàt", meaning: { fr: "code" } },
  { thai: "หาย", rom: "hǎai", meaning: { fr: "disparaître ; guérir" } },
  { thai: "เก่ง", rom: "kèng", meaning: { fr: "doué" } },
  { thai: "สิ", rom: "sì", meaning: { fr: "(insistance)" } },
  { thai: "สแกน", rom: "sà-kɛɛn", meaning: { fr: "scanner" } },
  { thai: "ขอบใจ", rom: "khɔ̀ɔp-jai", meaning: { fr: "merci (familier)" } },
  { thai: "ฝาก", rom: "fàak", meaning: { fr: "confier, laisser" } },
  { thai: "ซิม", rom: "sim", meaning: { fr: "carte SIM" } },
  { thai: "อุ่น", rom: "ùn", meaning: { fr: "réchauffer" } },
  { thai: "เดียว", rom: "diao", meaning: { fr: "seul, unique" } },
  { thai: "มัดจำ", rom: "mát-jam", meaning: { fr: "caution, acompte" } },
  { thai: "ยูโร", rom: "yuu-roo", meaning: { fr: "euro" } },
  { thai: "โชคดี", rom: "chôok-dii", meaning: { fr: "bonne chance" } },
  { thai: "เก็บเงิน", rom: "kèp-ngən", meaning: { fr: "encaisser" } },
  { thai: "สำหรับ", rom: "sǎm-ràp", meaning: { fr: "pour" } },
  { thai: "ผักชี", rom: "phàk-chii", meaning: { fr: "coriandre" } },
  { thai: "แนะนำ", rom: "nɛ́-nam", meaning: { fr: "recommander" } },
  { thai: "กิโล", rom: "kì-loo", meaning: { fr: "kilo" } },
  { thai: "บัตร", rom: "bàt", meaning: { fr: "carte" } },
  { thai: "สด", rom: "sòt", meaning: { fr: "frais" } },
  { thai: "ชิม", rom: "chim", meaning: { fr: "goûter" } },
  { thai: "ชั่ง", rom: "châng", meaning: { fr: "peser" } },
  { thai: "เสีย", rom: "sǐa", meaning: { fr: "en panne ; perdre" } },
  { thai: "ประชาสัมพันธ์", rom: "prà-chaa-sǎm-phan", meaning: { fr: "accueil, information" } },
  { thai: "อย่างไร", rom: "yàang-rai", meaning: { fr: "comment (formel)" } },
  { thai: "หลงทาง", rom: "lǒng-thaang", meaning: { fr: "se perdre" } },
  { thai: "การ", rom: "kaan", meaning: { fr: "(le fait de)" } },
  { thai: "ท่าน", rom: "thân", meaning: { fr: "personne (poli)" } },
  { thai: "สุวรรณภูมิ", rom: "sù-wan-ná-phuum", meaning: { fr: "Suvarnabhumi (aéroport)" } },
  { thai: "มิล", rom: "min", meaning: { fr: "millimètre" } },
  { thai: "เพิ่ง", rom: "phə̂ng", meaning: { fr: "venir juste de" } },
  { thai: "ผล", rom: "phǒn", meaning: { fr: "résultat" } },
  { thai: "เรื่อง", rom: "rʉ̂ang", meaning: { fr: "sujet, affaire" } },
  { thai: "ทะเบียน", rom: "thá-bian", meaning: { fr: "immatriculation" } },
  { thai: "เหรอ", rom: "rə̌ə", meaning: { fr: "ah bon ?" } },
  { thai: "แค่ไหน", rom: "khɛ̂ɛ-nǎi", meaning: { fr: "à quel point" } },
  { thai: "ปกติ", rom: "pòk-kà-tì", meaning: { fr: "normal" } },
  { thai: "ทาน", rom: "thaan", meaning: { fr: "manger (poli)" } },
  { thai: "ล่าสุด", rom: "lâa-sùt", meaning: { fr: "le plus récent" } },
  { thai: "ล่ะ", rom: "lâ", meaning: { fr: "(et… ?)" } },
  { thai: "นัด", rom: "nát", meaning: { fr: "rendez-vous" } },
  { thai: "เน็ต", rom: "nét", meaning: { fr: "internet" } },
  { thai: "ไม่อั้น", rom: "mâi-ân", meaning: { fr: "illimité" } },
  { thai: "ซอง", rom: "sɔɔng", meaning: { fr: "pochette, enveloppe" } },
  { thai: "สมาชิก", rom: "sà-maa-chík", meaning: { fr: "membre" } },
  { thai: "ตู้", rom: "tûu", meaning: { fr: "armoire ; wagon" } },
  { thai: "ชานชาลา", rom: "chaan-chaa-laa", meaning: { fr: "quai" } },
  { thai: "นวด", rom: "nûat", meaning: { fr: "masser" } },
  { thai: "หมวกกันน็อก", rom: "mùak-kan-nɔ́k", meaning: { fr: "casque (moto)" } },
  { thai: "ใบขับขี่", rom: "bai-khàp-khìi", meaning: { fr: "permis de conduire" } },
  { thai: "เติม", rom: "təəm", meaning: { fr: "remplir" } },
  { thai: "น้ำมัน", rom: "náam-man", meaning: { fr: "essence, huile" } },
  { thai: "ถัง", rom: "thǎng", meaning: { fr: "réservoir, seau" } },
  { thai: "เมื่อ", rom: "mʉ̂a", meaning: { fr: "quand, lorsque" } },
  { thai: "แลก", rom: "lɛ̂ɛk", meaning: { fr: "échanger" } },
  { thai: "แบงก์ย่อย", rom: "bɛ́ng-yɔ̂i", meaning: { fr: "petites coupures" } },
  { thai: "นับ", rom: "náp", meaning: { fr: "compter" } },
  { thai: "ครบ", rom: "khróp", meaning: { fr: "complet" } },
  { thai: "แป๊บนึง", rom: "pɛ́p-nʉng", meaning: { fr: "un instant (familier)" } },
  { thai: "คราว", rom: "khraao", meaning: { fr: "fois" } },
  { thai: "เรียบร้อย", rom: "rîap-rɔ́ɔi", meaning: { fr: "en ordre, terminé" } },
  { thai: "เก็บ", rom: "kèp", meaning: { fr: "ramasser, garder" } },
  { thai: "อย่าง", rom: "yàang", meaning: { fr: "sorte ; comme" } },
  { thai: "ทดสอบ", rom: "thót-sɔ̀ɔp", meaning: { fr: "tester" } },
  { thai: "อัด", rom: "àt", meaning: { fr: "comprimer" } },
  { thai: "บ่ม", rom: "bòm", meaning: { fr: "cure (du béton) ; mûrir" } },
  { thai: "ฮัลโหล", rom: "han-lǒo", meaning: { fr: "allô" } },
  { thai: "ความ", rom: "khwaam", meaning: { fr: "(nominalisateur)" } },
  { thai: "ค่อย", rom: "khɔ̂i", meaning: { fr: "peu à peu ; ensuite" } },
  { thai: "ดี", rom: "dii", meaning: { fr: "bon, bien" } },
  { thai: "กิน", rom: "kin", meaning: { fr: "manger" } },
  { thai: "น้ำ", rom: "náam", meaning: { fr: "eau" } },
  { thai: "ข้าว", rom: "khâao", meaning: { fr: "riz, repas" } },
];
