// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { Tone, ToneMark, ToneWord, ToneSet } from '../types';

export const TONES: Tone[] = [
  { id: "M", name: { fr: "moyen" }, thaiName: "เสียงสามัญ", rom: "sǐang sǎa-man", mark: "a", color: "var(--t-mid)", path: "M6 32 C 40 32, 70 33, 94 36", desc: { fr: "Voix posée, à hauteur normale, presque plate." }, example: { thai: "มา", rom: "maa", meaning: { fr: "venir" } } },
  { id: "L", name: { fr: "bas" }, thaiName: "เสียงเอก", rom: "sǐang èek", mark: "à", color: "var(--t-low)", path: "M6 40 C 36 44, 66 50, 94 54", desc: { fr: "Part un peu sous la voix normale et descend doucement vers le grave." }, example: { thai: "ไข่", rom: "khài", meaning: { fr: "œuf" } } },
  { id: "F", name: { fr: "descendant" }, thaiName: "เสียงโท", rom: "sǐang thoo", mark: "â", color: "var(--t-fall)", path: "M6 18 C 30 8, 50 12, 66 30 S 86 54, 94 56", desc: { fr: "Part haut, monte à peine, puis tombe nettement. Comme un « ah ! » de compréhension." }, example: { thai: "ข้าว", rom: "khâao", meaning: { fr: "riz" } } },
  { id: "H", name: { fr: "haut" }, thaiName: "เสียงตรี", rom: "sǐang trii", mark: "á", color: "var(--t-high)", path: "M6 28 C 34 24, 62 16, 94 8", desc: { fr: "Part au-dessus de la voix normale et monte encore, voix un peu tendue." }, example: { thai: "น้ำ", rom: "náam", meaning: { fr: "eau" } } },
  { id: "R", name: { fr: "montant" }, thaiName: "เสียงจัตวา", rom: "sǐang jàt-tà-waa", mark: "ǎ", color: "var(--t-rise)", path: "M6 40 C 28 52, 46 56, 60 44 S 84 14, 94 10", desc: { fr: "Descend d'abord dans le grave puis remonte franchement. Comme un « ah ? » interrogatif." }, example: { thai: "หมา", rom: "mǎa", meaning: { fr: "chien" } } },
];

export const TONE_MARKS: ToneMark[] = [
  { n: 1, char: "่", name: "ไม้เอก", rom: "mái èek" },
  { n: 2, char: "้", name: "ไม้โท", rom: "mái thoo" },
  { n: 3, char: "๊", name: "ไม้ตรี", rom: "mái trii" },
  { n: 4, char: "๋", name: "ไม้จัตวา", rom: "mái jàt-tà-waa" },
];

/** Monosyllabes analysés à la main pour les règles de ton. */

export const TONE_WORDS: ToneWord[] = [
  { id: "t:กา", thai: "กา", rom: "kaa", meaning: { fr: "corbeau" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:กิน", thai: "กิน", rom: "kin", meaning: { fr: "manger" }, cls: "M", live: true, long: false, mark: 0 },
  { id: "t:ดี", thai: "ดี", rom: "dii", meaning: { fr: "bon" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:ตา", thai: "ตา", rom: "taa", meaning: { fr: "œil" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:ไป", thai: "ไป", rom: "pai", meaning: { fr: "aller" }, cls: "M", live: true, long: false, mark: 0, note: { fr: "ไ– finit par le son y : syllabe vivante." } },
  { id: "t:ปู", thai: "ปู", rom: "puu", meaning: { fr: "crabe" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:บ้าน", thai: "บ้าน", rom: "bâan", meaning: { fr: "maison" }, cls: "M", live: true, long: true, mark: 2 },
  { id: "t:ได้", thai: "ได้", rom: "dâai", meaning: { fr: "pouvoir" }, cls: "M", live: true, long: true, mark: 2 },
  { id: "t:เก้า", thai: "เก้า", rom: "kâao", meaning: { fr: "neuf" }, cls: "M", live: true, long: true, mark: 2 },
  { id: "t:ไก่", thai: "ไก่", rom: "kài", meaning: { fr: "poulet" }, cls: "M", live: true, long: false, mark: 1 },
  { id: "t:เก่า", thai: "เก่า", rom: "kào", meaning: { fr: "vieux, ancien" }, cls: "M", live: true, long: false, mark: 1 },
  { id: "t:ป่า", thai: "ป่า", rom: "pàa", meaning: { fr: "forêt" }, cls: "M", live: true, long: true, mark: 1 },
  { id: "t:กับ", thai: "กับ", rom: "kàp", meaning: { fr: "avec" }, cls: "M", live: false, long: false, mark: 0 },
  { id: "t:จาก", thai: "จาก", rom: "jàak", meaning: { fr: "de, depuis" }, cls: "M", live: false, long: true, mark: 0 },
  { id: "t:เด็ก", thai: "เด็ก", rom: "dèk", meaning: { fr: "enfant" }, cls: "M", live: false, long: false, mark: 0 },
  { id: "t:ปาก", thai: "ปาก", rom: "pàak", meaning: { fr: "bouche" }, cls: "M", live: false, long: true, mark: 0 },
  { id: "t:โต๊ะ", thai: "โต๊ะ", rom: "tó", meaning: { fr: "table" }, cls: "M", live: false, long: false, mark: 3 },
  { id: "t:ตั๋ว", thai: "ตั๋ว", rom: "tǔa", meaning: { fr: "billet" }, cls: "M", live: true, long: true, mark: 4 },
  { id: "t:เดี๋ยว", thai: "เดี๋ยว", rom: "dǐao", meaning: { fr: "un instant" }, cls: "M", live: true, long: true, mark: 4 },
  { id: "t:อ่าน", thai: "อ่าน", rom: "àan", meaning: { fr: "lire" }, cls: "M", live: true, long: true, mark: 1, note: { fr: "อ est une consonne de classe moyenne." } },
  { id: "t:อิ่ม", thai: "อิ่ม", rom: "ìm", meaning: { fr: "rassasié" }, cls: "M", live: true, long: false, mark: 1 },
  { id: "t:จะ", thai: "จะ", rom: "jà", meaning: { fr: "(futur)" }, cls: "M", live: false, long: false, mark: 0, note: { fr: "Voyelle brève sans finale : syllabe morte." } },
  { id: "t:ขา", thai: "ขา", rom: "khǎa", meaning: { fr: "jambe" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:สี", thai: "สี", rom: "sǐi", meaning: { fr: "couleur" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ผม", thai: "ผม", rom: "phǒm", meaning: { fr: "je (homme) ; cheveux" }, cls: "H", live: true, long: false, mark: 0 },
  { id: "t:หู", thai: "หู", rom: "hǔu", meaning: { fr: "oreille" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:สอง", thai: "สอง", rom: "sɔ̌ɔng", meaning: { fr: "deux" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ไข่", thai: "ไข่", rom: "khài", meaning: { fr: "œuf" }, cls: "H", live: true, long: false, mark: 1 },
  { id: "t:สี่", thai: "สี่", rom: "sìi", meaning: { fr: "quatre" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:ถั่ว", thai: "ถั่ว", rom: "thùa", meaning: { fr: "haricot, cacahuète" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:ข้าว", thai: "ข้าว", rom: "khâao", meaning: { fr: "riz" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ห้า", thai: "ห้า", rom: "hâa", meaning: { fr: "cinq" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ผ้า", thai: "ผ้า", rom: "phâa", meaning: { fr: "tissu" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ถ้า", thai: "ถ้า", rom: "thâa", meaning: { fr: "si" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ขับ", thai: "ขับ", rom: "khàp", meaning: { fr: "conduire" }, cls: "H", live: false, long: false, mark: 0 },
  { id: "t:สิบ", thai: "สิบ", rom: "sìp", meaning: { fr: "dix" }, cls: "H", live: false, long: false, mark: 0 },
  { id: "t:ถูก", thai: "ถูก", rom: "thùuk", meaning: { fr: "bon marché ; correct" }, cls: "H", live: false, long: true, mark: 0 },
  { id: "t:ผัด", thai: "ผัด", rom: "phàt", meaning: { fr: "faire sauter (cuisine)" }, cls: "H", live: false, long: false, mark: 0 },
  { id: "t:หก", thai: "หก", rom: "hòk", meaning: { fr: "six" }, cls: "H", live: false, long: false, mark: 0 },
  { id: "t:มา", thai: "มา", rom: "maa", meaning: { fr: "venir" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:นา", thai: "นา", rom: "naa", meaning: { fr: "rizière" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:งู", thai: "งู", rom: "nguu", meaning: { fr: "serpent" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ยา", thai: "ยา", rom: "yaa", meaning: { fr: "médicament" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:คน", thai: "คน", rom: "khon", meaning: { fr: "personne" }, cls: "L", live: true, long: false, mark: 0 },
  { id: "t:แม่", thai: "แม่", rom: "mɛ̂ɛ", meaning: { fr: "mère" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:พ่อ", thai: "พ่อ", rom: "phɔ̂ɔ", meaning: { fr: "père" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:ไม่", thai: "ไม่", rom: "mâi", meaning: { fr: "ne… pas" }, cls: "L", live: true, long: false, mark: 1 },
  { id: "t:พี่", thai: "พี่", rom: "phîi", meaning: { fr: "aîné(e)" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:นี่", thai: "นี่", rom: "nîi", meaning: { fr: "ceci" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:ม้า", thai: "ม้า", rom: "máa", meaning: { fr: "cheval" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:ร้อน", thai: "ร้อน", rom: "rɔ́ɔn", meaning: { fr: "chaud" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:รู้", thai: "รู้", rom: "rúu", meaning: { fr: "savoir" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:ช้าง", thai: "ช้าง", rom: "cháang", meaning: { fr: "éléphant" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:ซื้อ", thai: "ซื้อ", rom: "sʉ́ʉ", meaning: { fr: "acheter" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:รัก", thai: "รัก", rom: "rák", meaning: { fr: "aimer" }, cls: "L", live: false, long: false, mark: 0 },
  { id: "t:นก", thai: "นก", rom: "nók", meaning: { fr: "oiseau" }, cls: "L", live: false, long: false, mark: 0, note: { fr: "Voyelle o brève non écrite." } },
  { id: "t:เล็ก", thai: "เล็ก", rom: "lék", meaning: { fr: "petit" }, cls: "L", live: false, long: false, mark: 0 },
  { id: "t:คิด", thai: "คิด", rom: "khít", meaning: { fr: "penser" }, cls: "L", live: false, long: false, mark: 0 },
  { id: "t:มาก", thai: "มาก", rom: "mâak", meaning: { fr: "très, beaucoup" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:พูด", thai: "พูด", rom: "phûut", meaning: { fr: "parler" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:เลือด", thai: "เลือด", rom: "lʉ̂at", meaning: { fr: "sang" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:ชอบ", thai: "ชอบ", rom: "chɔ̂ɔp", meaning: { fr: "aimer bien" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:ยาก", thai: "ยาก", rom: "yâak", meaning: { fr: "difficile" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:ลูก", thai: "ลูก", rom: "lûuk", meaning: { fr: "enfant (de qqn)" }, cls: "L", live: false, long: true, mark: 0 },
  { id: "t:หมา", thai: "หมา", rom: "mǎa", meaning: { fr: "chien" }, cls: "H", live: true, long: true, mark: 0, note: { fr: "ห นำ : le ห muet fait passer ม en classe haute." } },
  { id: "t:หนู", thai: "หนู", rom: "nǔu", meaning: { fr: "souris" }, cls: "H", live: true, long: true, mark: 0, note: { fr: "ห นำ : น suit les règles de la classe haute." } },
  { id: "t:หมู", thai: "หมู", rom: "mǔu", meaning: { fr: "porc" }, cls: "H", live: true, long: true, mark: 0, note: { fr: "ห นำ." } },
  { id: "t:หนึ่ง", thai: "หนึ่ง", rom: "nʉ̀ng", meaning: { fr: "un" }, cls: "H", live: true, long: false, mark: 1, note: { fr: "ห นำ + ไม้เอก." } },
  { id: "t:หน้า", thai: "หน้า", rom: "nâa", meaning: { fr: "visage ; devant" }, cls: "H", live: true, long: true, mark: 2, note: { fr: "ห นำ + ไม้โท." } },
  { id: "t:ใหม่", thai: "ใหม่", rom: "mài", meaning: { fr: "nouveau" }, cls: "H", live: true, long: false, mark: 1, note: { fr: "ห นำ + ไม้เอก." } },
  { id: "t:หลับ", thai: "หลับ", rom: "làp", meaning: { fr: "dormir" }, cls: "H", live: false, long: false, mark: 0, note: { fr: "ห นำ, syllabe morte." } },
  { id: "t:หยุด", thai: "หยุด", rom: "yùt", meaning: { fr: "arrêter" }, cls: "H", live: false, long: false, mark: 0, note: { fr: "ห นำ, syllabe morte." } },
  { id: "t:อย่า", thai: "อย่า", rom: "yàa", meaning: { fr: "ne… pas ! (interdiction)" }, cls: "M", live: true, long: true, mark: 1, note: { fr: "อ นำ : อ muet, ย suit la classe moyenne (4 mots : อย่า อยู่ อย่าง อยาก)." } },
  { id: "t:อยู่", thai: "อยู่", rom: "yùu", meaning: { fr: "être (quelque part)" }, cls: "M", live: true, long: true, mark: 1, note: { fr: "อ นำ." } },
  { id: "t:อยาก", thai: "อยาก", rom: "yàak", meaning: { fr: "avoir envie de" }, cls: "M", live: false, long: true, mark: 0, note: { fr: "อ นำ, syllabe morte." } },
  { id: "t:ขาว", thai: "ขาว", rom: "khǎao", meaning: { fr: "blanc" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ข่าว", thai: "ข่าว", rom: "khàao", meaning: { fr: "nouvelles, informations" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:เสือ", thai: "เสือ", rom: "sʉ̌a", meaning: { fr: "tigre" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:เสื่อ", thai: "เสื่อ", rom: "sʉ̀a", meaning: { fr: "natte" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:เสื้อ", thai: "เสื้อ", rom: "sʉ̂a", meaning: { fr: "chemise, haut" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ปา", thai: "ปา", rom: "paa", meaning: { fr: "lancer" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:ป้า", thai: "ป้า", rom: "pâa", meaning: { fr: "tante (sœur aînée d'un parent)" }, cls: "M", live: true, long: true, mark: 2 },
  { id: "t:ไม้", thai: "ไม้", rom: "máai", meaning: { fr: "bois" }, cls: "L", live: true, long: true, mark: 2, note: { fr: "Écrit avec une voyelle courte, mais prononcé long." } },
  { id: "t:ไหม้", thai: "ไหม้", rom: "mâi", meaning: { fr: "brûler" }, cls: "H", live: true, long: false, mark: 2, note: { fr: "ห นำ : le ห muet donne la classe haute à ม." } },
  { id: "t:หา", thai: "หา", rom: "hǎa", meaning: { fr: "chercher" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:น้า", thai: "น้า", rom: "náa", meaning: { fr: "oncle, tante (cadets de la mère)" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:หนา", thai: "หนา", rom: "nǎa", meaning: { fr: "épais" }, cls: "H", live: true, long: true, mark: 0, note: { fr: "ห นำ : le ห muet donne la classe haute à น." } },
  { id: "t:ย่า", thai: "ย่า", rom: "yâa", meaning: { fr: "grand-mère paternelle" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:หญ้า", thai: "หญ้า", rom: "yâa", meaning: { fr: "herbe" }, cls: "H", live: true, long: true, mark: 2, note: { fr: "ห นำ : le ห muet donne la classe haute à ญ." } },
  { id: "t:ปู่", thai: "ปู่", rom: "pùu", meaning: { fr: "grand-père paternel" }, cls: "M", live: true, long: true, mark: 1 },
  { id: "t:แม้", thai: "แม้", rom: "mɛ́ɛ", meaning: { fr: "même (si)" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:ใส", thai: "ใส", rom: "sǎi", meaning: { fr: "limpide, clair" }, cls: "H", live: true, long: false, mark: 0, note: { fr: "ใ– finit par le son y : syllabe vivante." } },
  { id: "t:ใส่", thai: "ใส่", rom: "sài", meaning: { fr: "mettre ; porter" }, cls: "H", live: true, long: false, mark: 1 },
  { id: "t:ไส้", thai: "ไส้", rom: "sâi", meaning: { fr: "intestin ; farce" }, cls: "H", live: true, long: false, mark: 2 },
  { id: "t:ผี", thai: "ผี", rom: "phǐi", meaning: { fr: "fantôme" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ไข้", thai: "ไข้", rom: "khâi", meaning: { fr: "fièvre" }, cls: "H", live: true, long: false, mark: 2 },
  { id: "t:ทา", thai: "ทา", rom: "thaa", meaning: { fr: "enduire, appliquer" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ท่า", thai: "ท่า", rom: "thâa", meaning: { fr: "quai ; posture" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:คอ", thai: "คอ", rom: "khɔɔ", meaning: { fr: "cou" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ขอ", thai: "ขอ", rom: "khɔ̌ɔ", meaning: { fr: "demander" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ข้อ", thai: "ข้อ", rom: "khɔ̂ɔ", meaning: { fr: "point, article ; articulation" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ฟ้า", thai: "ฟ้า", rom: "fáa", meaning: { fr: "ciel" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:ฝา", thai: "ฝา", rom: "fǎa", meaning: { fr: "couvercle" }, cls: "H", live: true, long: true, mark: 0 },
  { id: "t:ชา", thai: "ชา", rom: "chaa", meaning: { fr: "thé" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ช้า", thai: "ช้า", rom: "cháa", meaning: { fr: "lent" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:รู", thai: "รู", rom: "ruu", meaning: { fr: "trou" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:สื่อ", thai: "สื่อ", rom: "sʉ̀ʉ", meaning: { fr: "média ; communiquer" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:ใช่", thai: "ใช่", rom: "châi", meaning: { fr: "oui, c'est ça" }, cls: "L", live: true, long: false, mark: 1 },
  { id: "t:ใช้", thai: "ใช้", rom: "chái", meaning: { fr: "utiliser" }, cls: "L", live: true, long: false, mark: 2 },
  { id: "t:ที", thai: "ที", rom: "thii", meaning: { fr: "fois" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ที่", thai: "ที่", rom: "thîi", meaning: { fr: "à ; qui, que ; lieu" }, cls: "L", live: true, long: true, mark: 1 },
  { id: "t:เกา", thai: "เกา", rom: "kao", meaning: { fr: "gratter" }, cls: "M", live: true, long: false, mark: 0, note: { fr: "เ–า finit par le son w : syllabe vivante." } },
  { id: "t:ใกล้", thai: "ใกล้", rom: "klâi", meaning: { fr: "près" }, cls: "M", live: true, long: false, mark: 2 },
  { id: "t:ไกล", thai: "ไกล", rom: "klai", meaning: { fr: "loin" }, cls: "M", live: true, long: false, mark: 0 },
  { id: "t:คา", thai: "คา", rom: "khaa", meaning: { fr: "être coincé" }, cls: "L", live: true, long: true, mark: 0 },
  { id: "t:ข่า", thai: "ข่า", rom: "khàa", meaning: { fr: "galanga" }, cls: "H", live: true, long: true, mark: 1 },
  { id: "t:ข้า", thai: "ข้า", rom: "khâa", meaning: { fr: "serviteur ; je (ancien)" }, cls: "H", live: true, long: true, mark: 2 },
  { id: "t:ค้า", thai: "ค้า", rom: "kháa", meaning: { fr: "faire du commerce" }, cls: "L", live: true, long: true, mark: 2 },
  { id: "t:เขา", thai: "เขา", rom: "khǎo", meaning: { fr: "il, elle ; montagne" }, cls: "H", live: true, long: false, mark: 0 },
  { id: "t:เข้า", thai: "เข้า", rom: "khâo", meaning: { fr: "entrer" }, cls: "H", live: true, long: false, mark: 2 },
  { id: "t:เข่า", thai: "เข่า", rom: "khào", meaning: { fr: "genou" }, cls: "H", live: true, long: false, mark: 1 },
  { id: "t:แก", thai: "แก", rom: "kɛɛ", meaning: { fr: "tu, il (familier)" }, cls: "M", live: true, long: true, mark: 0 },
  { id: "t:แก่", thai: "แก่", rom: "kɛ̀ɛ", meaning: { fr: "âgé (personne)" }, cls: "M", live: true, long: true, mark: 1 },
  { id: "t:แก้", thai: "แก้", rom: "kɛ̂ɛ", meaning: { fr: "réparer, résoudre" }, cls: "M", live: true, long: true, mark: 2 },
];

/** Séries « même syllabe, tons différents ». */

export const TONE_SETS: ToneSet[] = [
  { words: ["มา", "ม้า", "หมา"] },
  { words: ["ขาว", "ข่าว", "ข้าว"] },
  { words: ["เสือ", "เสื่อ", "เสื้อ"] },
  { words: ["คา", "ข่า", "ข้า", "ค้า", "ขา"], note: { fr: "Les cinq tons sur la même syllabe." } },
  { words: ["ใกล้", "ไกล"], note: { fr: "« Près » et « loin » ne diffèrent que par le ton." } },
  { words: ["ไม้", "ใหม่", "ไม่", "ไหม้"], note: { fr: "ไม่ et ไหม้ se prononcent de la même façon." } },
  { words: ["ปา", "ป่า", "ป้า"] },
  { words: ["นา", "น้า", "หน้า", "หนา"] },
  { words: ["ยา", "ย่า", "หญ้า", "อย่า"], note: { fr: "ย่า et หญ้า se prononcent de la même façon." } },
  { words: ["สี", "สี่"] },
  { words: ["หา", "ห้า"] },
  { words: ["ปู", "ปู่"] },
  { words: ["แม่", "แม้"] },
  { words: ["ใส", "ใส่", "ไส้"] },
  { words: ["พี่", "ผี"] },
  { words: ["ไข่", "ไข้"] },
  { words: ["ทา", "ท่า", "ถ้า"], note: { fr: "ท่า et ถ้า : deux orthographes, un seul son." } },
  { words: ["คอ", "ขอ", "ข้อ"] },
  { words: ["ฟ้า", "ฝา"] },
  { words: ["ชา", "ช้า"] },
  { words: ["รู", "รู้"] },
  { words: ["ซื้อ", "สื่อ"] },
  { words: ["ใช่", "ใช้"] },
  { words: ["ที", "ที่"] },
  { words: ["เกา", "เก่า", "เก้า"], note: { fr: "เก้า (neuf) se prononce avec une voyelle longue." } },
  { words: ["เขา", "เข้า", "เข่า"] },
  { words: ["แก", "แก่", "แก้"] },
];
