/**
 * Niveau A2 : seize thèmes de vocabulaire (≈ 25 mots chacun, avec phrase d’exemple), rédigés puis relus par un
 * second passage linguistique (orthographe, naturel, niveau, phonétique). Les mots déjà présents ailleurs ont été écartés.
 */
import type { VocabItem, VocabTheme } from '../types';

const w = (thai: string, rom: string, fr: string, theme: string, example: [string, string, string]): VocabItem => ({
  id: 'w:' + thai, thai, rom, meaning: { fr }, themes: [theme], example: { thai: example[0], rom: example[1], meaning: { fr: example[2] } },
});

export const A2_THEMES: VocabTheme[] = [
  {
    id: "admin", name: { fr: "Démarches et administration" }, icon: "clipboard",
    items: [
      w("แบบฟอร์ม", "bɛ̀ɛp-fɔɔm", "formulaire", "admin", ["ขอแบบฟอร์มหนึ่งใบ{P}", "khɔ̌ɔ bɛ̀ɛp-fɔɔm nʉ̀ng bai {p}", "un formulaire, s’il vous plaît"]),
      w("กรอก", "krɔ̀ɔk", "remplir (un formulaire)", "admin", ["{I}กรอกแบบฟอร์มเสร็จแล้ว{P}", "{i} krɔ̀ɔk bɛ̀ɛp-fɔɔm sèt lɛ́ɛo {p}", "j’ai fini de remplir le formulaire"]),
      w("เซ็น", "sen", "signer", "admin", ["เซ็นตรงนี้ได้เลย{P}", "sen trong-níi dâai ləəi {p}", "vous pouvez signer ici"]),
      w("ลายเซ็น", "laai-sen", "signature", "admin", ["ต้องมีลายเซ็นของคุณ{P}", "tɔ̂ng mii laai-sen khɔ̌ɔng khun {p}", "il faut votre signature"]),
      w("ถ่ายเอกสาร", "thàai èek-kà-sǎan", "photocopier ; photocopie", "admin", ["แถวนี้มีร้านถ่ายเอกสารไหม{Q}", "thɛ̌ɛo-níi mii ráan thàai èek-kà-sǎan mái {q}", "y a-t-il une boutique de photocopies par ici ?"]),
      w("สำเนา", "sǎm-nao", "copie (d’un document)", "admin", ["ขอสำเนาหนังสือเดินทางด้วย{P}", "khɔ̌ɔ sǎm-nao nǎng-sʉ̌ʉ dəən-thaang dûai {p}", "une copie du passeport aussi, s’il vous plaît"]),
      w("รูปถ่าย", "rûup-thàai", "photo (d’identité)", "admin", ["ต้องใช้รูปถ่ายสองใบ", "tɔ̂ng chái rûup-thàai sɔ̌ɔng bai", "il faut deux photos d’identité"]),
      w("บัตรประชาชน", "bàt prà-chaa-chon", "carte d’identité", "admin", ["ขอดูบัตรประชาชนด้วย{P}", "khɔ̌ɔ duu bàt prà-chaa-chon dûai {p}", "votre carte d’identité, s’il vous plaît"]),
      w("ที่อยู่", "thîi-yùu", "adresse", "admin", ["เขียนที่อยู่ตรงนี้ด้วย{P}", "khǐan thîi-yùu trong-níi dûai {p}", "écrivez l’adresse ici, s’il vous plaît"]),
      w("สัญชาติ", "sǎn-châat", "nationalité", "admin", ["คุณสัญชาติอะไร{Q}", "khun sǎn-châat à-rai {q}", "quelle est votre nationalité ?"]),
      w("นัด", "nát", "rendez-vous ; fixer un rendez-vous", "admin", ["{I}มีนัดตอนสิบโมง{P}", "{i} mii nát tɔɔn sìp moong {p}", "j’ai rendez-vous à dix heures"]),
      w("เลื่อนนัด", "lʉ̂an nát", "reporter un rendez-vous", "admin", ["{I}ขอเลื่อนนัดได้ไหม{Q}", "{i} khɔ̌ɔ lʉ̂an nát dâai mái {q}", "est-ce que je peux reporter le rendez-vous ?"]),
      w("คิว", "khiu", "file d’attente ; numéro d’attente", "admin", ["วันนี้คิวยาวมาก", "wan-níi khiu yaao mâak", "aujourd’hui, la file d’attente est très longue"]),
      w("ช่อง", "chɔ̂ng", "guichet ; case", "admin", ["เชิญที่ช่องสาม{P}", "chəən thîi chɔ̂ng sǎam {p}", "présentez-vous au guichet trois"]),
      w("เจ้าหน้าที่", "jâo-nâa-thîi", "agent, employé (d’un service)", "admin", ["ถามเจ้าหน้าที่ได้เลย{P}", "thǎam jâo-nâa-thîi dâai ləəi {p}", "vous pouvez demander à l’agent"]),
      w("ยื่น", "yʉ̂ʉn", "déposer (un dossier), remettre", "admin", ["{I}มายื่นเอกสาร{P}", "{i} maa yʉ̂ʉn èek-kà-sǎan {p}", "je viens déposer des documents"]),
      w("สมัคร", "sà-màk", "s’inscrire ; postuler", "admin", ["{I}อยากสมัครเรียนภาษาไทย", "{i} yàak sà-màk rian phaa-sǎa thai", "je voudrais m’inscrire à un cours de thaï"]),
      w("ต่ออายุ", "tɔ̀ɔ aa-yú", "prolonger, renouveler (un document)", "admin", ["{I}ต้องต่ออายุวีซ่า", "{i} tɔ̂ng tɔ̀ɔ aa-yú wii-sâa", "je dois prolonger mon visa"]),
      w("หมดอายุ", "mòt aa-yú", "expirer ; périmé", "admin", ["หนังสือเดินทางหมดอายุแล้ว", "nǎng-sʉ̌ʉ dəən-thaang mòt aa-yú lɛ́ɛo", "le passeport a expiré"]),
      w("ใบอนุญาตทำงาน", "bai à-nú-yâat tham-ngaan", "permis de travail", "admin", ["{I}ยังไม่มีใบอนุญาตทำงาน", "{i} yang mâi mii bai à-nú-yâat tham-ngaan", "je n’ai pas encore de permis de travail"]),
      w("รายงานตัว", "raai-ngaan tua", "se présenter (aux autorités), signaler sa présence", "admin", ["ต้องรายงานตัวทุกเก้าสิบวัน", "tɔ̂ng raai-ngaan tua thúk kâo-sìp wan", "il faut se présenter tous les quatre-vingt-dix jours"]),
      w("หลักฐาน", "làk-thǎan", "justificatif, preuve", "admin", ["ต้องมีหลักฐานที่อยู่", "tɔ̂ng mii làk-thǎan thîi-yùu", "il faut un justificatif de domicile"]),
      w("ประทับตรา", "prà-tháp traa", "tamponner ; tampon", "admin", ["ช่วยประทับตราให้หน่อย{P}", "chûai prà-tháp traa hâi nɔ̀i {p}", "pourriez-vous mettre un tampon, s’il vous plaît ?"]),
      w("ค่าปรับ", "khâa-pràp", "amende", "admin", ["ค่าปรับวันละห้าร้อยบาท", "khâa-pràp wan lá hâa rɔ́ɔi bàat", "l’amende est de cinq cents bahts par jour"]),
      w("อำเภอ", "am-phəə", "bureau de district (≈ mairie) ; district", "admin", ["พรุ่งนี้{I}จะไปที่อำเภอ", "phrûng-níi {i} jà pai thîi am-phəə", "demain, je vais au bureau de district"]),
    ],
  },
  {
    id: "housing", name: { fr: "Logement" }, icon: "home",
    items: [
      w("ห้องเช่า", "hɔ̂ng-châo", "logement à louer, chambre en location", "housing", ["แถวนี้มีห้องเช่าไหม{Q}", "thɛ̌ɛo-níi mii hɔ̂ng-châo mái {q}", "y a-t-il des logements à louer par ici ?"]),
      w("อพาร์ตเมนต์", "à-phâat-mén", "appartement (immeuble de location)", "housing", ["{I}อยู่อพาร์ตเมนต์ใกล้ตลาด", "{i} yùu à-phâat-mén klâi tà-làat", "j’habite un appartement près du marché"]),
      w("หอพัก", "hɔ̌ɔ-phák", "résidence (chambres à louer), foyer", "housing", ["หอพักนี้ถูกและสะอาด", "hɔ̌ɔ-phák níi thùuk lɛ́ sà-àat", "cette résidence est bon marché et propre"]),
      w("ผู้เช่า", "phûu-châo", "locataire", "housing", ["ผู้เช่าต้องจ่ายค่าไฟเอง", "phûu-châo tɔ̂ng jàai khâa fai eeng", "le locataire doit payer l’électricité lui-même"]),
      w("เพื่อนบ้าน", "phʉ̂an-bâan", "voisin", "housing", ["เพื่อนบ้าน{I}ใจดีมาก", "phʉ̂an-bâan {i} jai-dii mâak", "mes voisins sont très gentils"]),
      w("ค่ามัดจำ", "khâa mát-jam", "caution, dépôt de garantie", "housing", ["ค่ามัดจำเท่าไหร่{Q}", "khâa mát-jam thâo-rài {q}", "la caution, c’est combien ?"]),
      w("ล่วงหน้า", "lûang-nâa", "à l’avance", "housing", ["ต้องจ่ายล่วงหน้าหนึ่งเดือน", "tɔ̂ng jàai lûang-nâa nʉ̀ng dʉan", "il faut payer un mois d’avance"]),
      w("รายเดือน", "raai-dʉan", "au mois, mensuel", "housing", ["ห้องนี้เช่ารายเดือนได้ไหม{Q}", "hɔ̂ng níi châo raai-dʉan dâai mái {q}", "peut-on louer cette chambre au mois ?"]),
      w("ค่าน้ำ", "khâa náam", "facture d’eau", "housing", ["ค่าน้ำเดือนนี้เท่าไหร่{Q}", "khâa náam dʉan níi thâo-rài {q}", "combien est la facture d’eau ce mois-ci ?"]),
      w("ค่าไฟ", "khâa fai", "facture d’électricité", "housing", ["เปิดแอร์ทั้งวัน ค่าไฟแพงมาก", "pə̀ət ɛɛ tháng wan khâa fai phɛɛng mâak", "avec la clim toute la journée, l’électricité coûte très cher"]),
      w("ย้ายบ้าน", "yáai bâan", "déménager", "housing", ["เดือนหน้า{I}จะย้ายบ้าน", "dʉan nâa {i} jà yáai bâan", "le mois prochain, je déménage"]),
      w("เฟอร์นิเจอร์", "fəə-ní-jə̂ə", "meubles", "housing", ["ห้องนี้มีเฟอร์นิเจอร์ครบ", "hɔ̂ng níi mii fəə-ní-jə̂ə khróp", "cette chambre est entièrement meublée"]),
      w("ห้องนั่งเล่น", "hɔ̂ng nâng-lên", "salon, séjour", "housing", ["ห้องนั่งเล่นกว้างมาก", "hɔ̂ng nâng-lên kwâang mâak", "le salon est très spacieux"]),
      w("ระเบียง", "rá-biang", "balcon", "housing", ["ห้องนี้มีระเบียงไหม{Q}", "hɔ̂ng níi mii rá-biang mái {q}", "cette chambre a-t-elle un balcon ?"]),
      w("ที่จอดรถ", "thîi-jɔ̀ɔt-rót", "parking, place de stationnement", "housing", ["คอนโดนี้มีที่จอดรถไหม{Q}", "khɔɔn-doo níi mii thîi-jɔ̀ɔt-rót mái {q}", "ce condo a-t-il un parking ?"]),
      w("เครื่องซักผ้า", "khrʉ̂ang sák-phâa", "machine à laver", "housing", ["เครื่องซักผ้าอยู่ชั้นล่าง", "khrʉ̂ang sák-phâa yùu chán lâang", "la machine à laver est au rez-de-chaussée"]),
      w("ก๊อกน้ำ", "kɔ́k-náam", "robinet", "housing", ["ก๊อกน้ำในห้องน้ำเสีย", "kɔ́k-náam nai hɔ̂ng-náam sǐa", "le robinet de la salle de bain est cassé"]),
      w("ท่อ", "thɔ̂ɔ", "tuyau, canalisation", "housing", ["ท่อน้ำในห้องครัวแตก", "thɔ̂ɔ náam nai hɔ̂ng-khrua tɛ̀ɛk", "le tuyau d’eau de la cuisine a éclaté"]),
      w("รั่ว", "rûa", "fuir ; fuite", "housing", ["หลังคารั่วตอนฝนตก", "lǎng-khaa rûa tɔɔn fǒn tòk", "le toit fuit quand il pleut"]),
      w("ตัน", "tan", "bouché", "housing", ["ชักโครกในห้องน้ำตัน", "chák-khrôok nai hɔ̂ng-náam tan", "les toilettes sont bouchées"]),
      w("เสีย", "sǐa", "en panne, cassé", "housing", ["ตู้เย็นเสียตั้งแต่เมื่อวาน", "tûu-yen sǐa tâng-tɛ̀ɛ mʉ̂a-waan", "le frigo est en panne depuis hier"]),
      w("หลอดไฟ", "lɔ̀ɔt-fai", "ampoule", "housing", ["หลอดไฟในห้องนอนขาด", "lɔ̀ɔt-fai nai hɔ̂ng-nɔɔn khàat", "l’ampoule de la chambre a grillé"]),
      w("แจ้ง", "jɛ̂ɛng", "signaler, prévenir", "housing", ["{I}แจ้งเจ้าของห้องแล้ว{P}", "{i} jɛ̂ɛng jâo-khɔ̌ɔng hɔ̂ng lɛ́ɛo {p}", "j’ai déjà prévenu le propriétaire"]),
      w("เสียงดัง", "sǐang dang", "bruyant ; faire du bruit", "housing", ["ห้องข้างๆ เสียงดังทุกคืน", "hɔ̂ng khâang-khâang sǐang dang thúk khʉʉn", "la chambre d’à côté est bruyante tous les soirs"]),
      w("ขยะ", "khà-yà", "ordures, déchets", "housing", ["ทิ้งขยะได้ที่ไหน{Q}", "thíng khà-yà dâai thîi-nǎi {q}", "où peut-on jeter les ordures ?"]),
    ],
  },
  {
    id: "cooking", name: { fr: "Cuisiner" }, icon: "bowl",
    items: [
      w("หั่น", "hàn", "couper (en morceaux), émincer", "cooking", ["หั่นผักให้หน่อยได้ไหม{Q}", "hàn phàk hâi nɔ̀i dâai mái {q}", "pouvez-vous couper les légumes, s’il vous plaît ?"]),
      w("ทอด", "thɔ̂ɔt", "faire frire ; frit", "cooking", ["แม่ทอดไข่ทุกเช้า", "mɛ̂ɛ thɔ̂ɔt khài thúk cháao", "maman fait frire des œufs tous les matins"]),
      w("ผัด", "phàt", "faire sauter (au wok) ; sauté", "cooking", ["ผัดผักด้วยไฟแรง", "phàt phàk dûai fai rɛɛng", "faire sauter les légumes à feu vif"]),
      w("ต้ม", "tôm", "faire bouillir ; bouilli", "cooking", ["ต้มน้ำก่อนนะ", "tôm náam kɔ̀ɔn ná", "fais d’abord bouillir l’eau"]),
      w("ย่าง", "yâang", "griller (au barbecue) ; grillé", "cooking", ["พ่อกำลังย่างหมูอยู่", "phɔ̂ɔ kam-lang yâang mǔu yùu", "papa est en train de griller du porc"]),
      w("นึ่ง", "nʉ̂ng", "cuire à la vapeur ; (à la) vapeur", "cooking", ["ปลานึ่งมะนาวอร่อยมาก", "plaa nʉ̂ng má-naao à-rɔ̀i mâak", "le poisson vapeur au citron vert est délicieux"]),
      w("ผสม", "phà-sǒm", "mélanger", "cooking", ["ผสมไข่กับนมในชาม", "phà-sǒm khài kàp nom nai chaam", "mélanger les œufs et le lait dans un bol"]),
      w("ปอก", "pɔ̀ɔk", "éplucher, peler", "cooking", ["{I}ปอกมะม่วงไม่เป็น", "{i} pɔ̀ɔk má-mûang mâi pen", "je ne sais pas éplucher une mangue"]),
      w("ล้าง", "láang", "laver, rincer", "cooking", ["ล้างผักให้สะอาดก่อน", "láang phàk hâi sà-àat kɔ̀ɔn", "lave d’abord bien les légumes"]),
      w("อุ่น", "ùn", "réchauffer ; tiède", "cooking", ["อุ่นแกงให้ร้อนก่อนกิน", "ùn kɛɛng hâi rɔ́ɔn kɔ̀ɔn kin", "réchauffe le curry avant de manger"]),
      w("วัตถุดิบ", "wát-thù-dìp", "ingrédients ; matières premières", "cooking", ["วัตถุดิบหาซื้อได้ที่ตลาด", "wát-thù-dìp hǎa sʉ́ʉ dâai thîi tà-làat", "on trouve les ingrédients au marché"]),
      w("สูตร", "sùut", "recette ; formule", "cooking", ["ขอสูตรแกงนี้หน่อยได้ไหม{Q}", "khɔ̌ɔ sùut kɛɛng níi nɔ̀i dâai mái {q}", "pouvez-vous me donner la recette de ce curry ?"]),
      w("กระทะ", "krà-thá", "poêle, wok", "cooking", ["ใส่น้ำมันลงในกระทะ", "sài náam-man long nai krà-thá", "mettre de l’huile dans la poêle"]),
      w("หม้อ", "mɔ̂ɔ", "casserole, marmite", "cooking", ["ต้มน้ำในหม้อใบใหญ่", "tôm náam nai mɔ̂ɔ bai yài", "faire bouillir l’eau dans une grande casserole"]),
      w("มีด", "mîit", "couteau", "cooking", ["มีดเล่มนี้คมมาก", "mîit lêm níi khom mâak", "ce couteau est très tranchant"]),
      w("เขียง", "khǐang", "planche à découper", "cooking", ["วางผักไว้บนเขียง", "waang phàk wái bon khǐang", "pose les légumes sur la planche à découper"]),
      w("เตา", "tao", "réchaud, feu (de cuisson), cuisinière", "cooking", ["อย่าลืมปิดเตานะ", "yàa lʉʉm pìt tao ná", "n’oublie pas d’éteindre le feu"]),
      w("เตาอบ", "tao-òp", "four", "cooking", ["บ้าน{I}ไม่มีเตาอบ", "bâan {i} mâi mii tao-òp", "je n’ai pas de four chez moi"]),
      w("น้ำมัน", "náam-man", "huile ; essence", "cooking", ["ใช้น้ำมันน้อยหน่อย", "chái náam-man nɔ́ɔi nɔ̀i", "utilise un peu moins d’huile"]),
      w("กระเทียม", "krà-thiam", "ail", "cooking", ["ผัดกระเทียมให้หอมก่อน", "phàt krà-thiam hâi hɔ̌ɔm kɔ̀ɔn", "fais d’abord revenir l’ail pour qu’il embaume"]),
      w("หัวหอม", "hǔa-hɔ̌ɔm", "oignon", "cooking", ["หั่นหัวหอมแล้วน้ำตาไหล", "hàn hǔa-hɔ̌ɔm lɛ́ɛo náam-taa lǎi", "quand on coupe des oignons, on pleure"]),
      w("ซีอิ๊ว", "sii-íu", "sauce soja", "cooking", ["ใส่ซีอิ๊วนิดหน่อย", "sài sii-íu nít-nɔ̀i", "ajoute un peu de sauce soja"]),
      w("พริกไทย", "phrík-thai", "poivre", "cooking", ["ขอพริกไทยหน่อย{P}", "khɔ̌ɔ phrík-thai nɔ̀i {p}", "un peu de poivre, s’il vous plaît"]),
      w("รสชาติ", "rót-châat", "goût, saveur", "cooking", ["รสชาติเป็นยังไงบ้าง{Q}", "rót-châat pen yang-ngai bâang {q}", "quel goût ça a ?"]),
      w("จืด", "jʉ̀ut", "fade, sans goût", "cooking", ["ซุปนี้จืดไป ใส่เกลืออีกหน่อย", "súp níi jʉ̀ut pai sài klʉa ìik nɔ̀i", "cette soupe est fade, rajoute un peu de sel"]),
    ],
  },
  {
    id: "transit", name: { fr: "Trajets et correspondances" }, icon: "train",
    items: [
      w("ต่อรถ", "tɔ̀ɔ rót", "prendre une correspondance, changer (de bus, de train)", "transit", ["ต้องต่อรถที่ไหน{Q}", "tɔ̂ng tɔ̀ɔ rót thîi-nǎi {q}", "où faut-il prendre la correspondance ?"]),
      w("ไปกลับ", "pai-klàp", "aller-retour", "transit", ["ขอตั๋วไปกลับหนึ่งใบ{P}", "khɔ̌ɔ tǔa pai-klàp nʉ̀ng bai {p}", "un billet aller-retour, s’il vous plaît"]),
      w("เที่ยวเดียว", "thîao-diao", "aller simple", "transit", ["ตั๋วเที่ยวเดียวราคาเท่าไหร่{Q}", "tǔa thîao-diao raa-khaa thâo-rài {q}", "combien coûte un aller simple ?"]),
      w("ชานชาลา", "chaan-chaa-laa", "quai (de gare)", "transit", ["รถไฟออกจากชานชาลาที่สาม", "rót-fai ɔ̀ɔk jàak chaan-chaa-laa thîi sǎam", "le train part du quai numéro trois"]),
      w("ตารางเวลา", "taa-raang wee-laa", "horaire(s)", "transit", ["ดูตารางเวลารถไฟได้ที่ไหน{Q}", "duu taa-raang wee-laa rót-fai dâai thîi-nǎi {q}", "où peut-on consulter les horaires des trains ?"]),
      w("จองล่วงหน้า", "jɔɔng lûang-nâa", "réserver à l’avance", "transit", ["ช่วงสงกรานต์ต้องจองล่วงหน้า", "chûang sǒng-kraan tɔ̂ng jɔɔng lûang-nâa", "à Songkran, il faut réserver à l’avance"]),
      w("ตรงเวลา", "trong wee-laa", "à l’heure, ponctuel", "transit", ["รถไฟวันนี้มาตรงเวลา", "rót-fai wan-níi maa trong wee-laa", "aujourd’hui, le train est arrivé à l’heure"]),
      w("ทัน", "than", "(arriver) à temps, avoir le temps d’attraper", "transit", ["{I}ขึ้นรถไฟไม่ทัน", "{i} khʉ̂n rót-fai mâi than", "je n’ai pas eu le train à temps (je l’ai raté)"]),
      w("รถทัวร์", "rót-thua", "autocar (grandes lignes)", "transit", ["นั่งรถทัวร์ไปเชียงใหม่", "nâng rót-thua pai chiang-mài", "aller à Chiang Mai en autocar"]),
      w("รถตู้", "rót-tûu", "minibus", "transit", ["รถตู้ไปพัทยาออกทุกชั่วโมง", "rót-tûu pai phát-thá-yaa ɔ̀ɔk thúk chûa-moong", "les minibus pour Pattaya partent toutes les heures"]),
      w("สถานีขนส่ง", "sà-thǎa-nii khǒn-sòng", "gare routière", "transit", ["สถานีขนส่งอยู่ไกลไหม{Q}", "sà-thǎa-nii khǒn-sòng yùu klai mái {q}", "la gare routière est-elle loin ?"]),
      w("เที่ยวสุดท้าย", "thîao sùt-tháai", "dernier départ (bus, train, bateau)", "transit", ["รถเที่ยวสุดท้ายออกกี่โมง{Q}", "rót thîao sùt-tháai ɔ̀ɔk kìi moong {q}", "à quelle heure part le dernier bus ?"]),
      w("ค่าโดยสาร", "khâa dooi-sǎan", "prix du trajet, tarif", "transit", ["ค่าโดยสารคนละสี่สิบบาท", "khâa dooi-sǎan khon lá sìi-sìp bàat", "le trajet coûte quarante bahts par personne"]),
      w("ผู้โดยสาร", "phûu-dooi-sǎan", "passager", "transit", ["วันนี้ผู้โดยสารเยอะมาก", "wan-níi phûu-dooi-sǎan yə́ mâak", "il y a beaucoup de passagers aujourd’hui"]),
      w("เติมเงิน", "təəm ngən", "recharger (une carte, un téléphone)", "transit", ["เติมเงินบัตรรถไฟฟ้าที่ไหน{Q}", "təəm ngən bàt rót-fai-fáa thîi-nǎi {q}", "où recharge-t-on la carte du métro aérien ?"]),
      w("ขับรถ", "khàp rót", "conduire (une voiture)", "transit", ["{I}ไม่กล้าขับรถในกรุงเทพ", "{i} mâi klâa khàp rót nai krung-thêep", "je n’ose pas conduire à Bangkok"]),
      w("ใบขับขี่", "bai-khàp-khìi", "permis de conduire", "transit", ["ขอดูใบขับขี่ด้วย{P}", "khɔ̌ɔ duu bai-khàp-khìi dûai {p}", "votre permis de conduire, s’il vous plaît"]),
      w("ชั่วโมงเร่งด่วน", "chûa-moong rêng-dùan", "heure de pointe", "transit", ["ชั่วโมงเร่งด่วนรถติดมาก", "chûa-moong rêng-dùan rót tìt mâak", "aux heures de pointe, ça bouchonne beaucoup"]),
      w("ช่องขายตั๋ว", "chɔ̂ng khǎai tǔa", "guichet (vente de billets)", "transit", ["ช่องขายตั๋วอยู่ทางซ้าย", "chɔ̂ng khǎai tǔa yùu thaang sáai", "le guichet est sur la gauche"]),
      w("ป้ายหน้า", "pâai nâa", "prochain arrêt", "transit", ["{I}จะลงป้ายหน้า{P}", "{i} jà long pâai nâa {p}", "je descends au prochain arrêt"]),
      w("แวะ", "wɛ́", "faire un arrêt, passer par", "transit", ["แวะปั๊มน้ำมันก่อนได้ไหม{Q}", "wɛ́ pám náam-man kɔ̀ɔn dâai mái {q}", "on peut d’abord s’arrêter à la station-service ?"]),
      w("เลื่อน", "lʉ̂an", "reporter, décaler ; faire glisser", "transit", ["เที่ยวบินเลื่อนไปพรุ่งนี้", "thîao-bin lʉ̂an pai phrûng-níi", "le vol est reporté à demain"]),
      w("คาดเข็มขัด", "khâat khěm-khàt", "attacher sa ceinture", "transit", ["กรุณาคาดเข็มขัดด้วย{P}", "kà-rú-naa khâat khěm-khàt dûai {p}", "veuillez attacher votre ceinture"]),
      w("ขากลับ", "khǎa-klàp", "(au) retour, sur le chemin du retour", "transit", ["ขากลับเรานั่งเรือ", "khǎa-klàp rao nâng rʉa", "au retour, nous avons pris le bateau"]),
    ],
  },
  {
    id: "office", name: { fr: "Au bureau (A2)" }, icon: "briefcase",
    items: [
      w("เจ้านาย", "jâo-naai", "patron, patronne", "office", ["เจ้านาย{I}ใจดีมาก", "jâo-naai {i} jai-dii mâak", "mon patron est très gentil"]),
      w("ผู้จัดการ", "phûu-jàt-kaan", "directeur, directrice ; manager", "office", ["ผู้จัดการอยากคุยกับคุณ", "phûu-jàt-kaan yàak khui kàp khun", "le directeur veut vous parler"]),
      w("พนักงาน", "phá-nák-ngaan", "employé(e), membre du personnel", "office", ["บริษัทนี้มีพนักงานห้าสิบคน", "bɔɔ-rí-sàt níi mii phá-nák-ngaan hâa-sìp khon", "cette entreprise compte cinquante employés"]),
      w("ลูกน้อง", "lûuk-nɔ́ɔng", "subordonné(e), membre de son équipe", "office", ["เขามีลูกน้องสิบคน", "khǎo mii lûuk-nɔ́ɔng sìp khon", "il a dix personnes sous ses ordres"]),
      w("ห้องประชุม", "hɔ̂ng prà-chum", "salle de réunion", "office", ["ห้องประชุมเล็กไปหน่อย", "hɔ̂ng prà-chum lék pai nɔ̀i", "la salle de réunion est un peu petite"]),
      w("รายงาน", "raai-ngaan", "rapport ; faire un rapport", "office", ["{I}ต้องเขียนรายงานให้เสร็จวันนี้", "{i} tɔ̂ng khǐan raai-ngaan hâi sèt wan-níi", "je dois finir d’écrire le rapport aujourd’hui"]),
      w("อีเมล", "ii-meo", "e-mail, courriel", "office", ["{I}ส่งอีเมลให้คุณแล้ว{P}", "{i} sòng ii-meo hâi khun lɛ́ɛo {p}", "je vous ai envoyé un e-mail"]),
      w("เครื่องพิมพ์", "khrʉ̂ang-phim", "imprimante", "office", ["เครื่องพิมพ์เสียอีกแล้ว", "khrʉ̂ang-phim sǐa ìik lɛ́ɛo", "l’imprimante est encore en panne"]),
      w("นำเสนอ", "nam-sà-nə̌ə", "présenter (un projet, une idée)", "office", ["พรุ่งนี้{I}ต้องนำเสนองานให้ลูกค้า", "phrûng-níi {i} tɔ̂ng nam-sà-nə̌ə ngaan hâi lûuk-kháa", "demain, je dois présenter le projet au client"]),
      w("ทันเวลา", "than wee-laa", "à temps, dans les délais", "office", ["งานจะเสร็จทันเวลาไหม{Q}", "ngaan jà sèt than wee-laa mái {q}", "le travail sera-t-il fini à temps ?"]),
      w("ตำแหน่ง", "tam-nɛ̀ng", "poste, fonction", "office", ["คุณทำงานตำแหน่งอะไร{Q}", "khun tham-ngaan tam-nɛ̀ng à-rai {q}", "quel poste occupez-vous ?"]),
      w("สัมภาษณ์งาน", "sǎm-phâat ngaan", "entretien d’embauche", "office", ["พรุ่งนี้{I}มีสัมภาษณ์งาน", "phrûng-níi {i} mii sǎm-phâat ngaan", "demain, j’ai un entretien d’embauche"]),
      w("จ้าง", "jâang", "embaucher, engager ; payer (quelqu’un pour un travail)", "office", ["บริษัทจะจ้างวิศวกรเพิ่ม", "bɔɔ-rí-sàt jà jâang wít-sà-wá-kɔɔn phə̂əm", "l’entreprise va embaucher des ingénieurs supplémentaires"]),
      w("ลาออก", "laa-ɔ̀ɔk", "démissionner", "office", ["เขาลาออกเมื่อเดือนที่แล้ว", "khǎo laa-ɔ̀ɔk mʉ̂a dʉan thîi-lɛ́ɛo", "il a démissionné le mois dernier"]),
      w("ลางาน", "laa-ngaan", "prendre un congé, poser un jour", "office", ["{I}ขอลางานวันศุกร์{P}", "{i} khɔ̌ɔ laa-ngaan wan-sùk {p}", "je voudrais prendre un congé vendredi"]),
      w("ลาป่วย", "laa-pùai", "se mettre en congé maladie ; congé maladie", "office", ["วันนี้เขาลาป่วย", "wan-níi khǎo laa-pùai", "aujourd’hui, il est en congé maladie"]),
      w("ทำโอที", "tham oo-thii", "faire des heures supplémentaires", "office", ["คืนนี้{I}ต้องทำโอที", "khʉʉn-níi {i} tɔ̂ng tham oo-thii", "ce soir, je dois faire des heures supplémentaires"]),
      w("ขึ้นเงินเดือน", "khʉ̂n ngən-dʉan", "augmentation de salaire ; augmenter le salaire", "office", ["ปีนี้{I}ได้ขึ้นเงินเดือน", "pii-níi {i} dâai khʉ̂n ngən-dʉan", "cette année, j’ai eu une augmentation"]),
      w("โบนัส", "boo-nát", "prime, bonus", "office", ["ปลายปีมีโบนัสไหม{Q}", "plaai pii mii boo-nát mái {q}", "y a-t-il une prime en fin d’année ?"]),
      w("เข้างาน", "khâo ngaan", "commencer le travail, prendre son poste", "office", ["{I}เข้างานแปดโมงเช้า", "{i} khâo ngaan pɛ̀ɛt moong cháao", "je commence le travail à 8 h du matin"]),
      w("เลิกงาน", "lə̂ək ngaan", "finir le travail, quitter le bureau", "office", ["วันนี้เลิกงานกี่โมง{Q}", "wan-níi lə̂ək ngaan kìi moong {q}", "à quelle heure finissez-vous aujourd’hui ?"]),
    ],
  },
  {
    id: "safety", name: { fr: "Sécurité sur le chantier" }, icon: "alert",
    items: [
      w("เข็มขัดนิรภัย", "khěm-khàt ní-rá-phai", "harnais de sécurité ; ceinture de sécurité", "safety", ["ขึ้นที่สูงต้องใส่เข็มขัดนิรภัย", "khʉ̂n thîi-sǔung tɔ̂ng sài khěm-khàt ní-rá-phai", "pour monter en hauteur, il faut porter un harnais"]),
      w("รองเท้านิรภัย", "rɔɔng-tháao ní-rá-phai", "chaussures de sécurité", "safety", ["ทุกคนต้องใส่รองเท้านิรภัย", "thúk khon tɔ̂ng sài rɔɔng-tháao ní-rá-phai", "tout le monde doit porter des chaussures de sécurité"]),
      w("ถุงมือ", "thǔng-mʉʉ", "gants", "safety", ["อย่าลืมใส่ถุงมือนะ", "yàa lʉʉm sài thǔng-mʉʉ ná", "n’oublie pas de mettre tes gants"]),
      w("หน้ากาก", "nâa-kàak", "masque", "safety", ["ฝุ่นเยอะ ใส่หน้ากากด้วย", "fùn yə́ sài nâa-kàak dûai", "il y a beaucoup de poussière, mets un masque"]),
      w("อุปกรณ์", "ùp-pà-kɔɔn", "équipement, matériel", "safety", ["อุปกรณ์ความปลอดภัยครบไหม{Q}", "ùp-pà-kɔɔn khwaam plɔ̀ɔt-phai khróp mái {q}", "l’équipement de sécurité est-il complet ?"]),
      w("ป้องกัน", "pɔ̂ng-kan", "protéger ; prévenir, empêcher", "safety", ["หมวกนิรภัยช่วยป้องกันหัว", "mùak ní-rá-phai chûai pɔ̂ng-kan hǔa", "le casque protège la tête"]),
      w("ป้ายเตือน", "pâai tʉan", "panneau d’avertissement", "safety", ["ต้องติดป้ายเตือนตรงนี้", "tɔ̂ng tìt pâai tʉan trong-níi", "il faut mettre un panneau d’avertissement ici"]),
      w("ห้าม", "hâam", "interdire ; interdit de…", "safety", ["ห้ามสูบบุหรี่ในหน้างาน", "hâam sùup bù-rìi nai nâa-ngaan", "il est interdit de fumer sur le chantier"]),
      w("เสี่ยง", "sìang", "risqué ; prendre un risque", "safety", ["ทำแบบนี้เสี่ยงเกินไป", "tham bɛ̀ɛp níi sìang kəən pai", "faire comme ça, c’est trop risqué"]),
      w("ตก", "tòk", "tomber", "safety", ["ระวังตกจากนั่งร้าน", "rá-wang tòk jàak nâng-ráan", "attention à ne pas tomber de l’échafaudage"]),
      w("บาดเจ็บ", "bàat-jèp", "être blessé ; blessure", "safety", ["มีคนงานบาดเจ็บสองคน", "mii khon-ngaan bàat-jèp sɔ̌ɔng khon", "deux ouvriers ont été blessés"]),
      w("ปฐมพยาบาล", "pà-thǒm phá-yaa-baan", "premiers secours", "safety", ["กล่องปฐมพยาบาลอยู่ที่ไหน{Q}", "klɔ̀ng pà-thǒm phá-yaa-baan yùu thîi-nǎi {q}", "où est la trousse de premiers secours ?"]),
      w("ถังดับเพลิง", "thǎng dàp-phləəng", "extincteur", "safety", ["ถังดับเพลิงอยู่ข้างประตู", "thǎng dàp-phləəng yùu khâang prà-tuu", "l’extincteur est à côté de la porte"]),
      w("ทางหนีไฟ", "thaang nǐi-fai", "sortie de secours", "safety", ["ทางหนีไฟอยู่ทางนี้{P}", "thaang nǐi-fai yùu thaang níi {p}", "la sortie de secours est par ici"]),
      w("ไฟดูด", "fai dùut", "s’électrocuter, prendre une décharge", "safety", ["อย่าจับสายไฟ เดี๋ยวไฟดูด", "yàa jàp sǎai-fai dǐao fai dùut", "ne touche pas le câble, sinon tu vas t’électrocuter"]),
      w("ตรวจ", "trùat", "contrôler, vérifier, examiner", "safety", ["ต้องตรวจเหล็กเสริมก่อนเท", "tɔ̂ng trùat lèk-sə̌əm kɔ̀ɔn thee", "il faut contrôler les armatures avant de couler le béton"]),
      w("คุณภาพ", "khun-ná-phâap", "qualité", "safety", ["คอนกรีตนี้คุณภาพไม่ดี", "khɔɔn-krìit níi khun-ná-phâap mâi dii", "ce béton n’est pas de bonne qualité"]),
      w("มาตรฐาน", "mâat-trà-thǎan", "norme, standard", "safety", ["งานนี้ไม่ได้มาตรฐาน", "ngaan níi mâi dâai mâat-trà-thǎan", "ce travail n’est pas aux normes"]),
      w("ข้อบกพร่อง", "khɔ̂ɔ bòk-phrɔ̂ng", "défaut, malfaçon", "safety", ["เจอข้อบกพร่องสามจุด", "jəə khɔ̂ɔ bòk-phrɔ̂ng sǎam jùt", "on a trouvé trois défauts"]),
      w("แก้ไข", "kɛ̂ɛ-khǎi", "corriger, rectifier", "safety", ["ต้องแก้ไขก่อนวันศุกร์", "tɔ̂ng kɛ̂ɛ-khǎi kɔ̀ɔn wan-sùk", "il faut corriger ça avant vendredi"]),
      w("ผ่าน", "phàan", "passer ; être validé (contrôle)", "safety", ["งานนี้ตรวจผ่านแล้ว", "ngaan níi trùat phàan lɛ́ɛo", "ce travail a passé le contrôle"]),
      w("ทรุด", "sút", "s’affaisser, se tasser", "safety", ["พื้นตรงนี้ทรุดลงไป", "phʉ́ʉn trong-níi sút long pai", "le sol s’est affaissé ici"]),
      w("เอียง", "iang", "penché, incliné", "safety", ["เสาต้นนี้เอียงนิดหน่อย", "sǎo tôn níi iang nít-nɔ̀i", "ce poteau penche un peu"]),
      w("พัง", "phang", "s’effondrer ; être cassé, hors d’usage", "safety", ["กำแพงนี้อาจจะพังลงมา", "kam-phɛɛng níi àat-jà phang long maa", "ce mur risque de s’effondrer"]),
    ],
  },
  {
    id: "character", name: { fr: "Caractère et personnalité" }, icon: "user",
    items: [
      w("นิสัย", "ní-sǎi", "caractère ; habitude", "character", ["เขานิสัยดี ใครๆ ก็ชอบ", "khǎo ní-sǎi dii khrai-khrai kɔ̂ɔ chɔ̂ɔp", "il a bon caractère, tout le monde l’aime"]),
      w("ใจเย็น", "jai-yen", "patient, calme (qui ne s’énerve pas)", "character", ["ครูคนนี้ใจเย็นมาก", "khruu khon níi jai-yen mâak", "ce professeur est très patient"]),
      w("ใจร้อน", "jai-rɔ́ɔn", "impatient, qui s’emporte vite", "character", ["เวลาขับรถอย่าใจร้อน", "wee-laa khàp rót yàa jai-rɔ́ɔn", "quand tu conduis, ne sois pas impatient"]),
      w("ขี้อาย", "khîi-aai", "timide", "character", ["ลูกสาว{I}ขี้อายมาก", "lûuk-sǎao {i} khîi-aai mâak", "ma fille est très timide"]),
      w("ขยัน", "khà-yǎn", "travailleur, assidu", "character", ["เขาขยันทำงานทุกวัน", "khǎo khà-yǎn tham-ngaan thúk wan", "il travaille dur tous les jours"]),
      w("ขี้เกียจ", "khîi-kìat", "paresseux ; avoir la flemme de", "character", ["วันนี้{I}ขี้เกียจทำอาหาร", "wan-níi {i} khîi-kìat tham aa-hǎan", "aujourd’hui, j’ai la flemme de cuisiner"]),
      w("ซื่อสัตย์", "sʉ̂ʉ-sàt", "honnête", "character", ["เขาเป็นคนซื่อสัตย์มาก", "khǎo pen khon sʉ̂ʉ-sàt mâak", "c’est quelqu’un de très honnête"]),
      w("อารมณ์ดี", "aa-rom-dii", "de bonne humeur, jovial", "character", ["วันนี้หัวหน้าอารมณ์ดี", "wan-níi hǔa-nâa aa-rom-dii", "aujourd’hui, le chef est de bonne humeur"]),
      w("จริงจัง", "jing-jang", "sérieux", "character", ["เขาจริงจังกับงานมาก", "khǎo jing-jang kàp ngaan mâak", "il prend son travail très au sérieux"]),
      w("ใจกว้าง", "jai-kwâang", "généreux ; ouvert d’esprit", "character", ["พี่ชาย{I}ใจกว้างมาก", "phîi-chaai {i} jai-kwâang mâak", "mon grand frère est très généreux"]),
      w("ขี้เหนียว", "khîi-nǐao", "radin, avare", "character", ["เขาไม่ขี้เหนียวเลย", "khǎo mâi khîi-nǐao ləəi", "il n’est pas du tout radin"]),
      w("ดื้อ", "dʉ̂ʉ", "têtu ; désobéissant", "character", ["ลูกชาย{I}ดื้อมาก ไม่ฟังใครเลย", "lûuk-chaai {i} dʉ̂ʉ mâak mâi fang khrai ləəi", "mon fils est très têtu, il n’écoute personne"]),
      w("ขี้บ่น", "khîi-bòn", "râleur", "character", ["ยาย{I}ขี้บ่นนิดหน่อย", "yaai {i} khîi-bòn nít-nɔ̀i", "ma grand-mère est un peu râleuse"]),
      w("ใจร้าย", "jai-ráai", "méchant", "character", ["อย่าใจร้ายกับน้องนะ", "yàa jai-ráai kàp nɔ́ɔng ná", "ne sois pas méchant avec ton petit frère"]),
      w("สุภาพ", "sù-phâap", "poli", "character", ["คนไทยสุภาพมาก", "khon thai sù-phâap mâak", "les Thaïlandais sont très polis"]),
      w("เงียบ", "ngîap", "silencieux, calme ; discret", "character", ["เขาเป็นคนเงียบๆ ไม่ค่อยพูด", "khǎo pen khon ngîap-ngîap mâi khɔ̂i phûut", "c’est quelqu’un de discret, il ne parle pas beaucoup"]),
      w("ช่างพูด", "châang-phûut", "bavard", "character", ["เขาช่างพูด แต่{I}ชอบฟัง", "khǎo châang-phûut tɛ̀ɛ {i} chɔ̂ɔp fang", "lui est bavard, mais moi, j’aime écouter"]),
      w("เก่ง", "kèng", "doué, fort (en)", "character", ["เขาเก่งภาษาอังกฤษมาก", "khǎo kèng phaa-sǎa ang-krìt mâak", "il est très fort en anglais"]),
      w("ฉลาด", "chà-làat", "intelligent", "character", ["เด็กคนนี้ฉลาดมาก", "dèk khon níi chà-làat mâak", "cet enfant est très intelligent"]),
      w("มั่นใจ", "mân-jai", "sûr de soi, confiant ; sûr", "character", ["เขามั่นใจในตัวเองมาก", "khǎo mân-jai nai tua-eeng mâak", "il a très confiance en lui"]),
      w("เห็นแก่ตัว", "hěn-kɛ̀ɛ-tua", "égoïste", "character", ["อย่าเห็นแก่ตัวนะ", "yàa hěn-kɛ̀ɛ-tua ná", "ne sois pas égoïste"]),
      w("ตรงต่อเวลา", "trong-tɔ̀ɔ-wee-laa", "ponctuel", "character", ["เขาตรงต่อเวลาเสมอ ไม่เคยมาสาย", "khǎo trong-tɔ̀ɔ-wee-laa sà-mə̌ə mâi khəəi maa sǎai", "il est toujours ponctuel, il n’est jamais en retard"]),
      w("ละเอียด", "lá-ìat", "minutieux ; détaillé", "character", ["เขาทำงานละเอียดมาก", "khǎo tham-ngaan lá-ìat mâak", "il est très minutieux dans son travail"]),
      w("อดทน", "òt-thon", "endurant, persévérant ; supporter", "character", ["งานนี้ต้องอดทนมาก", "ngaan níi tɔ̂ng òt-thon mâak", "ce travail demande beaucoup de patience"]),
      w("เป็นกันเอง", "pen-kan-eeng", "simple, accessible, sans façon", "character", ["คนที่นี่เป็นกันเองมาก", "khon thîi-nîi pen-kan-eeng mâak", "les gens d’ici sont très simples et accueillants"]),
    ],
  },
  {
    id: "opinion", name: { fr: "Donner son avis" }, icon: "chat",
    items: [
      w("คิดว่า", "khít wâa", "penser que", "opinion", ["{I}คิดว่าพรุ่งนี้ฝนจะตก", "{i} khít wâa phrûng-níi fǒn jà tòk", "je pense qu’il va pleuvoir demain"]),
      w("ในความคิดของ{I}", "nai khwaam-khít khɔ̌ɔng {i}", "à mon avis", "opinion", ["ในความคิดของ{I} อาหารไทยอร่อยที่สุด", "nai khwaam-khít khɔ̌ɔng {i} aa-hǎan thai à-rɔ̀i thîi-sùt", "à mon avis, la cuisine thaïe est la meilleure"]),
      w("ความคิดเห็น", "khwaam-khít-hěn", "avis, opinion", "opinion", ["เราอยากฟังความคิดเห็นของคุณ", "rao yàak fang khwaam-khít-hěn khɔ̌ɔng khun", "nous aimerions connaître votre avis"]),
      w("ความคิด", "khwaam-khít", "idée ; pensée", "opinion", ["เป็นความคิดที่ดี{P}", "pen khwaam-khít thîi dii {p}", "c’est une bonne idée"]),
      w("รู้สึกว่า", "rúu-sʉ̀k wâa", "avoir l’impression que", "opinion", ["{I}รู้สึกว่าวันนี้ร้อนมาก", "{i} rúu-sʉ̀k wâa wan-níi rɔ́ɔn mâak", "j’ai l’impression qu’il fait très chaud aujourd’hui"]),
      w("เชื่อ", "chʉ̂a", "croire", "opinion", ["{I}เชื่อว่าเขาทำได้", "{i} chʉ̂a wâa khǎo tham dâai", "je crois qu’il peut y arriver"]),
      w("เห็นด้วย", "hěn-dûai", "être d’accord", "opinion", ["{I}เห็นด้วยกับคุณทุกอย่าง{P}", "{i} hěn-dûai kàp khun thúk yàang {p}", "je suis d’accord avec vous sur tout"]),
      w("ไม่เห็นด้วย", "mâi hěn-dûai", "ne pas être d’accord", "opinion", ["ขอโทษ{P} แต่{I}ไม่เห็นด้วย", "khɔ̌ɔ-thôot {p} tɛ̀ɛ {i} mâi hěn-dûai", "désolé, mais je ne suis pas d’accord"]),
      w("ตกลง", "tòk-long", "d’accord, entendu ; se mettre d’accord", "opinion", ["ตกลง{P} เจอกันหกโมง", "tòk-long {p} jəə kan hòk moong", "d’accord, on se retrouve à six heures"]),
      w("พูดถูก", "phûut thùuk", "avoir raison", "opinion", ["จริงด้วย คุณพูดถูก{P}", "jing dûai khun phûut thùuk {p}", "c’est vrai, vous avez raison"]),
      w("ผิด", "phìt", "faux ; se tromper, avoir tort", "opinion", ["ขอโทษ{P} {I}เข้าใจผิด", "khɔ̌ɔ-thôot {p} {i} khâo-jai phìt", "désolé, j’ai mal compris"]),
      w("ถูกต้อง", "thùuk-tɔ̂ng", "correct, exact", "opinion", ["คำตอบนี้ถูกต้อง", "kham-tɔ̀ɔp níi thùuk-tɔ̂ng", "cette réponse est correcte"]),
      w("แน่ใจ", "nɛ̂ɛ-jai", "être sûr", "opinion", ["{I}ไม่แน่ใจว่าเขาจะมา", "{i} mâi nɛ̂ɛ-jai wâa khǎo jà maa", "je ne suis pas sûr qu’il vienne"]),
      w("ข้อดี", "khɔ̂ɔ-dii", "avantage, point fort", "opinion", ["ข้อดีของที่นี่คือเงียบ", "khɔ̂ɔ-dii khɔ̌ɔng thîi-nîi khʉʉ ngîap", "l’avantage d’ici, c’est le calme"]),
      w("ข้อเสีย", "khɔ̂ɔ-sǐa", "inconvénient, point faible", "opinion", ["ข้อเสียคือแพงไปหน่อย", "khɔ̂ɔ-sǐa khʉʉ phɛɛng pai nɔ̀i", "l’inconvénient, c’est que c’est un peu cher"]),
      w("เหตุผล", "hèet-phǒn", "raison, motif", "opinion", ["เขามีเหตุผลที่ดี", "khǎo mii hèet-phǒn thîi dii", "il a une bonne raison"]),
      w("ส่วนตัว", "sùan-tua", "personnellement ; personnel, privé", "opinion", ["ส่วนตัว{I}ชอบทะเลมากกว่าภูเขา", "sùan-tua {i} chɔ̂ɔp thá-lee mâak-kwàa phuu-khǎo", "personnellement, je préfère la mer à la montagne"]),
      w("ดีกว่า", "dii-kwàa", "mieux, meilleur ; mieux vaut", "opinion", ["ไปพรุ่งนี้ดีกว่า{P}", "pai phrûng-níi dii-kwàa {p}", "mieux vaut y aller demain"]),
      w("แย่", "yɛ̂ɛ", "mauvais, nul ; ça va mal", "opinion", ["หนังเรื่องนี้แย่มาก", "nǎng rʉ̂ang níi yɛ̂ɛ mâak", "ce film est vraiment nul"]),
      w("น่าสนใจ", "nâa-sǒn-jai", "intéressant", "opinion", ["เรื่องนี้น่าสนใจมาก", "rʉ̂ang níi nâa-sǒn-jai mâak", "c’est très intéressant"]),
      w("ขึ้นอยู่กับ", "khʉ̂n-yùu kàp", "ça dépend de", "opinion", ["ขึ้นอยู่กับราคา{P}", "khʉ̂n-yùu kàp raa-khaa {p}", "ça dépend du prix"]),
      w("ควร", "khuan", "devoir (conseil), il vaudrait mieux", "opinion", ["คุณควรไปหาหมอ", "khun khuan pai hǎa mɔ̌ɔ", "vous devriez aller voir un médecin"]),
      w("คำแนะนำ", "kham-nɛ́-nam", "conseil, recommandation", "opinion", ["ขอบคุณสำหรับคำแนะนำ{P}", "khɔ̀ɔp-khun sǎm-ràp kham-nɛ́-nam {p}", "merci pour le conseil"]),
      w("ตัดสินใจ", "tàt-sǐn-jai", "décider, se décider", "opinion", ["{I}ยังตัดสินใจไม่ได้", "{i} yang tàt-sǐn-jai mâi dâai", "je n’arrive pas encore à me décider"]),
      w("เลือก", "lʉ̂ak", "choisir", "opinion", ["{I}เลือกไม่ถูก มีหลายอย่างมาก", "{i} lʉ̂ak mâi thùuk mii lǎai yàang mâak", "je n’arrive pas à choisir, il y a trop de choix"]),
    ],
  },
  {
    id: "social", name: { fr: "Vie sociale et invitations" }, icon: "sparkles",
    items: [
      w("ชวน", "chuan", "inviter, proposer (de venir)", "social", ["เพื่อนชวน{I}ไปกินข้าวเย็น", "phʉ̂an chuan {i} pai kin khâao yen", "un ami m’a invité à dîner"]),
      w("งานเลี้ยง", "ngaan-líang", "fête, réception", "social", ["คืนนี้มีงานเลี้ยงที่บ้านเพื่อน", "khʉʉn-níi mii ngaan-líang thîi bâan phʉ̂an", "ce soir, il y a une fête chez un ami"]),
      w("ปาร์ตี้", "paa-tîi", "soirée, fête (party)", "social", ["ปาร์ตี้วันเกิดสนุกมาก", "paa-tîi wan-kə̀ət sà-nùk mâak", "la fête d’anniversaire était super"]),
      w("แต่งงาน", "tɛ̀ng-ngaan", "se marier ; mariage", "social", ["พี่สาว{I}จะแต่งงานปีหน้า", "phîi-sǎao {i} jà tɛ̀ng-ngaan pii-nâa", "ma grande sœur se marie l’année prochaine"]),
      w("ยินดีด้วย", "yin-dii dûai", "félicitations", "social", ["ยินดีด้วยกับงานใหม่นะ", "yin-dii dûai kàp ngaan mài ná", "félicitations pour ton nouveau travail !"]),
      w("สุขสันต์วันเกิด", "sùk-sǎn wan-kə̀ət", "joyeux anniversaire", "social", ["สุขสันต์วันเกิด ขอให้มีความสุขมากๆ นะ", "sùk-sǎn wan-kə̀ət khɔ̌ɔ hâi mii khwaam-sùk mâak-mâak ná", "joyeux anniversaire, je te souhaite plein de bonheur"]),
      w("ปฏิเสธ", "pà-tì-sèet", "refuser", "social", ["เขาชวน{I}ไปเที่ยว แต่{I}ต้องปฏิเสธ", "khǎo chuan {i} pai thîao tɛ̀ɛ {i} tɔ̂ng pà-tì-sèet", "il m’a invité à sortir, mais j’ai dû refuser"]),
      w("แขก", "khɛ̀ɛk", "invité, visiteur", "social", ["วันนี้มีแขกมาที่บ้าน", "wan-níi mii khɛ̀ɛk maa thîi bâan", "aujourd’hui, nous avons des invités à la maison"]),
      w("เจ้าภาพ", "jâo-phâap", "hôte (celui qui reçoit)", "social", ["เจ้าภาพทำอาหารอร่อยมาก", "jâo-phâap tham aa-hǎan à-rɔ̀i mâak", "l’hôte a préparé un très bon repas"]),
      w("ฉลอง", "chà-lɔ̌ɔng", "fêter, célébrer", "social", ["คืนนี้ไปฉลองกันไหม{Q}", "khʉʉn-níi pai chà-lɔ̌ɔng kan mái {q}", "on va fêter ça ce soir ?"]),
      w("เค้ก", "khéek", "gâteau", "social", ["{I}ซื้อเค้กวันเกิดให้แม่", "{i} sʉ́ʉ khéek wan-kə̀ət hâi mɛ̂ɛ", "j’ai acheté un gâteau d’anniversaire pour ma mère"]),
      w("แนะนำ", "nɛ́-nam", "présenter (quelqu’un) ; recommander", "social", ["ขอแนะนำเพื่อน{I}{P}", "khɔ̌ɔ nɛ́-nam phʉ̂an {i} {p}", "je vous présente mon ami"]),
      w("รู้จัก", "rúu-jàk", "connaître (quelqu’un, un lieu)", "social", ["คุณรู้จักเขาไหม{Q}", "khun rúu-jàk khǎo mái {q}", "vous le connaissez ?"]),
      w("อวยพร", "uai-phɔɔn", "adresser des vœux, souhaiter", "social", ["ทุกคนอวยพรวันเกิด{I}", "thúk khon uai-phɔɔn wan-kə̀ət {i}", "tout le monde m’a souhaité un bon anniversaire"]),
      w("การ์ดเชิญ", "káat chəən", "carte d’invitation, faire-part", "social", ["{I}ได้การ์ดเชิญงานแต่งงาน", "{i} dâai káat chəən ngaan tɛ̀ng-ngaan", "j’ai reçu un faire-part de mariage"]),
      w("เจ้าสาว", "jâo-sǎao", "la mariée", "social", ["เจ้าสาวสวยมาก", "jâo-sǎao sǔai mâak", "la mariée est très belle"]),
      w("เจ้าบ่าว", "jâo-bàao", "le marié", "social", ["เจ้าบ่าวเป็นคนเบลเยียม", "jâo-bàao pen khon ben-yîam", "le marié est belge"]),
      w("สังสรรค์", "sǎng-sǎn", "se retrouver entre amis, faire la fête", "social", ["เย็นนี้เพื่อนร่วมงานไปสังสรรค์กัน", "yen-níi phʉ̂an-rûam-ngaan pai sǎng-sǎn kan", "ce soir, les collègues sortent ensemble"]),
      w("ขอบใจ", "khɔ̀ɔp-jai", "merci (entre amis, à un plus jeune)", "social", ["ขอบใจนะที่มาช่วย", "khɔ̀ɔp-jai ná thîi maa chûai", "merci d’être venu m’aider"]),
      w("ตามสบาย", "taam sà-baai", "à votre aise, faites comme chez vous", "social", ["เชิญนั่งตามสบาย{P}", "chəən nâng taam sà-baai {p}", "asseyez-vous, mettez-vous à l’aise"]),
      w("ขอตัว", "khɔ̌ɔ tua", "prendre congé, s’excuser (pour partir)", "social", ["{I}ขอตัวก่อนนะ{P} พรุ่งนี้ต้องตื่นเช้า", "{i} khɔ̌ɔ tua kɔ̀ɔn ná {p} phrûng-níi tɔ̂ng tʉ̀ʉn cháao", "je vais vous laisser, demain je dois me lever tôt"]),
      w("ไว้โอกาสหน้า", "wái oo-kàat nâa", "une autre fois (pour décliner poliment)", "social", ["วันนี้{I}ไม่ว่าง ไว้โอกาสหน้านะ{P}", "wan-níi {i} mâi wâang wái oo-kàat nâa ná {p}", "aujourd’hui je ne suis pas libre, ce sera pour une autre fois"]),
    ],
  },
  {
    id: "study", name: { fr: "Études et apprentissage" }, icon: "book",
    items: [
      w("ครู", "khruu", "professeur, instituteur (école)", "study", ["ครูภาษาไทยใจดีมาก", "khruu phaa-sǎa thai jai-dii mâak", "le professeur de thaï est très gentil"]),
      w("อาจารย์", "aa-jaan", "professeur (université), enseignant", "study", ["อาจารย์คนนี้สอนที่มหาวิทยาลัย", "aa-jaan khon níi sɔ̌ɔn thîi má-hǎa-wít-thá-yaa-lai", "ce professeur enseigne à l’université"]),
      w("นักเรียน", "nák-rian", "élève", "study", ["ห้องนี้มีนักเรียนยี่สิบคน", "hɔ̂ng níi mii nák-rian yîi-sìp khon", "il y a vingt élèves dans cette classe"]),
      w("นักศึกษา", "nák-sʉ̀k-sǎa", "étudiant (université)", "study", ["น้องสาว{I}เป็นนักศึกษา", "nɔ́ɔng-sǎao {i} pen nák-sʉ̀k-sǎa", "ma petite sœur est étudiante"]),
      w("สอน", "sɔ̌ɔn", "enseigner, apprendre (à quelqu’un)", "study", ["สอนภาษาไทยให้{I}หน่อยได้ไหม{Q}", "sɔ̌ɔn phaa-sǎa thai hâi {i} nɔ̀i dâai mái {q}", "vous pourriez m’apprendre le thaï ?"]),
      w("สอบ", "sɔ̀ɔp", "examen ; passer un examen", "study", ["พรุ่งนี้{I}มีสอบภาษาไทย", "phrûng-níi {i} mii sɔ̀ɔp phaa-sǎa thai", "demain, j’ai un examen de thaï"]),
      w("สอบผ่าน", "sɔ̀ɔp phàan", "réussir un examen", "study", ["ดีใจด้วย คุณสอบผ่านแล้ว", "dii-jai dûai khun sɔ̀ɔp phàan lɛ́ɛo", "bravo, vous avez réussi votre examen !"]),
      w("สอบตก", "sɔ̀ɔp tòk", "échouer à un examen, rater", "study", ["เขาสอบตกเพราะไม่ได้อ่านหนังสือ", "khǎo sɔ̀ɔp tòk phrɔ́ mâi dâai àan nǎng-sʉ̌ʉ", "il a échoué parce qu’il n’avait pas révisé"]),
      w("การบ้าน", "kaan-bâan", "devoirs (à la maison)", "study", ["ทำการบ้านเสร็จหรือยัง", "tham kaan-bâan sèt rʉ̌ʉ yang", "tu as fini tes devoirs ?"]),
      w("ห้องเรียน", "hɔ̂ng-rian", "salle de classe", "study", ["ห้องเรียนนี้ร้อนมาก", "hɔ̂ng-rian níi rɔ́ɔn mâak", "il fait très chaud dans cette salle de classe"]),
      w("วิชา", "wí-chaa", "matière (scolaire), cours", "study", ["คุณชอบวิชาอะไร{Q}", "khun chɔ̂ɔp wí-chaa à-rai {q}", "quelle matière préférez-vous ?"]),
      w("เรียนพิเศษ", "rian phí-sèet", "prendre des cours particuliers, du soutien", "study", ["ลูกสาว{I}เรียนพิเศษทุกวันเสาร์", "lûuk-sǎao {i} rian phí-sèet thúk wan-sǎo", "ma fille a des cours particuliers tous les samedis"]),
      w("ปริญญา", "pà-rin-yaa", "diplôme universitaire", "study", ["พี่ชาย{I}เพิ่งได้ปริญญา", "phîi-chaai {i} phə̂ng dâai pà-rin-yaa", "mon grand frère vient d’obtenir son diplôme"]),
      w("เรียนจบ", "rian jòp", "finir ses études, être diplômé", "study", ["เขาเรียนจบปีที่แล้ว", "khǎo rian jòp pii thîi-lɛ́ɛo", "il a terminé ses études l’an dernier"]),
      w("ทุนการศึกษา", "thun kaan-sʉ̀k-sǎa", "bourse d’études", "study", ["เขาได้ทุนการศึกษาไปเรียนที่ญี่ปุ่น", "khǎo dâai thun kaan-sʉ̀k-sǎa pai rian thîi yîi-pùn", "il a obtenu une bourse pour étudier au Japon"]),
      w("ฝึก", "fʉ̀k", "s’entraîner, pratiquer", "study", ["{I}ฝึกพูดภาษาไทยทุกวัน", "{i} fʉ̀k phûut phaa-sǎa thai thúk wan", "je m’entraîne à parler thaï tous les jours"]),
      w("ทบทวน", "thóp-thuan", "réviser, revoir", "study", ["ก่อนสอบต้องทบทวนบทเรียน", "kɔ̀ɔn sɔ̀ɔp tɔ̂ng thóp-thuan bòt-rian", "avant l’examen, il faut revoir les leçons"]),
      w("บทเรียน", "bòt-rian", "leçon", "study", ["บทเรียนวันนี้ง่ายมาก", "bòt-rian wan-níi ngâai mâak", "la leçon d’aujourd’hui est très facile"]),
      w("คำศัพท์", "kham-sàp", "vocabulaire, mot", "study", ["วันนี้{I}จำคำศัพท์ใหม่ได้สิบคำ", "wan-níi {i} jam kham-sàp mài dâai sìp kham", "aujourd’hui, j’ai retenu dix nouveaux mots"]),
      w("คะแนน", "khá-nɛɛn", "note, points", "study", ["{I}ได้คะแนนดีมาก", "{i} dâai khá-nɛɛn dii mâak", "j’ai eu une très bonne note"]),
      w("ห้องสมุด", "hɔ̂ng-sà-mùt", "bibliothèque", "study", ["{I}ไปอ่านหนังสือที่ห้องสมุด", "{i} pai àan nǎng-sʉ̌ʉ thîi hɔ̂ng-sà-mùt", "je vais étudier à la bibliothèque"]),
      w("เทอม", "thəəm", "semestre, trimestre (scolaire)", "study", ["เทอมนี้{I}เรียนสี่วิชา", "thəəm níi {i} rian sìi wí-chaa", "ce semestre, je suis quatre matières"]),
      w("อธิบาย", "à-thí-baai", "expliquer", "study", ["ช่วยอธิบายอีกครั้งได้ไหม{Q}", "chûai à-thí-baai ìik khráng dâai mái {q}", "pourriez-vous réexpliquer ?"]),
    ],
  },
  {
    id: "digital", name: { fr: "Numérique au quotidien" }, icon: "phone",
    items: [
      w("ออนไลน์", "ɔɔn-laai", "en ligne", "digital", ["{I}ชอบซื้อของออนไลน์", "{i} chɔ̂ɔp sʉ́ʉ khɔ̌ɔng ɔɔn-laai", "j’aime acheter en ligne"]),
      w("โซเชียล", "soo-chìan", "réseaux sociaux", "digital", ["เขาเล่นโซเชียลทั้งวัน", "khǎo lên soo-chìan tháng-wan", "il passe toute la journée sur les réseaux sociaux"]),
      w("ดาวน์โหลด", "daao-lòot", "télécharger", "digital", ["ดาวน์โหลดแอปนี้ก่อน{P}", "daao-lòot ɛ́p níi kɔ̀ɔn {p}", "téléchargez d’abord cette application"]),
      w("อัปโหลด", "àp-lòot", "mettre en ligne (une photo, un fichier)", "digital", ["{I}อัปโหลดรูปแล้ว", "{i} àp-lòot rûup lɛ́ɛo", "j’ai mis la photo en ligne"]),
      w("อัปเดต", "àp-dèet", "mettre à jour ; mise à jour", "digital", ["ต้องอัปเดตแอปก่อน", "tɔ̂ng àp-dèet ɛ́p kɔ̀ɔn", "il faut d’abord mettre l’application à jour"]),
      w("แชร์", "chɛɛ", "partager (sur internet)", "digital", ["แชร์รูปให้{I}หน่อย", "chɛɛ rûup hâi {i} nɔ̀i", "partage-moi les photos, s’il te plaît"]),
      w("โพสต์", "phóot", "publier ; publication (post)", "digital", ["เขาโพสต์รูปทุกวัน", "khǎo phóot rûup thúk wan", "il publie des photos tous les jours"]),
      w("กดไลก์", "kòt lái", "liker, mettre un « j’aime »", "digital", ["ช่วยกดไลก์ด้วยนะ", "chûai kòt lái dûai ná", "pense à liker, s’il te plaît"]),
      w("ล็อกอิน", "lɔ́k-in", "se connecter (à un compte)", "digital", ["{I}ล็อกอินไม่ได้", "{i} lɔ́k-in mâi dâai", "je n’arrive pas à me connecter"]),
      w("ข้อความเสียง", "khɔ̂ɔ-khwaam sǐang", "message vocal", "digital", ["{I}ส่งข้อความเสียงไปแล้ว", "{i} sòng khɔ̂ɔ-khwaam sǐang pai lɛ́ɛo", "j’ai déjà envoyé un message vocal"]),
      w("วิดีโอคอล", "wí-dii-oo khɔɔn", "appel vidéo", "digital", ["คืนนี้วิดีโอคอลกันไหม", "khʉʉn-níi wí-dii-oo khɔɔn kan mái", "on se fait un appel vidéo ce soir ?"]),
      w("รูปโปรไฟล์", "rûup proo-fai", "photo de profil", "digital", ["รูปโปรไฟล์ใหม่สวยจัง", "rûup proo-fai mài sǔai jang", "ta nouvelle photo de profil est vraiment belle"]),
      w("ไฟล์", "fai", "fichier", "digital", ["ส่งไฟล์ทางอีเมลได้ไหม{Q}", "sòng fai thaang ii-meo dâai mái {q}", "pouvez-vous envoyer le fichier par e-mail ?"]),
      w("เว็บไซต์", "wép-sái", "site internet", "digital", ["ดูราคาในเว็บไซต์ได้", "duu raa-khaa nai wép-sái dâai", "on peut voir les prix sur le site internet"]),
      w("ค้นหา", "khón-hǎa", "chercher, rechercher (en ligne)", "digital", ["ลองค้นหาในอินเทอร์เน็ตดู", "lɔɔng khón-hǎa nai in-təə-nét duu", "essaie de chercher sur internet"]),
      w("ลบ", "lóp", "effacer, supprimer", "digital", ["อย่าลบรูปนี้นะ", "yàa lóp rûup níi ná", "n’efface pas cette photo, hein"]),
      w("บันทึก", "ban-thʉ́k", "enregistrer, sauvegarder", "digital", ["อย่าลืมบันทึกไฟล์นะ", "yàa lʉʉm ban-thʉ́k fai ná", "n’oublie pas d’enregistrer le fichier"]),
      w("ติดตั้ง", "tìt-tâng", "installer", "digital", ["{I}ติดตั้งแอปใหม่แล้ว", "{i} tìt-tâng ɛ́p mài lɛ́ɛo", "j’ai installé la nouvelle application"]),
      w("ตั้งค่า", "tâng-khâa", "paramètres ; régler", "digital", ["เปลี่ยนภาษาได้ในหน้าตั้งค่า", "plìan phaa-sǎa dâai nai nâa tâng-khâa", "on peut changer la langue dans les paramètres"]),
      w("คลิป", "khlíp", "(courte) vidéo, clip", "digital", ["คลิปนี้ตลกมาก", "khlíp níi tà-lòk mâak", "cette vidéo est très drôle"]),
      w("สแกน", "sà-kɛɛn", "scanner (un QR code)", "digital", ["สแกนตรงนี้ได้เลย{P}", "sà-kɛɛn trong-níi dâai ləəi {p}", "vous pouvez scanner ici"]),
      w("ค้าง", "kháang", "planter, se figer (appareil)", "digital", ["มือถือ{I}ค้างอีกแล้ว", "mʉʉ-thʉ̌ʉ {i} kháang ìik lɛ́ɛo", "mon portable a encore planté"]),
      w("โน้ตบุ๊ก", "nóot-búk", "ordinateur portable", "digital", ["{I}ลืมโน้ตบุ๊กไว้ที่บ้าน", "{i} lʉʉm nóot-búk wái thîi bâan", "j’ai oublié mon ordinateur portable à la maison"]),
    ],
  },
  {
    id: "environment", name: { fr: "Environnement" }, icon: "leaf",
    items: [
      w("สิ่งแวดล้อม", "sìng-wɛ̂ɛt-lɔ́ɔm", "environnement", "environment", ["เราต้องช่วยกันดูแลสิ่งแวดล้อม", "rao tɔ̂ng chûai kan duu-lɛɛ sìng-wɛ̂ɛt-lɔ́ɔm", "nous devons tous prendre soin de l’environnement"]),
      w("มลพิษ", "mon-lá-phít", "pollution", "environment", ["ในเมืองมีมลพิษเยอะ", "nai mʉang mii mon-lá-phít yə́", "en ville, il y a beaucoup de pollution"]),
      w("ถังขยะ", "thǎng khà-yà", "poubelle", "environment", ["ถังขยะอยู่ที่ไหน{Q}", "thǎng khà-yà yùu thîi-nǎi {q}", "où est la poubelle ?"]),
      w("ทิ้ง", "thíng", "jeter ; abandonner", "environment", ["ทิ้งขวดตรงนี้ได้ไหม{Q}", "thíng khùat trong-níi dâai mái {q}", "je peux jeter la bouteille ici ?"]),
      w("แยกขยะ", "yɛ̂ɛk khà-yà", "trier les déchets", "environment", ["ที่บ้าน{I}แยกขยะทุกวัน", "thîi bâan {i} yɛ̂ɛk khà-yà thúk wan", "à la maison, je trie les déchets tous les jours"]),
      w("รีไซเคิล", "rii-sai-khəən", "recycler ; recyclage", "environment", ["ขวดพลาสติกรีไซเคิลได้", "khùat phlâat-sà-tìk rii-sai-khəən dâai", "les bouteilles en plastique se recyclent"]),
      w("ใช้ซ้ำ", "chái sám", "réutiliser", "environment", ["ถุงนี้ใช้ซ้ำได้หลายครั้ง", "thǔng níi chái sám dâai lǎai khráng", "ce sac peut être réutilisé plusieurs fois"]),
      w("ถุงพลาสติก", "thǔng phlâat-sà-tìk", "sac en plastique", "environment", ["ร้านนี้ไม่ให้ถุงพลาสติก", "ráan níi mâi hâi thǔng phlâat-sà-tìk", "ce magasin ne donne pas de sacs en plastique"]),
      w("ถุงผ้า", "thǔng phâa", "sac en tissu", "environment", ["{I}เอาถุงผ้ามาเอง", "{i} ao thǔng phâa maa eeng", "j’ai apporté mon propre sac en tissu"]),
      w("หลอด", "lɔ̀ɔt", "paille ; tube", "environment", ["ไม่ต้องใส่หลอด{P}", "mâi tɔ̂ng sài lɔ̀ɔt {p}", "pas besoin de paille, merci"]),
      w("น้ำท่วม", "náam thûam", "inondation ; être inondé", "environment", ["ถนนนี้น้ำท่วมทุกปี", "thà-nǒn níi náam thûam thúk pii", "cette rue est inondée tous les ans"]),
      w("ภัยแล้ง", "phai-lɛ́ɛng", "sécheresse", "environment", ["ปีนี้ภัยแล้งหนักมาก", "pii níi phai-lɛ́ɛng nàk mâak", "cette année, la sécheresse est très grave"]),
      w("ควัน", "khwan", "fumée", "environment", ["ควันรถเยอะมาก", "khwan rót yə́ mâak", "il y a énormément de fumée de voitures"]),
      w("ฝุ่น", "fùn", "poussière ; particules fines", "environment", ["วันนี้ฝุ่นเยอะมาก", "wan-níi fùn yə́ mâak", "aujourd’hui, il y a beaucoup de particules fines"]),
      w("หมอกควัน", "mɔ̀ɔk-khwan", "brume de pollution, smog", "environment", ["ช่วงนี้เชียงใหม่มีหมอกควัน", "chûang-níi chiang-mài mii mɔ̀ɔk-khwan", "en ce moment, il y a du smog à Chiang Mai"]),
      w("หน้ากากอนามัย", "nâa-kàak à-naa-mai", "masque (sanitaire)", "environment", ["ฝุ่นเยอะ ใส่หน้ากากอนามัยด้วย", "fùn yə́ sài nâa-kàak à-naa-mai dûai", "il y a beaucoup de poussière, mets un masque"]),
      w("เผา", "phǎo", "brûler", "environment", ["ห้ามเผาขยะ", "hâam phǎo khà-yà", "interdit de brûler les déchets"]),
      w("ไฟป่า", "fai pàa", "feu de forêt", "environment", ["ไฟป่าทำให้อากาศไม่ดี", "fai pàa tham-hâi aa-kàat mâi dii", "les feux de forêt rendent l’air mauvais"]),
      w("ปกป้อง", "pòk-pɔ̂ng", "protéger", "environment", ["เราต้องปกป้องป่าไม้", "rao tɔ̂ng pòk-pɔ̂ng pàa-máai", "nous devons protéger les forêts"]),
      w("พลังงาน", "phá-lang-ngaan", "énergie", "environment", ["ช่วยกันประหยัดพลังงาน", "chûai kan prà-yàt phá-lang-ngaan", "économisons l’énergie ensemble"]),
      w("ไฟฟ้า", "fai-fáa", "électricité", "environment", ["เดือนนี้ค่าไฟฟ้าแพงมาก", "dʉan níi khâa fai-fáa phɛɛng mâak", "ce mois-ci, la facture d’électricité est très chère"]),
      w("โลก", "lôok", "la Terre ; le monde", "environment", ["เราอยู่บนโลกใบเดียวกัน", "rao yùu bon lôok bai diao kan", "nous vivons tous sur la même planète"]),
      w("โลกร้อน", "lôok rɔ́ɔn", "réchauffement climatique", "environment", ["โลกร้อนเป็นปัญหาใหญ่", "lôok rɔ́ɔn pen pan-hǎa yài", "le réchauffement climatique est un gros problème"]),
      w("น้ำเสีย", "náam sǐa", "eaux usées, eau polluée", "environment", ["โรงงานปล่อยน้ำเสียลงแม่น้ำ", "roong-ngaan plɔ̀i náam sǐa long mɛ̂ɛ-náam", "l’usine rejette des eaux usées dans la rivière"]),
    ],
  },
  {
    id: "fitness", name: { fr: "Sport et forme" }, icon: "heart",
    items: [
      w("ยิม", "yim", "salle de sport", "fitness", ["{I}ไปยิมอาทิตย์ละสามครั้ง", "{i} pai yim aa-thít lá sǎam khráng", "je vais à la salle de sport trois fois par semaine"]),
      w("สมาชิก", "sà-maa-chík", "membre, adhérent", "fitness", ["ค่าสมาชิกเดือนละเท่าไหร่{Q}", "khâa sà-maa-chík dʉan lá thâo-rài {q}", "combien coûte l’abonnement par mois ?"]),
      w("ซ้อม", "sɔ́ɔm", "s’entraîner (sport), répéter", "fitness", ["เขาซ้อมวิ่งทุกเย็น", "khǎo sɔ́ɔm wîng thúk yen", "il s’entraîne à courir tous les soirs"]),
      w("โค้ช", "khóot", "entraîneur, coach", "fitness", ["โค้ชคนนี้ใจดีมาก", "khóot khon níi jai-dii mâak", "cet entraîneur est très gentil"]),
      w("อบอุ่นร่างกาย", "ɔ̀p-ùn râang-kaai", "s’échauffer", "fitness", ["ต้องอบอุ่นร่างกายก่อนวิ่ง", "tɔ̂ng ɔ̀p-ùn râang-kaai kɔ̀ɔn wîng", "il faut s’échauffer avant de courir"]),
      w("ยืดเส้น", "yʉ̂ʉt-sên", "s’étirer", "fitness", ["อย่าลืมยืดเส้นหลังวิ่ง", "yàa lʉʉm yʉ̂ʉt-sên lǎng wîng", "n’oublie pas de t’étirer après avoir couru"]),
      w("ยกน้ำหนัก", "yók náam-nàk", "soulever des poids, faire de la musculation", "fitness", ["{I}ชอบยกน้ำหนักที่ยิม", "{i} chɔ̂ɔp yók náam-nàk thîi yim", "j’aime soulever des poids à la salle"]),
      w("กล้ามเนื้อ", "klâam-nʉ́a", "muscle", "fitness", ["ออกกำลังกายช่วยให้กล้ามเนื้อแข็งแรง", "ɔ̀ɔk-kam-lang-kaai chûai hâi klâam-nʉ́a khɛ̌ng-rɛɛng", "faire du sport renforce les muscles"]),
      w("ลู่วิ่ง", "lûu-wîng", "tapis de course ; piste", "fitness", ["{I}วิ่งบนลู่วิ่งสามสิบนาที", "{i} wîng bon lûu-wîng sǎam-sìp naa-thii", "je cours trente minutes sur le tapis"]),
      w("สระว่ายน้ำ", "sà-wâai-náam", "piscine", "fitness", ["โรงแรมนี้มีสระว่ายน้ำไหม{Q}", "roong-rɛɛm níi mii sà-wâai-náam mái {q}", "cet hôtel a-t-il une piscine ?"]),
      w("เหงื่อออก", "ngʉ̀a ɔ̀ɔk", "transpirer", "fitness", ["อากาศร้อน เหงื่อออกเยอะมาก", "aa-kàat rɔ́ɔn ngʉ̀a ɔ̀ɔk yə́ mâak", "il fait chaud, on transpire beaucoup"]),
      w("หายใจ", "hǎai-jai", "respirer", "fitness", ["หายใจลึกๆ ช้าๆ", "hǎai-jai lʉ́k-lʉ́k cháa-cháa", "respirez profondément et lentement"]),
      w("หอบ", "hɔ̀ɔp", "essoufflé, haleter", "fitness", ["เขาวิ่งมาจนหอบ", "khǎo wîng maa jon hɔ̀ɔp", "il est arrivé en courant, tout essoufflé"]),
      w("ปวดเมื่อย", "pùat-mʉ̂ai", "avoir des courbatures", "fitness", ["เมื่อวานวิ่ง วันนี้เลยปวดเมื่อยทั้งตัว", "mʉ̂a-waan wîng wan-níi ləəi pùat-mʉ̂ai tháng tua", "j’ai couru hier, alors aujourd’hui j’ai des courbatures partout"]),
      w("เป็นตะคริว", "pen tà-khriu", "avoir une crampe", "fitness", ["{I}เป็นตะคริวที่ขา", "{i} pen tà-khriu thîi khǎa", "j’ai une crampe à la jambe"]),
      w("ข้อเท้าพลิก", "khɔ̂ɔ-tháao phlík", "se tordre la cheville", "fitness", ["{I}ข้อเท้าพลิกตอนวิ่ง", "{i} khɔ̂ɔ-tháao phlík tɔɔn wîng", "je me suis tordu la cheville en courant"]),
      w("ลดน้ำหนัก", "lót náam-nàk", "perdre du poids, maigrir", "fitness", ["{I}อยากลดน้ำหนักห้ากิโล", "{i} yàak lót náam-nàk hâa kì-loo", "je voudrais perdre cinq kilos"]),
      w("อ้วน", "ûan", "gros ; grossir (อ้วนขึ้น)", "fitness", ["ช่วงนี้{I}อ้วนขึ้น", "chûang-níi {i} ûan khʉ̂n", "ces temps-ci, j’ai grossi"]),
      w("ผอม", "phɔ̌ɔm", "mince, maigre", "fitness", ["น้องสาว{I}ผอมมาก", "nɔ́ɔng-sǎao {i} phɔ̌ɔm mâak", "ma petite sœur est très mince"]),
      w("ฟิต", "fít", "en forme", "fitness", ["พ่ออายุเจ็ดสิบแต่ยังฟิตอยู่", "phɔ̂ɔ aa-yú jèt-sìp tɛ̀ɛ yang fít yùu", "mon père a soixante-dix ans mais il est encore en forme"]),
      w("นักกีฬา", "nák-kii-laa", "sportif, athlète", "fitness", ["เขาอยากเป็นนักกีฬา", "khǎo yàak pen nák-kii-laa", "il veut devenir athlète"]),
      w("ทีม", "thiim", "équipe", "fitness", ["{I}อยู่ทีมเดียวกับเขา", "{i} yùu thiim diao kàp khǎo", "je suis dans la même équipe que lui"]),
      w("แข่งขัน", "khɛ̀ng-khǎn", "compétition ; concourir", "fitness", ["พรุ่งนี้มีการแข่งขันวิ่ง", "phrûng-níi mii kaan khɛ̀ng-khǎn wîng", "demain, il y a une course à pied"]),
      w("ชนะ", "chá-ná", "gagner (un match)", "fitness", ["ทีมไทยชนะสองต่อศูนย์", "thiim thai chá-ná sɔ̌ɔng tɔ̀ɔ sǔun", "l’équipe thaïlandaise a gagné deux à zéro"]),
    ],
  },
  {
    id: "service", name: { fr: "Services et réclamations" }, icon: "bag",
    items: [
      w("ร้องเรียน", "rɔ́ɔng-rian", "se plaindre, faire une réclamation", "service", ["{I}อยากร้องเรียนเรื่องบริการ", "{i} yàak rɔ́ɔng-rian rʉ̂ang bɔɔ-rí-kaan", "je voudrais faire une réclamation au sujet du service"]),
      w("รับประกัน", "ráp-prà-kan", "garantie ; garantir", "service", ["เครื่องนี้รับประกันหนึ่งปี", "khrʉ̂ang níi ráp-prà-kan nʉ̀ng pii", "cet appareil est garanti un an"]),
      w("สินค้า", "sǐn-kháa", "article, produit, marchandise", "service", ["สินค้าหมดแล้ว{P}", "sǐn-kháa mòt lɛ́ɛo {p}", "l’article est épuisé"]),
      w("สั่งของ", "sàng khɔ̌ɔng", "commander (un article), passer commande", "service", ["{I}สั่งของไปเมื่อวาน", "{i} sàng khɔ̌ɔng pai mʉ̂a-waan", "j’ai passé une commande hier"]),
      w("ยืนยัน", "yʉʉn-yan", "confirmer", "service", ["ช่วยยืนยันวันส่งของได้ไหม{Q}", "chûai yʉʉn-yan wan sòng khɔ̌ɔng dâai mái {q}", "pouvez-vous confirmer la date de livraison ?"]),
      w("จัดส่ง", "jàt-sòng", "livrer ; livraison", "service", ["ค่าจัดส่งห้าสิบบาท", "khâa jàt-sòng hâa-sìp bàat", "les frais de livraison sont de cinquante bahts"]),
      w("พัสดุ", "phát-sà-dù", "colis", "service", ["มีพัสดุมาส่ง{P}", "mii phát-sà-dù maa sòng {p}", "il y a un colis pour vous"]),
      w("ติดตาม", "tìt-taam", "suivre (un colis, une affaire)", "service", ["ติดตามพัสดุได้ในแอป", "tìt-taam phát-sà-dù dâai nai ɛ́p", "on peut suivre le colis dans l’appli"]),
      w("ได้รับ", "dâai-ráp", "recevoir", "service", ["{I}ยังไม่ได้รับของเลย", "{i} yang mâi dâai-ráp khɔ̌ɔng ləəi", "je n’ai toujours pas reçu ma commande"]),
      w("เก็บเงินปลายทาง", "kèp ngən plaai-thaang", "paiement à la livraison", "service", ["จ่ายแบบเก็บเงินปลายทางได้ไหม{Q}", "jàai bɛ̀ɛp kèp ngən plaai-thaang dâai mái {q}", "peut-on payer à la livraison ?"]),
      w("ขาด", "khàat", "manquer (il manque)", "service", ["ของขาดไปหนึ่งชิ้น", "khɔ̌ɔng khàat pai nʉ̀ng chín", "il manque un article"]),
      w("ชิ้น", "chín", "pièce, article (classificateur)", "service", ["{I}สั่งไปสามชิ้น แต่ได้สองชิ้น", "{i} sàng pai sǎam chín tɛ̀ɛ dâai sɔ̌ɔng chín", "j’en ai commandé trois, mais j’en ai reçu deux"]),
      w("เสียหาย", "sǐa-hǎai", "endommagé, abîmé", "service", ["กล่องเสียหายตอนจัดส่ง", "klɔ̀ng sǐa-hǎai tɔɔn jàt-sòng", "le carton a été abîmé pendant la livraison"]),
      w("แตก", "tɛ̀ɛk", "cassé, brisé (verre, vaisselle)", "service", ["แก้วแตกมาสองใบ", "kɛ̂ɛo tɛ̀ɛk maa sɔ̌ɔng bai", "deux verres sont arrivés cassés"]),
      w("ใช้ไม่ได้", "chái mâi dâai", "ne fonctionne pas, inutilisable", "service", ["ของใหม่แต่ใช้ไม่ได้", "khɔ̌ɔng mài tɛ̀ɛ chái mâi dâai", "c’est neuf, mais ça ne marche pas"]),
      w("คืนสินค้า", "khʉʉn sǐn-kháa", "retourner un article", "service", ["คืนสินค้าได้ภายในเจ็ดวัน", "khʉʉn sǐn-kháa dâai phaai-nai jèt wan", "on peut retourner l’article sous sept jours"]),
      w("บิล", "bin", "facture ; addition", "service", ["บิลค่าไฟเดือนนี้แพงมาก", "bin khâa fai dʉan níi phɛɛng mâak", "la facture d’électricité est très chère ce mois-ci"]),
      w("ฝ่ายบริการลูกค้า", "fàai bɔɔ-rí-kaan lûuk-kháa", "service client", "service", ["โทรหาฝ่ายบริการลูกค้าดีกว่า", "thoo hǎa fàai bɔɔ-rí-kaan lûuk-kháa dii kwàa", "mieux vaut appeler le service client"]),
      w("ติดต่อ", "tìt-tɔ̀ɔ", "contacter, joindre", "service", ["ติดต่อร้านไม่ได้เลย", "tìt-tɔ̀ɔ ráan mâi dâai ləəi", "impossible de joindre le magasin"]),
      w("พอใจ", "phɔɔ-jai", "satisfait", "service", ["{I}ไม่พอใจบริการนี้เลย", "{i} mâi phɔɔ-jai bɔɔ-rí-kaan níi ləəi", "je ne suis pas du tout satisfait de ce service"]),
    ],
  },
  {
    id: "time2", name: { fr: "Le temps qui passe" }, icon: "clock",
    items: [
      w("ตั้งแต่", "tâng-tɛ̀ɛ", "depuis (un moment précis)", "time2", ["{I}เรียนภาษาไทยตั้งแต่ปีที่แล้ว", "{i} rian phaa-sǎa thai tâng-tɛ̀ɛ pii thîi-lɛ́ɛo", "j’apprends le thaï depuis l’année dernière"]),
      w("จนถึง", "jon-thʉ̌ng", "jusqu’à", "time2", ["ร้านเปิดจนถึงสี่ทุ่ม", "ráan pə̀ət jon-thʉ̌ng sìi thûm", "le magasin est ouvert jusqu’à 22 h"]),
      w("จนกว่า", "jon-kwàa", "jusqu’à ce que", "time2", ["รอจนกว่าฝนจะหยุดนะ", "rɔɔ jon-kwàa fǒn jà yùt ná", "attends jusqu’à ce que la pluie s’arrête"]),
      w("ระหว่าง", "rá-wàang", "pendant ; entre", "time2", ["อย่าใช้มือถือระหว่างขับรถ", "yàa chái mʉʉ-thʉ̌ʉ rá-wàang khàp rót", "n’utilise pas ton portable pendant que tu conduis"]),
      w("อีกไม่นาน", "ìik mâi naan", "d’ici peu, bientôt", "time2", ["อีกไม่นานรถไฟจะมาถึง", "ìik mâi naan rót-fai jà maa thʉ̌ng", "le train va arriver d’ici peu"]),
      w("เมื่อเร็วๆนี้", "mʉ̂a reo-reo níi", "récemment", "time2", ["เขาเพิ่งแต่งงานเมื่อเร็วๆนี้", "khǎo phə̂ng tɛ̀ng-ngaan mʉ̂a reo-reo níi", "il s’est marié récemment"]),
      w("สมัยก่อน", "sà-mǎi kɔ̀ɔn", "autrefois, jadis", "time2", ["สมัยก่อนที่นี่เป็นทุ่งนา", "sà-mǎi kɔ̀ɔn thîi-nîi pen thûng-naa", "autrefois, il y avait des rizières ici"]),
      w("เมื่อก่อน", "mʉ̂a-kɔ̀ɔn", "avant (dans le passé)", "time2", ["เมื่อก่อน{I}ไม่ชอบผัก", "mʉ̂a-kɔ̀ɔn {i} mâi chɔ̂ɔp phàk", "avant, je n’aimais pas les légumes"]),
      w("ในอนาคต", "nai à-naa-khót", "à l’avenir", "time2", ["ในอนาคต{I}อยากมีบ้านริมทะเล", "nai à-naa-khót {i} yàak mii bâan rim thá-lee", "à l’avenir, j’aimerais avoir une maison au bord de la mer"]),
      w("เดี๋ยว", "dǐao", "tout à l’heure, dans un instant", "time2", ["เดี๋ยวเจอกันที่ร้านกาแฟนะ", "dǐao jəə kan thîi ráan kaa-fɛɛ ná", "on se retrouve tout à l’heure au café"]),
      w("ไม่ทัน", "mâi than", "ne pas arriver à temps, rater", "time2", ["{I}ขึ้นรถไฟไม่ทัน", "{i} khʉ̂n rót-fai mâi than", "j’ai raté le train"]),
      w("นาน", "naan", "longtemps", "time2", ["คุณรอนานไหม{Q}", "khun rɔɔ naan mái {q}", "vous avez attendu longtemps ?"]),
      w("สักพัก", "sàk phák", "un moment, un petit moment", "time2", ["นั่งพักสักพักก่อนไหม{Q}", "nâng phák sàk phák kɔ̀ɔn mái {q}", "vous voulez vous asseoir un moment ?"]),
      w("ช่วงนี้", "chûang-níi", "ces temps-ci, en ce moment", "time2", ["ช่วงนี้{I}ยุ่งมาก", "chûang-níi {i} yûng mâak", "ces temps-ci, je suis très occupé"]),
      w("วันก่อน", "wan kɔ̀ɔn", "l’autre jour", "time2", ["วันก่อน{I}เจอครูที่ตลาด", "wan kɔ̀ɔn {i} jəə khruu thîi tà-làat", "l’autre jour, j’ai croisé mon professeur au marché"]),
      w("ตอนแรก", "tɔɔn-rɛ̂ɛk", "au début", "time2", ["ตอนแรก{I}ไม่เข้าใจ แต่ตอนนี้เข้าใจแล้ว", "tɔɔn-rɛ̂ɛk {i} mâi khâo-jai tɛ̀ɛ tɔɔn-níi khâo-jai lɛ́ɛo", "au début, je ne comprenais pas, mais maintenant je comprends"]),
      w("ตอนหลัง", "tɔɔn-lǎng", "plus tard, par la suite", "time2", ["ตอนหลังเขาย้ายไปเชียงใหม่", "tɔɔn-lǎng khǎo yáai pai chiang-mài", "par la suite, il a déménagé à Chiang Mai"]),
      w("ครั้งแรก", "khráng-rɛ̂ɛk", "la première fois", "time2", ["นี่เป็นครั้งแรกที่{I}มาเมืองไทย", "nîi pen khráng-rɛ̂ɛk thîi {i} maa mʉang-thai", "c’est la première fois que je viens en Thaïlande"]),
      w("ครั้งหน้า", "khráng-nâa", "la prochaine fois", "time2", ["ครั้งหน้า{I}จะมาใหม่นะ", "khráng-nâa {i} jà maa mài ná", "la prochaine fois, je reviendrai"]),
      w("ตอนเด็ก", "tɔɔn dèk", "quand j’étais petit, dans l’enfance", "time2", ["ตอนเด็ก{I}ชอบว่ายน้ำมาก", "tɔɔn dèk {i} chɔ̂ɔp wâai-náam mâak", "quand j’étais petit, j’adorais nager"]),
      w("ภายใน", "phaai-nai", "d’ici, en moins de (délai) ; à l’intérieur", "time2", ["เราจะส่งของให้ภายในสามวัน", "rao jà sòng khɔ̌ɔng hâi phaai-nai sǎam wan", "nous vous livrerons sous trois jours"]),
      w("นานๆครั้ง", "naan-naan khráng", "de temps en temps, rarement", "time2", ["{I}กลับบ้านนานๆครั้ง", "{i} klàp bâan naan-naan khráng", "je ne rentre chez moi que de temps en temps"]),
      w("แต่เช้า", "tɛ̀ɛ cháao", "tôt le matin, dès le matin", "time2", ["พรุ่งนี้{I}ต้องออกจากบ้านแต่เช้า", "phrûng-níi {i} tɔ̂ng ɔ̀ɔk jàak bâan tɛ̀ɛ cháao", "demain, je dois partir tôt de la maison"]),
    ],
  },
  {
    id: "linkers", name: { fr: "Relier ses idées" }, icon: "link",
    items: [
      w("ก็เลย", "kɔ̂ɔ ləəi", "donc, du coup", "linkers", ["ฝนตก {I}ก็เลยไม่ไป", "fǒn tòk {i} kɔ̂ɔ ləəi mâi pai", "il pleuvait, du coup je n’y suis pas allé"]),
      w("เพราะฉะนั้น", "phrɔ́-chà-nán", "c’est pourquoi, par conséquent", "linkers", ["พรุ่งนี้{I}ต้องตื่นเช้า เพราะฉะนั้นจะนอนเร็ว", "phrûng-níi {i} tɔ̂ng tʉ̀ʉn cháao phrɔ́-chà-nán jà nɔɔn reo", "demain, je dois me lever tôt, c’est pourquoi je vais me coucher de bonne heure"]),
      w("อย่างไรก็ตาม", "yàang-rai kɔ̂ɔ-taam", "cependant, toutefois", "linkers", ["ห้องเล็กไปหน่อย อย่างไรก็ตาม ห้องสะอาดมาก", "hɔ̂ng lék pai nɔ̀i yàang-rai kɔ̂ɔ-taam hɔ̂ng sà-àat mâak", "la chambre est un peu petite ; cependant, elle est très propre"]),
      w("ถึงแม้ว่า", "thʉ̌ng-mɛ́ɛ-wâa", "bien que, même si", "linkers", ["ถึงแม้ว่าจะแพง {I}ก็อยากซื้อ", "thʉ̌ng-mɛ́ɛ-wâa jà phɛɛng {i} kɔ̂ɔ yàak sʉ́ʉ", "même si c’est cher, j’ai quand même envie de l’acheter"]),
      w("เช่น", "chên", "par exemple, comme", "linkers", ["{I}ชอบผลไม้ไทย เช่น มะม่วง", "{i} chɔ̂ɔp phǒn-lá-máai thai chên má-mûang", "j’aime les fruits thaïs, par exemple la mangue"]),
      w("ที่จริง", "thîi-jing", "en fait, à vrai dire", "linkers", ["ที่จริง{I}ไม่ชอบเบียร์", "thîi-jing {i} mâi chɔ̂ɔp bia", "en fait, je n’aime pas la bière"]),
      w("ยังไงก็", "yang-ngai kɔ̂ɔ", "de toute façon, quoi qu’il arrive", "linkers", ["ยังไงก็ต้องไป", "yang-ngai kɔ̂ɔ tɔ̂ng pai", "de toute façon, il faut y aller"]),
      w("ก่อนอื่น", "kɔ̀ɔn ʉ̀ʉn", "d’abord, avant tout", "linkers", ["ก่อนอื่น ขอแนะนำตัว{P}", "kɔ̀ɔn ʉ̀ʉn khɔ̌ɔ nɛ́-nam tua {p}", "avant tout, permettez-moi de me présenter"]),
      w("แล้วก็", "lɛ́ɛo kɔ̂ɔ", "et puis, et aussi", "linkers", ["{I}ไปตลาด แล้วก็ไปวัด", "{i} pai tà-làat lɛ́ɛo kɔ̂ɔ pai wát", "je vais au marché, et puis au temple"]),
      w("จากนั้น", "jàak-nán", "ensuite, après ça", "linkers", ["ตรงไป จากนั้นเลี้ยวซ้าย", "trong pai jàak-nán líao sáai", "allez tout droit, ensuite tournez à gauche"]),
      w("ในที่สุด", "nai thîi-sùt", "finalement, enfin", "linkers", ["ในที่สุดเราก็มาถึง", "nai thîi-sùt rao kɔ̂ɔ maa thʉ̌ng", "enfin, nous sommes arrivés"]),
      w("สุดท้าย", "sùt-tháai", "au final ; en dernier", "linkers", ["สุดท้ายเขาก็ไม่มา", "sùt-tháai khǎo kɔ̂ɔ mâi maa", "au final, il n’est pas venu"]),
      w("ไม่งั้น", "mâi ngán", "sinon", "linkers", ["รีบหน่อย ไม่งั้นจะไม่ทัน", "rîip nɔ̀i mâi ngán jà mâi than", "dépêche-toi, sinon on ne sera pas à temps"]),
      w("โดยเฉพาะ", "dooi-chà-phɔ́", "surtout, en particulier", "linkers", ["{I}ชอบอาหารไทย โดยเฉพาะส้มตำ", "{i} chɔ̂ɔp aa-hǎan thai dooi-chà-phɔ́ sôm-tam", "j’aime la cuisine thaïe, surtout la salade de papaye"]),
      w("นอกจากนี้", "nɔ̂ɔk-jàak-níi", "de plus, en outre", "linkers", ["โรงแรมนี้ถูก นอกจากนี้ยังใกล้ทะเล", "roong-rɛɛm níi thùuk nɔ̂ɔk-jàak-níi yang klâi thá-lee", "cet hôtel est bon marché ; de plus, il est près de la mer"]),
      w("อีกอย่าง", "ìik yàang", "et puis, en plus (à l’oral)", "linkers", ["{I}ไม่ไปดีกว่า อีกอย่างฝนก็ตกด้วย", "{i} mâi pai dii kwàa ìik yàang fǒn kɔ̂ɔ tòk dûai", "je préfère ne pas y aller ; et puis, il pleut"]),
      w("หรือว่า", "rʉ̌ʉ-wâa", "ou bien (dans une question)", "linkers", ["กินที่นี่หรือว่าห่อกลับบ้าน{Q}", "kin thîi-nîi rʉ̌ʉ-wâa hɔ̀ɔ klàp bâan {q}", "sur place ou à emporter ?"]),
      w("เพื่อ", "phʉ̂a", "pour, afin de (but)", "linkers", ["{I}เรียนภาษาไทยเพื่อคุยกับเพื่อน", "{i} rian phaa-sǎa thai phʉ̂a khui kàp phʉ̂an", "j’apprends le thaï pour parler avec mes amis"]),
      w("ถ้างั้น", "thâa ngán", "dans ce cas, alors", "linkers", ["ถ้างั้นเราไปกันเลย", "thâa ngán rao pai kan ləəi", "dans ce cas, allons-y"]),
      w("ส่วน", "sùan", "quant à, tandis que", "linkers", ["{I}กินข้าวผัด ส่วนเขากินก๋วยเตี๋ยว", "{i} kin khâao-phàt sùan khǎo kin kǔai-tǐao", "moi, je prends du riz sauté ; quant à lui, il prend une soupe de nouilles"]),
      w("คือว่า", "khʉʉ-wâa", "c’est que… (pour expliquer)", "linkers", ["คือว่า{I}ลืมเอากระเป๋าสตางค์มา{P}", "khʉʉ-wâa {i} lʉʉm ao krà-pǎo sà-taang maa {p}", "c’est que j’ai oublié mon portefeuille"]),
      w("ทั้ง…และ…", "tháng … lɛ́ …", "à la fois… et…", "linkers", ["ร้านนี้ทั้งถูกและอร่อย", "ráan níi tháng thùuk lɛ́ à-rɔ̀i", "ce restaurant est à la fois bon marché et délicieux"]),
      w("สรุปว่า", "sà-rùp-wâa", "bref, au final", "linkers", ["สรุปว่าพรุ่งนี้ไม่ไปนะ", "sà-rùp-wâa phrûng-níi mâi pai ná", "bref, demain on n’y va pas, d’accord ?"]),
      w("แม้แต่", "mɛ́ɛ-tɛ̀ɛ", "même (pour insister)", "linkers", ["แม้แต่คนไทยก็ว่าเผ็ด", "mɛ́ɛ-tɛ̀ɛ khon thai kɔ̂ɔ wâa phèt", "même les Thaïlandais trouvent ça épicé"]),
      w("อย่างน้อย", "yàang-nɔ́ɔi", "au moins", "linkers", ["อย่างน้อยก็ไม่มีใครเจ็บ", "yàang-nɔ́ɔi kɔ̂ɔ mâi mii khrai jèp", "au moins, personne n’est blessé"]),
    ],
  },
];

/** Ordre des thèmes A2 dans le parcours (après tout le niveau A1). */
export const A2_THEME_ORDER = ["admin", "housing", "cooking", "transit", "office", "safety", "character", "opinion", "social", "study", "digital", "environment", "fitness", "service", "time2", "linkers"];
