/**
 * Vocabulaire ajouté après la maquette : huit thèmes supplémentaires et des phrases d'exemple pour les
 * mots essentiels des premiers thèmes (on retient mieux un mot dans une phrase que l'on peut réutiliser).
 *
 * Conventions de transcription : celles du reste du contenu (kh/th/ph aspirés, ɛ ɔ ʉ ə, voyelle longue
 * doublée, tons à â á ǎ, jetons {P} {Q} {I} pour les particules et le pronom selon le genre).
 */
import type { VocabItem, VocabTheme } from '../types';

const w = (thai: string, rom: string, fr: string, theme: string, example?: [string, string, string]): VocabItem => ({
  id: 'w:' + thai, thai, rom, meaning: { fr }, themes: [theme],
  ...(example ? { example: { thai: example[0], rom: example[1], meaning: { fr: example[2] } } } : {}),
});

export const EXTRA_THEMES: VocabTheme[] = [
  {
    id: 'qw', name: { fr: 'Poser des questions' }, icon: '❓',
    items: [
      w('ใคร', 'khrai', 'qui', 'qw', ['นั่นใคร{Q}', 'nân khrai {q}', 'qui est-ce ?']),
      w('อะไร', 'à-rai', 'quoi, quel', 'qw', ['นี่อะไร{Q}', 'nîi à-rai {q}', 'qu’est-ce que c’est ?']),
      w('เมื่อไหร่', 'mʉ̂a-rài', 'quand', 'qw', ['คุณจะกลับเมื่อไหร่{Q}', 'khun jà klàp mʉ̂a-rài {q}', 'quand rentrez-vous ?']),
      w('ทำไม', 'tham-mai', 'pourquoi', 'qw', ['ทำไมแพงจัง', 'tham-mai phɛɛng jang', 'pourquoi est-ce si cher ?']),
      w('ยังไง', 'yang-ngai', 'comment (à l’oral)', 'qw', ['ไปยังไง{Q}', 'pai yang-ngai {q}', 'comment y va-t-on ?']),
      w('อันไหน', 'an-nǎi', 'lequel', 'qw', ['เอาอันไหน{Q}', 'ao an-nǎi {q}', 'vous prenez lequel ?']),
      w('อยู่ที่ไหน', 'yùu thîi-nǎi', 'où se trouve…', 'qw', ['โรงแรมอยู่ที่ไหน{Q}', 'roong-rɛɛm yùu thîi-nǎi {q}', 'où est l’hôtel ?']),
      w('ใช่ไหม', 'châi mái', '…, n’est-ce pas ?', 'qw', ['คุณเป็นคนไทยใช่ไหม{Q}', 'khun pen khon thai châi mái {q}', 'vous êtes thaïlandais, n’est-ce pas ?']),
      w('หรือเปล่า', 'rʉ̌ʉ-plàao', '… ou pas ?', 'qw', ['ชอบหรือเปล่า{Q}', 'chɔ̂ɔp rʉ̌ʉ-plàao {q}', 'vous aimez, ou pas ?']),
      w('หรือยัง', 'rʉ̌ʉ-yang', 'déjà… ou pas encore ?', 'qw', ['กินข้าวหรือยัง{Q}', 'kin khâao rʉ̌ʉ-yang {q}', 'avez-vous déjà mangé ?']),
      w('นานเท่าไหร่', 'naan thâo-rài', 'combien de temps', 'qw', ['รอนานเท่าไหร่{Q}', 'rɔɔ naan thâo-rài {q}', 'on attend combien de temps ?']),
      w('ไกลไหม', 'klai mái', 'c’est loin ?', 'qw', ['จากที่นี่ไกลไหม{Q}', 'jàak thîi-nîi klai mái {q}', 'c’est loin d’ici ?']),
      w('ได้ไหม', 'dâai mái', 'est-ce possible ? puis-je ?', 'qw', ['ขอดูได้ไหม{Q}', 'khɔ̌ɔ duu dâai mái {q}', 'je peux regarder ?']),
      w('มีไหม', 'mii mái', 'en avez-vous ?', 'qw', ['มีน้ำเปล่าไหม{Q}', 'mii náam-plàao mái {q}', 'avez-vous de l’eau plate ?']),
      w('กี่บาท', 'kìi bàat', 'combien de bahts ?', 'qw', ['อันนี้กี่บาท{Q}', 'an-níi kìi bàat {q}', 'celui-ci, combien de bahts ?']),
    ],
  },
  {
    id: 'fruit', name: { fr: 'Fruits' }, icon: '🍉',
    items: [
      w('กล้วย', 'klûai', 'banane', 'fruit', ['ขอกล้วยหนึ่งหวี{P}', 'khɔ̌ɔ klûai nʉ̀ng wǐi {p}', 'une main de bananes, s’il vous plaît']),
      w('สับปะรด', 'sàp-pà-rót', 'ananas', 'fruit'),
      w('แตงโม', 'tɛɛng-moo', 'pastèque', 'fruit', ['แตงโมหวานมาก', 'tɛɛng-moo wǎan mâak', 'la pastèque est très sucrée']),
      w('มะพร้าว', 'má-phráao', 'noix de coco', 'fruit'),
      w('ส้ม', 'sôm', 'orange, mandarine', 'fruit'),
      w('มะละกอ', 'má-lá-kɔɔ', 'papaye', 'fruit'),
      w('ทุเรียน', 'thú-rian', 'durian', 'fruit', ['ทุเรียนเหม็นแต่อร่อย', 'thú-rian měn tɛ̀ɛ à-rɔ̀i', 'le durian sent fort, mais il est délicieux']),
      w('มังคุด', 'mang-khút', 'mangoustan', 'fruit'),
      w('เงาะ', 'ngɔ́', 'ramboutan', 'fruit', ['เงาะกิโลละเท่าไหร่{Q}', 'ngɔ́ kì-loo lá thâo-rài {q}', 'combien le kilo de ramboutans ?']),
      w('ลำไย', 'lam-yai', 'longane', 'fruit'),
      w('ฝรั่ง', 'fà-ràng', 'goyave ; Occidental', 'fruit'),
      w('ขนุน', 'khà-nǔn', 'jacque (fruit du jacquier)', 'fruit'),
      w('องุ่น', 'à-ngùn', 'raisin', 'fruit'),
      w('มะนาว', 'má-naao', 'citron vert', 'fruit', ['น้ำมะนาว', 'náam má-naao', 'jus de citron vert']),
      w('ลิ้นจี่', 'lín-jìi', 'litchi', 'fruit'),
      w('สุก', 'sùk', 'mûr', 'fruit', ['มะม่วงสุกไหม{Q}', 'má-mûang sùk mái {q}', 'la mangue est-elle mûre ?']),
      w('ดิบ', 'dìp', 'pas mûr ; cru', 'fruit'),
    ],
  },
  {
    id: 'adv', name: { fr: 'Quand ? Moments et fréquence' }, icon: '⏳',
    items: [
      w('เสมอ', 'sà-mə̌ə', 'toujours', 'adv', ['{I}ตื่นเช้าเสมอ', '{i} tʉ̀ʉn cháao sà-mə̌ə', 'je me lève toujours tôt']),
      w('บ่อย', 'bɔ̀i', 'souvent', 'adv', ['คุณมาที่นี่บ่อยไหม{Q}', 'khun maa thîi-nîi bɔ̀i mái {q}', 'vous venez souvent ici ?']),
      w('บางครั้ง', 'baang-khráng', 'parfois', 'adv'),
      w('บางที', 'baang-thii', 'parfois ; peut-être', 'adv'),
      w('ไม่เคย', 'mâi khəəi', 'jamais (n’avoir jamais fait)', 'adv', ['{I}ไม่เคยไปเชียงใหม่', '{i} mâi khəəi pai chiang-mài', 'je ne suis jamais allé à Chiang Mai']),
      w('ตลอด', 'tà-lɔ̀ɔt', 'tout le temps, sans arrêt', 'adv'),
      w('ทั้งวัน', 'tháng-wan', 'toute la journée', 'adv', ['ฝนตกทั้งวัน', 'fǒn tòk tháng-wan', 'il a plu toute la journée']),
      w('ตอนเช้า', 'tɔɔn-cháao', 'le matin', 'adv'),
      w('ตอนเย็น', 'tɔɔn-yen', 'le soir, en fin d’après-midi', 'adv'),
      w('เมื่อกี้', 'mʉ̂a-kîi', 'à l’instant', 'adv'),
      w('เพิ่ง', 'phə̂ng', 'venir de (faire)', 'adv', ['{I}เพิ่งมาถึง', '{i} phə̂ng maa thʉ̌ng', 'je viens d’arriver']),
      w('ทันที', 'than-thii', 'immédiatement', 'adv'),
      w('เร็วๆนี้', 'reo-reo níi', 'bientôt', 'adv', ['เจอกันเร็วๆนี้', 'jəə kan reo-reo níi', 'à très bientôt']),
      w('นานแล้ว', 'naan lɛ́ɛo', 'il y a longtemps', 'adv', ['ไม่ได้เจอกันนานแล้ว', 'mâi dâai jəə kan naan lɛ́ɛo', 'ça fait longtemps qu’on ne s’est pas vus']),
      w('ก่อน', 'kɔ̀ɔn', 'avant ; d’abord', 'adv', ['{I}ไปก่อนนะ', '{i} pai kɔ̀ɔn ná', 'j’y vais (je pars en premier)']),
      w('หลังจาก', 'lǎng-jàak', 'après (que)', 'adv'),
      w('ทุกอาทิตย์', 'thúk aa-thít', 'chaque semaine', 'adv'),
      w('ปีที่แล้ว', 'pii thîi-lɛ́ɛo', 'l’année dernière', 'adv'),
      w('ปีหน้า', 'pii-nâa', 'l’année prochaine', 'adv', ['ปีหน้า{I}จะกลับมาอีก', 'pii-nâa {i} jà klàp maa ìik', 'l’année prochaine, je reviendrai']),
      w('เดือนหน้า', 'dʉan-nâa', 'le mois prochain', 'adv'),
    ],
  },
  {
    id: 'tech', name: { fr: 'Téléphone et internet' }, icon: '📱',
    items: [
      w('โทรศัพท์', 'thoo-rá-sàp', 'téléphone', 'tech'),
      w('มือถือ', 'mʉʉ-thʉ̌ʉ', 'téléphone portable', 'tech', ['มือถือ{I}แบตหมด', 'mʉʉ-thʉ̌ʉ {i} bɛ̀t mòt', 'mon portable n’a plus de batterie']),
      w('แบตหมด', 'bɛ̀t mòt', 'batterie vide', 'tech'),
      w('ชาร์จแบต', 'cháat bɛ̀t', 'charger la batterie', 'tech', ['ขอชาร์จแบตหน่อยได้ไหม{Q}', 'khɔ̌ɔ cháat bɛ̀t nɔ̀i dâai mái {q}', 'puis-je recharger mon téléphone ?']),
      w('ปลั๊ก', 'plák', 'prise électrique', 'tech'),
      w('รหัสผ่าน', 'rá-hàt-phàan', 'mot de passe', 'tech'),
      w('อินเทอร์เน็ต', 'in-təə-nét', 'internet', 'tech'),
      w('สัญญาณ', 'sǎn-yaan', 'réseau, signal', 'tech', ['ไม่มีสัญญาณ', 'mâi mii sǎn-yaan', 'il n’y a pas de réseau']),
      w('ซิม', 'sim', 'carte SIM', 'tech', ['ซื้อซิมได้ที่ไหน{Q}', 'sʉ́ʉ sim dâai thîi-nǎi {q}', 'où peut-on acheter une carte SIM ?']),
      w('เบอร์โทร', 'bəə thoo', 'numéro de téléphone', 'tech', ['ขอเบอร์โทรหน่อย{P}', 'khɔ̌ɔ bəə thoo nɔ̀i {p}', 'votre numéro, s’il vous plaît']),
      w('ข้อความ', 'khɔ̂ɔ-khwaam', 'message (texto)', 'tech'),
      w('ส่งข้อความ', 'sòng khɔ̂ɔ-khwaam', 'envoyer un message', 'tech', ['ส่งข้อความหา{I}นะ', 'sòng khɔ̂ɔ-khwaam hǎa {i} ná', 'envoie-moi un message']),
      w('โทรหา', 'thoo hǎa', 'appeler (quelqu’un)', 'tech', ['เดี๋ยว{I}โทรหา', 'dǐao {i} thoo hǎa', 'je vous rappelle tout à l’heure']),
      w('แอป', 'ɛ́p', 'application (mobile)', 'tech'),
      w('หน้าจอ', 'nâa-jɔɔ', 'écran', 'tech'),
      w('เปิดเครื่อง', 'pə̀ət khrʉ̂ang', 'allumer (un appareil)', 'tech'),
      w('ปิดเครื่อง', 'pìt khrʉ̂ang', 'éteindre (un appareil)', 'tech'),
    ],
  },
  {
    id: 'nature', name: { fr: 'Nature' }, icon: '🌿',
    items: [
      w('ธรรมชาติ', 'tham-má-châat', 'nature', 'nature'),
      w('ต้นไม้', 'tôn-máai', 'arbre', 'nature'),
      w('ใบไม้', 'bai-máai', 'feuille', 'nature'),
      w('หญ้า', 'yâa', 'herbe', 'nature'),
      w('ป่า', 'pàa', 'forêt', 'nature', ['ในป่ามีช้าง', 'nai pàa mii cháang', 'dans la forêt, il y a des éléphants']),
      w('น้ำตก', 'náam-tòk', 'cascade', 'nature', ['น้ำตกสวยมาก', 'náam-tòk sǔai mâak', 'la cascade est très belle']),
      w('ทะเลสาบ', 'thá-lee-sàap', 'lac', 'nature'),
      w('คลื่น', 'khlʉ̂ʉn', 'vague', 'nature', ['วันนี้คลื่นแรง', 'wan-níi khlʉ̂ʉn rɛɛng', 'aujourd’hui, les vagues sont fortes']),
      w('ปะการัง', 'pà-kaa-rang', 'corail', 'nature'),
      w('ถ้ำ', 'thâm', 'grotte', 'nature'),
      w('หิน', 'hǐn', 'pierre, rocher', 'nature'),
      w('ดิน', 'din', 'terre, sol', 'nature'),
      w('พระอาทิตย์', 'phrá-aa-thít', 'soleil (l’astre)', 'nature'),
      w('พระอาทิตย์ตก', 'phrá-aa-thít tòk', 'coucher de soleil', 'nature', ['ไปดูพระอาทิตย์ตกกัน', 'pai duu phrá-aa-thít tòk kan', 'allons voir le coucher de soleil']),
      w('พระจันทร์', 'phrá-jan', 'lune', 'nature'),
      w('ดาว', 'daao', 'étoile', 'nature', ['คืนนี้ดาวเยอะ', 'khʉʉn-níi daao yə́', 'ce soir, il y a plein d’étoiles']),
      w('ท้องฟ้า', 'thɔ́ɔng-fáa', 'ciel', 'nature'),
      w('ทุ่งนา', 'thûng-naa', 'rizière', 'nature'),
    ],
  },
  {
    id: 'money', name: { fr: 'Argent et banque' }, icon: '🏦',
    items: [
      w('เงิน', 'ngən', 'argent', 'money', ['{I}ไม่มีเงิน', '{i} mâi mii ngən', 'je n’ai pas d’argent']),
      w('กระเป๋าสตางค์', 'krà-pǎo sà-taang', 'portefeuille', 'money'),
      w('เหรียญ', 'rǐan', 'pièce de monnaie', 'money'),
      w('ธนบัตร', 'thá-ná-bàt', 'billet de banque', 'money'),
      w('บัตรเครดิต', 'bàt khree-dìt', 'carte de crédit', 'money'),
      w('จ่ายด้วยบัตร', 'jàai dûai bàt', 'payer par carte', 'money', ['จ่ายด้วยบัตรได้ไหม{Q}', 'jàai dûai bàt dâai mái {q}', 'peut-on payer par carte ?']),
      w('บัญชี', 'ban-chii', 'compte (bancaire)', 'money'),
      w('โอนเงิน', 'oon ngən', 'faire un virement', 'money'),
      w('ถอนเงิน', 'thɔ̌ɔn ngən', 'retirer de l’argent', 'money', ['{I}จะไปถอนเงิน', '{i} jà pai thɔ̌ɔn ngən', 'je vais retirer de l’argent']),
      w('ค่าธรรมเนียม', 'khâa tham-niam', 'frais (bancaires)', 'money', ['มีค่าธรรมเนียมไหม{Q}', 'mii khâa tham-niam mái {q}', 'y a-t-il des frais ?']),
      w('อัตราแลกเปลี่ยน', 'àt-traa lɛ̂ɛk-plìan', 'taux de change', 'money'),
      w('ยูโร', 'yuu-roo', 'euro', 'money', ['หนึ่งยูโรได้กี่บาท{Q}', 'nʉ̀ng yuu-roo dâai kìi bàat {q}', 'un euro fait combien de bahts ?']),
      w('ค่าใช้จ่าย', 'khâa chái-jàai', 'dépenses, coûts', 'money'),
      w('ค่าเช่า', 'khâa châo', 'loyer', 'money'),
      w('ประหยัด', 'prà-yàt', 'économiser ; économique', 'money'),
      w('ยืมเงิน', 'yʉʉm ngən', 'emprunter de l’argent', 'money'),
    ],
  },
  {
    id: 'hobby', name: { fr: 'Loisirs et sport' }, icon: '⚽',
    items: [
      w('เวลาว่าง', 'wee-laa wâang', 'temps libre', 'hobby', ['เวลาว่างคุณทำอะไร{Q}', 'wee-laa wâang khun tham à-rai {q}', 'que faites-vous pendant votre temps libre ?']),
      w('เล่นกีฬา', 'lên kii-laa', 'faire du sport', 'hobby', ['คุณเล่นกีฬาอะไร{Q}', 'khun lên kii-laa à-rai {q}', 'quel sport pratiquez-vous ?']),
      w('ออกกำลังกาย', 'ɔ̀ɔk-kam-lang-kaai', 'faire de l’exercice', 'hobby', ['{I}ออกกำลังกายทุกเช้า', '{i} ɔ̀ɔk-kam-lang-kaai thúk cháao', 'je fais de l’exercice tous les matins']),
      w('ว่ายน้ำ', 'wâai-náam', 'nager', 'hobby'),
      w('ดำน้ำ', 'dam-náam', 'plonger', 'hobby'),
      w('ฟุตบอล', 'fút-bɔɔn', 'football', 'hobby', ['{I}ชอบดูฟุตบอล', '{i} chɔ̂ɔp duu fút-bɔɔn', 'j’aime regarder le football']),
      w('มวยไทย', 'muai-thai', 'boxe thaïe', 'hobby'),
      w('ปั่นจักรยาน', 'pàn jàk-krà-yaan', 'faire du vélo', 'hobby'),
      w('เดินเล่น', 'dəən-lên', 'se promener', 'hobby', ['ไปเดินเล่นกันไหม{Q}', 'pai dəən-lên kan mái {q}', 'on va se promener ?']),
      w('อ่านหนังสือ', 'àan nǎng-sʉ̌ʉ', 'lire (un livre)', 'hobby'),
      w('ทำอาหาร', 'tham aa-hǎan', 'cuisiner', 'hobby', ['{I}ทำอาหารไทยได้', '{i} tham aa-hǎan thai dâai', 'je sais cuisiner thaï']),
      w('วาดรูป', 'wâat rûup', 'dessiner', 'hobby'),
      w('เล่นดนตรี', 'lên don-trii', 'jouer de la musique', 'hobby'),
      w('เล่นเกม', 'lên keem', 'jouer aux jeux vidéo', 'hobby'),
      w('ตกปลา', 'tòk plaa', 'pêcher', 'hobby'),
      w('โยคะ', 'yoo-khá', 'yoga', 'hobby'),
      w('ปลูกต้นไม้', 'plùuk tôn-máai', 'jardiner', 'hobby'),
    ],
  },
  {
    id: 'culture', name: { fr: 'Fêtes et culture' }, icon: '🎎',
    items: [
      w('พระ', 'phrá', 'moine', 'culture', ['ห้ามผู้หญิงแตะตัวพระ', 'hâam phûu-yǐng tɛ̀ tua phrá', 'les femmes ne doivent pas toucher un moine']),
      w('เจดีย์', 'jee-dii', 'chedi, stupa', 'culture'),
      w('พระพุทธรูป', 'phrá-phút-thá-rûup', 'statue de Bouddha', 'culture'),
      w('ทำบุญ', 'tham-bun', 'faire des mérites', 'culture', ['คนไทยชอบไปทำบุญที่วัด', 'khon thai chɔ̂ɔp pai tham-bun thîi wát', 'les Thaïlandais aiment aller faire des mérites au temple']),
      w('ตักบาตร', 'tàk-bàat', 'faire l’offrande aux moines (le matin)', 'culture'),
      w('ไหว้', 'wâai', 'saluer les mains jointes (wai)', 'culture', ['เด็กไหว้ผู้ใหญ่', 'dèk wâai phûu-yài', 'les enfants saluent les aînés d’un wai']),
      w('ถอดรองเท้า', 'thɔ̀ɔt rɔɔng-tháao', 'enlever ses chaussures', 'culture', ['ถอดรองเท้าก่อนเข้าบ้าน', 'thɔ̀ɔt rɔɔng-tháao kɔ̀ɔn khâo bâan', 'on enlève ses chaussures avant d’entrer dans la maison']),
      w('เกรงใจ', 'kreeng-jai', 'avoir scrupule à déranger', 'culture'),
      w('สงกรานต์', 'sǒng-kraan', 'Songkran, le nouvel an thaï', 'culture', ['สงกรานต์อยู่ในเดือนเมษายน', 'sǒng-kraan yùu nai dʉan mee-sǎa-yon', 'Songkran a lieu en avril']),
      w('สาดน้ำ', 'sàat náam', 's’asperger d’eau', 'culture'),
      w('ลอยกระทง', 'lɔɔi krà-thong', 'Loy Krathong, la fête des lumières', 'culture'),
      w('กระทง', 'krà-thong', 'krathong (petit radeau de fleurs)', 'culture'),
      w('ปีใหม่', 'pii-mài', 'nouvel an', 'culture', ['สวัสดีปีใหม่', 'sà-wàt-dii pii-mài', 'bonne année !']),
      w('ของขวัญ', 'khɔ̌ɔng-khwǎn', 'cadeau', 'culture'),
      w('งานเทศกาล', 'ngaan thêet-sà-kaan', 'festival', 'culture'),
      w('ประเพณี', 'prà-phee-nii', 'tradition', 'culture'),
      w('ตลาดน้ำ', 'tà-làat-náam', 'marché flottant', 'culture'),
      w('รำไทย', 'ram-thai', 'danse traditionnelle thaïe', 'culture'),
      w('ในหลวง', 'nai-lǔang', 'le roi (terme affectueux)', 'culture'),
      w('พุทธศาสนา', 'phút-thá-sàat-sà-nǎa', 'bouddhisme', 'culture'),
    ],
  },
];

/** Phrases d'exemple ajoutées aux mots essentiels qui n'en avaient pas (clé : identifiant du mot). */
const ex = (thai: string, rom: string, fr: string) => ({ thai, rom, meaning: { fr } });
export const EXTRA_EXAMPLES: Record<string, { thai: string; rom: string; meaning: { fr: string } }> = {
  // Salutations
  'w:สวัสดี{P}': ex('สวัสดีตอนเช้า{P}', 'sà-wàt-dii tɔɔn-cháao {p}', 'bonjour (le matin)'),
  'w:ขอบคุณ{P}': ex('ขอบคุณสำหรับอาหาร{P}', 'khɔ̀ɔp-khun sǎm-ràp aa-hǎan {p}', 'merci pour le repas'),
  'w:ขอโทษ{P}': ex('ขอโทษ{P} {I}มาสาย', 'khɔ̌ɔ-thôot {p} {i} maa sǎai', 'pardon, je suis en retard'),
  'w:ไม่เป็นไร{P}': ex('ไม่เป็นไร{P} ไม่ต้องรีบ', 'mâi-pen-rai {p} mâi tɔ̂ng rîip', 'ce n’est rien, pas besoin de se presser'),
  'w:สบายดี{P}': ex('สบายดี{P} แล้วคุณล่ะ{Q}', 'sà-baai-dii {p} lɛ́ɛo khun lâ {q}', 'je vais bien, et vous ?'),
  'w:แล้วเจอกัน': ex('แล้วเจอกันพรุ่งนี้', 'lɛ́ɛo jəə kan phrûng-níi', 'à demain'),
  'w:ไม่ใช่': ex('ไม่ใช่{P} อันนี้ของ{I}', 'mâi châi {p} an-níi khɔ̌ɔng {i}', 'non, celui-ci est à moi'),
  'w:ไม่ได้': ex('วันนี้ไม่ได้{P}', 'wan-níi mâi dâai {p}', 'aujourd’hui, ce n’est pas possible'),
  'w:โชคดี{P}': ex('โชคดีนะ{P}', 'chôok-dii ná {p}', 'bonne chance !'),
  // Se présenter
  'w:{I}ไม่เข้าใจ': ex('ขอโทษ{P} {I}ไม่เข้าใจ', 'khɔ̌ɔ-thôot {p} {i} mâi khâo-jai', 'pardon, je ne comprends pas'),
  'w:ภาษาไทย': ex('ภาษาไทยยากไหม{Q}', 'phaa-sǎa thai yâak mái {q}', 'le thaï est-il difficile ?'),
  // Nourriture, boissons, restaurant
  'w:ข้าวผัด': ex('ขอข้าวผัดกุ้งหนึ่งจาน{P}', 'khɔ̌ɔ khâao-phàt kûng nʉ̀ng jaan {p}', 'un riz sauté aux crevettes, s’il vous plaît'),
  'w:ผัดไทย': ex('ผัดไทยไม่ใส่ถั่วงอก{P}', 'phàt-thai mâi sài thùa-ngɔ̂ɔk {p}', 'un pad thaï sans germes de soja'),
  'w:ไก่': ex('ไก่หรือหมู{Q}', 'kài rʉ̌ʉ mǔu {q}', 'poulet ou porc ?'),
  'w:ปลา': ex('{I}ไม่กินปลา', '{i} mâi kin plaa', 'je ne mange pas de poisson'),
  'w:ผัก': ex('ขอผักเยอะๆ{P}', 'khɔ̌ɔ phàk yə́-yə́ {p}', 'beaucoup de légumes, s’il vous plaît'),
  'w:หวาน': ex('หวานไปหน่อย', 'wǎan pai nɔ̀i', 'c’est un peu trop sucré'),
  'w:เค็ม': ex('เค็มไปนิดหน่อย', 'khem pai nít-nɔ̀i', 'c’est un petit peu trop salé'),
  'w:พริก': ex('ไม่ใส่พริก{P}', 'mâi sài phrík {p}', 'sans piment, s’il vous plaît'),
  'w:น้ำ': ex('ขอน้ำหน่อย{P}', 'khɔ̌ɔ náam nɔ̀i {p}', 'de l’eau, s’il vous plaît'),
  'w:ชา': ex('ชาร้อนหนึ่งแก้ว{P}', 'chaa rɔ́ɔn nʉ̀ng kɛ̂ɛo {p}', 'un thé chaud'),
  'w:เบียร์': ex('เบียร์เย็นๆ หนึ่งขวด{P}', 'bia yen-yen nʉ̀ng khùat {p}', 'une bière bien fraîche'),
  'w:ร้อน': ex('กาแฟร้อนหรือเย็น{Q}', 'kaa-fɛɛ rɔ́ɔn rʉ̌ʉ yen {q}', 'café chaud ou glacé ?'),
  'w:ร้านอาหาร': ex('ร้านอาหารนี้อร่อยมาก', 'ráan-aa-hǎan níi à-rɔ̀i mâak', 'ce restaurant est délicieux'),
  'w:สั่งอาหาร': ex('สั่งอาหารได้ไหม{Q}', 'sàng aa-hǎan dâai mái {q}', 'peut-on commander ?'),
  'w:ตะเกียบ': ex('ขอตะเกียบหน่อย{P}', 'khɔ̌ɔ tà-kìap nɔ̀i {p}', 'des baguettes, s’il vous plaît'),
  'w:อิ่มแล้ว': ex('อิ่มแล้ว{P} อร่อยมาก', 'ìm lɛ́ɛo {p} à-rɔ̀i mâak', 'je n’ai plus faim, c’était délicieux'),
  // Marché, prix, nombres
  'w:แพงไป': ex('แพงไป ลดหน่อยได้ไหม{Q}', 'phɛɛng pai lót nɔ̀i dâai mái {q}', 'c’est trop cher, vous pouvez baisser un peu ?'),
  'w:เงินสด': ex('จ่ายเงินสด{P}', 'jàai ngən-sòt {p}', 'je paie en espèces'),
  'w:เงินทอน': ex('เงินทอนไม่ครบ{P}', 'ngən-thɔɔn mâi khróp {p}', 'il manque de la monnaie'),
  'w:ราคา': ex('ราคานี้รวมภาษีไหม{Q}', 'raa-khaa níi ruam phaa-sǐi mái {q}', 'ce prix inclut-il la taxe ?'),
  'w:ถูก': ex('ร้านนี้ถูกกว่า', 'ráan níi thùuk kwàa', 'cette boutique est moins chère'),
  'w:ฟรี': ex('น้ำฟรีไหม{Q}', 'náam frii mái {q}', 'l’eau est gratuite ?'),
  'w:ครึ่ง': ex('ครึ่งชั่วโมง', 'khrʉ̂ng chûa-moong', 'une demi-heure'),
  'w:ประมาณ': ex('ประมาณสิบนาที', 'prà-maan sìp naa-thii', 'environ dix minutes'),
  // Dates, heures
  'w:วันนี้': ex('วันนี้วันอะไร{Q}', 'wan-níi wan à-rai {q}', 'quel jour sommes-nous ?'),
  'w:พรุ่งนี้': ex('พรุ่งนี้เจอกัน', 'phrûng-níi jəə kan', 'à demain'),
  'w:เมื่อวาน': ex('เมื่อวาน{I}ไปตลาด', 'mʉ̂a-waan {i} pai tà-làat', 'hier, je suis allé au marché'),
  'w:เดือน': ex('เดือนหน้า{I}จะไปเชียงใหม่', 'dʉan-nâa {i} jà pai chiang-mài', 'le mois prochain, je vais à Chiang Mai'),
  'w:วันหยุด': ex('วันหยุดคุณทำอะไร{Q}', 'wan-yùt khun tham à-rai {q}', 'que faites-vous les jours de congé ?'),
  'w:นาที': ex('อีกห้านาที', 'ìik hâa naa-thii', 'encore cinq minutes'),
  'w:เที่ยง': ex('เจอกันตอนเที่ยง', 'jəə kan tɔɔn thîang', 'on se voit à midi'),
  'w:กลางคืน': ex('กลางคืนอากาศเย็น', 'klaang-khʉʉn aa-kàat yen', 'la nuit, il fait frais'),
  'w:สาย': ex('ขอโทษที่มาสาย{P}', 'khɔ̌ɔ-thôot thîi maa sǎai {p}', 'désolé d’être en retard'),
  // Taxi, hôtel, directions
  'w:แท็กซี่': ex('เรียกแท็กซี่ให้หน่อย{P}', 'rîak thɛ́k-sîi hâi nɔ̀i {p}', 'appelez-moi un taxi, s’il vous plaît'),
  'w:ตรงไป': ex('ตรงไปแล้วเลี้ยวขวา', 'trong pai lɛ́ɛo líao khwǎa', 'tout droit, puis à droite'),
  'w:รถติด': ex('วันนี้รถติดมาก', 'wan-níi rót tìt mâak', 'aujourd’hui, il y a beaucoup de bouchons'),
  'w:ถึงแล้ว': ex('ถึงแล้ว{P} จอดตรงนี้', 'thʉ̌ng lɛ́ɛo {p} jɔ̀ɔt trong-níi', 'on est arrivés, arrêtez-vous ici'),
  'w:ห้อง': ex('ห้องของ{I}อยู่ชั้นสาม', 'hɔ̂ng khɔ̌ɔng {i} yùu chán sǎam', 'ma chambre est au troisième étage'),
  'w:กุญแจ': ex('{I}ลืมกุญแจไว้ในห้อง', '{i} lʉʉm kun-jɛɛ wái nai hɔ̂ng', 'j’ai oublié la clé dans la chambre'),
  'w:ซ้าย': ex('อยู่ทางซ้าย', 'yùu thaang sáai', 'c’est sur la gauche'),
  'w:ขวา': ex('เลี้ยวขวาที่สี่แยก', 'líao khwǎa thîi sìi-yɛ̂ɛk', 'tournez à droite au carrefour'),
  'w:ตรงข้าม': ex('ตรงข้ามธนาคาร', 'trong-khâam thá-naa-khaan', 'en face de la banque'),
  'w:ที่นี่': ex('จอดที่นี่{P}', 'jɔ̀ɔt thîi-nîi {p}', 'arrêtez-vous ici'),
  'w:ถนน': ex('ถนนนี้ชื่ออะไร{Q}', 'thà-nǒn níi chʉ̂ʉ à-rai {q}', 'comment s’appelle cette rue ?'),
  // Verbes
  'w:ไป': ex('{I}ไปตลาด', '{i} pai tà-làat', 'je vais au marché'),
  'w:มา': ex('มาจากไหน{Q}', 'maa jàak nǎi {q}', 'd’où venez-vous ?'),
  'w:กิน': ex('{I}กินเผ็ดได้', '{i} kin phèt dâai', 'je peux manger épicé'),
  'w:นอน': ex('{I}นอนดึก', '{i} nɔɔn dʉ̀k', 'je me couche tard'),
  'w:พูด': ex('พูดภาษาอังกฤษได้ไหม{Q}', 'phûut phaa-sǎa ang-krìt dâai mái {q}', 'parlez-vous anglais ?'),
  'w:ฟัง': ex('ฟังอีกครั้ง{P}', 'fang ìik khráng {p}', 'écoutez encore une fois'),
  'w:ดู': ex('ดูนี่สิ', 'duu nîi sì', 'regarde ça'),
  'w:อ่าน': ex('{I}อ่านภาษาไทยได้นิดหน่อย', '{i} àan phaa-sǎa thai dâai nít-nɔ̀i', 'je lis un peu le thaï'),
  'w:เขียน': ex('เขียนให้หน่อย{P}', 'khǐan hâi nɔ̀i {p}', 'écrivez-le-moi, s’il vous plaît'),
  'w:เรียน': ex('{I}เรียนภาษาไทยมาสองเดือน', '{i} rian phaa-sǎa thai maa sɔ̌ɔng dʉan', 'j’apprends le thaï depuis deux mois'),
  'w:ให้': ex('ให้{I}ช่วยไหม{Q}', 'hâi {i} chûai mái {q}', 'voulez-vous que je vous aide ?'),
  'w:มี': ex('มีห้องว่างไหม{Q}', 'mii hɔ̂ng wâang mái {q}', 'avez-vous une chambre libre ?'),
  'w:อยู่': ex('คุณอยู่ที่ไหน{Q}', 'khun yùu thîi-nǎi {q}', 'où êtes-vous ?'),
  'w:รอ': ex('รอสักครู่{P}', 'rɔɔ sàk-khrûu {p}', 'attendez un instant'),
  'w:ช่วย': ex('ช่วยถ่ายรูปให้หน่อยได้ไหม{Q}', 'chûai thàai-rûup hâi nɔ̀i dâai mái {q}', 'pouvez-vous me prendre en photo ?'),
  'w:ถาม': ex('ขอถามหน่อย{P}', 'khɔ̌ɔ thǎam nɔ̀i {p}', 'puis-je vous poser une question ?'),
  'w:อยาก': ex('{I}อยากไปทะเล', '{i} yàak pai thá-lee', 'j’ai envie d’aller à la mer'),
  'w:ต้อง': ex('{I}ต้องไปแล้ว', '{i} tɔ̂ng pai lɛ́ɛo', 'je dois y aller'),
  'w:ลืม': ex('{I}ลืมกระเป๋าสตางค์', '{i} lʉʉm krà-pǎo sà-taang', 'j’ai oublié mon portefeuille'),
  'w:ลอง': ex('ลองชิมดู', 'lɔɔng chim duu', 'goûte pour voir'),
  'w:หา': ex('{I}หาโรงแรมไม่เจอ', '{i} hǎa roong-rɛɛm mâi jəə', 'je ne trouve pas l’hôtel'),
  'w:บอก': ex('บอก{I}ด้วยนะ', 'bɔ̀ɔk {i} dûai ná', 'dites-le-moi'),
  // Adjectifs
  'w:ดี': ex('อากาศดีมาก', 'aa-kàat dii mâak', 'il fait très beau'),
  'w:ใหญ่': ex('ห้องใหญ่กว่านี้มีไหม{Q}', 'hɔ̂ng yài kwàa níi mii mái {q}', 'avez-vous une chambre plus grande ?'),
  'w:ใหม่': ex('{I}เพิ่งซื้อมือถือใหม่', '{i} phə̂ng sʉ́ʉ mʉʉ-thʉ̌ʉ mài', 'je viens d’acheter un nouveau téléphone'),
  'w:สวย': ex('ชุดนี้สวยมาก', 'chút níi sǔai mâak', 'cette tenue est très belle'),
  'w:ยาก': ex('ภาษาไทยยากแต่สนุก', 'phaa-sǎa thai yâak tɛ̀ɛ sà-nùk', 'le thaï est difficile, mais amusant'),
  'w:แพง': ex('ไม่แพง{P}', 'mâi phɛɛng {p}', 'ce n’est pas cher'),
  'w:สะอาด': ex('ห้องสะอาดมาก', 'hɔ̂ng sà-àat mâak', 'la chambre est très propre'),
  'w:ว่าง': ex('พรุ่งนี้คุณว่างไหม{Q}', 'phrûng-níi khun wâang mái {q}', 'êtes-vous libre demain ?'),
  'w:พร้อม': ex('พร้อมแล้ว{P}', 'phrɔ́ɔm lɛ́ɛo {p}', 'je suis prêt'),
  // Petits mots
  'w:แต่': ex('อร่อยแต่เผ็ดมาก', 'à-rɔ̀i tɛ̀ɛ phèt mâak', 'c’est bon, mais très épicé'),
  'w:หรือ': ex('ชาหรือกาแฟ{Q}', 'chaa rʉ̌ʉ kaa-fɛɛ {q}', 'thé ou café ?'),
  'w:เพราะว่า': ex('{I}ชอบเมืองไทยเพราะว่าคนใจดี', '{i} chɔ̂ɔp mʉang-thai phrɔ́-wâa khon jai-dii', 'j’aime la Thaïlande parce que les gens sont gentils'),
  'w:ถ้า': ex('ถ้าฝนตก{I}จะไม่ไป', 'thâa fǒn tòk {i} jà mâi pai', 's’il pleut, je n’irai pas'),
  'w:ยัง': ex('{I}ยังไม่หิว', '{i} yang mâi hǐu', 'je n’ai pas encore faim'),
  'w:เคย': ex('คุณเคยไปภูเก็ตไหม{Q}', 'khun khəəi pai phuu-kèt mái {q}', 'êtes-vous déjà allé à Phuket ?'),
  'w:จะ': ex('{I}จะกลับบ้าน', '{i} jà klàp bâan', 'je vais rentrer à la maison'),
  'w:กำลัง': ex('{I}กำลังกินข้าว', '{i} kam-lang kin khâao', 'je suis en train de manger'),
  'w:อีก': ex('ขออีกหนึ่ง{P}', 'khɔ̌ɔ ìik nʉ̀ng {p}', 'encore un, s’il vous plaît'),
  'w:อาจจะ': ex('พรุ่งนี้อาจจะฝนตก', 'phrûng-níi àat-jà fǒn tòk', 'il pleuvra peut-être demain'),
  'w:แน่นอน': ex('แน่นอน{P}', 'nɛ̂ɛ-nɔɔn {p}', 'bien sûr'),
  'w:เหมือนกัน': ex('{I}ก็เหมือนกัน', '{i} kɔ̂ɔ mʉ̌an-kan', 'moi aussi'),
  'w:ด้วยกัน': ex('ไปด้วยกันไหม{Q}', 'pai dûai-kan mái {q}', 'on y va ensemble ?'),
  // Famille, météo
  'w:พ่อ': ex('พ่อของ{I}เป็นหมอ', 'phɔ̂ɔ khɔ̌ɔng {i} pen mɔ̌ɔ', 'mon père est médecin'),
  'w:แม่': ex('แม่ทำอาหารอร่อย', 'mɛ̂ɛ tham aa-hǎan à-rɔ̀i', 'maman cuisine bien'),
  'w:สามี': ex('สามีของ{I}เป็นคนไทย', 'sǎa-mii khɔ̌ɔng {i} pen khon thai', 'mon mari est thaïlandais'),
  'w:เพื่อน': ex('{I}มากับเพื่อน', '{i} maa kàp phʉ̂an', 'je suis venu avec un ami'),
  'w:หนาว': ex('วันนี้หนาวนิดหน่อย', 'wan-níi nǎao nít-nɔ̀i', 'aujourd’hui, il fait un peu froid'),
  'w:ฝนตก': ex('ฝนตกหนักมาก', 'fǒn tòk nàk mâak', 'il pleut très fort'),
  'w:ร่ม': ex('{I}ลืมเอาร่มมา', '{i} lʉʉm ao rôm maa', 'j’ai oublié d’apporter un parapluie'),
};
