// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { VocabTheme } from '../types';

/** Ordre d'utilité des thèmes dans le parcours. */
export const THEME_ORDER: string[] = ["sal","pres","small","num","price","food","drink","resto","market","taxi","dir","time","date","hotel","hosp","health","sos","work","eng","trans","grab","airport","travel","weather","color","shop","fam","friends","out","feel","verbs","adj","body","clothes","places","animals","home"];

/** Regroupement des thèmes dans la bibliothèque. */
export const THEME_GROUPS: { title: { fr: string }; ids: string[] }[] = [
  { title: { fr: "Mes thèmes" }, ids: ["market","taxi","hosp","eng"] },
  { title: { fr: "L'essentiel" }, ids: ["sal","pres","small","num","date","time"] },
  { title: { fr: "Se déplacer" }, ids: ["dir","places","trans","grab","airport","travel","hotel"] },
  { title: { fr: "Manger et acheter" }, ids: ["food","drink","resto","shop","price","clothes"] },
  { title: { fr: "Personnes et quotidien" }, ids: ["fam","body","home","color","weather","animals","friends","out","feel"] },
  { title: { fr: "Santé et urgences" }, ids: ["health","sos"] },
  { title: { fr: "Travail" }, ids: ["work"] },
  { title: { fr: "Verbes et adjectifs" }, ids: ["verbs","adj"] },
];

export const VOCAB_THEMES: VocabTheme[] = [
  {
    id: "sal", name: { fr: "Salutations" }, icon: "🙏",
    items: [
      { id: "w:สวัสดี{P}", thai: "สวัสดี{P}", rom: "sà-wàt-dii {p}", meaning: { fr: "bonjour ; au revoir" }, themes: ["sal"] },
      { id: "w:ขอบคุณ{P}", thai: "ขอบคุณ{P}", rom: "khɔ̀ɔp-khun {p}", meaning: { fr: "merci" }, themes: ["sal"] },
      { id: "w:ขอบคุณมาก{P}", thai: "ขอบคุณมาก{P}", rom: "khɔ̀ɔp-khun mâak {p}", meaning: { fr: "merci beaucoup" }, themes: ["sal"] },
      { id: "w:ขอโทษ{P}", thai: "ขอโทษ{P}", rom: "khɔ̌ɔ-thôot {p}", meaning: { fr: "pardon ; excusez-moi" }, themes: ["sal"] },
      { id: "w:ไม่เป็นไร{P}", thai: "ไม่เป็นไร{P}", rom: "mâi-pen-rai {p}", meaning: { fr: "ce n'est rien ; de rien" }, themes: ["sal"] },
      { id: "w:สบายดีไหม{Q}", thai: "สบายดีไหม{Q}", rom: "sà-baai-dii mái {q}", meaning: { fr: "comment allez-vous ?" }, themes: ["sal"] },
      { id: "w:สบายดี{P}", thai: "สบายดี{P}", rom: "sà-baai-dii {p}", meaning: { fr: "je vais bien" }, themes: ["sal"] },
      { id: "w:ยินดีที่ได้รู้จัก{P}", thai: "ยินดีที่ได้รู้จัก{P}", rom: "yin-dii thîi dâai rúu-jàk {p}", meaning: { fr: "enchanté(e)" }, themes: ["sal"] },
      { id: "w:แล้วเจอกัน", thai: "แล้วเจอกัน", rom: "lɛ́ɛo jəə kan", meaning: { fr: "à bientôt" }, themes: ["sal"] },
      { id: "w:ลาก่อน", thai: "ลาก่อน", rom: "laa-kɔ̀ɔn", meaning: { fr: "adieu ; au revoir (pour longtemps)" }, themes: ["sal"] },
      { id: "w:ใช่", thai: "ใช่", rom: "châi", meaning: { fr: "oui (c'est ça)" }, themes: ["sal"], example: { thai: "ใช่{P}", rom: "châi {p}", meaning: { fr: "oui, c'est ça" } } },
      { id: "w:ไม่ใช่", thai: "ไม่ใช่", rom: "mâi châi", meaning: { fr: "non (ce n'est pas ça)" }, themes: ["sal"] },
      { id: "w:ได้", thai: "ได้", rom: "dâai", meaning: { fr: "d'accord ; c'est possible" }, themes: ["sal"], example: { thai: "ได้{P}", rom: "dâai {p}", meaning: { fr: "d'accord" } } },
      { id: "w:ไม่ได้", thai: "ไม่ได้", rom: "mâi dâai", meaning: { fr: "ce n'est pas possible" }, themes: ["sal"] },
      { id: "w:เชิญ{P}", thai: "เชิญ{P}", rom: "chəən {p}", meaning: { fr: "je vous en prie (allez-y)" }, themes: ["sal"] },
      { id: "w:โชคดี{P}", thai: "โชคดี{P}", rom: "chôok-dii {p}", meaning: { fr: "bonne chance" }, themes: ["sal"] },
      { id: "w:ราตรีสวัสดิ์", thai: "ราตรีสวัสดิ์", rom: "raa-trii sà-wàt", meaning: { fr: "bonne nuit" }, themes: ["sal"] },
    ],
  },
  {
    id: "pres", name: { fr: "Se présenter" }, icon: "👋",
    items: [
      { id: "w:{I}ชื่อ...", thai: "{I}ชื่อ...", rom: "{i} chʉ̂ʉ ...", meaning: { fr: "je m'appelle…" }, themes: ["pres"] },
      { id: "w:คุณชื่ออะไร{Q}", thai: "คุณชื่ออะไร{Q}", rom: "khun chʉ̂ʉ à-rai {q}", meaning: { fr: "comment vous appelez-vous ?" }, themes: ["pres"] },
      { id: "w:{I}มาจากประเทศเบลเยียม", thai: "{I}มาจากประเทศเบลเยียม", rom: "{i} maa jàak prà-thêet ben-yîam", meaning: { fr: "je viens de Belgique" }, themes: ["pres"] },
      { id: "w:{I}เป็นคนเบลเยียม", thai: "{I}เป็นคนเบลเยียม", rom: "{i} pen khon ben-yîam", meaning: { fr: "je suis belge" }, themes: ["pres"] },
      { id: "w:คุณมาจากไหน{Q}", thai: "คุณมาจากไหน{Q}", rom: "khun maa jàak nǎi {q}", meaning: { fr: "d'où venez-vous ?" }, themes: ["pres"] },
      { id: "w:{I}เป็นวิศวกร", thai: "{I}เป็นวิศวกร", rom: "{i} pen wít-sà-wá-kɔɔn", meaning: { fr: "je suis ingénieur" }, themes: ["pres"] },
      { id: "w:คุณทำงานอะไร{Q}", thai: "คุณทำงานอะไร{Q}", rom: "khun tham-ngaan à-rai {q}", meaning: { fr: "quel est votre métier ?" }, themes: ["pres"] },
      { id: "w:{I}อายุ...ปี", thai: "{I}อายุ...ปี", rom: "{i} aa-yú ... pii", meaning: { fr: "j'ai … ans" }, themes: ["pres"] },
      { id: "w:{I}พูดภาษาไทยได้นิดหน่อย", thai: "{I}พูดภาษาไทยได้นิดหน่อย", rom: "{i} phûut phaa-sǎa thai dâai nít-nɔ̀i", meaning: { fr: "je parle un peu thaï" }, themes: ["pres"] },
      { id: "w:{I}กำลังเรียนภาษาไทย", thai: "{I}กำลังเรียนภาษาไทย", rom: "{i} kam-lang rian phaa-sǎa thai", meaning: { fr: "j'apprends le thaï" }, themes: ["pres"] },
      { id: "w:พูดช้าๆหน่อยได้ไหม{Q}", thai: "พูดช้าๆหน่อยได้ไหม{Q}", rom: "phûut cháa-cháa nɔ̀i dâai mái {q}", meaning: { fr: "pouvez-vous parler lentement ?" }, themes: ["pres"] },
      { id: "w:พูดอีกครั้งได้ไหม{Q}", thai: "พูดอีกครั้งได้ไหม{Q}", rom: "phûut ìik khráng dâai mái {q}", meaning: { fr: "pouvez-vous répéter ?" }, themes: ["pres"] },
      { id: "w:{I}ไม่เข้าใจ", thai: "{I}ไม่เข้าใจ", rom: "{i} mâi khâo-jai", meaning: { fr: "je ne comprends pas" }, themes: ["pres"] },
      { id: "w:เข้าใจแล้ว", thai: "เข้าใจแล้ว", rom: "khâo-jai lɛ́ɛo", meaning: { fr: "j'ai compris" }, themes: ["pres"] },
      { id: "w:ภาษาไทย", thai: "ภาษาไทย", rom: "phaa-sǎa thai", meaning: { fr: "la langue thaïe" }, themes: ["pres"] },
      { id: "w:ภาษาฝรั่งเศส", thai: "ภาษาฝรั่งเศส", rom: "phaa-sǎa fà-ràng-sèet", meaning: { fr: "le français" }, themes: ["pres"] },
      { id: "w:ภาษาอังกฤษ", thai: "ภาษาอังกฤษ", rom: "phaa-sǎa ang-krìt", meaning: { fr: "l'anglais" }, themes: ["pres"], example: { thai: "คุณพูดภาษาอังกฤษได้ไหม{Q}", rom: "khun phûut phaa-sǎa ang-krìt dâai mái {q}", meaning: { fr: "parlez-vous anglais ?" } } },
    ],
  },
  {
    id: "fam", name: { fr: "Famille" }, icon: "👨‍👩‍👧",
    items: [
      { id: "w:ครอบครัว", thai: "ครอบครัว", rom: "khrɔ̂ɔp-khrua", meaning: { fr: "famille" }, themes: ["fam"], example: { thai: "ครอบครัว{I}อยู่ที่เบลเยียม", rom: "khrɔ̂ɔp-khrua {i} yùu thîi ben-yîam", meaning: { fr: "ma famille est en Belgique" } } },
      { id: "w:พ่อ", thai: "พ่อ", rom: "phɔ̂ɔ", meaning: { fr: "père" }, themes: ["fam"] },
      { id: "w:แม่", thai: "แม่", rom: "mɛ̂ɛ", meaning: { fr: "mère" }, themes: ["fam"] },
      { id: "w:พี่ชาย", thai: "พี่ชาย", rom: "phîi-chaai", meaning: { fr: "grand frère" }, themes: ["fam"] },
      { id: "w:พี่สาว", thai: "พี่สาว", rom: "phîi-sǎao", meaning: { fr: "grande sœur" }, themes: ["fam"], example: { thai: "{I}มีพี่สาวหนึ่งคน", rom: "{i} mii phîi-sǎao nʉ̀ng khon", meaning: { fr: "j'ai une grande sœur" } } },
      { id: "w:น้องชาย", thai: "น้องชาย", rom: "nɔ́ɔng-chaai", meaning: { fr: "petit frère" }, themes: ["fam"] },
      { id: "w:น้องสาว", thai: "น้องสาว", rom: "nɔ́ɔng-sǎao", meaning: { fr: "petite sœur" }, themes: ["fam"] },
      { id: "w:ลูก", thai: "ลูก", rom: "lûuk", meaning: { fr: "enfant (de quelqu'un)" }, themes: ["fam"], example: { thai: "คุณมีลูกไหม{Q}", rom: "khun mii lûuk mái {q}", meaning: { fr: "avez-vous des enfants ?" } } },
      { id: "w:ลูกชาย", thai: "ลูกชาย", rom: "lûuk-chaai", meaning: { fr: "fils" }, themes: ["fam"] },
      { id: "w:ลูกสาว", thai: "ลูกสาว", rom: "lûuk-sǎao", meaning: { fr: "fille (de quelqu'un)" }, themes: ["fam"] },
      { id: "w:สามี", thai: "สามี", rom: "sǎa-mii", meaning: { fr: "mari" }, themes: ["fam"] },
      { id: "w:ภรรยา", thai: "ภรรยา", rom: "phan-rá-yaa", meaning: { fr: "épouse" }, themes: ["fam"] },
      { id: "w:แฟน", thai: "แฟน", rom: "fɛɛn", meaning: { fr: "petit(e) ami(e) ; conjoint(e)" }, themes: ["fam"] },
      { id: "w:ปู่", thai: "ปู่", rom: "pùu", meaning: { fr: "grand-père paternel" }, themes: ["fam"] },
      { id: "w:ย่า", thai: "ย่า", rom: "yâa", meaning: { fr: "grand-mère paternelle" }, themes: ["fam"] },
      { id: "w:ตา", thai: "ตา", rom: "taa", meaning: { fr: "grand-père maternel" }, themes: ["fam"] },
      { id: "w:ยาย", thai: "ยาย", rom: "yaai", meaning: { fr: "grand-mère maternelle" }, themes: ["fam"] },
      { id: "w:หลาน", thai: "หลาน", rom: "lǎan", meaning: { fr: "neveu, nièce ; petit-enfant" }, themes: ["fam"] },
      { id: "w:เพื่อน", thai: "เพื่อน", rom: "phʉ̂an", meaning: { fr: "ami(e)" }, themes: ["fam"] },
    ],
  },
  {
    id: "food", name: { fr: "Nourriture" }, icon: "🍜",
    items: [
      { id: "w:อาหาร", thai: "อาหาร", rom: "aa-hǎan", meaning: { fr: "nourriture, plat" }, themes: ["food"], example: { thai: "อาหารไทยอร่อยมาก", rom: "aa-hǎan thai à-rɔ̀i mâak", meaning: { fr: "la cuisine thaïe est délicieuse" } } },
      { id: "w:ข้าว", thai: "ข้าว", rom: "khâao", meaning: { fr: "riz" }, themes: ["food"], example: { thai: "กินข้าวหรือยัง", rom: "kin khâao rʉ̌ʉ yang", meaning: { fr: "as-tu déjà mangé ?" } } },
      { id: "w:ข้าวผัด", thai: "ข้าวผัด", rom: "khâao-phàt", meaning: { fr: "riz sauté" }, themes: ["food"] },
      { id: "w:ผัดไทย", thai: "ผัดไทย", rom: "phàt-thai", meaning: { fr: "pad thaï" }, themes: ["food"] },
      { id: "w:ต้มยำกุ้ง", thai: "ต้มยำกุ้ง", rom: "tôm-yam-kûng", meaning: { fr: "soupe tom yam aux crevettes" }, themes: ["food"] },
      { id: "w:ส้มตำ", thai: "ส้มตำ", rom: "sôm-tam", meaning: { fr: "salade de papaye verte" }, themes: ["food"] },
      { id: "w:แกง", thai: "แกง", rom: "kɛɛng", meaning: { fr: "curry" }, themes: ["food"] },
      { id: "w:ก๋วยเตี๋ยว", thai: "ก๋วยเตี๋ยว", rom: "kǔai-tǐao", meaning: { fr: "soupe de nouilles" }, themes: ["food"] },
      { id: "w:ไก่", thai: "ไก่", rom: "kài", meaning: { fr: "poulet" }, themes: ["food"] },
      { id: "w:หมู", thai: "หมู", rom: "mǔu", meaning: { fr: "porc" }, themes: ["food"] },
      { id: "w:เนื้อ", thai: "เนื้อ", rom: "nʉ́a", meaning: { fr: "bœuf ; viande" }, themes: ["food"] },
      { id: "w:ปลา", thai: "ปลา", rom: "plaa", meaning: { fr: "poisson" }, themes: ["food"] },
      { id: "w:กุ้ง", thai: "กุ้ง", rom: "kûng", meaning: { fr: "crevette" }, themes: ["food"] },
      { id: "w:ไข่", thai: "ไข่", rom: "khài", meaning: { fr: "œuf" }, themes: ["food"] },
      { id: "w:ผัก", thai: "ผัก", rom: "phàk", meaning: { fr: "légumes" }, themes: ["food"] },
      { id: "w:ผลไม้", thai: "ผลไม้", rom: "phǒn-lá-máai", meaning: { fr: "fruits" }, themes: ["food"] },
      { id: "w:มะม่วง", thai: "มะม่วง", rom: "má-mûang", meaning: { fr: "mangue" }, themes: ["food"] },
      { id: "w:เผ็ด", thai: "เผ็ด", rom: "phèt", meaning: { fr: "épicé" }, themes: ["food"], example: { thai: "เผ็ดไหม{Q}", rom: "phèt mái {q}", meaning: { fr: "c'est épicé ?" } } },
      { id: "w:อร่อย", thai: "อร่อย", rom: "à-rɔ̀i", meaning: { fr: "délicieux" }, themes: ["food"], example: { thai: "อร่อยมาก{P}", rom: "à-rɔ̀i mâak {p}", meaning: { fr: "c'est très bon" } } },
      { id: "w:หวาน", thai: "หวาน", rom: "wǎan", meaning: { fr: "sucré" }, themes: ["food"] },
      { id: "w:เค็ม", thai: "เค็ม", rom: "khem", meaning: { fr: "salé" }, themes: ["food"] },
      { id: "w:เปรี้ยว", thai: "เปรี้ยว", rom: "prîao", meaning: { fr: "acide" }, themes: ["food"] },
      { id: "w:แกงเขียวหวาน", thai: "แกงเขียวหวาน", rom: "kɛɛng khǐao-wǎan", meaning: { fr: "curry vert" }, themes: ["food"] },
      { id: "w:ข้าวเหนียว", thai: "ข้าวเหนียว", rom: "khâao-nǐao", meaning: { fr: "riz gluant" }, themes: ["food"] },
      { id: "w:ไข่เจียว", thai: "ไข่เจียว", rom: "khài-jiao", meaning: { fr: "omelette thaïe" }, themes: ["food"] },
      { id: "w:หมูปิ้ง", thai: "หมูปิ้ง", rom: "mǔu-pîng", meaning: { fr: "brochettes de porc grillé" }, themes: ["food"] },
      { id: "w:ผัดกะเพรา", thai: "ผัดกะเพรา", rom: "phàt kà-phrao", meaning: { fr: "sauté au basilic sacré" }, themes: ["food"] },
      { id: "w:ไก่ย่าง", thai: "ไก่ย่าง", rom: "kài-yâang", meaning: { fr: "poulet grillé" }, themes: ["food"] },
      { id: "w:ข้าวมันไก่", thai: "ข้าวมันไก่", rom: "khâao-man-kài", meaning: { fr: "riz au poulet" }, themes: ["food"] },
      { id: "w:น้ำปลา", thai: "น้ำปลา", rom: "náam-plaa", meaning: { fr: "sauce de poisson" }, themes: ["food"] },
      { id: "w:พริก", thai: "พริก", rom: "phrík", meaning: { fr: "piment" }, themes: ["food"] },
      { id: "w:เกลือ", thai: "เกลือ", rom: "klʉa", meaning: { fr: "sel" }, themes: ["food"] },
    ],
  },
  {
    id: "drink", name: { fr: "Boissons" }, icon: "🥤",
    items: [
      { id: "w:น้ำ", thai: "น้ำ", rom: "náam", meaning: { fr: "eau" }, themes: ["drink"] },
      { id: "w:น้ำเปล่า", thai: "น้ำเปล่า", rom: "náam-plàao", meaning: { fr: "eau plate" }, themes: ["drink"], example: { thai: "ขอน้ำเปล่าหนึ่งขวด{P}", rom: "khɔ̌ɔ náam-plàao nʉ̀ng khùat {p}", meaning: { fr: "une bouteille d'eau, s'il vous plaît" } } },
      { id: "w:น้ำแข็ง", thai: "น้ำแข็ง", rom: "náam-khɛ̌ng", meaning: { fr: "glaçons" }, themes: ["drink"], example: { thai: "ไม่ใส่น้ำแข็ง{P}", rom: "mâi sài náam-khɛ̌ng {p}", meaning: { fr: "sans glaçons" } } },
      { id: "w:กาแฟ", thai: "กาแฟ", rom: "kaa-fɛɛ", meaning: { fr: "café" }, themes: ["drink"], example: { thai: "ขอกาแฟร้อนหนึ่งแก้ว{P}", rom: "khɔ̌ɔ kaa-fɛɛ rɔ́ɔn nʉ̀ng kɛ̂ɛo {p}", meaning: { fr: "un café chaud, s'il vous plaît" } } },
      { id: "w:ชา", thai: "ชา", rom: "chaa", meaning: { fr: "thé" }, themes: ["drink"] },
      { id: "w:ชาเย็น", thai: "ชาเย็น", rom: "chaa-yen", meaning: { fr: "thé glacé thaï" }, themes: ["drink"] },
      { id: "w:นม", thai: "นม", rom: "nom", meaning: { fr: "lait" }, themes: ["drink"] },
      { id: "w:น้ำผลไม้", thai: "น้ำผลไม้", rom: "náam phǒn-lá-máai", meaning: { fr: "jus de fruits" }, themes: ["drink"] },
      { id: "w:น้ำส้ม", thai: "น้ำส้ม", rom: "náam-sôm", meaning: { fr: "jus d'orange" }, themes: ["drink"] },
      { id: "w:น้ำมะพร้าว", thai: "น้ำมะพร้าว", rom: "náam má-phráao", meaning: { fr: "eau de coco" }, themes: ["drink"] },
      { id: "w:เบียร์", thai: "เบียร์", rom: "bia", meaning: { fr: "bière" }, themes: ["drink"] },
      { id: "w:ไวน์", thai: "ไวน์", rom: "waai", meaning: { fr: "vin" }, themes: ["drink"] },
      { id: "w:ร้อน", thai: "ร้อน", rom: "rɔ́ɔn", meaning: { fr: "chaud" }, themes: ["drink"] },
      { id: "w:เย็น", thai: "เย็น", rom: "yen", meaning: { fr: "froid, frais" }, themes: ["drink"] },
      { id: "w:ไม่ใส่น้ำตาล", thai: "ไม่ใส่น้ำตาล", rom: "mâi sài náam-taan", meaning: { fr: "sans sucre" }, themes: ["drink"] },
      { id: "w:หวานน้อย", thai: "หวานน้อย", rom: "wǎan nɔ́ɔi", meaning: { fr: "peu sucré" }, themes: ["drink"] },
    ],
  },
  {
    id: "resto", name: { fr: "Restaurant" }, icon: "🍽️",
    items: [
      { id: "w:ร้านอาหาร", thai: "ร้านอาหาร", rom: "ráan-aa-hǎan", meaning: { fr: "restaurant" }, themes: ["resto"] },
      { id: "w:เมนู", thai: "เมนู", rom: "mee-nuu", meaning: { fr: "menu" }, themes: ["resto"], example: { thai: "ขอเมนูหน่อย{P}", rom: "khɔ̌ɔ mee-nuu nɔ̀i {p}", meaning: { fr: "le menu, s'il vous plaît" } } },
      { id: "w:สั่งอาหาร", thai: "สั่งอาหาร", rom: "sàng aa-hǎan", meaning: { fr: "commander (un plat)" }, themes: ["resto"] },
      { id: "w:เอาอันนี้{P}", thai: "เอาอันนี้{P}", rom: "ao an-níi {p}", meaning: { fr: "je prends ceci" }, themes: ["resto"] },
      { id: "w:ไม่เผ็ด{P}", thai: "ไม่เผ็ด{P}", rom: "mâi phèt {p}", meaning: { fr: "pas épicé" }, themes: ["resto"] },
      { id: "w:เผ็ดนิดหน่อย", thai: "เผ็ดนิดหน่อย", rom: "phèt nít-nɔ̀i", meaning: { fr: "un peu épicé" }, themes: ["resto"] },
      { id: "w:{I}กินเผ็ดไม่ได้", thai: "{I}กินเผ็ดไม่ได้", rom: "{i} kin phèt mâi dâai", meaning: { fr: "je ne peux pas manger épicé" }, themes: ["resto"] },
      { id: "w:{I}ไม่กินเนื้อสัตว์", thai: "{I}ไม่กินเนื้อสัตว์", rom: "{i} mâi kin nʉ́a-sàt", meaning: { fr: "je ne mange pas de viande" }, themes: ["resto"] },
      { id: "w:เช็กบิลด้วย{P}", thai: "เช็กบิลด้วย{P}", rom: "chék-bin dûai {p}", meaning: { fr: "l'addition, s'il vous plaît" }, themes: ["resto"] },
      { id: "w:เก็บเงินด้วย{P}", thai: "เก็บเงินด้วย{P}", rom: "kèp-ngən dûai {p}", meaning: { fr: "l'addition (restaurant simple)" }, themes: ["resto"] },
      { id: "w:ห้องน้ำอยู่ที่ไหน{Q}", thai: "ห้องน้ำอยู่ที่ไหน{Q}", rom: "hɔ̂ng-náam yùu thîi-nǎi {q}", meaning: { fr: "où sont les toilettes ?" }, themes: ["resto"] },
      { id: "w:ช้อน", thai: "ช้อน", rom: "chɔ́ɔn", meaning: { fr: "cuillère" }, themes: ["resto"] },
      { id: "w:ส้อม", thai: "ส้อม", rom: "sɔ̂m", meaning: { fr: "fourchette" }, themes: ["resto"] },
      { id: "w:ตะเกียบ", thai: "ตะเกียบ", rom: "tà-kìap", meaning: { fr: "baguettes" }, themes: ["resto"] },
      { id: "w:แก้ว", thai: "แก้ว", rom: "kɛ̂ɛo", meaning: { fr: "verre" }, themes: ["resto"] },
      { id: "w:จาน", thai: "จาน", rom: "jaan", meaning: { fr: "assiette" }, themes: ["resto"] },
      { id: "w:หิว", thai: "หิว", rom: "hǐu", meaning: { fr: "avoir faim" }, themes: ["resto"], example: { thai: "{I}หิวแล้ว", rom: "{i} hǐu lɛ́ɛo", meaning: { fr: "j'ai faim" } } },
      { id: "w:อิ่มแล้ว", thai: "อิ่มแล้ว", rom: "ìm lɛ́ɛo", meaning: { fr: "je n'ai plus faim" }, themes: ["resto"] },
      { id: "w:ขอโต๊ะสำหรับสองคน{P}", thai: "ขอโต๊ะสำหรับสองคน{P}", rom: "khɔ̌ɔ tó sǎm-ràp sɔ̌ɔng khon {p}", meaning: { fr: "une table pour deux, s'il vous plaît" }, themes: ["resto"] },
      { id: "w:ไม่ใส่ผักชี{P}", thai: "ไม่ใส่ผักชี{P}", rom: "mâi sài phàk-chii {p}", meaning: { fr: "sans coriandre, s'il vous plaît" }, themes: ["resto"] },
      { id: "w:ไม่ใส่น้ำแข็ง", thai: "ไม่ใส่น้ำแข็ง", rom: "mâi sài náam-khɛ̌ng", meaning: { fr: "sans glaçons" }, themes: ["resto"] },
      { id: "w:เผ็ดน้อย", thai: "เผ็ดน้อย", rom: "phèt nɔ́ɔi", meaning: { fr: "peu épicé" }, themes: ["resto"] },
      { id: "w:ขอช้อนส้อม{P}", thai: "ขอช้อนส้อม{P}", rom: "khɔ̌ɔ chɔ́ɔn sɔ̂m {p}", meaning: { fr: "une cuillère et une fourchette, s'il vous plaît" }, themes: ["resto"] },
      { id: "w:ห่อกลับบ้าน", thai: "ห่อกลับบ้าน", rom: "hɔ̀ɔ klàp bâan", meaning: { fr: "à emporter" }, themes: ["resto"] },
      { id: "w:กินที่นี่", thai: "กินที่นี่", rom: "kin thîi-nîi", meaning: { fr: "sur place" }, themes: ["resto"] },
      { id: "w:แนะนำอะไร{Q}", thai: "แนะนำอะไร{Q}", rom: "nɛ́-nam à-rai {q}", meaning: { fr: "que recommandez-vous ?" }, themes: ["resto"] },
    ],
  },
  {
    id: "market", name: { fr: "Marché" }, icon: "🧺",
    items: [
      { id: "w:ตลาด", thai: "ตลาด", rom: "tà-làat", meaning: { fr: "marché" }, themes: ["market"], example: { thai: "{I}จะไปตลาด", rom: "{i} jà pai tà-làat", meaning: { fr: "je vais aller au marché" } } },
      { id: "w:อันนี้เท่าไหร่{Q}", thai: "อันนี้เท่าไหร่{Q}", rom: "an-níi thâo-rài {q}", meaning: { fr: "combien coûte ceci ?" }, themes: ["market"] },
      { id: "w:ราคาเท่าไหร่{Q}", thai: "ราคาเท่าไหร่{Q}", rom: "raa-khaa thâo-rài {q}", meaning: { fr: "quel est le prix ?" }, themes: ["market"] },
      { id: "w:แพงไป", thai: "แพงไป", rom: "phɛɛng pai", meaning: { fr: "trop cher" }, themes: ["market"] },
      { id: "w:แพงมาก", thai: "แพงมาก", rom: "phɛɛng mâak", meaning: { fr: "très cher" }, themes: ["market"] },
      { id: "w:ลดหน่อยได้ไหม{Q}", thai: "ลดหน่อยได้ไหม{Q}", rom: "lót nɔ̀i dâai mái {q}", meaning: { fr: "pouvez-vous baisser un peu le prix ?" }, themes: ["market"] },
      { id: "w:ลดได้เท่าไหร่{Q}", thai: "ลดได้เท่าไหร่{Q}", rom: "lót dâai thâo-rài {q}", meaning: { fr: "vous pouvez baisser de combien ?" }, themes: ["market"] },
      { id: "w:{I}เอาอันนี้", thai: "{I}เอาอันนี้", rom: "{i} ao an-níi", meaning: { fr: "je voudrais celui-ci" }, themes: ["market"] },
      { id: "w:เอาแบบนี้สองอัน", thai: "เอาแบบนี้สองอัน", rom: "ao bɛ̀ɛp-níi sɔ̌ɔng an", meaning: { fr: "j'en prends deux comme ça" }, themes: ["market"] },
      { id: "w:มีขนาดอื่นไหม{Q}", thai: "มีขนาดอื่นไหม{Q}", rom: "mii khà-nàat ʉ̀ʉn mái {q}", meaning: { fr: "avez-vous une autre taille ?" }, themes: ["market"] },
      { id: "w:มีสีอื่นไหม{Q}", thai: "มีสีอื่นไหม{Q}", rom: "mii sǐi ʉ̀ʉn mái {q}", meaning: { fr: "avez-vous une autre couleur ?" }, themes: ["market"] },
      { id: "w:ลองได้ไหม{Q}", thai: "ลองได้ไหม{Q}", rom: "lɔɔng dâai mái {q}", meaning: { fr: "puis-je essayer ?" }, themes: ["market"] },
      { id: "w:ใหญ่ไป", thai: "ใหญ่ไป", rom: "yài pai", meaning: { fr: "trop grand" }, themes: ["market"] },
      { id: "w:เล็กไป", thai: "เล็กไป", rom: "lék pai", meaning: { fr: "trop petit" }, themes: ["market"] },
      { id: "w:ขอดูหน่อย{P}", thai: "ขอดูหน่อย{P}", rom: "khɔ̌ɔ duu nɔ̀i {p}", meaning: { fr: "puis-je regarder ?" }, themes: ["market"] },
      { id: "w:ไม่เอา{P}", thai: "ไม่เอา{P}", rom: "mâi ao {p}", meaning: { fr: "je n'en veux pas, merci" }, themes: ["market"] },
      { id: "w:กิโลละเท่าไหร่{Q}", thai: "กิโลละเท่าไหร่{Q}", rom: "kì-loo lá thâo-rài {q}", meaning: { fr: "c'est combien le kilo ?" }, themes: ["market"] },
      { id: "w:จ่ายเงิน", thai: "จ่ายเงิน", rom: "jàai ngən", meaning: { fr: "payer" }, themes: ["market"] },
      { id: "w:เงินสด", thai: "เงินสด", rom: "ngən-sòt", meaning: { fr: "espèces" }, themes: ["market"] },
      { id: "w:รับบัตรไหม{Q}", thai: "รับบัตรไหม{Q}", rom: "ráp bàt mái {q}", meaning: { fr: "acceptez-vous la carte ?" }, themes: ["market"] },
      { id: "w:เงินทอน", thai: "เงินทอน", rom: "ngən-thɔɔn", meaning: { fr: "monnaie rendue" }, themes: ["market"] },
      { id: "w:ถุง", thai: "ถุง", rom: "thǔng", meaning: { fr: "sac" }, themes: ["market"], example: { thai: "ไม่เอาถุง{P}", rom: "mâi ao thǔng {p}", meaning: { fr: "pas de sac, merci" } } },
      { id: "w:สดไหม{Q}", thai: "สดไหม{Q}", rom: "sòt mái {q}", meaning: { fr: "c'est frais ?" }, themes: ["market"] },
      { id: "w:หวานไหม{Q}", thai: "หวานไหม{Q}", rom: "wǎan mái {q}", meaning: { fr: "c'est sucré ?" }, themes: ["market"] },
      { id: "w:ชิมได้ไหม{Q}", thai: "ชิมได้ไหม{Q}", rom: "chim dâai mái {q}", meaning: { fr: "puis-je goûter ?" }, themes: ["market"] },
      { id: "w:ครึ่งกิโล", thai: "ครึ่งกิโล", rom: "khrʉ̂ng kì-loo", meaning: { fr: "un demi-kilo" }, themes: ["market"] },
      { id: "w:หนึ่งกิโล", thai: "หนึ่งกิโล", rom: "nʉ̀ng kì-loo", meaning: { fr: "un kilo" }, themes: ["market"] },
      { id: "w:ชั่งให้หน่อย{P}", thai: "ชั่งให้หน่อย{P}", rom: "châng hâi nɔ̀i {p}", meaning: { fr: "pesez-le-moi, s'il vous plaît" }, themes: ["market"] },
      { id: "w:ขอถุงหน่อย{P}", thai: "ขอถุงหน่อย{P}", rom: "khɔ̌ɔ thǔng nɔ̀i {p}", meaning: { fr: "un sac, s'il vous plaît" }, themes: ["market"] },
    ],
  },
  {
    id: "shop", name: { fr: "Shopping" }, icon: "🛍️",
    items: [
      { id: "w:ห้างสรรพสินค้า", thai: "ห้างสรรพสินค้า", rom: "hâang sàp-phá-sǐn-kháa", meaning: { fr: "grand magasin, centre commercial" }, themes: ["shop"] },
      { id: "w:ร้าน", thai: "ร้าน", rom: "ráan", meaning: { fr: "boutique" }, themes: ["shop"] },
      { id: "w:เสื้อ", thai: "เสื้อ", rom: "sʉ̂a", meaning: { fr: "chemise, haut" }, themes: ["shop"], example: { thai: "เสื้อตัวนี้สวย", rom: "sʉ̂a tua níi sǔai", meaning: { fr: "cette chemise est belle" } } },
      { id: "w:กางเกง", thai: "กางเกง", rom: "kaang-keeng", meaning: { fr: "pantalon" }, themes: ["shop"] },
      { id: "w:รองเท้า", thai: "รองเท้า", rom: "rɔɔng-tháao", meaning: { fr: "chaussures" }, themes: ["shop"] },
      { id: "w:กระเป๋า", thai: "กระเป๋า", rom: "krà-pǎo", meaning: { fr: "sac" }, themes: ["shop"] },
      { id: "w:ของฝาก", thai: "ของฝาก", rom: "khɔ̌ɔng-fàak", meaning: { fr: "souvenir à offrir" }, themes: ["shop"] },
      { id: "w:ลดราคา", thai: "ลดราคา", rom: "lót raa-khaa", meaning: { fr: "en promotion" }, themes: ["shop"] },
      { id: "w:ใบเสร็จ", thai: "ใบเสร็จ", rom: "bai-sèt", meaning: { fr: "reçu" }, themes: ["shop"], example: { thai: "ขอใบเสร็จด้วย{P}", rom: "khɔ̌ɔ bai-sèt dûai {p}", meaning: { fr: "le reçu, s'il vous plaît" } } },
      { id: "w:เปิด", thai: "เปิด", rom: "pə̀ət", meaning: { fr: "ouvrir ; ouvert" }, themes: ["shop"], example: { thai: "ร้านเปิดกี่โมง{Q}", rom: "ráan pə̀ət kìi moong {q}", meaning: { fr: "à quelle heure ouvre la boutique ?" } } },
      { id: "w:ปิด", thai: "ปิด", rom: "pìt", meaning: { fr: "fermer ; fermé" }, themes: ["shop"] },
      { id: "w:ซื้อ", thai: "ซื้อ", rom: "sʉ́ʉ", meaning: { fr: "acheter" }, themes: ["shop"] },
      { id: "w:ขาย", thai: "ขาย", rom: "khǎai", meaning: { fr: "vendre" }, themes: ["shop"] },
      { id: "w:เปลี่ยน", thai: "เปลี่ยน", rom: "plìan", meaning: { fr: "changer, échanger" }, themes: ["shop"], example: { thai: "เปลี่ยนได้ไหม{Q}", rom: "plìan dâai mái {q}", meaning: { fr: "puis-je l'échanger ?" } } },
      { id: "w:คืนเงิน", thai: "คืนเงิน", rom: "khʉʉn ngən", meaning: { fr: "rembourser" }, themes: ["shop"] },
      { id: "w:ขอลองได้ไหม{Q}", thai: "ขอลองได้ไหม{Q}", rom: "khɔ̌ɔ lɔɔng dâai mái {q}", meaning: { fr: "puis-je essayer ?" }, themes: ["shop"] },
    ],
  },
  {
    id: "price", name: { fr: "Prix" }, icon: "💰",
    items: [
      { id: "w:บาท", thai: "บาท", rom: "bàat", meaning: { fr: "baht" }, themes: ["price"], example: { thai: "ร้อยบาท", rom: "rɔ́ɔi bàat", meaning: { fr: "cent bahts" } } },
      { id: "w:ราคา", thai: "ราคา", rom: "raa-khaa", meaning: { fr: "prix" }, themes: ["price"] },
      { id: "w:เท่าไหร่", thai: "เท่าไหร่", rom: "thâo-rài", meaning: { fr: "combien" }, themes: ["price"] },
      { id: "w:ทั้งหมดเท่าไหร่{Q}", thai: "ทั้งหมดเท่าไหร่{Q}", rom: "tháng-mòt thâo-rài {q}", meaning: { fr: "ça fait combien en tout ?" }, themes: ["price"] },
      { id: "w:ห้าสิบบาท", thai: "ห้าสิบบาท", rom: "hâa-sìp bàat", meaning: { fr: "cinquante bahts" }, themes: ["price"] },
      { id: "w:ส่วนลด", thai: "ส่วนลด", rom: "sùan-lót", meaning: { fr: "réduction" }, themes: ["price"] },
      { id: "w:ราคาพิเศษ", thai: "ราคาพิเศษ", rom: "raa-khaa phí-sèet", meaning: { fr: "prix spécial" }, themes: ["price"] },
      { id: "w:แพงเกินไป", thai: "แพงเกินไป", rom: "phɛɛng kəən pai", meaning: { fr: "beaucoup trop cher" }, themes: ["price"] },
      { id: "w:ถูก", thai: "ถูก", rom: "thùuk", meaning: { fr: "bon marché" }, themes: ["price"] },
      { id: "w:ฟรี", thai: "ฟรี", rom: "frii", meaning: { fr: "gratuit" }, themes: ["price"] },
      { id: "w:ไม่มีเงินทอน", thai: "ไม่มีเงินทอน", rom: "mâi mii ngən-thɔɔn", meaning: { fr: "je n'ai pas de monnaie" }, themes: ["price"] },
      { id: "w:แลกเงิน", thai: "แลกเงิน", rom: "lɛ̂ɛk ngən", meaning: { fr: "changer de l'argent" }, themes: ["price"] },
      { id: "w:ตู้เอทีเอ็ม", thai: "ตู้เอทีเอ็ม", rom: "tûu ee-thii-em", meaning: { fr: "distributeur de billets" }, themes: ["price"] },
    ],
  },
  {
    id: "num", name: { fr: "Nombres et quantités" }, icon: "🔢",
    items: [
      { id: "w:ที่หนึ่ง", thai: "ที่หนึ่ง", rom: "thîi-nʉ̀ng", meaning: { fr: "premier" }, themes: ["num"] },
      { id: "w:ครึ่ง", thai: "ครึ่ง", rom: "khrʉ̂ng", meaning: { fr: "demi, moitié" }, themes: ["num"] },
      { id: "w:คู่", thai: "คู่", rom: "khûu", meaning: { fr: "paire" }, themes: ["num"] },
      { id: "w:หลาย", thai: "หลาย", rom: "lǎai", meaning: { fr: "plusieurs" }, themes: ["num"], example: { thai: "หลายคน", rom: "lǎai khon", meaning: { fr: "plusieurs personnes" } } },
      { id: "w:ทุก", thai: "ทุก", rom: "thúk", meaning: { fr: "chaque" }, themes: ["num"], example: { thai: "ทุกวัน", rom: "thúk wan", meaning: { fr: "tous les jours" } } },
      { id: "w:กี่", thai: "กี่", rom: "kìi", meaning: { fr: "combien de" }, themes: ["num"], example: { thai: "กี่คน{Q}", rom: "kìi khon {q}", meaning: { fr: "combien de personnes ?" } } },
      { id: "w:ครั้ง", thai: "ครั้ง", rom: "khráng", meaning: { fr: "fois" }, themes: ["num"], example: { thai: "สองครั้ง", rom: "sɔ̌ɔng khráng", meaning: { fr: "deux fois" } } },
      { id: "w:เบอร์", thai: "เบอร์", rom: "bəə", meaning: { fr: "numéro" }, themes: ["num"] },
      { id: "w:เบอร์โทรศัพท์", thai: "เบอร์โทรศัพท์", rom: "bəə thoo-rá-sàp", meaning: { fr: "numéro de téléphone" }, themes: ["num"] },
      { id: "w:ประมาณ", thai: "ประมาณ", rom: "prà-maan", meaning: { fr: "environ" }, themes: ["num"] },
      { id: "w:มากกว่า", thai: "มากกว่า", rom: "mâak-kwàa", meaning: { fr: "plus que" }, themes: ["num"] },
      { id: "w:น้อยกว่า", thai: "น้อยกว่า", rom: "nɔ́ɔi-kwàa", meaning: { fr: "moins que" }, themes: ["num"] },
    ],
  },
  {
    id: "color", name: { fr: "Couleurs" }, icon: "🎨",
    items: [
      { id: "w:สี", thai: "สี", rom: "sǐi", meaning: { fr: "couleur" }, themes: ["color"], example: { thai: "คุณชอบสีอะไร{Q}", rom: "khun chɔ̂ɔp sǐi à-rai {q}", meaning: { fr: "quelle couleur aimez-vous ?" } } },
      { id: "w:สีแดง", thai: "สีแดง", rom: "sǐi-dɛɛng", meaning: { fr: "rouge" }, themes: ["color"] },
      { id: "w:สีน้ำเงิน", thai: "สีน้ำเงิน", rom: "sǐi-náam-ngən", meaning: { fr: "bleu foncé" }, themes: ["color"] },
      { id: "w:สีฟ้า", thai: "สีฟ้า", rom: "sǐi-fáa", meaning: { fr: "bleu ciel" }, themes: ["color"] },
      { id: "w:สีเขียว", thai: "สีเขียว", rom: "sǐi-khǐao", meaning: { fr: "vert" }, themes: ["color"] },
      { id: "w:สีเหลือง", thai: "สีเหลือง", rom: "sǐi-lʉ̌ang", meaning: { fr: "jaune" }, themes: ["color"] },
      { id: "w:สีดำ", thai: "สีดำ", rom: "sǐi-dam", meaning: { fr: "noir" }, themes: ["color"] },
      { id: "w:สีขาว", thai: "สีขาว", rom: "sǐi-khǎao", meaning: { fr: "blanc" }, themes: ["color"] },
      { id: "w:สีส้ม", thai: "สีส้ม", rom: "sǐi-sôm", meaning: { fr: "orange" }, themes: ["color"] },
      { id: "w:สีชมพู", thai: "สีชมพู", rom: "sǐi-chom-phuu", meaning: { fr: "rose" }, themes: ["color"] },
      { id: "w:สีม่วง", thai: "สีม่วง", rom: "sǐi-mûang", meaning: { fr: "violet" }, themes: ["color"] },
      { id: "w:สีน้ำตาล", thai: "สีน้ำตาล", rom: "sǐi-náam-taan", meaning: { fr: "brun" }, themes: ["color"] },
      { id: "w:สีเทา", thai: "สีเทา", rom: "sǐi-thao", meaning: { fr: "gris" }, themes: ["color"] },
    ],
  },
  {
    id: "date", name: { fr: "Dates" }, icon: "📅",
    items: [
      { id: "w:วันนี้", thai: "วันนี้", rom: "wan-níi", meaning: { fr: "aujourd'hui" }, themes: ["date"] },
      { id: "w:พรุ่งนี้", thai: "พรุ่งนี้", rom: "phrûng-níi", meaning: { fr: "demain" }, themes: ["date"] },
      { id: "w:เมื่อวาน", thai: "เมื่อวาน", rom: "mʉ̂a-waan", meaning: { fr: "hier" }, themes: ["date"] },
      { id: "w:วันจันทร์", thai: "วันจันทร์", rom: "wan-jan", meaning: { fr: "lundi" }, themes: ["date"] },
      { id: "w:วันอังคาร", thai: "วันอังคาร", rom: "wan-ang-khaan", meaning: { fr: "mardi" }, themes: ["date"] },
      { id: "w:วันพุธ", thai: "วันพุธ", rom: "wan-phút", meaning: { fr: "mercredi" }, themes: ["date"] },
      { id: "w:วันพฤหัส", thai: "วันพฤหัส", rom: "wan-phá-rʉ́-hàt", meaning: { fr: "jeudi" }, themes: ["date"] },
      { id: "w:วันศุกร์", thai: "วันศุกร์", rom: "wan-sùk", meaning: { fr: "vendredi" }, themes: ["date"] },
      { id: "w:วันเสาร์", thai: "วันเสาร์", rom: "wan-sǎo", meaning: { fr: "samedi" }, themes: ["date"] },
      { id: "w:วันอาทิตย์", thai: "วันอาทิตย์", rom: "wan-aa-thít", meaning: { fr: "dimanche" }, themes: ["date"] },
      { id: "w:อาทิตย์", thai: "อาทิตย์", rom: "aa-thít", meaning: { fr: "semaine" }, themes: ["date"], example: { thai: "อาทิตย์หน้า", rom: "aa-thít nâa", meaning: { fr: "la semaine prochaine" } } },
      { id: "w:เดือน", thai: "เดือน", rom: "dʉan", meaning: { fr: "mois" }, themes: ["date"] },
      { id: "w:ปี", thai: "ปี", rom: "pii", meaning: { fr: "année" }, themes: ["date"] },
      { id: "w:วันเกิด", thai: "วันเกิด", rom: "wan-kə̀ət", meaning: { fr: "anniversaire" }, themes: ["date"] },
      { id: "w:วันหยุด", thai: "วันหยุด", rom: "wan-yùt", meaning: { fr: "jour de congé" }, themes: ["date"] },
    ],
  },
  {
    id: "time", name: { fr: "Heures" }, icon: "🕐",
    items: [
      { id: "w:กี่โมงแล้ว{Q}", thai: "กี่โมงแล้ว{Q}", rom: "kìi moong lɛ́ɛo {q}", meaning: { fr: "quelle heure est-il ?" }, themes: ["time"] },
      { id: "w:โมง", thai: "โมง", rom: "moong", meaning: { fr: "heure (de la journée)" }, themes: ["time"] },
      { id: "w:นาที", thai: "นาที", rom: "naa-thii", meaning: { fr: "minute" }, themes: ["time"] },
      { id: "w:ชั่วโมง", thai: "ชั่วโมง", rom: "chûa-moong", meaning: { fr: "heure (durée)" }, themes: ["time"], example: { thai: "ครึ่งชั่วโมง", rom: "khrʉ̂ng chûa-moong", meaning: { fr: "une demi-heure" } } },
      { id: "w:เช้า", thai: "เช้า", rom: "cháao", meaning: { fr: "matin" }, themes: ["time"], example: { thai: "เก้าโมงเช้า", rom: "kâao moong cháao", meaning: { fr: "9 h du matin" } } },
      { id: "w:เที่ยง", thai: "เที่ยง", rom: "thîang", meaning: { fr: "midi" }, themes: ["time"] },
      { id: "w:บ่าย", thai: "บ่าย", rom: "bàai", meaning: { fr: "après-midi" }, themes: ["time"], example: { thai: "บ่ายสองโมง", rom: "bàai sɔ̌ɔng moong", meaning: { fr: "14 h" } } },
      { id: "w:เย็น", thai: "เย็น", rom: "yen", meaning: { fr: "début de soirée" }, themes: ["time"], example: { thai: "ห้าโมงเย็น", rom: "hâa moong yen", meaning: { fr: "17 h" } } },
      { id: "w:ทุ่ม", thai: "ทุ่ม", rom: "thûm", meaning: { fr: "heure du soir (19 h – 23 h)" }, themes: ["time"], example: { thai: "หนึ่งทุ่ม", rom: "nʉ̀ng thûm", meaning: { fr: "19 h" } } },
      { id: "w:กลางคืน", thai: "กลางคืน", rom: "klaang-khʉʉn", meaning: { fr: "nuit" }, themes: ["time"] },
      { id: "w:ตอนนี้", thai: "ตอนนี้", rom: "tɔɔn-níi", meaning: { fr: "maintenant" }, themes: ["time"] },
      { id: "w:เดี๋ยวนี้", thai: "เดี๋ยวนี้", rom: "dǐao-níi", meaning: { fr: "tout de suite" }, themes: ["time"] },
      { id: "w:ทีหลัง", thai: "ทีหลัง", rom: "thii-lǎng", meaning: { fr: "plus tard" }, themes: ["time"] },
      { id: "w:สาย", thai: "สาย", rom: "sǎai", meaning: { fr: "en retard" }, themes: ["time"] },
      { id: "w:เร็ว", thai: "เร็ว", rom: "reo", meaning: { fr: "rapide ; tôt" }, themes: ["time"] },
    ],
  },
  {
    id: "weather", name: { fr: "Météo" }, icon: "⛅",
    items: [
      { id: "w:อากาศ", thai: "อากาศ", rom: "aa-kàat", meaning: { fr: "temps (météo) ; air" }, themes: ["weather"], example: { thai: "วันนี้อากาศดี", rom: "wan-níi aa-kàat dii", meaning: { fr: "il fait beau aujourd'hui" } } },
      { id: "w:ร้อนมาก", thai: "ร้อนมาก", rom: "rɔ́ɔn mâak", meaning: { fr: "il fait très chaud" }, themes: ["weather"] },
      { id: "w:หนาว", thai: "หนาว", rom: "nǎao", meaning: { fr: "froid (météo)" }, themes: ["weather"] },
      { id: "w:ฝนตก", thai: "ฝนตก", rom: "fǒn tòk", meaning: { fr: "il pleut" }, themes: ["weather"] },
      { id: "w:แดด", thai: "แดด", rom: "dɛ̀ɛt", meaning: { fr: "soleil (lumière)" }, themes: ["weather"], example: { thai: "แดดแรง", rom: "dɛ̀ɛt rɛɛng", meaning: { fr: "le soleil tape fort" } } },
      { id: "w:ลม", thai: "ลม", rom: "lom", meaning: { fr: "vent" }, themes: ["weather"] },
      { id: "w:เมฆ", thai: "เมฆ", rom: "mêek", meaning: { fr: "nuage" }, themes: ["weather"] },
      { id: "w:พายุ", thai: "พายุ", rom: "phaa-yú", meaning: { fr: "tempête" }, themes: ["weather"] },
      { id: "w:ฤดูฝน", thai: "ฤดูฝน", rom: "rʉ́-duu fǒn", meaning: { fr: "saison des pluies" }, themes: ["weather"] },
      { id: "w:ฤดูร้อน", thai: "ฤดูร้อน", rom: "rʉ́-duu rɔ́ɔn", meaning: { fr: "saison chaude" }, themes: ["weather"] },
      { id: "w:ชื้น", thai: "ชื้น", rom: "chʉ́ʉn", meaning: { fr: "humide" }, themes: ["weather"] },
      { id: "w:ร่ม", thai: "ร่ม", rom: "rôm", meaning: { fr: "parapluie" }, themes: ["weather"] },
    ],
  },
  {
    id: "trans", name: { fr: "Transport" }, icon: "🚆",
    items: [
      { id: "w:รถ", thai: "รถ", rom: "rót", meaning: { fr: "voiture, véhicule" }, themes: ["trans"] },
      { id: "w:รถเมล์", thai: "รถเมล์", rom: "rót-mee", meaning: { fr: "bus" }, themes: ["trans"] },
      { id: "w:รถไฟ", thai: "รถไฟ", rom: "rót-fai", meaning: { fr: "train" }, themes: ["trans"] },
      { id: "w:รถไฟฟ้า", thai: "รถไฟฟ้า", rom: "rót-fai-fáa", meaning: { fr: "métro aérien" }, themes: ["trans"] },
      { id: "w:รถไฟใต้ดิน", thai: "รถไฟใต้ดิน", rom: "rót-fai tâi-din", meaning: { fr: "métro souterrain" }, themes: ["trans"] },
      { id: "w:เรือ", thai: "เรือ", rom: "rʉa", meaning: { fr: "bateau" }, themes: ["trans"] },
      { id: "w:เครื่องบิน", thai: "เครื่องบิน", rom: "khrʉ̂ang-bin", meaning: { fr: "avion" }, themes: ["trans"] },
      { id: "w:มอเตอร์ไซค์", thai: "มอเตอร์ไซค์", rom: "mɔɔ-təə-sai", meaning: { fr: "moto" }, themes: ["trans"] },
      { id: "w:ตุ๊กตุ๊ก", thai: "ตุ๊กตุ๊ก", rom: "túk-túk", meaning: { fr: "tuk-tuk" }, themes: ["trans"] },
      { id: "w:สถานี", thai: "สถานี", rom: "sà-thǎa-nii", meaning: { fr: "station" }, themes: ["trans"], example: { thai: "สถานีรถไฟ", rom: "sà-thǎa-nii rót-fai", meaning: { fr: "gare" } } },
      { id: "w:ป้ายรถเมล์", thai: "ป้ายรถเมล์", rom: "pâai rót-mee", meaning: { fr: "arrêt de bus" }, themes: ["trans"] },
      { id: "w:ตั๋ว", thai: "ตั๋ว", rom: "tǔa", meaning: { fr: "billet" }, themes: ["trans"], example: { thai: "ตั๋วไปเชียงใหม่หนึ่งใบ", rom: "tǔa pai chiang-mài nʉ̀ng bai", meaning: { fr: "un billet pour Chiang Mai" } } },
      { id: "w:ขึ้นรถ", thai: "ขึ้นรถ", rom: "khʉ̂n rót", meaning: { fr: "monter (dans un véhicule)" }, themes: ["trans"] },
      { id: "w:ลงรถ", thai: "ลงรถ", rom: "long rót", meaning: { fr: "descendre (d'un véhicule)" }, themes: ["trans"] },
      { id: "w:ไกล", thai: "ไกล", rom: "klai", meaning: { fr: "loin" }, themes: ["trans"] },
      { id: "w:ใกล้", thai: "ใกล้", rom: "klâi", meaning: { fr: "près" }, themes: ["trans"] },
    ],
  },
  {
    id: "taxi", name: { fr: "Taxi" }, icon: "🚕",
    items: [
      { id: "w:แท็กซี่", thai: "แท็กซี่", rom: "thɛ́k-sîi", meaning: { fr: "taxi" }, themes: ["taxi"] },
      { id: "w:ไปที่นี่{P}", thai: "ไปที่นี่{P}", rom: "pai thîi-nîi {p}", meaning: { fr: "allez ici (en montrant l'adresse)" }, themes: ["taxi"] },
      { id: "w:ไปสนามบิน{P}", thai: "ไปสนามบิน{P}", rom: "pai sà-nǎam-bin {p}", meaning: { fr: "à l'aéroport, s'il vous plaît" }, themes: ["taxi"] },
      { id: "w:จอดตรงนี้{P}", thai: "จอดตรงนี้{P}", rom: "jɔ̀ɔt trong-níi {p}", meaning: { fr: "arrêtez-vous ici" }, themes: ["taxi"] },
      { id: "w:เลี้ยวซ้าย", thai: "เลี้ยวซ้าย", rom: "líao sáai", meaning: { fr: "tournez à gauche" }, themes: ["taxi"] },
      { id: "w:เลี้ยวขวา", thai: "เลี้ยวขวา", rom: "líao khwǎa", meaning: { fr: "tournez à droite" }, themes: ["taxi"] },
      { id: "w:ตรงไป", thai: "ตรงไป", rom: "trong pai", meaning: { fr: "tout droit" }, themes: ["taxi"] },
      { id: "w:ใช้เวลานานเท่าไหร่{Q}", thai: "ใช้เวลานานเท่าไหร่{Q}", rom: "chái wee-laa naan thâo-rài {q}", meaning: { fr: "ça prend combien de temps ?" }, themes: ["taxi"] },
      { id: "w:ไปที่นั่นเท่าไหร่{Q}", thai: "ไปที่นั่นเท่าไหร่{Q}", rom: "pai thîi-nân thâo-rài {q}", meaning: { fr: "c'est combien pour aller là-bas ?" }, themes: ["taxi"] },
      { id: "w:เปิดมิเตอร์ด้วย{P}", thai: "เปิดมิเตอร์ด้วย{P}", rom: "pə̀ət mí-təə dûai {p}", meaning: { fr: "mettez le compteur, s'il vous plaît" }, themes: ["taxi"] },
      { id: "w:สนามบิน", thai: "สนามบิน", rom: "sà-nǎam-bin", meaning: { fr: "aéroport" }, themes: ["taxi"] },
      { id: "w:โรงแรม", thai: "โรงแรม", rom: "roong-rɛɛm", meaning: { fr: "hôtel" }, themes: ["taxi"] },
      { id: "w:สถานีรถไฟ", thai: "สถานีรถไฟ", rom: "sà-thǎa-nii rót-fai", meaning: { fr: "gare" }, themes: ["taxi"] },
      { id: "w:ขึ้นทางด่วนไหม{Q}", thai: "ขึ้นทางด่วนไหม{Q}", rom: "khʉ̂n thaang-dùan mái {q}", meaning: { fr: "on prend la voie express ?" }, themes: ["taxi"] },
      { id: "w:รถติด", thai: "รถติด", rom: "rót tìt", meaning: { fr: "embouteillage" }, themes: ["taxi"] },
      { id: "w:ช้าๆหน่อย{P}", thai: "ช้าๆหน่อย{P}", rom: "cháa-cháa nɔ̀i {p}", meaning: { fr: "plus doucement, s'il vous plaît" }, themes: ["taxi"] },
      { id: "w:ถึงแล้ว", thai: "ถึงแล้ว", rom: "thʉ̌ng lɛ́ɛo", meaning: { fr: "on est arrivé" }, themes: ["taxi"] },
      { id: "w:ไม่ต้องทอน{P}", thai: "ไม่ต้องทอน{P}", rom: "mâi tɔ̂ng thɔɔn {p}", meaning: { fr: "gardez la monnaie" }, themes: ["taxi"] },
      { id: "w:เลี้ยวซ้ายข้างหน้า{P}", thai: "เลี้ยวซ้ายข้างหน้า{P}", rom: "líao sáai khâang-nâa {p}", meaning: { fr: "tournez à gauche devant" }, themes: ["taxi"] },
      { id: "w:กลับรถ", thai: "กลับรถ", rom: "klàp rót", meaning: { fr: "faire demi-tour" }, themes: ["taxi"] },
      { id: "w:ช้าๆ หน่อย{P}", thai: "ช้าๆ หน่อย{P}", rom: "cháa-cháa nɔ̀i {p}", meaning: { fr: "plus lentement, s'il vous plaît" }, themes: ["taxi"] },
      { id: "w:รีบหน่อย{P}", thai: "รีบหน่อย{P}", rom: "rîip nɔ̀i {p}", meaning: { fr: "un peu plus vite, je suis pressé" }, themes: ["taxi"] },
      { id: "w:เปิดแอร์หน่อย{P}", thai: "เปิดแอร์หน่อย{P}", rom: "pə̀ət ɛɛ nɔ̀i {p}", meaning: { fr: "mettez la climatisation, s'il vous plaît" }, themes: ["taxi"] },
      { id: "w:มีเงินทอนไหม{Q}", thai: "มีเงินทอนไหม{Q}", rom: "mii ngən thɔɔn mái {q}", meaning: { fr: "avez-vous la monnaie ?" }, themes: ["taxi"] },
      { id: "w:รถติดมาก", thai: "รถติดมาก", rom: "rót tìt mâak", meaning: { fr: "il y a beaucoup d'embouteillages" }, themes: ["taxi"] },
      { id: "w:ทางลัด", thai: "ทางลัด", rom: "thaang-lát", meaning: { fr: "raccourci" }, themes: ["taxi"] },
      { id: "w:ค่าทางด่วน", thai: "ค่าทางด่วน", rom: "khâa thaang-dùan", meaning: { fr: "péage de la voie express" }, themes: ["taxi"] },
      { id: "w:สุดซอย", thai: "สุดซอย", rom: "sùt sɔɔi", meaning: { fr: "au bout de la ruelle" }, themes: ["taxi"] },
      { id: "w:ปากซอย", thai: "ปากซอย", rom: "pàak sɔɔi", meaning: { fr: "à l'entrée de la ruelle" }, themes: ["taxi"] },
      { id: "w:ฝั่งตรงข้าม", thai: "ฝั่งตรงข้าม", rom: "fàng trong-khâam", meaning: { fr: "de l'autre côté de la rue" }, themes: ["taxi"] },
    ],
  },
  {
    id: "grab", name: { fr: "Grab" }, icon: "📱",
    items: [
      { id: "w:เรียกรถ", thai: "เรียกรถ", rom: "rîak rót", meaning: { fr: "commander une voiture" }, themes: ["grab"] },
      { id: "w:คนขับ", thai: "คนขับ", rom: "khon-khàp", meaning: { fr: "chauffeur" }, themes: ["grab"] },
      { id: "w:{I}เรียกรถแล้ว", thai: "{I}เรียกรถแล้ว", rom: "{i} rîak rót lɛ́ɛo", meaning: { fr: "j'ai commandé une voiture" }, themes: ["grab"] },
      { id: "w:คุณอยู่ที่ไหน{Q}", thai: "คุณอยู่ที่ไหน{Q}", rom: "khun yùu thîi-nǎi {q}", meaning: { fr: "où êtes-vous ?" }, themes: ["grab"] },
      { id: "w:{I}อยู่หน้าโรงแรม", thai: "{I}อยู่หน้าโรงแรม", rom: "{i} yùu nâa roong-rɛɛm", meaning: { fr: "je suis devant l'hôtel" }, themes: ["grab"] },
      { id: "w:รอสักครู่{P}", thai: "รอสักครู่{P}", rom: "rɔɔ sàk-khrûu {p}", meaning: { fr: "attendez un instant" }, themes: ["grab"] },
      { id: "w:อีกห้านาทีถึง", thai: "อีกห้านาทีถึง", rom: "ìik hâa naa-thii thʉ̌ng", meaning: { fr: "j'arrive dans cinq minutes" }, themes: ["grab"] },
      { id: "w:ทะเบียนรถ", thai: "ทะเบียนรถ", rom: "thá-bian rót", meaning: { fr: "plaque d'immatriculation" }, themes: ["grab"] },
      { id: "w:จุดรับ", thai: "จุดรับ", rom: "jùt-ráp", meaning: { fr: "point de prise en charge" }, themes: ["grab"] },
      { id: "w:ปลายทาง", thai: "ปลายทาง", rom: "plaai-thaang", meaning: { fr: "destination" }, themes: ["grab"] },
      { id: "w:จ่ายเงินสด", thai: "จ่ายเงินสด", rom: "jàai ngən-sòt", meaning: { fr: "payer en espèces" }, themes: ["grab"] },
      { id: "w:จ่ายด้วยบัตร", thai: "จ่ายด้วยบัตร", rom: "jàai dûai bàt", meaning: { fr: "payer par carte" }, themes: ["grab"] },
      { id: "w:ยกเลิก", thai: "ยกเลิก", rom: "yók-lə̂ək", meaning: { fr: "annuler" }, themes: ["grab"] },
    ],
  },
  {
    id: "hotel", name: { fr: "Hôtel" }, icon: "🏨",
    items: [
      { id: "w:ห้อง", thai: "ห้อง", rom: "hɔ̂ng", meaning: { fr: "chambre ; pièce" }, themes: ["hotel"] },
      { id: "w:จองห้อง", thai: "จองห้อง", rom: "jɔɔng hɔ̂ng", meaning: { fr: "réserver une chambre" }, themes: ["hotel"] },
      { id: "w:{I}จองห้องไว้แล้ว", thai: "{I}จองห้องไว้แล้ว", rom: "{i} jɔɔng hɔ̂ng wái lɛ́ɛo", meaning: { fr: "j'ai une réservation" }, themes: ["hotel"] },
      { id: "w:เช็กอิน", thai: "เช็กอิน", rom: "chék-in", meaning: { fr: "faire le check-in" }, themes: ["hotel"] },
      { id: "w:คืนห้อง", thai: "คืนห้อง", rom: "khʉʉn hɔ̂ng", meaning: { fr: "rendre la chambre" }, themes: ["hotel"] },
      { id: "w:กุญแจ", thai: "กุญแจ", rom: "kun-jɛɛ", meaning: { fr: "clé" }, themes: ["hotel"] },
      { id: "w:ลิฟต์", thai: "ลิฟต์", rom: "líp", meaning: { fr: "ascenseur" }, themes: ["hotel"] },
      { id: "w:ชั้น", thai: "ชั้น", rom: "chán", meaning: { fr: "étage" }, themes: ["hotel"], example: { thai: "ชั้นสาม", rom: "chán sǎam", meaning: { fr: "troisième niveau" } } },
      { id: "w:อาหารเช้า", thai: "อาหารเช้า", rom: "aa-hǎan cháao", meaning: { fr: "petit déjeuner" }, themes: ["hotel"], example: { thai: "มีอาหารเช้าไหม{Q}", rom: "mii aa-hǎan cháao mái {q}", meaning: { fr: "y a-t-il un petit déjeuner ?" } } },
      { id: "w:ไวไฟ", thai: "ไวไฟ", rom: "waai-faai", meaning: { fr: "wifi" }, themes: ["hotel"], example: { thai: "รหัสไวไฟอะไร{Q}", rom: "rá-hàt waai-faai à-rai {q}", meaning: { fr: "quel est le mot de passe du wifi ?" } } },
      { id: "w:แอร์", thai: "แอร์", rom: "ɛɛ", meaning: { fr: "climatisation" }, themes: ["hotel"], example: { thai: "แอร์เสีย", rom: "ɛɛ sǐa", meaning: { fr: "la climatisation est en panne" } } },
      { id: "w:ผ้าเช็ดตัว", thai: "ผ้าเช็ดตัว", rom: "phâa-chét-tua", meaning: { fr: "serviette de bain" }, themes: ["hotel"] },
      { id: "w:กี่คืน{Q}", thai: "กี่คืน{Q}", rom: "kìi khʉʉn {q}", meaning: { fr: "combien de nuits ?" }, themes: ["hotel"] },
      { id: "w:สองคืน", thai: "สองคืน", rom: "sɔ̌ɔng khʉʉn", meaning: { fr: "deux nuits" }, themes: ["hotel"] },
      { id: "w:ฝากกระเป๋า", thai: "ฝากกระเป๋า", rom: "fàak krà-pǎo", meaning: { fr: "laisser ses bagages" }, themes: ["hotel"] },
      { id: "w:ห้องเงียบ", thai: "ห้องเงียบ", rom: "hɔ̂ng ngîap", meaning: { fr: "chambre calme" }, themes: ["hotel"] },
    ],
  },
  {
    id: "home", name: { fr: "Maison" }, icon: "🏠",
    items: [
      { id: "w:บ้าน", thai: "บ้าน", rom: "bâan", meaning: { fr: "maison" }, themes: ["home"], example: { thai: "บ้าน{I}อยู่ใกล้ที่นี่", rom: "bâan {i} yùu klâi thîi-nîi", meaning: { fr: "ma maison est près d'ici" } } },
      { id: "w:ห้องนอน", thai: "ห้องนอน", rom: "hɔ̂ng-nɔɔn", meaning: { fr: "chambre à coucher" }, themes: ["home"] },
      { id: "w:ห้องน้ำ", thai: "ห้องน้ำ", rom: "hɔ̂ng-náam", meaning: { fr: "salle de bain ; toilettes" }, themes: ["home"] },
      { id: "w:ห้องครัว", thai: "ห้องครัว", rom: "hɔ̂ng-khrua", meaning: { fr: "cuisine" }, themes: ["home"] },
      { id: "w:ประตู", thai: "ประตู", rom: "prà-tuu", meaning: { fr: "porte" }, themes: ["home"] },
      { id: "w:หน้าต่าง", thai: "หน้าต่าง", rom: "nâa-tàang", meaning: { fr: "fenêtre" }, themes: ["home"] },
      { id: "w:โต๊ะ", thai: "โต๊ะ", rom: "tó", meaning: { fr: "table" }, themes: ["home"] },
      { id: "w:เก้าอี้", thai: "เก้าอี้", rom: "kâo-îi", meaning: { fr: "chaise" }, themes: ["home"] },
      { id: "w:เตียง", thai: "เตียง", rom: "tiang", meaning: { fr: "lit" }, themes: ["home"] },
      { id: "w:ตู้เย็น", thai: "ตู้เย็น", rom: "tûu-yen", meaning: { fr: "réfrigérateur" }, themes: ["home"] },
      { id: "w:ไฟ", thai: "ไฟ", rom: "fai", meaning: { fr: "lumière ; électricité ; feu" }, themes: ["home"] },
      { id: "w:พัดลม", thai: "พัดลม", rom: "phát-lom", meaning: { fr: "ventilateur" }, themes: ["home"] },
      { id: "w:บันได", thai: "บันได", rom: "ban-dai", meaning: { fr: "escalier" }, themes: ["home"] },
      { id: "w:หลังคา", thai: "หลังคา", rom: "lǎng-khaa", meaning: { fr: "toit" }, themes: ["home"] },
      { id: "w:สวน", thai: "สวน", rom: "sǔan", meaning: { fr: "jardin" }, themes: ["home"] },
      { id: "w:คอนโด", thai: "คอนโด", rom: "khɔɔn-doo", meaning: { fr: "appartement (condo)" }, themes: ["home"] },
    ],
  },
  {
    id: "work", name: { fr: "Travail" }, icon: "💼",
    items: [
      { id: "w:งาน", thai: "งาน", rom: "ngaan", meaning: { fr: "travail" }, themes: ["work"] },
      { id: "w:ทำงาน", thai: "ทำงาน", rom: "tham-ngaan", meaning: { fr: "travailler" }, themes: ["work"], example: { thai: "วันนี้{I}ต้องทำงาน", rom: "wan-níi {i} tɔ̂ng tham-ngaan", meaning: { fr: "aujourd'hui je dois travailler" } } },
      { id: "w:บริษัท", thai: "บริษัท", rom: "bɔɔ-rí-sàt", meaning: { fr: "entreprise" }, themes: ["work"] },
      { id: "w:สำนักงาน", thai: "สำนักงาน", rom: "sǎm-nák-ngaan", meaning: { fr: "bureau (lieu)" }, themes: ["work"] },
      { id: "w:เพื่อนร่วมงาน", thai: "เพื่อนร่วมงาน", rom: "phʉ̂an-rûam-ngaan", meaning: { fr: "collègue" }, themes: ["work"] },
      { id: "w:หัวหน้า", thai: "หัวหน้า", rom: "hǔa-nâa", meaning: { fr: "chef, responsable" }, themes: ["work"] },
      { id: "w:ลูกค้า", thai: "ลูกค้า", rom: "lûuk-kháa", meaning: { fr: "client" }, themes: ["work"] },
      { id: "w:ประชุม", thai: "ประชุม", rom: "prà-chum", meaning: { fr: "réunion ; se réunir" }, themes: ["work"], example: { thai: "พรุ่งนี้มีประชุม", rom: "phrûng-níi mii prà-chum", meaning: { fr: "demain il y a une réunion" } } },
      { id: "w:โครงการ", thai: "โครงการ", rom: "khroong-kaan", meaning: { fr: "projet" }, themes: ["work"] },
      { id: "w:เอกสาร", thai: "เอกสาร", rom: "èek-kà-sǎan", meaning: { fr: "document" }, themes: ["work"] },
      { id: "w:คอมพิวเตอร์", thai: "คอมพิวเตอร์", rom: "khɔm-phíu-tə̂ə", meaning: { fr: "ordinateur" }, themes: ["work"] },
      { id: "w:เงินเดือน", thai: "เงินเดือน", rom: "ngən-dʉan", meaning: { fr: "salaire" }, themes: ["work"] },
      { id: "w:ยุ่ง", thai: "ยุ่ง", rom: "yûng", meaning: { fr: "occupé" }, themes: ["work"], example: { thai: "วันนี้{I}ยุ่งมาก", rom: "wan-níi {i} yûng mâak", meaning: { fr: "je suis très occupé aujourd'hui" } } },
      { id: "w:เสร็จแล้ว", thai: "เสร็จแล้ว", rom: "sèt lɛ́ɛo", meaning: { fr: "c'est terminé" }, themes: ["work"] },
      { id: "w:กำหนดส่ง", thai: "กำหนดส่ง", rom: "kam-nòt sòng", meaning: { fr: "échéance de remise" }, themes: ["work"] },
    ],
  },
  {
    id: "eng", name: { fr: "Ingénieur structure" }, icon: "🏗️",
    items: [
      { id: "w:วิศวกร", thai: "วิศวกร", rom: "wít-sà-wá-kɔɔn", meaning: { fr: "ingénieur" }, themes: ["eng"] },
      { id: "w:วิศวกรโครงสร้าง", thai: "วิศวกรโครงสร้าง", rom: "wít-sà-wá-kɔɔn khroong-sâang", meaning: { fr: "ingénieur en structure" }, themes: ["eng"], example: { thai: "{I}เป็นวิศวกรโครงสร้าง", rom: "{i} pen wít-sà-wá-kɔɔn khroong-sâang", meaning: { fr: "je suis ingénieur en structure" } } },
      { id: "w:วิศวกรโยธา", thai: "วิศวกรโยธา", rom: "wít-sà-wá-kɔɔn yoo-thaa", meaning: { fr: "ingénieur civil" }, themes: ["eng"] },
      { id: "w:โครงสร้าง", thai: "โครงสร้าง", rom: "khroong-sâang", meaning: { fr: "structure" }, themes: ["eng"] },
      { id: "w:ก่อสร้าง", thai: "ก่อสร้าง", rom: "kɔ̀ɔ-sâang", meaning: { fr: "construire ; construction" }, themes: ["eng"] },
      { id: "w:สถานที่ก่อสร้าง", thai: "สถานที่ก่อสร้าง", rom: "sà-thǎan-thîi kɔ̀ɔ-sâang", meaning: { fr: "chantier" }, themes: ["eng"] },
      { id: "w:หน้างาน", thai: "หน้างาน", rom: "nâa-ngaan", meaning: { fr: "sur place, sur le chantier" }, themes: ["eng"], example: { thai: "พรุ่งนี้{I}จะไปหน้างาน", rom: "phrûng-níi {i} jà pai nâa-ngaan", meaning: { fr: "demain j'irai sur le chantier" } } },
      { id: "w:อาคาร", thai: "อาคาร", rom: "aa-khaan", meaning: { fr: "bâtiment" }, themes: ["eng"] },
      { id: "w:ตึก", thai: "ตึก", rom: "tʉ̀k", meaning: { fr: "immeuble" }, themes: ["eng"] },
      { id: "w:คอนกรีต", thai: "คอนกรีต", rom: "khɔɔn-krìit", meaning: { fr: "béton" }, themes: ["eng"] },
      { id: "w:คอนกรีตเสริมเหล็ก", thai: "คอนกรีตเสริมเหล็ก", rom: "khɔɔn-krìit sə̌əm lèk", meaning: { fr: "béton armé" }, themes: ["eng"] },
      { id: "w:เหล็ก", thai: "เหล็ก", rom: "lèk", meaning: { fr: "acier, fer" }, themes: ["eng"] },
      { id: "w:เหล็กเสริม", thai: "เหล็กเสริม", rom: "lèk-sə̌əm", meaning: { fr: "armatures" }, themes: ["eng"] },
      { id: "w:เสา", thai: "เสา", rom: "sǎo", meaning: { fr: "colonne, poteau" }, themes: ["eng"], example: { thai: "เสาต้นนี้มีรอยร้าว", rom: "sǎo tôn níi mii rɔɔi-ráao", meaning: { fr: "ce poteau a une fissure" } } },
      { id: "w:คาน", thai: "คาน", rom: "khaan", meaning: { fr: "poutre" }, themes: ["eng"], example: { thai: "คานนี้รับน้ำหนักได้เท่าไหร่{Q}", rom: "khaan níi ráp náam-nàk dâai thâo-rài {q}", meaning: { fr: "quelle charge cette poutre peut-elle reprendre ?" } } },
      { id: "w:พื้น", thai: "พื้น", rom: "phʉ́ʉn", meaning: { fr: "dalle, plancher" }, themes: ["eng"] },
      { id: "w:ผนัง", thai: "ผนัง", rom: "phà-nǎng", meaning: { fr: "mur, paroi" }, themes: ["eng"] },
      { id: "w:กำแพง", thai: "กำแพง", rom: "kam-phɛɛng", meaning: { fr: "mur d'enceinte" }, themes: ["eng"] },
      { id: "w:ฐานราก", thai: "ฐานราก", rom: "thǎan-râak", meaning: { fr: "fondation" }, themes: ["eng"] },
      { id: "w:เสาเข็ม", thai: "เสาเข็ม", rom: "sǎo-khěm", meaning: { fr: "pieu" }, themes: ["eng"] },
      { id: "w:แบบ", thai: "แบบ", rom: "bɛ̀ɛp", meaning: { fr: "plan, dessin" }, themes: ["eng"], example: { thai: "ขอดูแบบหน่อย{P}", rom: "khɔ̌ɔ duu bɛ̀ɛp nɔ̀i {p}", meaning: { fr: "puis-je voir les plans ?" } } },
      { id: "w:แบบก่อสร้าง", thai: "แบบก่อสร้าง", rom: "bɛ̀ɛp kɔ̀ɔ-sâang", meaning: { fr: "plans d'exécution" }, themes: ["eng"] },
      { id: "w:เขียนแบบ", thai: "เขียนแบบ", rom: "khǐan bɛ̀ɛp", meaning: { fr: "dessiner des plans" }, themes: ["eng"] },
      { id: "w:คำนวณ", thai: "คำนวณ", rom: "kham-nuan", meaning: { fr: "calculer ; calcul" }, themes: ["eng"], example: { thai: "ต้องคำนวณใหม่", rom: "tɔ̂ng kham-nuan mài", meaning: { fr: "il faut recalculer" } } },
      { id: "w:รายการคำนวณ", thai: "รายการคำนวณ", rom: "raai-kaan kham-nuan", meaning: { fr: "note de calcul" }, themes: ["eng"] },
      { id: "w:น้ำหนัก", thai: "น้ำหนัก", rom: "náam-nàk", meaning: { fr: "poids ; charge" }, themes: ["eng"] },
      { id: "w:น้ำหนักบรรทุก", thai: "น้ำหนักบรรทุก", rom: "náam-nàk ban-thúk", meaning: { fr: "charge appliquée" }, themes: ["eng"] },
      { id: "w:รับน้ำหนัก", thai: "รับน้ำหนัก", rom: "ráp náam-nàk", meaning: { fr: "reprendre une charge" }, themes: ["eng"] },
      { id: "w:แรง", thai: "แรง", rom: "rɛɛng", meaning: { fr: "force ; fort" }, themes: ["eng"] },
      { id: "w:ขนาด", thai: "ขนาด", rom: "khà-nàat", meaning: { fr: "dimensions, taille" }, themes: ["eng"] },
      { id: "w:ความยาว", thai: "ความยาว", rom: "khwaam-yaao", meaning: { fr: "longueur" }, themes: ["eng"] },
      { id: "w:ความกว้าง", thai: "ความกว้าง", rom: "khwaam-kwâang", meaning: { fr: "largeur" }, themes: ["eng"] },
      { id: "w:ความสูง", thai: "ความสูง", rom: "khwaam-sǔung", meaning: { fr: "hauteur" }, themes: ["eng"] },
      { id: "w:ความหนา", thai: "ความหนา", rom: "khwaam-nǎa", meaning: { fr: "épaisseur" }, themes: ["eng"] },
      { id: "w:วัสดุ", thai: "วัสดุ", rom: "wát-sà-dù", meaning: { fr: "matériau" }, themes: ["eng"] },
      { id: "w:รอยร้าว", thai: "รอยร้าว", rom: "rɔɔi-ráao", meaning: { fr: "fissure" }, themes: ["eng"] },
      { id: "w:แข็งแรง", thai: "แข็งแรง", rom: "khɛ̌ng-rɛɛng", meaning: { fr: "solide, résistant" }, themes: ["eng"] },
      { id: "w:ปัญหา", thai: "ปัญหา", rom: "pan-hǎa", meaning: { fr: "problème" }, themes: ["eng"], example: { thai: "มีปัญหาอะไร{Q}", rom: "mii pan-hǎa à-rai {q}", meaning: { fr: "quel est le problème ?" } } },
      { id: "w:ความปลอดภัย", thai: "ความปลอดภัย", rom: "khwaam plɔ̀ɔt-phai", meaning: { fr: "sécurité" }, themes: ["eng"] },
      { id: "w:หมวกนิรภัย", thai: "หมวกนิรภัย", rom: "mùak ní-rá-phai", meaning: { fr: "casque de sécurité" }, themes: ["eng"] },
      { id: "w:ตรวจสอบ", thai: "ตรวจสอบ", rom: "trùat-sɔ̀ɔp", meaning: { fr: "inspecter, vérifier" }, themes: ["eng"] },
      { id: "w:เทคอนกรีต", thai: "เทคอนกรีต", rom: "thee khɔɔn-krìit", meaning: { fr: "couler le béton" }, themes: ["eng"] },
      { id: "w:ผู้รับเหมา", thai: "ผู้รับเหมา", rom: "phûu-ráp-mǎo", meaning: { fr: "entrepreneur" }, themes: ["eng"] },
      { id: "w:สถาปนิก", thai: "สถาปนิก", rom: "sà-thǎa-pà-ník", meaning: { fr: "architecte" }, themes: ["eng"] },
      { id: "w:นั่งร้าน", thai: "นั่งร้าน", rom: "nâng-ráan", meaning: { fr: "échafaudage" }, themes: ["eng"] },
      { id: "w:รถขุด", thai: "รถขุด", rom: "rót khùt", meaning: { fr: "pelleteuse" }, themes: ["eng"] },
      { id: "w:ปูน", thai: "ปูน", rom: "puun", meaning: { fr: "ciment ; mortier" }, themes: ["eng"] },
      { id: "w:ทราย", thai: "ทราย", rom: "saai", meaning: { fr: "sable" }, themes: ["eng"] },
      { id: "w:หิน", thai: "หิน", rom: "hǐn", meaning: { fr: "pierre ; gravier" }, themes: ["eng"] },
      { id: "w:อิฐ", thai: "อิฐ", rom: "ìt", meaning: { fr: "brique" }, themes: ["eng"] },
      { id: "w:ไม้แบบ", thai: "ไม้แบบ", rom: "máai bɛ̀ɛp", meaning: { fr: "coffrage (bois)" }, themes: ["eng"] },
      { id: "w:ระดับ", thai: "ระดับ", rom: "rá-dàp", meaning: { fr: "niveau (altitude)" }, themes: ["eng"] },
      { id: "w:แนวดิ่ง", thai: "แนวดิ่ง", rom: "nɛɛo dìng", meaning: { fr: "aplomb, verticale" }, themes: ["eng"] },
      { id: "w:ไม้", thai: "ไม้", rom: "máai", meaning: { fr: "bois" }, themes: ["eng"] },
      { id: "w:ตะปู", thai: "ตะปู", rom: "tà-puu", meaning: { fr: "clou" }, themes: ["eng"] },
      { id: "w:ค้อน", thai: "ค้อน", rom: "khɔ́ɔn", meaning: { fr: "marteau" }, themes: ["eng"] },
      { id: "w:สว่าน", thai: "สว่าน", rom: "sà-wàan", meaning: { fr: "perceuse" }, themes: ["eng"] },
      { id: "w:เพดาน", thai: "เพดาน", rom: "phee-daan", meaning: { fr: "plafond" }, themes: ["eng"] },
      { id: "w:ปลอดภัย", thai: "ปลอดภัย", rom: "plɔ̀ɔt-phai", meaning: { fr: "sûr, en sécurité" }, themes: ["eng"] },
      { id: "w:ซ่อม", thai: "ซ่อม", rom: "sɔ̂m", meaning: { fr: "réparer" }, themes: ["eng"] },
      { id: "w:ล่าช้า", thai: "ล่าช้า", rom: "lâa-cháa", meaning: { fr: "en retard (sur le planning)" }, themes: ["eng"] },
      { id: "w:งบประมาณ", thai: "งบประมาณ", rom: "ngóp-prà-maan", meaning: { fr: "budget" }, themes: ["eng"] },
      { id: "w:สัญญา", thai: "สัญญา", rom: "sǎn-yaa", meaning: { fr: "contrat" }, themes: ["eng"] },
      { id: "w:เจ้าของ", thai: "เจ้าของ", rom: "jâo-khɔ̌ɔng", meaning: { fr: "propriétaire" }, themes: ["eng"] },
      { id: "w:ช่าง", thai: "ช่าง", rom: "châang", meaning: { fr: "ouvrier qualifié, technicien" }, themes: ["eng"] },
      { id: "w:คนงาน", thai: "คนงาน", rom: "khon-ngaan", meaning: { fr: "ouvrier" }, themes: ["eng"] },
      { id: "w:รถปูน", thai: "รถปูน", rom: "rót puun", meaning: { fr: "camion-toupie" }, themes: ["eng"] },
      { id: "w:ตรงนี้ไม่ปลอดภัย", thai: "ตรงนี้ไม่ปลอดภัย", rom: "trong-níi mâi plɔ̀ɔt-phai", meaning: { fr: "ici, ce n'est pas sûr" }, themes: ["eng"] },
      { id: "w:ต้องซ่อมก่อน", thai: "ต้องซ่อมก่อน", rom: "tɔ̂ng sɔ̂m kɔ̀ɔn", meaning: { fr: "il faut d'abord réparer" }, themes: ["eng"] },
      { id: "w:งานเสร็จเมื่อไหร่{Q}", thai: "งานเสร็จเมื่อไหร่{Q}", rom: "ngaan sèt mʉ̂a-rài {q}", meaning: { fr: "quand le travail sera-t-il fini ?" }, themes: ["eng"] },
      { id: "w:ขอวัดอีกครั้ง{P}", thai: "ขอวัดอีกครั้ง{P}", rom: "khɔ̌ɔ wát ìik khráng {p}", meaning: { fr: "je voudrais remesurer" }, themes: ["eng"] },
    ],
  },
  {
    id: "health", name: { fr: "Santé" }, icon: "🩺",
    items: [
      { id: "w:สุขภาพ", thai: "สุขภาพ", rom: "sùk-khà-phâap", meaning: { fr: "santé" }, themes: ["health"] },
      { id: "w:ไม่สบาย", thai: "ไม่สบาย", rom: "mâi sà-baai", meaning: { fr: "ne pas se sentir bien" }, themes: ["health"], example: { thai: "{I}ไม่สบาย", rom: "{i} mâi sà-baai", meaning: { fr: "je ne me sens pas bien" } } },
      { id: "w:ป่วย", thai: "ป่วย", rom: "pùai", meaning: { fr: "malade" }, themes: ["health"] },
      { id: "w:ปวดหัว", thai: "ปวดหัว", rom: "pùat-hǔa", meaning: { fr: "mal de tête" }, themes: ["health"] },
      { id: "w:ปวดท้อง", thai: "ปวดท้อง", rom: "pùat-thɔ́ɔng", meaning: { fr: "mal de ventre" }, themes: ["health"] },
      { id: "w:เป็นไข้", thai: "เป็นไข้", rom: "pen khâi", meaning: { fr: "avoir de la fièvre" }, themes: ["health"] },
      { id: "w:เป็นหวัด", thai: "เป็นหวัด", rom: "pen wàt", meaning: { fr: "avoir un rhume" }, themes: ["health"] },
      { id: "w:ไอ", thai: "ไอ", rom: "ai", meaning: { fr: "tousser" }, themes: ["health"] },
      { id: "w:เจ็บ", thai: "เจ็บ", rom: "jèp", meaning: { fr: "avoir mal" }, themes: ["health"], example: { thai: "เจ็บตรงนี้", rom: "jèp trong-níi", meaning: { fr: "j'ai mal ici" } } },
      { id: "w:แพ้", thai: "แพ้", rom: "phɛ́ɛ", meaning: { fr: "être allergique à" }, themes: ["health"], example: { thai: "{I}แพ้กุ้ง", rom: "{i} phɛ́ɛ kûng", meaning: { fr: "je suis allergique aux crevettes" } } },
      { id: "w:ยา", thai: "ยา", rom: "yaa", meaning: { fr: "médicament" }, themes: ["health"] },
      { id: "w:ร้านขายยา", thai: "ร้านขายยา", rom: "ráan-khǎai-yaa", meaning: { fr: "pharmacie" }, themes: ["health"] },
      { id: "w:เหนื่อย", thai: "เหนื่อย", rom: "nʉ̀ai", meaning: { fr: "fatigué" }, themes: ["health"] },
      { id: "w:พักผ่อน", thai: "พักผ่อน", rom: "phák-phɔ̀n", meaning: { fr: "se reposer" }, themes: ["health"] },
      { id: "w:ดีขึ้นแล้ว", thai: "ดีขึ้นแล้ว", rom: "dii khʉ̂n lɛ́ɛo", meaning: { fr: "ça va mieux" }, themes: ["health"] },
      { id: "w:ยาแก้ปวด", thai: "ยาแก้ปวด", rom: "yaa kɛ̂ɛ pùat", meaning: { fr: "antidouleur" }, themes: ["health"] },
      { id: "w:ยาแก้ไอ", thai: "ยาแก้ไอ", rom: "yaa kɛ̂ɛ ai", meaning: { fr: "médicament contre la toux" }, themes: ["health"] },
      { id: "w:เม็ด", thai: "เม็ด", rom: "mét", meaning: { fr: "comprimé (classificateur)" }, themes: ["health"] },
      { id: "w:หลังอาหาร", thai: "หลังอาหาร", rom: "lǎng aa-hǎan", meaning: { fr: "après le repas" }, themes: ["health"] },
      { id: "w:ก่อนอาหาร", thai: "ก่อนอาหาร", rom: "kɔ̀ɔn aa-hǎan", meaning: { fr: "avant le repas" }, themes: ["health"] },
      { id: "w:วันละสามครั้ง", thai: "วันละสามครั้ง", rom: "wan lá sǎam khráng", meaning: { fr: "trois fois par jour" }, themes: ["health"] },
      { id: "w:เวียนหัว", thai: "เวียนหัว", rom: "wian-hǔa", meaning: { fr: "avoir le vertige" }, themes: ["health"] },
      { id: "w:ท้องเสีย", thai: "ท้องเสีย", rom: "thɔ́ɔng-sǐa", meaning: { fr: "avoir la diarrhée" }, themes: ["health"] },
      { id: "w:คลื่นไส้", thai: "คลื่นไส้", rom: "khlʉ̂ʉn-sâi", meaning: { fr: "avoir la nausée" }, themes: ["health"] },
      { id: "w:แผล", thai: "แผล", rom: "phlɛ̌ɛ", meaning: { fr: "plaie" }, themes: ["health"] },
      { id: "w:หายแล้ว", thai: "หายแล้ว", rom: "hǎai lɛ́ɛo", meaning: { fr: "guéri" }, themes: ["health"] },
    ],
  },
  {
    id: "hosp", name: { fr: "Hôpital" }, icon: "🏥",
    items: [
      { id: "w:โรงพยาบาล", thai: "โรงพยาบาล", rom: "roong-phá-yaa-baan", meaning: { fr: "hôpital" }, themes: ["hosp"] },
      { id: "w:{I}มาเยี่ยมคนไข้", thai: "{I}มาเยี่ยมคนไข้", rom: "{i} maa yîam khon-khâi", meaning: { fr: "je viens rendre visite à un patient" }, themes: ["hosp"] },
      { id: "w:{I}มาเยี่ยมเพื่อน", thai: "{I}มาเยี่ยมเพื่อน", rom: "{i} maa yîam phʉ̂an", meaning: { fr: "je viens voir un ami" }, themes: ["hosp"] },
      { id: "w:{I}มาหาคนนี้", thai: "{I}มาหาคนนี้", rom: "{i} maa hǎa khon níi", meaning: { fr: "je cherche cette personne (en montrant son nom)" }, themes: ["hosp"] },
      { id: "w:คนไข้ชื่อ...", thai: "คนไข้ชื่อ...", rom: "khon-khâi chʉ̂ʉ ...", meaning: { fr: "le patient s'appelle…" }, themes: ["hosp"] },
      { id: "w:ห้องอยู่ที่ไหน{Q}", thai: "ห้องอยู่ที่ไหน{Q}", rom: "hɔ̂ng yùu thîi-nǎi {q}", meaning: { fr: "où se trouve la chambre ?" }, themes: ["hosp"] },
      { id: "w:ห้องเบอร์อะไร{Q}", thai: "ห้องเบอร์อะไร{Q}", rom: "hɔ̂ng bəə à-rai {q}", meaning: { fr: "quel est le numéro de la chambre ?" }, themes: ["hosp"] },
      { id: "w:ชั้นไหน{Q}", thai: "ชั้นไหน{Q}", rom: "chán nǎi {q}", meaning: { fr: "à quel étage ?" }, themes: ["hosp"] },
      { id: "w:ประชาสัมพันธ์อยู่ที่ไหน{Q}", thai: "ประชาสัมพันธ์อยู่ที่ไหน{Q}", rom: "prà-chaa-sǎm-phan yùu thîi-nǎi {q}", meaning: { fr: "où est l'accueil (bureau d'information) ?" }, themes: ["hosp"] },
      { id: "w:เยี่ยมได้ไหม{Q}", thai: "เยี่ยมได้ไหม{Q}", rom: "yîam dâai mái {q}", meaning: { fr: "peut-on lui rendre visite ?" }, themes: ["hosp"] },
      { id: "w:เวลาเยี่ยมกี่โมง{Q}", thai: "เวลาเยี่ยมกี่โมง{Q}", rom: "wee-laa yîam kìi moong {q}", meaning: { fr: "quelles sont les heures de visite ?" }, themes: ["hosp"] },
      { id: "w:ลิฟต์อยู่ที่ไหน{Q}", thai: "ลิฟต์อยู่ที่ไหน{Q}", rom: "líp yùu thîi-nǎi {q}", meaning: { fr: "où est l'ascenseur ?" }, themes: ["hosp"] },
      { id: "w:อาการเป็นอย่างไรบ้าง{Q}", thai: "อาการเป็นอย่างไรบ้าง{Q}", rom: "aa-kaan pen yàang-rai bâang {q}", meaning: { fr: "comment va son état ?" }, themes: ["hosp"] },
      { id: "w:ขอให้หายเร็วๆ", thai: "ขอให้หายเร็วๆ", rom: "khɔ̌ɔ hâi hǎai reo-reo", meaning: { fr: "bon rétablissement" }, themes: ["hosp"] },
      { id: "w:หมอ", thai: "หมอ", rom: "mɔ̌ɔ", meaning: { fr: "médecin" }, themes: ["hosp"] },
      { id: "w:พยาบาล", thai: "พยาบาล", rom: "phá-yaa-baan", meaning: { fr: "infirmier, infirmière" }, themes: ["hosp"] },
      { id: "w:คนไข้", thai: "คนไข้", rom: "khon-khâi", meaning: { fr: "patient" }, themes: ["hosp"] },
      { id: "w:ปวด", thai: "ปวด", rom: "pùat", meaning: { fr: "avoir mal, douleur" }, themes: ["hosp"] },
      { id: "w:ฉุกเฉิน", thai: "ฉุกเฉิน", rom: "chùk-chə̌ən", meaning: { fr: "urgence" }, themes: ["hosp"] },
      { id: "w:ห้องฉุกเฉิน", thai: "ห้องฉุกเฉิน", rom: "hɔ̂ng chùk-chə̌ən", meaning: { fr: "service des urgences" }, themes: ["hosp"] },
      { id: "w:ผ่าตัด", thai: "ผ่าตัด", rom: "phàa-tàt", meaning: { fr: "opération (chirurgie)" }, themes: ["hosp"] },
      { id: "w:ไอซียู", thai: "ไอซียู", rom: "ai-sii-yuu", meaning: { fr: "soins intensifs" }, themes: ["hosp"] },
      { id: "w:ประกัน", thai: "ประกัน", rom: "prà-kan", meaning: { fr: "assurance" }, themes: ["hosp"] },
      { id: "w:ดอกไม้", thai: "ดอกไม้", rom: "dɔ̀ɔk-máai", meaning: { fr: "fleurs" }, themes: ["hosp"] },
      { id: "w:ของเยี่ยม", thai: "ของเยี่ยม", rom: "khɔ̌ɔng-yîam", meaning: { fr: "cadeau de visite" }, themes: ["hosp"] },
      { id: "w:ผู้ป่วย", thai: "ผู้ป่วย", rom: "phûu-pùai", meaning: { fr: "patient" }, themes: ["hosp"] },
      { id: "w:ญาติ", thai: "ญาติ", rom: "yâat", meaning: { fr: "proche, membre de la famille" }, themes: ["hosp"] },
      { id: "w:แผนก", thai: "แผนก", rom: "phà-nɛ̀ɛk", meaning: { fr: "service (d'un hôpital)" }, themes: ["hosp"] },
      { id: "w:พักฟื้น", thai: "พักฟื้น", rom: "phák-fʉ́ʉn", meaning: { fr: "convalescence ; se remettre" }, themes: ["hosp"] },
      { id: "w:เป็นยังไงบ้าง", thai: "เป็นยังไงบ้าง", rom: "pen yang-ngai bâang", meaning: { fr: "comment ça va ? (état)" }, themes: ["hosp"] },
      { id: "w:ดีขึ้นไหม", thai: "ดีขึ้นไหม", rom: "dii-khʉ̂n mái", meaning: { fr: "ça va mieux ?" }, themes: ["hosp"] },
      { id: "w:ต้องอยู่โรงพยาบาลกี่วัน{Q}", thai: "ต้องอยู่โรงพยาบาลกี่วัน{Q}", rom: "tɔ̂ng yùu roong-phá-yaa-baan kìi wan {q}", meaning: { fr: "combien de jours doit-il rester à l'hôpital ?" }, themes: ["hosp"] },
      { id: "w:ออกจากโรงพยาบาลเมื่อไหร่{Q}", thai: "ออกจากโรงพยาบาลเมื่อไหร่{Q}", rom: "ɔ̀ɔk jàak roong-phá-yaa-baan mʉ̂a-rài {q}", meaning: { fr: "quand sort-il de l'hôpital ?" }, themes: ["hosp"] },
      { id: "w:ต้องการอะไรไหม", thai: "ต้องการอะไรไหม", rom: "tɔ̂ng-kaan à-rai mái", meaning: { fr: "as-tu besoin de quelque chose ?" }, themes: ["hosp"] },
      { id: "w:เดี๋ยว{I}มาใหม่นะ", thai: "เดี๋ยว{I}มาใหม่นะ", rom: "dǐao {i} maa mài ná", meaning: { fr: "je reviens bientôt" }, themes: ["hosp"] },
      { id: "w:พักผ่อนเยอะๆ นะ", thai: "พักผ่อนเยอะๆ นะ", rom: "phák-phɔ̀n yə́-yə́ ná", meaning: { fr: "repose-toi bien" }, themes: ["hosp"] },
    ],
  },
  {
    id: "travel", name: { fr: "Voyage" }, icon: "🧳",
    items: [
      { id: "w:เที่ยว", thai: "เที่ยว", rom: "thîao", meaning: { fr: "voyager, se balader" }, themes: ["travel"], example: { thai: "{I}มาเที่ยวเมืองไทย", rom: "{i} maa thîao mʉang thai", meaning: { fr: "je suis venu visiter la Thaïlande" } } },
      { id: "w:นักท่องเที่ยว", thai: "นักท่องเที่ยว", rom: "nák-thɔ̂ng-thîao", meaning: { fr: "touriste" }, themes: ["travel"] },
      { id: "w:หนังสือเดินทาง", thai: "หนังสือเดินทาง", rom: "nǎng-sʉ̌ʉ dəən-thaang", meaning: { fr: "passeport" }, themes: ["travel"] },
      { id: "w:วีซ่า", thai: "วีซ่า", rom: "wii-sâa", meaning: { fr: "visa" }, themes: ["travel"] },
      { id: "w:กระเป๋าเดินทาง", thai: "กระเป๋าเดินทาง", rom: "krà-pǎo dəən-thaang", meaning: { fr: "valise" }, themes: ["travel"] },
      { id: "w:ทะเล", thai: "ทะเล", rom: "thá-lee", meaning: { fr: "mer" }, themes: ["travel"] },
      { id: "w:ชายหาด", thai: "ชายหาด", rom: "chaai-hàat", meaning: { fr: "plage" }, themes: ["travel"] },
      { id: "w:ภูเขา", thai: "ภูเขา", rom: "phuu-khǎo", meaning: { fr: "montagne" }, themes: ["travel"] },
      { id: "w:วัด", thai: "วัด", rom: "wát", meaning: { fr: "temple" }, themes: ["travel"] },
      { id: "w:เกาะ", thai: "เกาะ", rom: "kɔ̀", meaning: { fr: "île" }, themes: ["travel"] },
      { id: "w:แผนที่", thai: "แผนที่", rom: "phɛ̌ɛn-thîi", meaning: { fr: "carte, plan" }, themes: ["travel"] },
      { id: "w:ถ่ายรูป", thai: "ถ่ายรูป", rom: "thàai-rûup", meaning: { fr: "prendre une photo" }, themes: ["travel"], example: { thai: "ถ่ายรูปให้หน่อยได้ไหม{Q}", rom: "thàai-rûup hâi nɔ̀i dâai mái {q}", meaning: { fr: "pouvez-vous me prendre en photo ?" } } },
      { id: "w:สวยมาก", thai: "สวยมาก", rom: "sǔai mâak", meaning: { fr: "très beau" }, themes: ["travel"] },
      { id: "w:ตั๋วเครื่องบิน", thai: "ตั๋วเครื่องบิน", rom: "tǔa khrʉ̂ang-bin", meaning: { fr: "billet d'avion" }, themes: ["travel"] },
    ],
  },
  {
    id: "airport", name: { fr: "Aéroport" }, icon: "✈️",
    items: [
      { id: "w:เที่ยวบิน", thai: "เที่ยวบิน", rom: "thîao-bin", meaning: { fr: "vol" }, themes: ["airport"] },
      { id: "w:ประตูขึ้นเครื่อง", thai: "ประตูขึ้นเครื่อง", rom: "prà-tuu khʉ̂n khrʉ̂ang", meaning: { fr: "porte d'embarquement" }, themes: ["airport"] },
      { id: "w:ขาเข้า", thai: "ขาเข้า", rom: "khǎa-khâo", meaning: { fr: "arrivées" }, themes: ["airport"] },
      { id: "w:ขาออก", thai: "ขาออก", rom: "khǎa-ɔ̀ɔk", meaning: { fr: "départs" }, themes: ["airport"] },
      { id: "w:ตรวจคนเข้าเมือง", thai: "ตรวจคนเข้าเมือง", rom: "trùat khon khâo mʉang", meaning: { fr: "contrôle de l'immigration" }, themes: ["airport"] },
      { id: "w:ศุลกากร", thai: "ศุลกากร", rom: "sǔn-lá-kaa-kɔɔn", meaning: { fr: "douane" }, themes: ["airport"] },
      { id: "w:รับกระเป๋า", thai: "รับกระเป๋า", rom: "ráp krà-pǎo", meaning: { fr: "récupérer les bagages" }, themes: ["airport"] },
      { id: "w:กระเป๋าหาย", thai: "กระเป๋าหาย", rom: "krà-pǎo hǎai", meaning: { fr: "bagage perdu" }, themes: ["airport"], example: { thai: "กระเป๋า{I}หาย", rom: "krà-pǎo {i} hǎai", meaning: { fr: "mon bagage est perdu" } } },
      { id: "w:บัตรขึ้นเครื่อง", thai: "บัตรขึ้นเครื่อง", rom: "bàt khʉ̂n khrʉ̂ang", meaning: { fr: "carte d'embarquement" }, themes: ["airport"] },
      { id: "w:ที่นั่ง", thai: "ที่นั่ง", rom: "thîi-nâng", meaning: { fr: "siège" }, themes: ["airport"] },
      { id: "w:ริมหน้าต่าง", thai: "ริมหน้าต่าง", rom: "rim nâa-tàang", meaning: { fr: "côté hublot" }, themes: ["airport"] },
      { id: "w:ริมทางเดิน", thai: "ริมทางเดิน", rom: "rim thaang-dəən", meaning: { fr: "côté couloir" }, themes: ["airport"] },
    ],
  },
  {
    id: "dir", name: { fr: "Directions" }, icon: "🧭",
    items: [
      { id: "w:ที่ไหน", thai: "ที่ไหน", rom: "thîi-nǎi", meaning: { fr: "où" }, themes: ["dir"], example: { thai: "สถานีอยู่ที่ไหน{Q}", rom: "sà-thǎa-nii yùu thîi-nǎi {q}", meaning: { fr: "où est la station ?" } } },
      { id: "w:ซ้าย", thai: "ซ้าย", rom: "sáai", meaning: { fr: "gauche" }, themes: ["dir"] },
      { id: "w:ขวา", thai: "ขวา", rom: "khwǎa", meaning: { fr: "droite" }, themes: ["dir"] },
      { id: "w:ข้างหน้า", thai: "ข้างหน้า", rom: "khâang-nâa", meaning: { fr: "devant" }, themes: ["dir"] },
      { id: "w:ข้างหลัง", thai: "ข้างหลัง", rom: "khâang-lǎng", meaning: { fr: "derrière" }, themes: ["dir"] },
      { id: "w:ข้างๆ", thai: "ข้างๆ", rom: "khâang-khâang", meaning: { fr: "à côté" }, themes: ["dir"] },
      { id: "w:ตรงข้าม", thai: "ตรงข้าม", rom: "trong-khâam", meaning: { fr: "en face" }, themes: ["dir"] },
      { id: "w:ที่นี่", thai: "ที่นี่", rom: "thîi-nîi", meaning: { fr: "ici" }, themes: ["dir"] },
      { id: "w:ที่นั่น", thai: "ที่นั่น", rom: "thîi-nân", meaning: { fr: "là-bas" }, themes: ["dir"] },
      { id: "w:สี่แยก", thai: "สี่แยก", rom: "sìi-yɛ̂ɛk", meaning: { fr: "carrefour" }, themes: ["dir"] },
      { id: "w:ซอย", thai: "ซอย", rom: "sɔɔi", meaning: { fr: "ruelle (soi)" }, themes: ["dir"] },
      { id: "w:ถนน", thai: "ถนน", rom: "thà-nǒn", meaning: { fr: "rue, route" }, themes: ["dir"] },
      { id: "w:เดินไปได้ไหม{Q}", thai: "เดินไปได้ไหม{Q}", rom: "dəən pai dâai mái {q}", meaning: { fr: "peut-on y aller à pied ?" }, themes: ["dir"] },
      { id: "w:{I}หลงทาง", thai: "{I}หลงทาง", rom: "{i} lǒng-thaang", meaning: { fr: "je suis perdu" }, themes: ["dir"] },
      { id: "w:ทางเข้า", thai: "ทางเข้า", rom: "thaang-khâo", meaning: { fr: "entrée" }, themes: ["dir"] },
      { id: "w:ทางออก", thai: "ทางออก", rom: "thaang-ɔ̀ɔk", meaning: { fr: "sortie" }, themes: ["dir"] },
    ],
  },
  {
    id: "sos", name: { fr: "Urgence" }, icon: "🚨",
    items: [
      { id: "w:ช่วยด้วย", thai: "ช่วยด้วย", rom: "chûai dûai", meaning: { fr: "au secours !" }, themes: ["sos"] },
      { id: "w:เรียกตำรวจ", thai: "เรียกตำรวจ", rom: "rîak tam-rùat", meaning: { fr: "appelez la police" }, themes: ["sos"] },
      { id: "w:เรียกรถพยาบาล", thai: "เรียกรถพยาบาล", rom: "rîak rót phá-yaa-baan", meaning: { fr: "appelez une ambulance" }, themes: ["sos"] },
      { id: "w:ช่วย{I}หน่อยได้ไหม{Q}", thai: "ช่วย{I}หน่อยได้ไหม{Q}", rom: "chûai {i} nɔ̀i dâai mái {q}", meaning: { fr: "pouvez-vous m'aider ?" }, themes: ["sos"] },
      { id: "w:{I}ต้องการหมอ", thai: "{I}ต้องการหมอ", rom: "{i} tɔ̂ng-kaan mɔ̌ɔ", meaning: { fr: "j'ai besoin d'un médecin" }, themes: ["sos"] },
      { id: "w:เจ็บมาก", thai: "เจ็บมาก", rom: "jèp mâak", meaning: { fr: "j'ai très mal" }, themes: ["sos"] },
      { id: "w:ไฟไหม้", thai: "ไฟไหม้", rom: "fai-mâi", meaning: { fr: "incendie" }, themes: ["sos"] },
      { id: "w:ขโมย", thai: "ขโมย", rom: "khà-mooi", meaning: { fr: "voleur" }, themes: ["sos"] },
      { id: "w:อันตราย", thai: "อันตราย", rom: "an-tà-raai", meaning: { fr: "danger" }, themes: ["sos"] },
      { id: "w:อุบัติเหตุ", thai: "อุบัติเหตุ", rom: "ù-bàt-tì-hèet", meaning: { fr: "accident" }, themes: ["sos"] },
      { id: "w:ระวัง", thai: "ระวัง", rom: "rá-wang", meaning: { fr: "attention !" }, themes: ["sos"] },
      { id: "w:{I}ทำกระเป๋าสตางค์หาย", thai: "{I}ทำกระเป๋าสตางค์หาย", rom: "{i} tham krà-pǎo sà-taang hǎai", meaning: { fr: "j'ai perdu mon portefeuille" }, themes: ["sos"] },
      { id: "w:{I}ทำโทรศัพท์หาย", thai: "{I}ทำโทรศัพท์หาย", rom: "{i} tham thoo-rá-sàp hǎai", meaning: { fr: "j'ai perdu mon téléphone" }, themes: ["sos"] },
      { id: "w:สถานทูต", thai: "สถานทูต", rom: "sà-thǎan-thûut", meaning: { fr: "ambassade" }, themes: ["sos"] },
      { id: "w:สถานีตำรวจ", thai: "สถานีตำรวจ", rom: "sà-thǎa-nii tam-rùat", meaning: { fr: "commissariat" }, themes: ["sos"] },
    ],
  },
  {
    id: "friends", name: { fr: "Amis" }, icon: "🤝",
    items: [
      { id: "w:เพื่อนสนิท", thai: "เพื่อนสนิท", rom: "phʉ̂an sà-nìt", meaning: { fr: "ami proche" }, themes: ["friends"] },
      { id: "w:ว่างไหม", thai: "ว่างไหม", rom: "wâang mái", meaning: { fr: "tu es libre ?" }, themes: ["friends"] },
      { id: "w:ไปด้วยกัน", thai: "ไปด้วยกัน", rom: "pai dûai-kan", meaning: { fr: "y aller ensemble" }, themes: ["friends"] },
      { id: "w:ไปกินข้าวกันไหม", thai: "ไปกินข้าวกันไหม", rom: "pai kin khâao kan mái", meaning: { fr: "on va manger ensemble ?" }, themes: ["friends"] },
      { id: "w:เป็นไงบ้าง", thai: "เป็นไงบ้าง", rom: "pen-ngai bâang", meaning: { fr: "quoi de neuf ?" }, themes: ["friends"] },
      { id: "w:คิดถึง", thai: "คิดถึง", rom: "khít-thʉ̌ng", meaning: { fr: "tu me manques ; penser à" }, themes: ["friends"] },
      { id: "w:ขอเบอร์หน่อย", thai: "ขอเบอร์หน่อย", rom: "khɔ̌ɔ bəə nɔ̀i", meaning: { fr: "je peux avoir ton numéro ?" }, themes: ["friends"] },
      { id: "w:ไลน์", thai: "ไลน์", rom: "laai", meaning: { fr: "LINE (messagerie)" }, themes: ["friends"] },
      { id: "w:เจอกันพรุ่งนี้", thai: "เจอกันพรุ่งนี้", rom: "jəə kan phrûng-níi", meaning: { fr: "à demain" }, themes: ["friends"] },
      { id: "w:สนุก", thai: "สนุก", rom: "sà-nùk", meaning: { fr: "amusant" }, themes: ["friends"], example: { thai: "สนุกมาก", rom: "sà-nùk mâak", meaning: { fr: "c'était très amusant" } } },
      { id: "w:ตลก", thai: "ตลก", rom: "tà-lòk", meaning: { fr: "drôle" }, themes: ["friends"] },
      { id: "w:ใจดี", thai: "ใจดี", rom: "jai-dii", meaning: { fr: "gentil" }, themes: ["friends"] },
    ],
  },
  {
    id: "out", name: { fr: "Sorties" }, icon: "🎶",
    items: [
      { id: "w:ไปเที่ยว", thai: "ไปเที่ยว", rom: "pai thîao", meaning: { fr: "sortir, aller se balader" }, themes: ["out"] },
      { id: "w:ดูหนัง", thai: "ดูหนัง", rom: "duu nǎng", meaning: { fr: "voir un film" }, themes: ["out"] },
      { id: "w:ฟังเพลง", thai: "ฟังเพลง", rom: "fang phleeng", meaning: { fr: "écouter de la musique" }, themes: ["out"] },
      { id: "w:ร้องเพลง", thai: "ร้องเพลง", rom: "rɔ́ɔng phleeng", meaning: { fr: "chanter" }, themes: ["out"] },
      { id: "w:เต้น", thai: "เต้น", rom: "tên", meaning: { fr: "danser" }, themes: ["out"] },
      { id: "w:ดื่ม", thai: "ดื่ม", rom: "dʉ̀ʉm", meaning: { fr: "boire" }, themes: ["out"] },
      { id: "w:บาร์", thai: "บาร์", rom: "baa", meaning: { fr: "bar" }, themes: ["out"] },
      { id: "w:ร้านกาแฟ", thai: "ร้านกาแฟ", rom: "ráan kaa-fɛɛ", meaning: { fr: "café (lieu)" }, themes: ["out"] },
      { id: "w:คอนเสิร์ต", thai: "คอนเสิร์ต", rom: "khɔɔn-sə̀ət", meaning: { fr: "concert" }, themes: ["out"] },
      { id: "w:ชนแก้ว", thai: "ชนแก้ว", rom: "chon kɛ̂ɛo", meaning: { fr: "trinquer ; santé !" }, themes: ["out"] },
      { id: "w:เมา", thai: "เมา", rom: "mao", meaning: { fr: "ivre" }, themes: ["out"] },
      { id: "w:กลับบ้าน", thai: "กลับบ้าน", rom: "klàp bâan", meaning: { fr: "rentrer à la maison" }, themes: ["out"] },
      { id: "w:ดึกแล้ว", thai: "ดึกแล้ว", rom: "dʉ̀k lɛ́ɛo", meaning: { fr: "il est tard" }, themes: ["out"] },
      { id: "w:{I}เลี้ยงเอง", thai: "{I}เลี้ยงเอง", rom: "{i} líang eeng", meaning: { fr: "c'est moi qui invite" }, themes: ["out"] },
    ],
  },
  {
    id: "feel", name: { fr: "Sentiments" }, icon: "💛",
    items: [
      { id: "w:ดีใจ", thai: "ดีใจ", rom: "dii-jai", meaning: { fr: "content" }, themes: ["feel"] },
      { id: "w:เสียใจ", thai: "เสียใจ", rom: "sǐa-jai", meaning: { fr: "triste ; désolé" }, themes: ["feel"] },
      { id: "w:มีความสุข", thai: "มีความสุข", rom: "mii khwaam-sùk", meaning: { fr: "heureux" }, themes: ["feel"] },
      { id: "w:โกรธ", thai: "โกรธ", rom: "kròot", meaning: { fr: "en colère" }, themes: ["feel"] },
      { id: "w:กลัว", thai: "กลัว", rom: "klua", meaning: { fr: "avoir peur" }, themes: ["feel"] },
      { id: "w:เหงา", thai: "เหงา", rom: "ngǎo", meaning: { fr: "se sentir seul" }, themes: ["feel"] },
      { id: "w:ตื่นเต้น", thai: "ตื่นเต้น", rom: "tʉ̀ʉn-tên", meaning: { fr: "excité, impatient" }, themes: ["feel"] },
      { id: "w:เบื่อ", thai: "เบื่อ", rom: "bʉ̀a", meaning: { fr: "s'ennuyer, en avoir assez" }, themes: ["feel"] },
      { id: "w:เครียด", thai: "เครียด", rom: "khrîat", meaning: { fr: "stressé" }, themes: ["feel"] },
      { id: "w:สบายใจ", thai: "สบายใจ", rom: "sà-baai-jai", meaning: { fr: "serein" }, themes: ["feel"] },
      { id: "w:เป็นห่วง", thai: "เป็นห่วง", rom: "pen-hùang", meaning: { fr: "s'inquiéter pour quelqu'un" }, themes: ["feel"] },
      { id: "w:รัก", thai: "รัก", rom: "rák", meaning: { fr: "aimer" }, themes: ["feel"], example: { thai: "{I}รักคุณ", rom: "{i} rák khun", meaning: { fr: "je t'aime" } } },
      { id: "w:ชอบ", thai: "ชอบ", rom: "chɔ̂ɔp", meaning: { fr: "aimer bien" }, themes: ["feel"], example: { thai: "{I}ชอบเมืองไทย", rom: "{i} chɔ̂ɔp mʉang thai", meaning: { fr: "j'aime bien la Thaïlande" } } },
      { id: "w:อาย", thai: "อาย", rom: "aai", meaning: { fr: "gêné, timide" }, themes: ["feel"] },
      { id: "w:ประหลาดใจ", thai: "ประหลาดใจ", rom: "prà-làat-jai", meaning: { fr: "surpris" }, themes: ["feel"] },
    ],
  },
  {
    id: "verbs", name: { fr: "Verbes courants" }, icon: "🏃",
    items: [
      { id: "w:ไป", thai: "ไป", rom: "pai", meaning: { fr: "aller" }, themes: ["verbs"] },
      { id: "w:มา", thai: "มา", rom: "maa", meaning: { fr: "venir" }, themes: ["verbs"] },
      { id: "w:กิน", thai: "กิน", rom: "kin", meaning: { fr: "manger" }, themes: ["verbs"] },
      { id: "w:นอน", thai: "นอน", rom: "nɔɔn", meaning: { fr: "dormir" }, themes: ["verbs"] },
      { id: "w:ตื่น", thai: "ตื่น", rom: "tʉ̀ʉn", meaning: { fr: "se réveiller" }, themes: ["verbs"] },
      { id: "w:ทำ", thai: "ทำ", rom: "tham", meaning: { fr: "faire" }, themes: ["verbs"], example: { thai: "ทำอะไรอยู่", rom: "tham à-rai yùu", meaning: { fr: "qu'est-ce que tu fais ?" } } },
      { id: "w:พูด", thai: "พูด", rom: "phûut", meaning: { fr: "parler" }, themes: ["verbs"] },
      { id: "w:ฟัง", thai: "ฟัง", rom: "fang", meaning: { fr: "écouter" }, themes: ["verbs"] },
      { id: "w:ดู", thai: "ดู", rom: "duu", meaning: { fr: "regarder" }, themes: ["verbs"] },
      { id: "w:อ่าน", thai: "อ่าน", rom: "àan", meaning: { fr: "lire" }, themes: ["verbs"] },
      { id: "w:เขียน", thai: "เขียน", rom: "khǐan", meaning: { fr: "écrire" }, themes: ["verbs"] },
      { id: "w:เรียน", thai: "เรียน", rom: "rian", meaning: { fr: "étudier" }, themes: ["verbs"] },
      { id: "w:รู้", thai: "รู้", rom: "rúu", meaning: { fr: "savoir" }, themes: ["verbs"], example: { thai: "{I}ไม่รู้", rom: "{i} mâi rúu", meaning: { fr: "je ne sais pas" } } },
      { id: "w:คิด", thai: "คิด", rom: "khít", meaning: { fr: "penser" }, themes: ["verbs"] },
      { id: "w:ให้", thai: "ให้", rom: "hâi", meaning: { fr: "donner" }, themes: ["verbs"] },
      { id: "w:เอา", thai: "เอา", rom: "ao", meaning: { fr: "prendre ; vouloir" }, themes: ["verbs"] },
      { id: "w:มี", thai: "มี", rom: "mii", meaning: { fr: "avoir ; il y a" }, themes: ["verbs"] },
      { id: "w:เป็น", thai: "เป็น", rom: "pen", meaning: { fr: "être (quelque chose)" }, themes: ["verbs"] },
      { id: "w:อยู่", thai: "อยู่", rom: "yùu", meaning: { fr: "être (quelque part)" }, themes: ["verbs"] },
      { id: "w:เดิน", thai: "เดิน", rom: "dəən", meaning: { fr: "marcher" }, themes: ["verbs"] },
      { id: "w:วิ่ง", thai: "วิ่ง", rom: "wîng", meaning: { fr: "courir" }, themes: ["verbs"] },
      { id: "w:นั่ง", thai: "นั่ง", rom: "nâng", meaning: { fr: "s'asseoir" }, themes: ["verbs"] },
      { id: "w:ยืน", thai: "ยืน", rom: "yʉʉn", meaning: { fr: "être debout" }, themes: ["verbs"] },
      { id: "w:รอ", thai: "รอ", rom: "rɔɔ", meaning: { fr: "attendre" }, themes: ["verbs"] },
      { id: "w:ช่วย", thai: "ช่วย", rom: "chûai", meaning: { fr: "aider" }, themes: ["verbs"] },
      { id: "w:ใช้", thai: "ใช้", rom: "chái", meaning: { fr: "utiliser" }, themes: ["verbs"] },
      { id: "w:ถาม", thai: "ถาม", rom: "thǎam", meaning: { fr: "demander" }, themes: ["verbs"] },
      { id: "w:ตอบ", thai: "ตอบ", rom: "tɔ̀ɔp", meaning: { fr: "répondre" }, themes: ["verbs"] },
      { id: "w:อยาก", thai: "อยาก", rom: "yàak", meaning: { fr: "avoir envie de" }, themes: ["verbs"] },
      { id: "w:ต้อง", thai: "ต้อง", rom: "tɔ̂ng", meaning: { fr: "devoir" }, themes: ["verbs"] },
      { id: "w:เข้าใจ", thai: "เข้าใจ", rom: "khâo-jai", meaning: { fr: "comprendre" }, themes: ["verbs"] },
      { id: "w:จำได้", thai: "จำได้", rom: "jam dâai", meaning: { fr: "se souvenir" }, themes: ["verbs"] },
      { id: "w:ลืม", thai: "ลืม", rom: "lʉʉm", meaning: { fr: "oublier" }, themes: ["verbs"] },
      { id: "w:ลอง", thai: "ลอง", rom: "lɔɔng", meaning: { fr: "essayer" }, themes: ["verbs"] },
      { id: "w:เริ่ม", thai: "เริ่ม", rom: "rə̂əm", meaning: { fr: "commencer" }, themes: ["verbs"] },
      { id: "w:หยุด", thai: "หยุด", rom: "yùt", meaning: { fr: "arrêter" }, themes: ["verbs"] },
      { id: "w:ส่ง", thai: "ส่ง", rom: "sòng", meaning: { fr: "envoyer" }, themes: ["verbs"] },
      { id: "w:รับ", thai: "รับ", rom: "ráp", meaning: { fr: "recevoir ; prendre" }, themes: ["verbs"] },
      { id: "w:หา", thai: "หา", rom: "hǎa", meaning: { fr: "chercher" }, themes: ["verbs"] },
      { id: "w:เจอ", thai: "เจอ", rom: "jəə", meaning: { fr: "trouver ; rencontrer" }, themes: ["verbs"] },
      { id: "w:จำ", thai: "จำ", rom: "jam", meaning: { fr: "se souvenir" }, themes: ["verbs"] },
      { id: "w:บอก", thai: "บอก", rom: "bɔ̀ɔk", meaning: { fr: "dire" }, themes: ["verbs"] },
      { id: "w:จ่าย", thai: "จ่าย", rom: "jàai", meaning: { fr: "payer" }, themes: ["verbs"] },
      { id: "w:เช่า", thai: "เช่า", rom: "châo", meaning: { fr: "louer" }, themes: ["verbs"] },
    ],
  },
  {
    id: "adj", name: { fr: "Adjectifs courants" }, icon: "✨",
    items: [
      { id: "w:ดี", thai: "ดี", rom: "dii", meaning: { fr: "bon, bien" }, themes: ["adj"] },
      { id: "w:ใหญ่", thai: "ใหญ่", rom: "yài", meaning: { fr: "grand (taille)" }, themes: ["adj"] },
      { id: "w:เล็ก", thai: "เล็ก", rom: "lék", meaning: { fr: "petit" }, themes: ["adj"] },
      { id: "w:ใหม่", thai: "ใหม่", rom: "mài", meaning: { fr: "nouveau" }, themes: ["adj"] },
      { id: "w:เก่า", thai: "เก่า", rom: "kào", meaning: { fr: "vieux, ancien" }, themes: ["adj"] },
      { id: "w:สวย", thai: "สวย", rom: "sǔai", meaning: { fr: "beau, belle" }, themes: ["adj"] },
      { id: "w:น่ารัก", thai: "น่ารัก", rom: "nâa-rák", meaning: { fr: "mignon" }, themes: ["adj"] },
      { id: "w:ช้า", thai: "ช้า", rom: "cháa", meaning: { fr: "lent" }, themes: ["adj"] },
      { id: "w:ยาก", thai: "ยาก", rom: "yâak", meaning: { fr: "difficile" }, themes: ["adj"] },
      { id: "w:ง่าย", thai: "ง่าย", rom: "ngâai", meaning: { fr: "facile" }, themes: ["adj"], example: { thai: "ภาษาไทยไม่ง่าย", rom: "phaa-sǎa thai mâi ngâai", meaning: { fr: "le thaï n'est pas facile" } } },
      { id: "w:แพง", thai: "แพง", rom: "phɛɛng", meaning: { fr: "cher" }, themes: ["adj"] },
      { id: "w:สูง", thai: "สูง", rom: "sǔung", meaning: { fr: "haut ; grand (personne)" }, themes: ["adj"] },
      { id: "w:เตี้ย", thai: "เตี้ย", rom: "tîa", meaning: { fr: "petit (personne), bas" }, themes: ["adj"] },
      { id: "w:ยาว", thai: "ยาว", rom: "yaao", meaning: { fr: "long" }, themes: ["adj"] },
      { id: "w:สั้น", thai: "สั้น", rom: "sân", meaning: { fr: "court" }, themes: ["adj"] },
      { id: "w:หนัก", thai: "หนัก", rom: "nàk", meaning: { fr: "lourd" }, themes: ["adj"] },
      { id: "w:เบา", thai: "เบา", rom: "bao", meaning: { fr: "léger" }, themes: ["adj"] },
      { id: "w:สะอาด", thai: "สะอาด", rom: "sà-àat", meaning: { fr: "propre" }, themes: ["adj"] },
      { id: "w:สกปรก", thai: "สกปรก", rom: "sòk-kà-pròk", meaning: { fr: "sale" }, themes: ["adj"] },
      { id: "w:เต็ม", thai: "เต็ม", rom: "tem", meaning: { fr: "plein" }, themes: ["adj"] },
      { id: "w:ว่าง", thai: "ว่าง", rom: "wâang", meaning: { fr: "libre ; vide" }, themes: ["adj"] },
      { id: "w:สำคัญ", thai: "สำคัญ", rom: "sǎm-khan", meaning: { fr: "important" }, themes: ["adj"] },
      { id: "w:กว้าง", thai: "กว้าง", rom: "kwâang", meaning: { fr: "large" }, themes: ["adj"] },
      { id: "w:แคบ", thai: "แคบ", rom: "khɛ̂ɛp", meaning: { fr: "étroit" }, themes: ["adj"] },
      { id: "w:พร้อม", thai: "พร้อม", rom: "phrɔ́ɔm", meaning: { fr: "prêt" }, themes: ["adj"] },
      { id: "w:เหมือน", thai: "เหมือน", rom: "mʉ̌an", meaning: { fr: "pareil, semblable" }, themes: ["adj"] },
      { id: "w:ต่าง", thai: "ต่าง", rom: "tàang", meaning: { fr: "différent" }, themes: ["adj"] },
    ],
  },
  {
    id: "small", name: { fr: "Petits mots utiles" }, icon: "🔗",
    items: [
      { id: "w:และ", thai: "และ", rom: "lɛ́", meaning: { fr: "et" }, themes: ["small"] },
      { id: "w:กับ", thai: "กับ", rom: "kàp", meaning: { fr: "avec ; et" }, themes: ["small"] },
      { id: "w:แต่", thai: "แต่", rom: "tɛ̀ɛ", meaning: { fr: "mais" }, themes: ["small"] },
      { id: "w:หรือ", thai: "หรือ", rom: "rʉ̌ʉ", meaning: { fr: "ou" }, themes: ["small"] },
      { id: "w:เพราะ", thai: "เพราะ", rom: "phrɔ́", meaning: { fr: "parce que" }, themes: ["small"] },
      { id: "w:เพราะว่า", thai: "เพราะว่า", rom: "phrɔ́-wâa", meaning: { fr: "parce que" }, themes: ["small"] },
      { id: "w:ถ้า", thai: "ถ้า", rom: "thâa", meaning: { fr: "si" }, themes: ["small"] },
      { id: "w:ก็", thai: "ก็", rom: "kɔ̂ɔ", meaning: { fr: "alors ; aussi" }, themes: ["small"] },
      { id: "w:ด้วย", thai: "ด้วย", rom: "dûai", meaning: { fr: "aussi ; avec" }, themes: ["small"] },
      { id: "w:แล้ว", thai: "แล้ว", rom: "lɛ́ɛo", meaning: { fr: "déjà ; puis" }, themes: ["small"] },
      { id: "w:ยัง", thai: "ยัง", rom: "yang", meaning: { fr: "encore ; pas encore" }, themes: ["small"] },
      { id: "w:เคย", thai: "เคย", rom: "khəəi", meaning: { fr: "avoir déjà (fait)" }, themes: ["small"] },
      { id: "w:จะ", thai: "จะ", rom: "jà", meaning: { fr: "marque du futur" }, themes: ["small"] },
      { id: "w:กำลัง", thai: "กำลัง", rom: "kam-lang", meaning: { fr: "en train de" }, themes: ["small"] },
      { id: "w:มาก", thai: "มาก", rom: "mâak", meaning: { fr: "très ; beaucoup" }, themes: ["small"] },
      { id: "w:นิดหน่อย", thai: "นิดหน่อย", rom: "nít-nɔ̀i", meaning: { fr: "un peu" }, themes: ["small"] },
      { id: "w:ทุก", thai: "ทุก", rom: "thúk", meaning: { fr: "chaque, tous les" }, themes: ["small"] },
      { id: "w:บาง", thai: "บาง", rom: "baang", meaning: { fr: "certains" }, themes: ["small"] },
      { id: "w:ทั้งหมด", thai: "ทั้งหมด", rom: "tháng-mòt", meaning: { fr: "tout, en tout" }, themes: ["small"] },
      { id: "w:อีก", thai: "อีก", rom: "ìik", meaning: { fr: "encore, de plus" }, themes: ["small"] },
      { id: "w:เท่านั้น", thai: "เท่านั้น", rom: "thâo-nán", meaning: { fr: "seulement" }, themes: ["small"] },
      { id: "w:ประมาณ", thai: "ประมาณ", rom: "prà-maan", meaning: { fr: "environ" }, themes: ["small"] },
      { id: "w:อาจจะ", thai: "อาจจะ", rom: "àat-jà", meaning: { fr: "peut-être" }, themes: ["small"] },
      { id: "w:แน่นอน", thai: "แน่นอน", rom: "nɛ̂ɛ-nɔɔn", meaning: { fr: "bien sûr" }, themes: ["small"] },
      { id: "w:จริงๆ", thai: "จริงๆ", rom: "jing-jing", meaning: { fr: "vraiment" }, themes: ["small"] },
      { id: "w:เหมือนกัน", thai: "เหมือนกัน", rom: "mʉ̌an-kan", meaning: { fr: "pareil ; moi aussi" }, themes: ["small"] },
      { id: "w:ด้วยกัน", thai: "ด้วยกัน", rom: "dûai-kan", meaning: { fr: "ensemble" }, themes: ["small"] },
    ],
  },
  {
    id: "body", name: { fr: "Corps" }, icon: "🧍",
    items: [
      { id: "w:ร่างกาย", thai: "ร่างกาย", rom: "râang-kaai", meaning: { fr: "corps" }, themes: ["body"] },
      { id: "w:หัว", thai: "หัว", rom: "hǔa", meaning: { fr: "tête" }, themes: ["body"] },
      { id: "w:เส้นผม", thai: "เส้นผม", rom: "sên-phǒm", meaning: { fr: "cheveux" }, themes: ["body"] },
      { id: "w:ใบหน้า", thai: "ใบหน้า", rom: "bai-nâa", meaning: { fr: "visage" }, themes: ["body"] },
      { id: "w:ดวงตา", thai: "ดวงตา", rom: "duang-taa", meaning: { fr: "œil, yeux" }, themes: ["body"] },
      { id: "w:หู", thai: "หู", rom: "hǔu", meaning: { fr: "oreille" }, themes: ["body"] },
      { id: "w:จมูก", thai: "จมูก", rom: "jà-mùuk", meaning: { fr: "nez" }, themes: ["body"] },
      { id: "w:ปาก", thai: "ปาก", rom: "pàak", meaning: { fr: "bouche" }, themes: ["body"] },
      { id: "w:ฟัน", thai: "ฟัน", rom: "fan", meaning: { fr: "dent" }, themes: ["body"] },
      { id: "w:คอ", thai: "คอ", rom: "khɔɔ", meaning: { fr: "cou ; gorge" }, themes: ["body"] },
      { id: "w:ไหล่", thai: "ไหล่", rom: "lài", meaning: { fr: "épaule" }, themes: ["body"] },
      { id: "w:แขน", thai: "แขน", rom: "khɛ̌ɛn", meaning: { fr: "bras" }, themes: ["body"] },
      { id: "w:มือ", thai: "มือ", rom: "mʉʉ", meaning: { fr: "main" }, themes: ["body"] },
      { id: "w:นิ้ว", thai: "นิ้ว", rom: "níu", meaning: { fr: "doigt" }, themes: ["body"] },
      { id: "w:หลัง", thai: "หลัง", rom: "lǎng", meaning: { fr: "dos" }, themes: ["body"] },
      { id: "w:ท้อง", thai: "ท้อง", rom: "thɔ́ɔng", meaning: { fr: "ventre" }, themes: ["body"] },
      { id: "w:ขา", thai: "ขา", rom: "khǎa", meaning: { fr: "jambe" }, themes: ["body"] },
      { id: "w:เข่า", thai: "เข่า", rom: "khào", meaning: { fr: "genou" }, themes: ["body"] },
      { id: "w:เท้า", thai: "เท้า", rom: "tháao", meaning: { fr: "pied" }, themes: ["body"] },
      { id: "w:หัวใจ", thai: "หัวใจ", rom: "hǔa-jai", meaning: { fr: "cœur" }, themes: ["body"] },
      { id: "w:เลือด", thai: "เลือด", rom: "lʉ̂at", meaning: { fr: "sang" }, themes: ["body"] },
      { id: "w:{I}ปวดหลัง", thai: "{I}ปวดหลัง", rom: "{i} pùat lǎng", meaning: { fr: "j'ai mal au dos" }, themes: ["body"] },
      { id: "w:{I}เจ็บเข่า", thai: "{I}เจ็บเข่า", rom: "{i} jèp khào", meaning: { fr: "j'ai mal au genou" }, themes: ["body"] },
    ],
  },
  {
    id: "clothes", name: { fr: "Vêtements" }, icon: "👕",
    items: [
      { id: "w:เสื้อผ้า", thai: "เสื้อผ้า", rom: "sʉ̂a-phâa", meaning: { fr: "vêtements" }, themes: ["clothes"] },
      { id: "w:เสื้อยืด", thai: "เสื้อยืด", rom: "sʉ̂a-yʉ̂ʉt", meaning: { fr: "t-shirt" }, themes: ["clothes"] },
      { id: "w:เสื้อเชิ้ต", thai: "เสื้อเชิ้ต", rom: "sʉ̂a-chə́ət", meaning: { fr: "chemise" }, themes: ["clothes"] },
      { id: "w:กระโปรง", thai: "กระโปรง", rom: "krà-proong", meaning: { fr: "jupe" }, themes: ["clothes"] },
      { id: "w:ชุด", thai: "ชุด", rom: "chút", meaning: { fr: "tenue ; robe" }, themes: ["clothes"] },
      { id: "w:ถุงเท้า", thai: "ถุงเท้า", rom: "thǔng-tháao", meaning: { fr: "chaussettes" }, themes: ["clothes"] },
      { id: "w:หมวก", thai: "หมวก", rom: "mùak", meaning: { fr: "chapeau ; casquette" }, themes: ["clothes"] },
      { id: "w:แว่นตา", thai: "แว่นตา", rom: "wɛ̂n-taa", meaning: { fr: "lunettes" }, themes: ["clothes"] },
      { id: "w:เข็มขัด", thai: "เข็มขัด", rom: "khěm-khàt", meaning: { fr: "ceinture" }, themes: ["clothes"] },
      { id: "w:ใส่", thai: "ใส่", rom: "sài", meaning: { fr: "porter, mettre (un vêtement)" }, themes: ["clothes"] },
      { id: "w:ถอด", thai: "ถอด", rom: "thɔ̀ɔt", meaning: { fr: "enlever" }, themes: ["clothes"] },
      { id: "w:ขนาด", thai: "ขนาด", rom: "khà-nàat", meaning: { fr: "taille" }, themes: ["clothes"] },
      { id: "w:พอดี", thai: "พอดี", rom: "phɔɔ-dii", meaning: { fr: "juste à la bonne taille" }, themes: ["clothes"] },
      { id: "w:หลวม", thai: "หลวม", rom: "lǔam", meaning: { fr: "trop large" }, themes: ["clothes"] },
      { id: "w:คับ", thai: "คับ", rom: "kháp", meaning: { fr: "trop serré" }, themes: ["clothes"] },
      { id: "w:ลองใส่ได้ไหม{Q}", thai: "ลองใส่ได้ไหม{Q}", rom: "lɔɔng sài dâai mái {q}", meaning: { fr: "puis-je l'essayer ?" }, themes: ["clothes"] },
    ],
  },
  {
    id: "animals", name: { fr: "Animaux" }, icon: "🐘",
    items: [
      { id: "w:สัตว์", thai: "สัตว์", rom: "sàt", meaning: { fr: "animal" }, themes: ["animals"] },
      { id: "w:หมา", thai: "หมา", rom: "mǎa", meaning: { fr: "chien" }, themes: ["animals"] },
      { id: "w:แมว", thai: "แมว", rom: "mɛɛo", meaning: { fr: "chat" }, themes: ["animals"] },
      { id: "w:ช้าง", thai: "ช้าง", rom: "cháang", meaning: { fr: "éléphant" }, themes: ["animals"] },
      { id: "w:นก", thai: "นก", rom: "nók", meaning: { fr: "oiseau" }, themes: ["animals"] },
      { id: "w:ปลา", thai: "ปลา", rom: "plaa", meaning: { fr: "poisson" }, themes: ["animals"] },
      { id: "w:วัว", thai: "วัว", rom: "wua", meaning: { fr: "vache, bœuf" }, themes: ["animals"] },
      { id: "w:ควาย", thai: "ควาย", rom: "khwaai", meaning: { fr: "buffle" }, themes: ["animals"] },
      { id: "w:ม้า", thai: "ม้า", rom: "máa", meaning: { fr: "cheval" }, themes: ["animals"] },
      { id: "w:ลิง", thai: "ลิง", rom: "ling", meaning: { fr: "singe" }, themes: ["animals"] },
      { id: "w:งู", thai: "งู", rom: "nguu", meaning: { fr: "serpent" }, themes: ["animals"] },
      { id: "w:เสือ", thai: "เสือ", rom: "sʉ̌a", meaning: { fr: "tigre" }, themes: ["animals"] },
      { id: "w:ยุง", thai: "ยุง", rom: "yung", meaning: { fr: "moustique" }, themes: ["animals"] },
      { id: "w:มด", thai: "มด", rom: "mót", meaning: { fr: "fourmi" }, themes: ["animals"] },
      { id: "w:จิ้งจก", thai: "จิ้งจก", rom: "jîng-jòk", meaning: { fr: "petit gecko des maisons" }, themes: ["animals"] },
      { id: "w:ตุ๊กแก", thai: "ตุ๊กแก", rom: "túk-kɛɛ", meaning: { fr: "gecko tokay" }, themes: ["animals"] },
      { id: "w:ระวังหมาดุ", thai: "ระวังหมาดุ", rom: "rá-wang mǎa dù", meaning: { fr: "attention, chien méchant" }, themes: ["animals"] },
      { id: "w:{I}กลัวงู", thai: "{I}กลัวงู", rom: "{i} klua nguu", meaning: { fr: "j'ai peur des serpents" }, themes: ["animals"] },
    ],
  },
  {
    id: "places", name: { fr: "Lieux en ville" }, icon: "🏙️",
    items: [
      { id: "w:เมือง", thai: "เมือง", rom: "mʉang", meaning: { fr: "ville" }, themes: ["places"] },
      { id: "w:ธนาคาร", thai: "ธนาคาร", rom: "thá-naa-khaan", meaning: { fr: "banque" }, themes: ["places"] },
      { id: "w:ไปรษณีย์", thai: "ไปรษณีย์", rom: "prai-sà-nii", meaning: { fr: "poste" }, themes: ["places"] },
      { id: "w:สถานีตำรวจ", thai: "สถานีตำรวจ", rom: "sà-thǎa-nii tam-rùat", meaning: { fr: "commissariat" }, themes: ["places"] },
      { id: "w:โรงเรียน", thai: "โรงเรียน", rom: "roong-rian", meaning: { fr: "école" }, themes: ["places"] },
      { id: "w:มหาวิทยาลัย", thai: "มหาวิทยาลัย", rom: "má-hǎa-wít-thá-yaa-lai", meaning: { fr: "université" }, themes: ["places"] },
      { id: "w:ร้านกาแฟ", thai: "ร้านกาแฟ", rom: "ráan kaa-fɛɛ", meaning: { fr: "café (lieu)" }, themes: ["places"] },
      { id: "w:ร้านสะดวกซื้อ", thai: "ร้านสะดวกซื้อ", rom: "ráan sà-dùak-sʉ́ʉ", meaning: { fr: "supérette" }, themes: ["places"] },
      { id: "w:ปั๊มน้ำมัน", thai: "ปั๊มน้ำมัน", rom: "pám náam-man", meaning: { fr: "station-service" }, themes: ["places"] },
      { id: "w:สวนสาธารณะ", thai: "สวนสาธารณะ", rom: "sǔan sǎa-thaa-rá-ná", meaning: { fr: "parc public" }, themes: ["places"] },
      { id: "w:พิพิธภัณฑ์", thai: "พิพิธภัณฑ์", rom: "phí-phít-thá-phan", meaning: { fr: "musée" }, themes: ["places"] },
      { id: "w:สถานทูต", thai: "สถานทูต", rom: "sà-thǎan-thûut", meaning: { fr: "ambassade" }, themes: ["places"] },
      { id: "w:ตู้เอทีเอ็ม", thai: "ตู้เอทีเอ็ม", rom: "tûu ee-thii-em", meaning: { fr: "distributeur de billets" }, themes: ["places"] },
      { id: "w:สะพาน", thai: "สะพาน", rom: "sà-phaan", meaning: { fr: "pont" }, themes: ["places"] },
      { id: "w:แม่น้ำ", thai: "แม่น้ำ", rom: "mɛ̂ɛ-náam", meaning: { fr: "fleuve, rivière" }, themes: ["places"] },
      { id: "w:ตึก", thai: "ตึก", rom: "tʉ̀k", meaning: { fr: "immeuble" }, themes: ["places"] },
      { id: "w:หมู่บ้าน", thai: "หมู่บ้าน", rom: "mùu-bâan", meaning: { fr: "village ; lotissement" }, themes: ["places"] },
      { id: "w:ต่างจังหวัด", thai: "ต่างจังหวัด", rom: "tàang jang-wàt", meaning: { fr: "la province (hors de Bangkok)" }, themes: ["places"] },
    ],
  },
];
