// Généré depuis la maquette d'origine par scripts/gen-content.mjs, puis maintenu à la main.
import type { Vowel } from '../types';

export const VOWELS: Vowel[] = [
  { id: "v:–ะ", form: "–ะ", rom: "a", ipa: "a", length: "S", group: "simple", positions: "R", chars: ["ะ"], closedForm: "◌ั◌ avec finale : กัน kan", example: { thai: "จะ", rom: "jà", meaning: { fr: "(marque du futur)" } } },
  { id: "v:–า", form: "–า", rom: "aa", ipa: "aː", length: "L", group: "simple", positions: "R", chars: ["า"], example: { thai: "มา", rom: "maa", meaning: { fr: "venir" } } },
  { id: "v:–ิ", form: "–ิ", rom: "i", ipa: "i", length: "S", group: "simple", positions: "T", chars: ["ิ"], example: { thai: "กิน", rom: "kin", meaning: { fr: "manger" } } },
  { id: "v:–ี", form: "–ี", rom: "ii", ipa: "iː", length: "L", group: "simple", positions: "T", chars: ["ี"], example: { thai: "ดี", rom: "dii", meaning: { fr: "bon, bien" } } },
  { id: "v:–ึ", form: "–ึ", rom: "ʉ", ipa: "ɯ", length: "S", group: "simple", positions: "T", chars: ["ึ"], example: { thai: "ดึก", rom: "dʉ̀k", meaning: { fr: "tard dans la nuit" } } },
  { id: "v:–ือ", form: "–ือ", rom: "ʉʉ", ipa: "ɯː", length: "L", group: "simple", positions: "TR", chars: ["ื", "อ"], closedForm: "◌ื◌ avec finale : คืน khʉʉn", example: { thai: "มือ", rom: "mʉʉ", meaning: { fr: "main" } } },
  { id: "v:–ุ", form: "–ุ", rom: "u", ipa: "u", length: "S", group: "simple", positions: "B", chars: ["ุ"], example: { thai: "คุณ", rom: "khun", meaning: { fr: "vous" } } },
  { id: "v:–ู", form: "–ู", rom: "uu", ipa: "uː", length: "L", group: "simple", positions: "B", chars: ["ู"], example: { thai: "ดู", rom: "duu", meaning: { fr: "regarder" } } },
  { id: "v:เ–ะ", form: "เ–ะ", rom: "e", ipa: "e", length: "S", group: "simple", positions: "LR", chars: ["เ", "ะ"], closedForm: "เ◌็◌ avec finale : เด็ก dèk", example: { thai: "เตะ", rom: "tè", meaning: { fr: "donner un coup de pied" } } },
  { id: "v:เ–", form: "เ–", rom: "ee", ipa: "eː", length: "L", group: "simple", positions: "L", chars: ["เ"], example: { thai: "เพลง", rom: "phleeng", meaning: { fr: "chanson" } } },
  { id: "v:แ–ะ", form: "แ–ะ", rom: "ɛ", ipa: "ɛ", length: "S", group: "simple", positions: "LR", chars: ["แ", "ะ"], closedForm: "แ◌็◌ avec finale : แข็ง khɛ̌ng", example: { thai: "และ", rom: "lɛ́", meaning: { fr: "et" } } },
  { id: "v:แ–", form: "แ–", rom: "ɛɛ", ipa: "ɛː", length: "L", group: "simple", positions: "L", chars: ["แ"], example: { thai: "แดง", rom: "dɛɛng", meaning: { fr: "rouge" } } },
  { id: "v:โ–ะ", form: "โ–ะ", rom: "o", ipa: "o", length: "S", group: "simple", positions: "LR", chars: ["โ", "ะ"], closedForm: "aucune voyelle écrite avec finale : คน khon", example: { thai: "โต๊ะ", rom: "tó", meaning: { fr: "table" } } },
  { id: "v:โ–", form: "โ–", rom: "oo", ipa: "oː", length: "L", group: "simple", positions: "L", chars: ["โ"], example: { thai: "โมง", rom: "moong", meaning: { fr: "heure (de la journée)" } } },
  { id: "v:เ–าะ", form: "เ–าะ", rom: "ɔ", ipa: "ɔ", length: "S", group: "simple", positions: "LR", chars: ["เ", "า", "ะ"], closedForm: "◌็อ◌ avec finale : ล็อก lɔ́k", example: { thai: "เกาะ", rom: "kɔ̀", meaning: { fr: "île" } } },
  { id: "v:–อ", form: "–อ", rom: "ɔɔ", ipa: "ɔː", length: "L", group: "simple", positions: "R", chars: ["อ"], example: { thai: "รอ", rom: "rɔɔ", meaning: { fr: "attendre" } } },
  { id: "v:เ–อะ", form: "เ–อะ", rom: "ə", ipa: "ɤ", length: "S", group: "simple", positions: "LR", chars: ["เ", "อ", "ะ"], example: { thai: "เยอะ", rom: "yə́", meaning: { fr: "beaucoup" } } },
  { id: "v:เ–อ", form: "เ–อ", rom: "əə", ipa: "ɤː", length: "L", group: "simple", positions: "LR", chars: ["เ", "อ"], closedForm: "เ◌ิ◌ avec finale : เดิน dəən", example: { thai: "เจอ", rom: "jəə", meaning: { fr: "rencontrer" } } },
  { id: "v:เ–ียะ", form: "เ–ียะ", rom: "ia", ipa: "iaʔ", length: "S", group: "diph", positions: "LTR", chars: ["เ", "ี", "ย", "ะ"], note: { fr: "Forme brève, rare (onomatopées)." } },
  { id: "v:เ–ีย", form: "เ–ีย", rom: "ia", ipa: "iːa", length: "L", group: "diph", positions: "LTR", chars: ["เ", "ี", "ย"], example: { thai: "เรียน", rom: "rian", meaning: { fr: "étudier" } } },
  { id: "v:เ–ือะ", form: "เ–ือะ", rom: "ʉa", ipa: "ɯaʔ", length: "S", group: "diph", positions: "LTR", chars: ["เ", "ื", "อ", "ะ"], note: { fr: "Forme brève, très rare." } },
  { id: "v:เ–ือ", form: "เ–ือ", rom: "ʉa", ipa: "ɯːa", length: "L", group: "diph", positions: "LTR", chars: ["เ", "ื", "อ"], example: { thai: "เรือ", rom: "rʉa", meaning: { fr: "bateau" } } },
  { id: "v:–ัวะ", form: "–ัวะ", rom: "ua", ipa: "uaʔ", length: "S", group: "diph", positions: "TR", chars: ["ั", "ว", "ะ"], note: { fr: "Forme brève, rare." } },
  { id: "v:–ัว", form: "–ัว", rom: "ua", ipa: "uːa", length: "L", group: "diph", positions: "TR", chars: ["ั", "ว"], closedForm: "◌ว◌ avec finale : สวน sǔan", example: { thai: "ตัว", rom: "tua", meaning: { fr: "corps" } } },
  { id: "v:–ำ", form: "–ำ", rom: "am", ipa: "am", length: "S", group: "special", positions: "TR", chars: ["ำ"], example: { thai: "ทำ", rom: "tham", meaning: { fr: "faire" } }, note: { fr: "Voyelle brève, mais la syllabe est VIVANTE (elle finit par m)." } },
  { id: "v:ไ–", form: "ไ–", rom: "ai", ipa: "aj", length: "S", group: "special", positions: "L", chars: ["ไ"], example: { thai: "ไป", rom: "pai", meaning: { fr: "aller" } }, note: { fr: "Voyelle brève, mais la syllabe est VIVANTE (elle finit par y)." } },
  { id: "v:ใ–", form: "ใ–", rom: "ai", ipa: "aj", length: "S", group: "special", positions: "L", chars: ["ใ"], example: { thai: "ใจ", rom: "jai", meaning: { fr: "cœur" } }, note: { fr: "Même son que ไ–. Seulement 20 mots s'écrivent avec ใ." } },
  { id: "v:เ–า", form: "เ–า", rom: "ao", ipa: "aw", length: "S", group: "special", positions: "LR", chars: ["เ", "า"], example: { thai: "เรา", rom: "rao", meaning: { fr: "nous" } }, note: { fr: "Voyelle brève, mais la syllabe est VIVANTE (elle finit par w)." } },
  { id: "v:ฤ", form: "ฤ", rom: "rʉ", ipa: "rɯ", length: "S", group: "special", positions: "", chars: ["ฤ"], example: { thai: "ฤดู", rom: "rʉ́-duu", meaning: { fr: "saison" } }, note: { fr: "Lettre-voyelle autonome. Se lit aussi ri (อังกฤษ ang-krìt) ou rəə." } },
  { id: "v:ฤๅ", form: "ฤๅ", rom: "rʉʉ", ipa: "rɯː", length: "L", group: "special", positions: "", chars: ["ฤ", "ๅ"], example: { thai: "ฤๅษี", rom: "rʉʉ-sǐi", meaning: { fr: "ermite" } }, note: { fr: "Rare." } },
  { id: "v:–าย", form: "–าย", rom: "aai", ipa: "aːj", length: "L", group: "combo", positions: "R", chars: ["า", "ย"], example: { thai: "สบาย", rom: "sà-baai", meaning: { fr: "à l'aise" } } },
  { id: "v:–าว", form: "–าว", rom: "aao", ipa: "aːw", length: "L", group: "combo", positions: "R", chars: ["า", "ว"], example: { thai: "ข้าว", rom: "khâao", meaning: { fr: "riz" } } },
  { id: "v:–ิว", form: "–ิว", rom: "iu", ipa: "iw", length: "S", group: "combo", positions: "TR", chars: ["ิ", "ว"], example: { thai: "หิว", rom: "hǐu", meaning: { fr: "avoir faim" } } },
  { id: "v:เ–็ว", form: "เ–็ว", rom: "eo", ipa: "ew", length: "S", group: "combo", positions: "LTR", chars: ["เ", "็", "ว"], example: { thai: "เร็ว", rom: "reo", meaning: { fr: "rapide" } } },
  { id: "v:แ–ว", form: "แ–ว", rom: "ɛɛo", ipa: "ɛːw", length: "L", group: "combo", positions: "LR", chars: ["แ", "ว"], example: { thai: "แมว", rom: "mɛɛo", meaning: { fr: "chat" } } },
  { id: "v:เ–ียว", form: "เ–ียว", rom: "iao", ipa: "iaw", length: "L", group: "combo", positions: "LTR", chars: ["เ", "ี", "ย", "ว"], example: { thai: "เขียว", rom: "khǐao", meaning: { fr: "vert" } } },
  { id: "v:–อย", form: "–อย", rom: "ɔɔi", ipa: "ɔːj", length: "L", group: "combo", positions: "R", chars: ["อ", "ย"], example: { thai: "คอย", rom: "khɔɔi", meaning: { fr: "attendre, guetter" } } },
  { id: "v:โ–ย", form: "โ–ย", rom: "ooi", ipa: "oːj", length: "L", group: "combo", positions: "LR", chars: ["โ", "ย"], example: { thai: "โดย", rom: "dooi", meaning: { fr: "par, au moyen de" } } },
  { id: "v:–ุย", form: "–ุย", rom: "ui", ipa: "uj", length: "S", group: "combo", positions: "BR", chars: ["ุ", "ย"], example: { thai: "คุย", rom: "khui", meaning: { fr: "bavarder" } } },
  { id: "v:เ–ย", form: "เ–ย", rom: "əəi", ipa: "ɤːj", length: "L", group: "combo", positions: "LR", chars: ["เ", "ย"], example: { thai: "เคย", rom: "khəəi", meaning: { fr: "avoir déjà fait" } } },
  { id: "v:–วย", form: "–วย", rom: "uai", ipa: "uaj", length: "L", group: "combo", positions: "R", chars: ["ว", "ย"], example: { thai: "สวย", rom: "sǔai", meaning: { fr: "beau, belle" } } },
  { id: "v:เ–ือย", form: "เ–ือย", rom: "ʉai", ipa: "ɯaj", length: "L", group: "combo", positions: "LTR", chars: ["เ", "ื", "อ", "ย"], example: { thai: "เหนื่อย", rom: "nʉ̀ai", meaning: { fr: "fatigué" } } },
];
